docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseDiamondOperator.xml

This introduces the property "java7compatibility", which is disabled by default (for backwards
compatibility of the rule this can be enabled).
The rule now detects more cases by default, that are only valid for java8+: nested types,
types with wildcards, ternary operators.
With this property, the previously added version specific test cases are now all enabled.
- Fixes #2545

[java] Improve UseDiamondOperator rule

---

pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/DefaultPackage.xml

JUnit 5 allows test methods to be default / package scoped.
This PR adjusts the rule [DefaultPackage](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#defaultpackage)
See https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods
Also, Sonar now has a rule, S5786, which requires JUnit 5 method to be package scoped, so it would be nice for PMD and Sonar to be aligned. See https://jira.sonarsource.com/browse/RSPEC-5786
- Fixes #

[java] DefaultPackage: Allow package default JUnit 5 Test methods

---

docs/pages/pmd/userdocs/cli_reference.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
pmd-core/src/main/java/net/sourceforge/pmd/util/ClasspathClassLoader.java
pmd-core/src/test/java/net/sourceforge/pmd/ConfigurationTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/cli/auxclasspath-empty.cp
pmd-core/src/test/resources/net/sourceforge/pmd/cli/auxclasspath.cp

Supports relative `file:` urls for auxclasspath. Also allows comments now with "#" in the auxclasspath-file (although not documented).
- Fixes #2549

[java] Auxclasspath in PMD CLI does not support relative file path

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java

For the XPath expression
`(//ForStatement | //WhileStatement | //DoStatement)//AssignmentOperator`
we threw away "AssignmentOperator" and started visiting at this node.
But that's not possible, because that's not at the root of the expr.
That's the fix for the problem found in #2575

[core] Fix XPath 2.0 Rule Chain Analyzer with Unions

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AppendCharacterWithCharRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/ConsecutiveLiteralAppendsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientStringBufferingRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AppendCharacterWithChar.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientStringBuffering.xml

This originated from #1932 and merged the test cases in [InefficientStringBuffering](https://pmd.github.io/latest/pmd_rules_java_performance.html#inefficientstringbuffering).
Example false-negative, that is fixed:
```java
String someString = getSomeString();
StringBuilder sb = new StringBuilder();
sb.append("a" + someString + "b"); // bad - false negative
sb.append('a').append(someString).append('b'); // good
```
Note: This also fixes a false-negative with [AppendCharacterWithChar](https://pmd.github.io/latest/pmd_rules_java_performance.html#appendcharacterwithchar):
```java
StringBuilder sb = new StringBuilder(message).append("\n");
```
https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-context/src/main/java/org/springframework/context/event/ApplicationListener …

[java] InefficientStringBuffering/AppendCharacterWithChar: Fix false negatives with concats in appends

---

docs/pages/release_notes.md
pmd-core/src/main/resources/rulesets/releases/6250.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidCalendarDateCreationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidCalendarDateCreation.xml

This is the rule "AvoidCalendarDateCreation" split from original PR #1932 .
- Refs #1932 - note: other PRs will follow and eventually replace 1932.
https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-context/src/main/java/org/springframework/format/datetime/DateFormatterRegistrar.java#L112

[java] New Performance Rule AvoidCalendarDateCreation

---

docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNodeWithListAndEnum.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQueryTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java

Deprecates any access to List attributes with XPath queries.
I decided against marking the 3 getters in apex with `@DeprecatedAttribute`, since that would not cover any new getter that might be created in the future.
I don't think, we need to put this more prominently in the release notes, since this feature is probably not used very often (if at all).
- Fixes #2451

[core] Deprecate support for List attributes with XPath 2.0

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java

Add `$messagechannel` to safe resources for VfUnescapeEl rule
- Fixes  #2620

[visualforce] add new safe resource for VfUnescapeEl

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ClassScopeTest.java

Removes any remaining usages of DummyJavaNode - which accidentaly got added to the main source.
We could then simply delete this class in PMD 7 and forget about it.
This changes one rule: UnusedImports.

[java] Remove usages of DummyJavaNode

---

pmd-apex-jorje/pom.xml
pmd-doc/pom.xml
pom.xml

I've got snyk pointing to pmd and it keeps complaining about unsafe dependencies. 
https://app.snyk.io/vuln/SNYK-JAVA-ORGYAML-537645
https://app.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-31407
There is still a dependency on jcommander 1.72 which snyk [dislikes](https://app.snyk.io/vuln/SNYK-JAVA-COMBEUST-174815) but latest jcommander deleted some methods PMD is currently using.

Update libraries snyk is referring to as `unsafe`

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidInstantiatingObjectsInLoopsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UseStringBufferForStringAppendsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidInstantiatingObjectsInLoops.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseStringBufferForStringAppends.xml

[java] Fix issue #1736 and issue #2207

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileVisitor.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/StdCyclomaticComplexityRule.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRuleTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/codestyle/xml/ClassNamingConventions.xml

Top-Level enums where never visited in rules, only nested/inner enums.
Since ClassNamingConventions uses rulechain, it was not affected by this bug.
- on PMD 7, this is fixed in general via #2491 . The root problem is, that Apex has multiple root nodes...

[apex] Support top-level enums in rules

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ProperCloneImplementationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ProperCloneImplementation.xml

The method checking whether allocations of class are present in it's clone() method fails in case of non ASTClassOrInterfaceType allocation. But as we are interested in ASTClassOrInterfaceType allocations only, in my opinion, it's enough to check if allocated type is null.
- Fixes #2634

[java] NullPointerException in rule ProperCloneImplementation

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidCallingFinalizeRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidCallingFinalize.xml

I have modified the AvoidCallingFinalizeRule class to fix false positives when variables with name 'finalize' and finalize methods with args are detected as a problem. Also I've added 2 tests validating that the false positive bugs were fixed.
- Fixes #2578

[java] AvoidCallingFinalize detects some false positives (2578)

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml

returning Strings
I've changed the way we are getting operation name and primarySuffix in LiteralsFirstInComparisonsRule class, in order to fix false negative at methods chaining like this one:
public void bar() {
person.getName().equals("Hello, world!"); // <-- false negative here
}
In case we have methods chaining like the one above, there are multiple primarySuffixes and comparison operation name is no longer in a primary prefix, it's in (n - 1)th primarySuffix. 
Also I've refactored some other methods of the class.
- Fixes #2569

[java] False negative: LiteralsFirstInComparisons for methods... (2569)

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UseCollectionIsEmptyRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseCollectionIsEmpty.xml

The UseCollectionIsEmptyRule class uses a primaryPrefix to get a type of a variable on which `size()` is called. But in case `this` or `super` is used, the actual object info is stored in the first primarySuffix and contains only variable name, so additional operations are required to get the actual type.
Also I have refactored some of class methods.
- Fixes #2543

[java] UseCollectionIsEmpty can not detect the case this.foo.size()

---

Gemfile
Gemfile.lock
docs/pages/release_notes.md
pmd-core/pom.xml
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/Renderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XSLTRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/util/IOUtil.java
pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/ReportTest.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java
pmd-core/src/test/java/net/sourceforge/pmd/util/StringUtilTest.java
pmd-doc/pom.xml
pmd-java/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pom.xml

This PR tries to fix #2615 . In order to use the correct encoding through the rendering process, the new API `Renderer::setReportFile` is added.
I'm not entirely sure about CPD renderer, whether we have a similar issue there. But as far as I can see, only the default platform encoding is used, there is no way to change the encoding. There is also no way to specify a output file as a command line option, so CPD renderers always render to Sysout and hence should use the default platform encoding.
- Fixes #2615

[core] Fix XMLRenderer encoding issues

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/LawOfDemeter.xml

The primary prefix might not always be a method call and array access is also not a method call.
- Fixes #2181
- Replaces #2561

[java] LawOfDemeter: False positive with indexed array access

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/ImportWrapper.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/DuplicateImportsRule.java

* Deprecates the class `ImportWrapper`, which is in pmd-core, but is Java specific.
* Copies this class to pmd-java into package `...lang.java.ast.internal`.
* Contains the fix from #2644
- Found while working on #2644

[core][java] Deprecate pmd-core::lang.rule.ImportWrapper

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/RedundantFieldInitializerRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/RedundantFieldInitializer.xml

A check for `\0` character literal has been added.
- Fixes #2441

[java] RedundantFieldInitializer can not detect a special case for char initialize: char foo = '\0';

---

pmd-java/pom.xml
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTCatchStatementTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/Java11Test.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ParserTestSpec.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/SwitchExpressionTests.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/WildcardBoundsTest.kt
pmd-lang-test/pom.xml
pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/cpd/test/CpdTextComparisonTest.kt
pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/AstMatcherDslAdapter.kt
pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/TestUtils.kt
pmd-modelica/pom.xml
pmd-modelica/src/test/kotlin/net/sourceforge/pmd/lang/modelica/ast/ModelicaCoordsTest.kt
pmd-scala-modules/pmd-scala-common/pom.xml
pmd-scala-modules/pmd-scala-common/src/test/kotlin/net/sourceforge/pmd/lang/scala/ast/ScalaTreeTests.kt
pom.xml

Upgrade kotlintest to Kotest. Also updates the kotlin version to the latest stable
This is depended on by type resolution
@adangel FunSpec is contained in the kotest core module, but I still added the dependency on the kotest junit runner for pmd-java. This allows usage of the marker interface IntelliMarker, which for makes the tests written with the custom parser spec runnable from intellij. Surefire still mentions the runner as a plugin dependency
- Fixes #2653

[lang-test] Upgrade kotlintest to Kotest

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/AxisStream.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/IteratorBasedNStream.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/StreamImpl.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/internal/NodeStreamBlanketTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/internal/NodeStreamTest.java

Fix a bug in ancestor node streams. 
If you have an ancestor path like `/B/B/A/A`, where the innermost (last) node is named `a`, then
`a.ancestors(B.class).drop(1)` was equivalent to `a.getParent().ancestors(B.class)`, which is wrong as it still contains both `B` nodes.
This also makes ancestor streams less lazy, so that they can be folded to empty streams more often.

[core] Bug with node stream drop 

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

Mark field assignments as used, if they may be observed by an external method/constructor call. This may occur if a constructor calls "leaks" a `this` reference by passing it as a parameter, or calls its own methods.
- Fixes #2668

[java] UnusedAssignment false positive with leaking this in constructor

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidReassigningCatchVariablesRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidReassigningCatchVariablesTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningCatchVariables.xml

The PR introduces a new rule that detects caught exception variables reassignment like in the example below:
catch (Exception e) {
e = new RuntimeException(); // rule violation
}
The rule has been implemented as a java class.
- Fixes #2471

[java] New Rule: AvoidReassigningCatchVariables

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

Consider the following example:
} catch(Exception e) {
LOGGER.warn(e.getMessage());
}
In the code below, an argument `e.getMessage()` will provide us with non null type returned from `argumentList.get(0).getType()` which is not String type, so the argument is removed. But as it is the only argument of a logger method call, `remove` statement at line 98 throws an exception. So I've added a separate check whether the argument is the only one.
https://github.com/pmd/pmd/blob/fe82f6a448205328ba95923dbb6b761881e1cd4f/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java#L93-L98
- Fixes #2431

[java] InvalidLogMessageFormatRule throws IndexOutOfBoundsException when only logging exception message

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidCatchingThrowableRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidCatchingThrowable.xml

The predicate checking whether thrown type is Throwable has been changed to `Throwable.class.equals` to avoid false-negatives at `catch (java.lang.Throwable t)`.
- Fixes #2439

[java] AvoidCatchingThrowable can not detect the case: catch (java.lang.Throwable t)

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java

Deprecate RuleContext attributes. They're apparently a way to share state between threads. This appears useless, and RuleContext could be a simpler object without them. Their interaction with incremental analysis is also unclear and overall they can't be relied upon.

[core] Deprecate RuleContext attributes

---

.travis/before_install.sh
.travis/build-deploy.sh
docs/pages/release_notes.md
pmd-core/pom.xml
pmd-core/src/main/java/net/sourceforge/pmd/cpd/LanguageFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageRegistry.java
pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java
pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeExportCli.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java
pmd-dist/pom.xml
pmd-dist/src/test/java/net/sourceforge/pmd/it/AllRulesIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/ExecutionResult.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pom.xml

Running PMD with Java7 does not work as promised. Main problems are with JCommander and commons-text.
* Downgrade JCommander for java7 compatibility
* Downgrade commons-text for java7 compatibility
* Scala also requires java8 and it failed indirectly via a ServiceConfigurationError while discovering the language.
The Scala module itself doesn't need java8, but its dependencies require java8.
* Add integration test
- none

[core] Fix java7 compatibility

---

pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java

I'm seeing duplicated warnings from #2617, I think that's caused by `warnDeprecated`. This is because we parse rulesets twice, once with warnings, a second time without....

[core] Duplicate warning for missing language attribute

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

Fixes #2684. We conservatively assume that any method/ctor call may throw within a try block. There are several improvements we can do to this in PMD 7, with #2689: the overload resolution allows us to find out which methods throw checked exceptions and associate them to the actual catch block they would be dispatched to.
- Fixes #2684

[java] Fix UnusedAssignment FP with methods throwing exceptions

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringToStringRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/stringtostring/Car.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/stringtostring/User.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/StringToString.xml

I've added a visit to the ASTPrimaryExpression node checking whether call to a method returning String is followed by `toString()`. Method call arguments are checked in order to get the actual method's return type and avoid false positives like in the example below:
public String getId(String name) {...}
public Integer getId(int position) {...}
public void foo() {
String a = getId(0).toString(); // <-- avoiding false-positive here
}
- Fixes #2530

[java] StringToString can not detect the case: getStringMethod().toString()

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/UnnecessaryCaseChangeRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UnnecessaryCaseChange.xml

A check whether `toLowerCase()` or `toUpperCase()` method is called in arguments of an equals method has been added.
Also I've refactored some other methods of the class.
- Fixes #2531

[java] UnnecessaryCaseChange can not detect the case like: foo.equals(bar.toLowerCase())

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractLombokAwareRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml

Fix false positive with lombok annotation EqualsAndHashCode in UnusedPrivateField
- Fixes #2673

[java] add lombok.EqualsAndHashCode in AbstractLombokAwareRule

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ProperCloneImplementationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ProperCloneImplementation.xml

I've changed the rule to ignore cases when `clone()` is implemented using allocation and enclosing class is `final`.
- Fixes #2410

[java] ProperCloneImplementation not valid for final class

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveParameterListRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ExcessiveParameterList.xml

I've added a visit to the ASTFormalParameters with a predicate in order to skip counting private constructor parameters.
- Fixes #2461

[java] ExcessiveParameterListRule must ignore a private constructor

---

pmd-java/src/main/resources/category/java/multithreading.xml

Improve the example for rule [AvoidSynchronizedAtMethodLevel](https://pmd.github.io/latest/pmd_rules_java_multithreading.html#avoidsynchronizedatmethodlevel) to make
it clear, that this rule is about code, that doesn't need to be syncronized.
See https://stackoverflow.com/questions/63132263/avoid-synchronized-at-method-level
- None

[java] Improve example for AvoidSynchronizedAtMethodLevel

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/ImportWrapper.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/DuplicateImportsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java

When determining methods/fields by reflection, we could run into situations, that the classes, that are referenced in the methods (e.g. parameter types, return types) are not on the auxclasspath. Then a LinkageError is thrown, which was not handled before.
The reason, why the types are missing on the auxclasspath is actually a valid case: As long as the methods are not used in the code, the referenced classes neither need to be on the compile classpath. And we use the compile classpath as our auxclasspath.
This can happen, if a project uses a provided dependency and this dependency has other transitive dependencies. These transitive dependencies are not on the compile classpath.
This PR fixes the problem in ImportWrapper as well as in two other cases, where we use reflection.
- Fixes …

[java] Fix NoClassDefFoundErrors

---

pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactoryCompatibility.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryCompatibilityTest.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
pmd-core/src/test/java/net/sourceforge/pmd/processor/MultiThreadProcessorTest.java
pmd-doc/src/main/java/net/sourceforge/pmd/docs/DeadLinksChecker.java
pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java

Cleanup: use StandardCharsets instead of Charset.forName

---

pmd-core/src/test/java/net/sourceforge/pmd/util/database/DBMSMetadataTest.java

Cleanup: use print instead of printf if no format exists

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextPadRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/util/designer/DFAPanel.java
pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java
pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/SimpleNodeSubMenu.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/FileReporterTest.java
pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/TemplateParseException.java
pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/TokenMgrError.java

Cleanup: replace StringBuffer with StringBuilder

---

pmd-core/src/main/java/net/sourceforge/pmd/properties/BooleanProperty.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/GenericClassCounterRule.java

Cleanup: change valueOf to parse when we need primitive return value.

---

pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDCommandLineInterface.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/VSRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportHTMLPrintVisitor.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/IDEAJRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextColorRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextPadRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/VBHTMLRenderer.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/symboltable/ClassScope.java
pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java

Cleanup: StringBuilder issues

---

pmd-java/src/main/resources/category/java/errorprone.xml

Extends Java SuspiciousEqualsMethodName rule description
- Fixes #2264

[doc] [java] SuspiciousEqualsMethodName: update description, fixes #2264

---

pmd-dart/src/main/antlr4/net/sourceforge/pmd/lang/dart/antlr4/Dart2.g4
pmd-dart/src/test/java/net/sourceforge/pmd/cpd/DartTokenizerTest.java
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/escape_sequences.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/escape_sequences.txt
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/string_interpolation.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/string_interpolation.txt

The Dart tokenizer was incomplete, resulting in some strings that use
string interpolation not being parsed correctly. This has been worked
around by making sure that the contents of string interpolation are all
included in the same string token.

[dart] [cpd] Improvements for Dart interpolated strings

---

pmd-dart/src/main/antlr4/net/sourceforge/pmd/lang/dart/antlr4/Dart2.g4
pmd-dart/src/test/java/net/sourceforge/pmd/cpd/DartTokenizerTest.java
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/escape_sequences.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/escape_sequences.txt
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/escaped_dollar.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/escaped_dollar.txt
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/string_interpolation.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/testdata/string_interpolation.txt

Escaped characters in Dart multiline string are now handled correctly. This case was missing from the reference Dart grammar (https://github.com/chalin/dart-spec-and-grammar/blob/master/doc/grammar-AUTOGENERATED-DO-NOT-EDIT.txt), but these do occur in real Dart source code.

[dart] [cpd] Cpd dart escaped dollar

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchStatement.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchStatementTest.java

For isExhaustiveEnumSwitch method, the first descendant can be null for the default switch case hence adding null check.
Tried adding new unit tests for this but, I was not able to get it to work. Somehow expression type was coming out to null for switch on enums.
- Fixes #2738

[java] issue-2738: Adding null check to avoid npe when switch case is default

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeTestUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/TypeTestUtilTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/testdata/SomeClassWithAnon.java

* Fix the NPE
* Forbid testing types against anonymous/ local classes. The parameter must be a canonical name, and those don't have one. This means you can't write eg `TypeTestUtil.isA("java.util.Collections$1", node)` anymore, which anyway would be practically useless (eg can only match within this particular class). This simplifies the contract of SymbolResolver in PMD 7, in #2689 it is restricted to resolving only classes that have a canonical name, ie resolving anonymous or local classes is undefined behavior. Instead those are solely represented by AST symbols.
- Fixes #2756

[java] Fix #2756, NPE in TypeTestUtil

---

pmd-java/etc/grammar/Java.jjt
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java

The problem was, the stack is empty if the local var declaration is the first node of the compilation unit to be pushed.
- Fixes #2767

[java] Fix #2767, PMD cannot parse a local var with final in instance initializer

---

.github/dependabot.yml
.github/workflows/build.yml

travis-ci is toooo slow.
- Fixes #

[ci] Add github actions for a fast view of pr succeed/not

---

pmd-java/etc/grammar/Java.jjt
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/LambdaBug2783.java

There's a bug in the lookahead, I pulled out something from java-grammar to fix it
- Fixes #2783

[java] Lambda parsing bug

---

README.md

Adds a badge for PMD in the [Reproducible Central](https://github.com/jvm-repo-rebuild/reproducible-central) project.
PMD 6.24.0 and 6.25.0 have been verified as reproducible builds.
6.26.0 and 6.27.0 are being added now: https://github.com/jvm-repo-rebuild/reproducible-central/pull/33
- Fixes #

Add badge for reproducible build

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeTestUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/TypeTestUtilTest.java

* Fix a bug, whereby array types were not supported by `TypeTestUtil.isA`. The reason is, we use `getName` on the Class instance, but this method returns a type descriptor for array types, not a canonical name (eg `[Ljava.lang.Object;` instead of `java.lang.Object[]`). So parsing the descriptor to load the class failed, because the other overload requires a canonical name
* Array covariance was not really tested
* The examples in the documentation had the arguments the wrong way around
* This PR can be mentioned in the release notes as an issue

[java] Fix TypeTestUtil for arrays

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsRule.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsNestedClassTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSharingViolations.xml

Fixes https://github.com/pmd/pmd/issues/2774, false positives and false
negatives for [ApexSharingViolations](https://pmd.github.io/latest/pmd_rules_apex_security.html#apexsharingviolations).
Sharing settings are not inherited by inner classes. Sharing settings
need to be declared on the class that contains the Database method, DML,
SOQL, or SOSL.
The change inverts the direction from which nodes are found and
analyzed. The previous code visited the ASTUserClass and then searched
for descendant nodes that met a certain criteria. It did not visit inner
ASTUserClass nodes because it didn't use rule chains or call the super's
visit moethod for ASTUserClassi.
The new implementation visits all nodes that correspond to Database
method, DML, SOQL, or SOSL nodes and then finds the nearest …

[apex] Analyze inner classes for sharing violations

---

docs/pages/7_0_0_release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JAccessibleElementSymbol.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/AbstractJavaScope.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

* Update UnusedAssignment
* As described on #2701 I think the reaching definitions analysis may be useful for other rules, and maybe for the symbol table. This is work for later, but reenabling the tests of the rule is good for future refactorings.
This also fixes a bug with call chains. I'll open an issue to describe it (-> #2796)
- An item of #2701
- Fix #2796

[java] Update UnusedAssignmentRule to PMD 7 grammar

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

Fixes the NPE when trying to determine the type. The type might be null.
- Fixes #2755

[java] CloseResource: Fix NPE in case of "var"

---

pmd-core/src/test/java/net/sourceforge/pmd/ReportTest.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java

It is only used by the XMLRendererTest.

[core] Move method "renderTempFile" to XMLRendererTest

---

pmd-core/src/test/java/net/sourceforge/pmd/ConfigurationTest.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java
pmd-core/src/test/java/net/sourceforge/pmd/util/database/DBTypeTest.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/AbstractBinaryDistributionTest.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/AllRulesIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleDocGeneratorTest.java
pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java

Don't reinvent the wheel. TemporaryFolder already takes care of cleaning
up the created files.

[core] Use JUnit's TemporaryFolder rule

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DoNotCallSystemExit.xml

System.exit() and its equivalents should be allowed in static main() methods, added check for Runtime.getRuntime().halt()
- Fixes #2157

[java] Improve DoNotCallSystemExit (Fixes #2157)

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java

When running PMD under Windows with [IBM's Java](https://www.ibm.com/support/pages/java-sdk-downloads-version-80), then the produced XML report looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>&#xD;
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.28.0" timestamp="2020-10-15T10:24:55.318">&#xD;
</pmd>&#xD;
```
IBM's Java obviously uses an interesting implementation for XMLStreamWriter. The produced XML is invalid, e.g. xmllint says this:
```
$ xmllint out.xml
out.xml:1: parser error : Start tag expected, '<' not found
<?xml version="1.0" encoding="UTF-8"?>&#xD;
```
This problem exists since I've …

[core] Fix XMLRenderer newlines when running under IBM Java

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

This PR fixes a false-negative when re-assigning a variable without closing it before.
- Fixes #2764

[java] CloseResource - Fix #2764: False-negative when re-assigning variable

---

pmd-java/src/main/resources/category/java/design.xml

[ExcessiveImports](https://pmd.github.io/latest/pmd_rules_java_design.html#excessiveimports):
Since the default minimum is 30, I believe it would make more sense if the comment said "28" instead of "18".

[java] (doc) Update ExcessiveImports example code for clarity

---

pmd-java/etc/grammar/Java.jjt

The grammar had two strange string literals, which allowed ending a file with
* u001a (a SUBSTITUTE control char), or
*  the string `~[]`, which was probably a typo, meant to allow any number of trailing chars. 
A file with only those would also have been valid. I think it's safe to remove those
Edit: this also showed up in parse error messages:
```java
Was expecting one of:
<EOF> 
"import" ...
"\u001a" ...
"~[]" ...
```

[java] Remove weird trailing characters

---

pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ParserTestSpec.kt
pmd-lang-test/pom.xml
pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/IntelliMarker.kt
pom.xml

- Fixes #2762 
- Refs #2433: dokka now produces a normal javadoc jar, that is pushable to maven central

[lang-test] Upgrade Kotlin, Dokka and Kotest

---

.travis/before_install.sh
.travis/common-functions.sh
.travis/project-list.xml
.travis/regression-tester.sh
Dangerfile
Gemfile
Gemfile.lock

* For testing, this will use the pmd-regression-tester from PR-branch pmd/pmd-regression-tester#72 . If it works, we can merge that regression-tester-pr and point to the master branch
* ~This additionally - a bit unrelated - changes, how we download openjdk11. We now use a fixed URL, so that we don't need to update the version in the script anymore.~ I've cherry-picked these already on master
* Finally, updates the `project-list.xml` configuration to include build-command and auxclasspath-command for both checkstyle and spring-framework. This enables auxclasspath usage. We hopefully see the different between no-typeresolution (current master baseline) and typeresolution (this PR).
Note: the project-list has a minimal set of exclude-patterns (for checkstyle). For PMD7, there are more …

[ci] Use auxclasspath with regression-tester

---

pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/ReflectedFieldSymbolTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/Utils.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeOpsTest.kt
pom.xml

* Kotest 4.3.1 has been released -> https://github.com/kotest/kotest/releases/tag/v4.3.1
* This reverts the workaround that were necessary.
Note: This PR is draft, since the version change commit (the last one) should be done on master first.
- Relates #2870

[core] Update kotest to 4.3.1

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/ParserOptions.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ParametricRuleViolation.java
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/ModelicaRuleViolationFactory.java

* This adds deprecations introduced in #2807 
* Also adds missing internalization for ModelicaRuleViolationFactory
I've **not** internalized/deprecated `RuleViolationFactory`, since that is still public API and we don't have an alternative on master.

[core] Deprecations for ParametricRuleViolation and ParserOptions#suppressMarker

---

pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/internal/SystemProps.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/RuleApplicator.java
pmd-core/src/test/java/net/sourceforge/pmd/SourceCodeProcessorTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java

This can be enabled by setting system property "pmd.error_recovery"
to an arbitrary value, e.g. "-Dpmd.error_recovery".
Next step is, to add enable this in our regression tester by default (setting both "-Dpmd.error_recovery" and "-ea" for assertions).
- Fixes #2885

[core] Add error recovery mode

---

pmd-scala-modules/pmd-scala-common/src/main/java/net/sourceforge/pmd/cpd/ScalaTokenAdapter.java
pmd-scala-modules/pmd-scala-common/src/main/java/net/sourceforge/pmd/cpd/ScalaTokenizer.java
pmd-scala-modules/pmd-scala-common/src/test/java/net/sourceforge/pmd/cpd/ScalaTokenizerTest.java
pmd-scala-modules/pmd-scala-common/src/test/resources/net/sourceforge/pmd/lang/scala/cpd/testdata/sample-LiftActor.txt
pmd-scala-modules/pmd-scala-common/src/test/resources/net/sourceforge/pmd/lang/scala/cpd/testdata/special_comments.scala
pmd-scala-modules/pmd-scala-common/src/test/resources/net/sourceforge/pmd/lang/scala/cpd/testdata/special_comments.txt

This enhancement adds support for CPD-ON and CPD-OFF special comments for Scala.  It does this by wrapping the scala.meta.tokens.Token with an adapter which satisfies the GenericToken interface, then uses the special comments processing from the existing BaseTokenFilter.
A new test fixture and results file has been added to the test, which seems consistent with the level of other testing in this area.
- Fixes #2480

[scala] Add support for CPD-ON and CPD-OFF special comments

---

pmd-cs/src/main/java/net/sourceforge/pmd/cpd/CsTokenizer.java

CPD has an option to filter out using directives for C# code. When using the GUI to do this, enabling the option prevents it from being disabled again afterwards. The only way to work around this is to restart the application.
In order to reproduce:
1. Create a C# file with lots of identical using statements:
```
using System;
using System;
...
using System;
```
2. Start the CPD GUI, select C# as language and click "Go". This will result in many instances of code duplication being shown.
3. Click the "Ignore usings?" checkbox and click "Go" again. No duplicates will be found now.
4. Uncheck the "Ignore usings?" checkbox and click "Go" again. You'd expect to get the original results, but there are still no duplicates.
This is caused by the internal property only being updated when it has …

[cs] CPD: fix issue where ignoring using directives could not be disabled

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextRendererTest.java

This PR adds the RuleName of the violating rule at the end of the output line generated by the TextRenderer.
Before this was for each violating rule: ```SourceCodeFileName:LineNumber:<TAB>RuleDescription```
Now this is for each violating rule: ```SourceCodeFileName:LineNumber:<TAB>RuleName:<TAB>RuleDescription```
- Fixes https://github.com/pmd/pmd/issues/1961

[core] Include rule name in text renderer

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java

When using UTF-16 as encoding, the XMLRenderer produced
invalid XML: When inserting the linebreak encoded with the
given encoding "UTF-16", a BOM was created. This inserted additional
characters U+FEFF in the middle of the file, which is not allowed.
A partial workaround for this issue would be, to use "UTF-16BE" as
encoding instead. This doesn't create a BOM. However, the resulting XML
file is then completely without a BOM.
- Relates #2831

[core] Fix XMLRenderer with UTF-16

---

pmd-java/src/main/resources/category/java/bestpractices.xml

Change from "a accessor" to "an accessor".

[java] (doc) Fix typo: "an accessor" not "a"

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java

These exceptions are indications of an incomplete auxclasspath but should not fail PMD entirely.
Incomplete auxclasspath can still result in invalid violations, either false positives or false negatives.
You can reproduce this easily by build PMD with the following command:
`./mvnw clean verify` followed by `./mvnw verify -Daggregate=true`
That results in the following build error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd (pmd) on project pmd:
Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd failed:
A required class was missing while executing org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd:
apex/jorje/semantic/ast/AstNode
```
PMD doesn't catch the LinkageError and it falls through to maven which thinks, it's a …

[java] Catch additional TypeNotPresentExceptions / LinkageErrors

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml

The [issue](https://github.com/pmd/pmd/issues/575) is about a false negative: The PositionLiteralsFirstInComparisons rule in Java should consider constant fields as string literals and raise a warning to position these as the first argument in comparisons.
The warning is only to be triggered, if the field is:
a. static,
b. final, and
c. a String
- Fixes #575

[java] LiteralsFirstInComparisons should consider constant fields

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java

Code Climate issue severity are specified here
https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#issues
as `info`, `minor`, `major`, `critical`, or `blocker`. It was mapped to
a value `normal` that is not recognized by tools compatible with Code
Climate's format. I have mapped the five PMD priority values on the five Code Climate severity levels
I haven't open an issue

[core] Fix code climate severity strings

---

.ci/inc/regression-tester.inc
.github/workflows/pull-requests.yml
Dangerfile

This PR addresses some of the problems from the last builds:
The last baseline generated from master is from 2020-12-12 (see https://pmd-code.org/pmd-regression-tester/).
The [last build on master](https://github.com/pmd/pmd/runs/1664561802?check_suite_focus=true#step:6:48201) didn't run pmdtester successfully.
This PR hopefully fixes this problem (which can only be verified, after this PR has been merged). To see such problems earlier in the future, the build will fail now, when something doesn't work with the baseline.
The other problems from the [last build of PR 2983](https://github.com/pmd/pmd/pull/2983/checks#step:6:81765):
* a report has been generated, but the summary numbers are missing ("   new violations....")
* the report is very very big: 45mb... the PR only changed one rule …

[ci] Fixes for pmdtester (baseline, danger)

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java
pmd-apex/src/main/resources/category/apex/errorprone.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/OverrideBothEqualsAndHashcodeTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/OverrideBothEqualsAndHashcode.xml

Copied the Java override equals and hashcode rule into Apex. Only difference I intend between the two implementations are that the Apex implementation does not contain an exception for classes that implement the Comparable interface. I couldn't find a good reason for making that exclusion. 
For reference: Java's [OverrideBothEqualsAndHashcode](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#overridebothequalsandhashcode)
n/a

[apex] New Rule: override equals and hashcode rule

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodNamingConventionsRule.java

[java] Fix threading issue in MethodNamingConventionsRule

---

pmd-swift/src/main/antlr4/net/sourceforge/pmd/lang/swift/antlr4/Swift.g4
pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.0.swift
pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.0.txt

Previous PR on Swift 5 support missed string literals like explained in this article:
https://www.swiftbysundell.com/articles/string-literals-in-swift/
none

[swift] Manage swift5 string literals

---

pmd-core/src/main/java/net/sourceforge/pmd/internal/util/AssertionUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaAnnotatableNode.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/Annotatable.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeTestUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/xpath/TypeIsExactlyFunction.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/xpath/TypeIsFunction.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

The problem with #2454 is that the input to TypeTestUtil is not sanitized to remove whitespace from the property value.
We can either
* make TypeTestUtil lenient (as TypeHelper was)
* make TypeTestUtil stricter, and validate user input higher up in the call tree
I prefer solution 2, so TypeTestUtil now checks that its input is a binary name without whitespace. Annotatable, which is a bit higher in the call tree, still cleans up the input strings, so it doesn't change behavior.
In PMD 7 I think we should be more restrictive vis à vis this user input, and sanitize it directly in the properties (eg with property constraints, refs #1432). Then we're sure that every class name we handle is a valid binary name.
The AssertionUtil here is extracted from the pmd 7 branch
- Fixes #2454

[java] Fix problem with whitespace in properties

---

.ci/files/project-list.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidInstantiatingObjectsInLoopsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CompareObjectsWithEquals.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UseEqualsToCompareStrings.xml

Fix a bug in type resolution, by which expressions like `a.m()` have type `a` and not whatever the return type of `m` is. The fixed issues are instances of this same problem. It was not introduced in type resolution by 6.30.0, only made discoverable because UseEqualsToCompareStrings was updated to use type resolution in #2934. 
This could be caused by unresolved local variables, though given how rotten the typeres code is I'm not sure. Other tests are failing now...
----
update
With these changes, in a call chain, the return type of method calls is now set on the PrimarySuffix that corresponds to the arguments. Previously, it was the PrimarySuffix for the method name, or the PrimaryPrefix, if the receiver is an ambiguous name (ASTName). This was inconsistent and hid the type of the …

[java] Fix method calls in type resolution

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedFormalParameterRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedLocalVariableRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
pmd-java/src/test/resources/ant/java/EncodingTestClass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedFormalParameter.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedLocalVariable.xml

This PR fixes #2957.
The following rules are affected:
- [UnusedAssignment](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedassignment) (Best Practices)
- [UnusedFormalParameter](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedformalparameter) (Best Practices)
- [UnusedLocalVariable](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedlocalvariable) (Best Practices)
The following variable names are ignored:
- any name starting with `ignored`, e.g. `ignoredParameter`
- any name starting with `unused`, e.g. `unusedVar`

[java] Make unused rules ignore some names

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml

Deprecates AvoidUsingShortType and SimplifyStartsWith, according to #2296 and #2740

[java] Deprecate some performance rules

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java
pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/internal/ElEscapeDetector.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml

Unescaped identifiers will no longer trigger VfUnescapeEl when used as arguments for inherently safe built-in functions like BEGINS() or AND().
Nor will they trigger VfUnescapeEl when used as in expressions that are evaluated on the server, e.g. the test parameter of IF() or CASE().
- Fixes [#3081](https://github.com/pmd/pmd/issues/3081)

[vf] VfUnescapeEl false-positive with builtin functions

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/TypesFromAst.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/AbstractHardCodedConstructorArgsVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/HardCodedConstructorArgsBaseRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/HardCodedCryptoKeyRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/InsecureCryptoIvRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ExprMirror.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ast/CtorInvocMirror.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/security/HardCodedCryptoKeyTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/security/InsecureCryptoIvTest.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/CtorInferenceTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/ast/CtorInvocMirrorTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/security/xml/InsecureCryptoIv.xml

* Updated both rules HardCodedCryptoKey and InsecureCryptoIv
* Enabled the unit tests
* Introduced a common package-private base class, since both rules do actually the same - checking for hard coded constructor arguments
- Part of #2701

[java] Update security rules for pmd7

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/documentation/ApexDocRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/documentation/xml/ApexDoc.xml

Grants the ability to report missing ApexDoc in classes, methods and properties that have a `private` or `protected` access modifier.
Two new properties have been added to the ApexDoc rule  
* `reportPrivate`
* `reportProtected`
Those have a `false` default value to avoid inconsistent behaviour with existing rulesets.
- Fixes #3075

[apex] ApexDoc optionally report private and protected

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediateIssue3106.pls

This fixes the ParseExeception for the PLSQL parser when it finds a statement like
EXECUTE IMMEDIATE 'drop database link ' || v_link_name;
- Fixes #3106

[plsql] Fix ParseException for EXECUTE IMMEDIATE str1||str2;

---

.ci/build-pr-win-macos.sh
.ci/build.sh
.ci/inc/maven-dependencies.inc

Use the `--no-transfer-progress` Maven option in the CI scripts.  We could also use batch mode (`-B`), but i'm not sure what else that changes
See also https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication 
I hope, this removes the rows of download progress from the build log. In a normal terminal these lines overwrite each other so it's not so noisy.
- Fixes #3067
I tried this out quickly in a docker but I'm not sure if there are other things it would break, or if I updated all the relevant places.

[ci] Stop logging download progress in CI

---

docs/pages/pmd/userdocs/configuring_rules.md
docs/pages/pmd/userdocs/cpd/cpd.md
docs/pages/pmd/userdocs/tools/maven.md

Affected pages:
* [CPD](https://pmd.github.io/latest/pmd_userdocs_cpd.html)
* [PMD: configuring rules](https://pmd.github.io/latest/pmd_userdocs_configuring_rules.html)
* [PMD: Maven plugin](https://pmd.github.io/latest/pmd_userdocs_tools_maven.html)

[doc] Fix sample code indentation in documentation

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MyList.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MyListAbstract.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/GitHubBug3101.java

If the explicit type arguments couldn't be resolved due to incomplete auxclasspath, we now use "Object" instead of null.
- Fixes #3101

[java] NullPointerException when running PMD under JRE 11 (fixes #3101)

---

docs/pages/release_notes.md
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CompareObjectsWithEquals.xml

Add a unit test to verify #2716
As described in the issue, with type resolution, this FP is not reproducible. Without type resolution, it is fixed since 6.30.0.
This uses the same test case as from https://github.com/pmd/pmd/commit/7c5fbb26ac402991f25837565c0aacbfbec9617b (pmd7). However, we probably get a merge conflict, or we get the test case twice. So, we need to watch out when merging master->pmd7.

[java] CompareObjectsWithEqualsRule: False positive with Enums

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

- Fixes #3133
~Hm... basically this adds now support for StringFormattedMessages, which not documented.... maybe we should update the rule doc?~ :heavy_check_mark:

[java] InvalidLogMessageFormat fix FP with StringFormattedMessage and ParameterizedMessage

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/properties/AbstractMultiValueProperty.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/ValueParserConstants.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/PropertyDescriptorTest.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

- Most single-valued properties are trimmed
- Some types keep whitespaces, e.g. Character and Regex
Fixes #3089

[core] Trim property values

---

docs/pages/release_notes.md
pmd-java/etc/grammar/Java.jjt
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/InfiniteLoopInLookahead.java

- fixes #3117
- backports part of StatementExpression production from pmd7
When the parse exception occurs, javacc tries to figure out, which tokens instead of the current one and which next tokens would make a valid source code. And there seems to be lots of options...
One way would be, to disable this feature (via ERROR_REPORTING=false). But I found the difference in the grammars between pmd6/pmd7: It's in the StatementExpression.

[java] Infinite loop when parsing invalid code nested in lambdas

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

[java] InvalidLogMessageFormat detection failing when String.format used

---

docs/pages/release_notes.md
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml

Add test case for #2427, already fixed since PMD 6.25.0

[java] ConsecutiveLiteralAppend false-positive with builder inside lambda

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/ConsecutiveLiteralAppendsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InsufficientStringBufferDeclaration.xml

[java] ConsecutiveLiteralAppends and InsufficientStringBufferDeclaration: FP with switch expressions

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml

- Fixes #3144 (doc update, examples)
- Fixes false negative with method calls as arguments

[java] GuardLogStatement: False negative with unguarded method call

---

pmd-java/src/main/resources/rulesets/java/quickstart.xml

Fixed package name from LoosePackageCouling -> LoosePackageCoupling.
There was a minor typo in `rulesets/java/quickstart.xml`

[java] Minor typo in quickstart ruleset

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

- fixes #3148
The problem with "!= null" comparison couldn't be reproduced. Depending on further feedback for #3148 this PR needs to be enhanced.

[java] CloseResource false positive with Objects.nonNull

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTMethod.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexRootNode.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/ast/InnerClassLocations.cls
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/ExcessiveClassLength.xml

- fixes #3142
Not perfect, but better than before. The classes at least look ok, but the synthetic methods/nodes (like UserClassMethods, BridgeMethodCreator) look still weird.

[apex] ExcessiveClassLength multiple warning on the same class

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

- Fixes #3118
- Is as good as "var", which means, we don't check / determine
the actual type. Could lead to false negatives, when overloaded
methods are used.

[java] UnusedPrivateMethod false positive when passing in lombok.val as argument

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit4SuitesShouldUseSuiteAnnotationTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit4TestShouldUseAfterAnnotationTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit4TestShouldUseBeforeAnnotationTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit4TestShouldUseTestAnnotationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4SuitesShouldUseSuiteAnnotation.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseAfterAnnotation.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseBeforeAnnotation.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseTestAnnotation.xml

Update 4 related rules in bestpractices.xml:
- JUnit4SuitesShouldUseSuiteAnnotation
- JUnit4TestShouldUseAfterAnnotation
- JUnit4TestShouldUseBeforeAnnotation
- JUnit4TestShouldUseTestAnnotation
Both `JUnit4TestShouldUse(After|Before)Annotation` now are more conservative when finding `setUp`/`tearDown` methods. 
- Items of #2701

[java] Update junit annotation rules

---

pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UseStandardCharsetsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseStandardCharsets.xml

(My first PR against PMD. Hopefully I did not screw up too badly :-D)
Starting with Java 7, StandardCharsets provides constants for common Charset objects, such as UTF-8.
Using the constants is less error prone, and can provide a small performance advantage compared to Charset.forName(...)
since no scan across the internal Charset caches is needed.
More discussion available in the linked issue
- Fixes #3190
Unsure about the last point, the xml rule definition contains description and example, is there anything else to add?

[java] New rule: UseStandardCharsets

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryReturnRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryReturnTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryReturn.xml

Update UnnecessaryReturn. The rule is more general than before, so I guess there will be fps to find out. But it will also be much more useful. Namely it now checks return statements in initializers, constructors, and lambdas properly. Also it doesn't flag just a return statement at the very end of a method, which is exceedingly rare and useless, but recurses to find out whether we're at the end of the control flow graph of the method. So it should handle arbitrarily complex code.
- Item of #2701

[java] Improve rule UnnecessaryReturn to detect more cases

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/performance/OperationWithLimitsInLoopRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/OperationWithLimitsInLoop.xml

This addresses some missing **static** method invocations of that also consume governor limits. 
- Relates to #3186 but doesn't fix it entirely, I'm afraid I don't have the knowledge to tackle the rest by myself

[apex] OperationWithLimitsInLoopRule: Support more limit consuming static method invocations

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/VariableNameDeclaration.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

In pmd 6, `getAccessNodeParent` returns null for record components.
- Fixes #3224

[java] Fix #3224 - UnusedAssignment crashes with nested records

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CheckSkipResult.xml

Now getUsages should not return null. Note that the variableNameDeclaration may still be null, but see 
https://github.com/pmd/pmd/blob/ac94110fc4e7e40fa85bc0804abb22c54c5ccb0c/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java#L278-L283
- Fixes #3169

[java] Fix #3169 - NPE in CheckSkipResult

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Remove assumption (and therefore bypassing of CRUD check) that a method is a Visualforce getter based on its signature. Naming doesn't guarantee it actually is a VF getter.
- Fixes #3210

[apex] ApexCRUDViolationRule: Do not assume method is VF getter to avoid CRUD checks

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleTargetSelector.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonExprTransformations.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQuery.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java

I noticed many java XPath rules were not recognized as rulechain ones and investigated. Saxon parses some expressions somewhat inconsistently. Now we have a normalization step that should bring more rules in line with what the RuleChainAnalyser expects.
Java rules that were not recognized as Rulechain and that now are:
- AvoidDecimalLiteralsInBigDecimalConstructor
- AvoidPrintStackTrace
- AvoidSynchronizedAtMethodLevel
- AvoidUsingVolatile
- DoNotUseThreads
- DontCallThreadRun
- EmptyMethodInAbstractClassShouldBeAbstract
- JUnit4TestShouldUseTestAnnotation
- LocalHomeNamingConvention
- LocalInterfaceSessionNamingConvention
- MDBAndSessionBeanNamingConvention
- RemoteInterfaceNamingConvention
- RemoteSessionInterfaceNamingConvention
- ReplaceHashtableWithMap
- ReplaceVectorWithList
- …

[core] Make more rules be recognized as rulechain (saxon HE)

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

`COUNT()` queries do expose data that should be enforced before querying since could expose the ability to count records on an object that the user may not have access to.
- Fixes #3202

[apex] ApexCRUDViolation: COUNT is indeed CRUD checkable since it exposes data (false-negative)

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTExpression.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTStatementExpressionList.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/BinaryOp.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ExprContext.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/LazyTypeResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/PolyResolution.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryCastRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeSystem.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/ConversionContextTests.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/ParserCornerCases.txt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/ParserCornerCases18.txt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryCast.xml

Fix some FNs of UnnecessaryCast (the 7.0 version, #3204) by improving the underlying context machinery. Some of the new FNs are unboxing casts for a Boolean in eg
```java
assert (boolean) boxedBool;
if ((boolean) boxedBool);
```
but also casts in arithmetic expressions:
```java
// given: int i;
i * (int) i
i << (int) i
```
I think this could be added to the pmd 7 release notes as is.
TODO:
```java
char c;
"(" + (int) c + ")" + c; // the toString is different -> necessary (string contexts aren't implemented yet)
Integer integer;
(int) integer + 1.0 // integer is unboxed to int, then widened to double -> unnecessary
```

[java] Improve ExprContext, fix FNs of UnnecessaryCast

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldDeclarationsShouldBeAtStartOfClassRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FieldDeclarationsShouldBeAtStartOfClass.xml

This fixes a false negative found in #2687 :
https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/InputMultipleVariableDeclarations.java#L66
Code sample:
```java
public class TestFieldDeclarations {
class Inner {
void method1() { }
private int field1; // violation 1
private Inner anon = new Inner() { // ignored due to ignoreAnonymousClassDeclarations
void method2() { }
private int field2; // violation 2
};
}
}
```
Violation 2 is currently not detected.
:warning: This rule is already updated on the pmd7 branch!

[java] FieldDeclarationsShouldBeAtStartOfClass: false negative with anon classes

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodArgumentCouldBeFinalRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningLoopVariables.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/MethodArgumentCouldBeFinal.xml

This fixes a couple of false negatives in [MethodArgumentCouldBeFinal](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#methodargumentcouldbefinal) which have been found in #2687 .
It also adds additional test cases for [AvoidReassigningLoopVariables](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#avoidreassigningloopvariables), but this rule already worked correctly (by using rulechain).
Note: :warning: The rule MethodArgumentCouldBeFinal has already been updated in pmd7 branch.
Here's the code sample:
```java
public interface DefaultMethodInInterface {
default String toString(Object one) { // one could be final
return toString(one, one);
}
String toString(Object one, Object two);
default Object justReturn(Object o) { // o cold be final
return o;
}
}
public …
```

[java] MethodArgumentCouldBeFinal: false negatives with interfaces and inner classes

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CompareObjectsWithEquals.xml

Improve CompareObjectsWithEquals
- Fixes #3110: add a property with a list of exceptions. 
- Fixes #3205: ignore comparison against constants. "Constants" are found by looking for an all-caps identifier. There's no property to disable that, because I'm not sure it would be worth the complexity. In pmd 7 we could improve that to look at whether the field is a final one, using the symbol. The one thing I'm not sure about is, that some types should most likely never be compared by reference, even against constants (String)...
Also we could maybe whitelist comparing against `this` altogether, instead of looking for an enclosing `equals` method... Maybe not in this pr

[java] Improve CompareObjectsWithEquals

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml

[java] Fix LiteralsFirstInComparison ignoring constants

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/bestpractices.xml

The rule should be renamed `NonExhaustiveSwitchStatement` eventually.
- Fixes #2737

[java] Fix misleading rule message on rule SwitchStmtsShouldHaveDefault with non-exhaustive enum switch

---

.github/workflows/build.yml
.github/workflows/troubleshooting.yml
docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java

In one of the last pmd regression reports, strange new errors appeared, e.g.
https://chunk.io/pmd/0263b81c16b8417b993b6ea93f55d7be/diff/spring-framework/index.html#section-errors
```
Caused by: java.lang.NullPointerException
at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.isSubtypeable(MethodTypeResolution.java:692)
at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.isSubtypeable(MethodTypeResolution.java:656)
at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.selectMethodsFirstPhase(MethodTypeResolution.java:165)
at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.getBestMethodReturnType(MethodTypeResolution.java:381)
at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:445) …
```

[java] Fix NPE in MethodTypeResolution

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/util/StringUtilTest.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeTestUtil.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

[java] Fix #1175 - UnusedPrivateMethod FP with Junit 5 @MethodSource

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidFieldNameMatchingTypeNameRule.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidFieldNameMatchingTypeName.xml

Fields in interfaces and nested classes have not been considered, e.g.
```java
interface Operation {
Object apply();
final Operation OPERATION = () -> { return null; };  // Violation expected here
class Inner {
int inner; // Violation expected here
}
}
```
This was originally found by #2687 in https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameLambda.java#L31
It's fixed by using rulechain and skipping interfaces. The rule name just mentions "type name", in the rule description for [AvoidFieldNameMatchingTypeName](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#avoidfieldnamematchingtypename) it says "class". But I don't see a reason, why to exclude …

[java] AvoidFieldNameMatchingTypeName: False negative with interfaces

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidReassigningParametersRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningParameters.xml

[java] AvoidReassigningParameters reports violations on wrong line numbers

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/GenericLiteralCheckerRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/StringConcatenationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/SymbolTableTestRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/UselessAssignment.java

These are in rules, that are not really in use, so shouldn't
have any effect.
I'm eager to know, how the regression tester reacts to these.... these are rules, that are not referenced in any ruleset.
This PR is part of the older PR #2687 .

[java] Minor rulechain usage fixes

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ConstructorCallsOverridableMethod.xml

This fixes a IOOBE with annotations in the rule [ConstructorCallsOverridableMethod](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#constructorcallsoverridablemethod). From now on, annotations are ignored like enums.
The bug was mentioned here: https://chunk.io/pmd/c971f51d18f6444aab9ee0363d6d1204/diff/checkstyle/index.html#section-errors
while analyzing: https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java
For reference, the original stacktrace:
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at …
```

[java] ConstructorCallsOverridableMethod: IndexOutOfBoundsException with annotations

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/OnlyOneReturnRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/OnlyOneReturn.xml

Converts the rule [OnlyOneReturn](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#onlyonereturn) to use rulechain. Now all method
declarations are visited regardless where they are
nested.
This FN has been found via #2687.
Example code:
```java
public class OnlyOneReturn {
void foo() {
Object o = new Object() {
void method(int i) {
switch (i) {
case 1: return;  // missing violation
case 2: return; // missing violation
}
return;
}
};
}
}
```
Note: this rule has already been converted in pmd7

[java] OnlyOneReturn: false negative with anonymous class

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryLocalBeforeReturn.xml

The rule [UnnecessaryLocalBeforeReturn](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#unnecessarylocalbeforereturn) uses rule chain now, so that each return is visited,
also in lambdas and anonymous classes.
This FN has been found via #2687.
Example code:
```java
import java.util.concurrent.Callable;
public class UnnecessaryLocal {
void foo() {
Callable<String> c = () -> { String s = "1"; return s; };
}
}
```
Note: this rule has already been converted in pmd7

[java] UnnecessaryLocalBeforeReturn: false negatives with lambda and anon class

---

docs/pages/pmd/userdocs/cli_reference.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
pmd-core/src/main/java/net/sourceforge/pmd/util/IOUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/cli/FakeRuleset.xml
pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java

(The bug was that the parent directories of the report file were not created. The file itself was already properly created.)
Fixes #2639

[core] Fix #2639, create report file directories if they do not exist

---

BUILDING.md
docs/pages/pmd/devdocs/building.md
docs/pages/pmd/userdocs/installation.md
docs/pages/release_notes.md
pmd-dist/pom.xml
pmd-dist/src/test/java/net/sourceforge/pmd/it/AllRulesIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-javascript/pom.xml
pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptParserTest.java
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/jquery-selector.txt
pom.xml

*   Convert pmd-javascript to a java8 module
*   Fixes #699
*   Fixes #2081
This PR replaces the older #2906 
Note: This introduces some incompatibility: From now on, at least Java 8 is required to analyze JavaScript code.
We did a similar upgrade with VisualForce in [6.30.0](https://github.com/pmd/pmd/releases/tag/pmd_releases%2F6.30.0).

[javascript] Update Rhino library to 1.7.13

---

pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit5TestShouldBePackagePrivateTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit5TestShouldBePackagePrivate.xml

Add the rule to check that JUnit5 tests methods and classes are package private.
Add unit tests
Propose a codestyle rule for Jupiter / JUnit5 tests according to the feedback received from @adangel in the issue.
Not sure how to add the 'externalInfoURL', so simply pointed at the rule name, assuming that the site is generated from the XML rule file
- Fixes #3239 
- Relates #3288 - that's another rule to handle private tests

[java] New rule: JUnit5TestShouldBePackagePrivate

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/Report.java
pmd-core/src/main/java/net/sourceforge/pmd/ThreadSafeReportListener.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDCommandLineInterface.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PmdParametersParseResult.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/BaseLanguageModule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/Language.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageRegistry.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersion.java
pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java

Deprecate some more APIs around PMD's entry point (cf #2635), including ThreadSafeReportListener (#3196). Introduce some replacements and newer APIs, including an enum for PMD's status code (which allows for better documentation), and a way to parse CLI arguments into a configuration without using internal APIs (as suggested on gitter some time ago by @KroArtem).
The main takeaway is that `PMD#run` is deprecated in favor of `PMD#runPmd`. 
~TODO I think we should also deprecate the system properties defined in `PMDCommandLineInterface`: `net.sourceforge.pmd.cli.noExit` and `net.sourceforge.pmd.cli.status`. There's `PMD#runPmd` which doesn't call `System.exit`, and ideally `PMD#main` would always call `System.exit`. Clients can chose the behavior they want without system properties.~ …

[core] Deprecate more APIs around PMD's entry point

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/InaccessibleAuraEnabledGetterRule.java
pmd-apex/src/main/resources/category/apex/errorprone.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/InaccessibleAuraEnabledGetterTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/InaccessibleAuraEnabledGetter.xml

In the Summer '21 release, a mandatory [security update](https://help.salesforce.com/articleView?id=release-notes.rn_lc_enforce_prop_modifiers_cruc.htm&type=5&release=232) enforces access modifiers on Apex properties in Lightning component markup. The update prevents access to private or protected Apex getters from Aura and Lightning Web Components.
This rule detects and reports such getters.
- Fixes #3321

[apex] added rule to detect inaccessible AuraEnabled getters

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

Update [UnnecessaryImport](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#unnecessaryimport) to recognize usage of imported types in javadoc's `@exception` tag.
This fixes a false positive.
According to the javadoc docs, this tag is equivalent to `@throws` and not deprecated:
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDCEAHH
> **@exception** **_class-name description_**
>
>    Introduced in JDK 1.0
>
>    Identical to the @throws tag. See [@throws _class-name description_](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDCHAHD).
https://github.com/pmd/pmd/commit/77e3c19cb28e0250f67348691c2dfe421a187eab#r51465948
-----
First commit locally failed - as expected.

[java] Update UnnecessaryImport to recognize usage of imported types in javadoc's `@exception` tag

---

docs/report-examples/pmd-report.sarif.json
pmd-core/src/main/java/net/sourceforge/pmd/renderers/internal/sarif/SarifLog.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/internal/sarif/SarifLogBuilder.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/SarifRendererTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-multiple.sarif.json
pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected.sarif.json

First time contributor (long time fan) so please go easy on me 😄 this adds the fullDescription, help and tags attributes into the SARIF report being produced (both compliant in the [SARIF 2.1.0 schema](https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json)). These fields also have support in [GitHub](https://docs.github.com/en/code-security/secure-coding/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object) and was hoping that by adding them into the SARIF report produced I could make use of it in the [PMD Analyser GitHub Action](https://github.com/synergy-au/pmd-analyser-action) I was working on.
I didn't try the complete build as was trying to make the change in GitHub Codespaces (so was unsure if it was …

[core] Adds fullDescription and tags in SARIF report

---

pmd-apex/src/main/resources/category/apex/performance.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/performance/AvoidDebugStatementsTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/AvoidDebugStatements.xml

Flags usage of `System.debug` statements since it's demonstrated that impacts performance even when no debug traces are active. Also promoting the usage of Apex Replay Debugger and Checkpoints that doesn't pollute the code and grants most of the functionality.
- Fixes #3307

[apex] New AvoidDebugStatements rule to mitigate performance impact

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml

[java] GuardLogStatement: False positive with compile-time constant arguments

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

identically named String variable
Uses symbol table to find a referenced variable.
- Fixes #3284

[java] InvalidLogMessageFormat may examine the value of a different but identically named String variable

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml

Now we also consider the left hand side of the method call. The easy cases are supported:
* referencing a field in the local class
* referencing a static field in a different class
This basically does some reimplementation of the type res in the rule, so that we know the type and field on which the method is called. The current type res just gives as the type of the method result.
The solution here is not nice, but maybe good enough for PMD 6. I'm sure that the solution in PMD 7 will be much easier.
Note: This rule has already been converted  in PMD 7 - so we should expect some merge conflicts when merging master->pmd/7.0.x later.
- Fixes #3315

[java] LiteralsFirstInComparisons false positive with two constants

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml

As described in https://github.com/pmd/pmd/issues/1455#issuecomment-851667408, JUnit5 and AssertJ do assertions with the pattern `Assertions.assert*`
This pattern is not recognized by rule [JUnitTestsShouldIncludeAssert](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#junittestsshouldincludeassert)
Add this pattern to the existing patterns to avoid the false positive
Also add a test case.
- Refs #1455 ~Partially fixes it~
- Fixes #3341

[java] JUnitTestsShouldIncludeAssert Tweak assertion definition to avoid false positive with modern JUnit5

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloneMethodMustImplementCloneableRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloneMethodMustImplementCloneable.xml

**Rule:** [CloneMethodMustImplementCloneable](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#clonemethodmustimplementcloneable)
**Description:**
This PR fixes a false negative for local classes defined inside methods.
**Code Sample demonstrating the issue:**
```java
public class Outer {
public static class Inner {
public Object clone() throws CloneNotSupportedException {
return super.clone();
}
}
public void foo() {
class Local {
public Object clone() throws CloneNotSupportedException {      // <---- missing violation
return super.clone();
}
}
}
}
```
Original occurrences:
* https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassBasic.java#L39
* …

[java] CloneMethodMustImplementCloneable: FN with local classes

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientEmptyStringCheckRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/inefficientemptystringcheck/StringTrimIsEmpty.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/inefficientemptystringcheck/StringTrimLength.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/inefficientemptystringcheck/StringTrimMethodArgument.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientEmptyStringCheck.xml

**Rule:** [InefficientEmptyStringCheck](https://pmd.github.io/latest/pmd_rules_java_performance.html#inefficientemptystringcheck)
**Description:**
This PR fixes a false negative for calls to trim().length() and trim().isEmpty() when used as method arguments
**Code Sample demonstrating the issue:**
```java
public class StringTrimLength {
String get() {
return "foo";
}
void bar() {
if (get().trim().length() == 0) {
// violation missing
}
if (this.get().trim().length() == 0) {
// violation missing
}
String bar = get();
if (bar.trim().length() == 0) {
// violation already detected
}
if (bar.toString().trim().length() == 0) {
// violation missing
}
}
}
```
```java
package net.sourceforge.pmd.lang.java.rule.performance.inefficientemptystringcheck;
public class StringTrimMethodArgument {
public …
```

[java] InefficientEmptyStringCheck FN with trim.length on method call

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimedOperationCategory.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/ClasspathEntryFingerprinter.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/ClasspathFingerprinter.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/NoopFingerprinter.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/RawFileFingerprinter.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/ZipFileFingerprinter.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/internal/AbstractClasspathEntryFingerprinterTest.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/internal/RawFileFingerprinterTest.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/internal/ZipFileFingerprinterTest.java

As per #2704, we improve on the classpath checksum computation to detect changes.
While the old implementation performed full reads of all files in the classpath to compute an Adler32 checksum, we now introduce a series of fingerprinting strategies, specialized for different file formats:
- For .class files, we still perform the same old whole-file checksum
- For .jar / .zip files, we first tinker with the entries to:
- Ignore non .class files
- Sort all entries (order is irrelevant, well-formed jars don't include duplicates)
- Focus on the archived file contents themselves (their checksum) rather than any metadata (ie: modification time)
- For all other files, we ignore them (noop)
The ignoring of irrelevant changes both within jar / files and simply referenced in the classpath improves …

[core] Better classpath fingerprinting

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml

Ignores now log calls without any arguments
- Fixes #3340

[java] NullPointerException applying rule GuardLogStatement

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ConstructorCallsOverridableMethod.xml

[java] Fix #3305 - ConstructorCallsOverridableMethod NPE with records

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Report SOQL CRUD check absence on for-loops
- Fixes #3329

[apex] Check SOQL CRUD on for loops

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/TokenEntry.java

This PR optimizes the state saving mechanism for --skip-lexical-errors option:
1. Instead of copying the `tokens` array for all files processed so far, just save the array index and remove entries after the index when doing the recovery. This is appropriate because tokenizing the current file can't affect the tokens of previous files even when a lexical error occurs.
2. Similarly, instead of copying the "token content to unique integer" map, save the current map size and remove entries added afterwards when doing the recovery. The added entries can be easily identified because the unique integer is assigned as "current map size + 1".
I did some benchmarking and it shows that the performance gain is substantial for large projects:
- Project: https://github.com/pmd/pmd/ (Java / 2,871 files …

[core] CPD: Optimize --skip-lexical-errors option

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/internal/Helper.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/main/resources/category/apex/security.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Until now `ApexCRUDViolation` didn't support checks when using the `Database` class DML methods, only the inline DML statements.
Also when a DML statement was issued with an inline instantiation of an SObject without any arguments it was not checked. Similarly with an inline instantiation of an SObject list with inline item adding.
- Fixes #3201

[apex] Add ApexCRUDViolation support for database class, inline no-arg object construction DML and inline list initialization DML

---

Dangerfile

This prevents failing rules in pmd 7 to make the regression tester fail entirely. This is a stopgap, that we can revert when all rules have been ported (#2701)
The following PRs have recently had problems in CI that this should "solve":
- #3384
- #3389
- #3396
- #3397 
-

[ci] Stop autogenerating ruleset from branch differences

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/BigIntegerInstantiationRule.java
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/BigIntegerInstantiationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/BigIntegerInstantiation.xml

Part of #2701 
It also adds support for BigInteger.TWO, which was added with Java9.

[java] Update BigIntegerInstantiation

---

.ci/build.sh
pom.xml

This is only executed on push builds. In order to do this,
we must change the version temporarily to avoid a circular
dependency to ourselves.
The latest version is brought in via the maven profile "pmd-dogfood"
and the property "pmd.dogfood.version".
That way we hopefully see potential problems earlier.

[ci] Run PMD on PMD with the latest snapshot

---

.ci/inc/regression-tester.inc

This should fix the problems, that danger is not running with the following error:
```
bundler: failed to load command: danger (/home/runner/work/pmd/pmd/vendor/bundle/ruby/2.7.0/bin/danger)
RuntimeError: Cannot find a merge base between danger_base and danger_head.
```
Last time this happened on pmd/7.0.x , see #3408.
Now we correctly fetch both branches: the base branch on which the PR is based and PR's head branch.
Previously we fetched only HEAD^2 which was only one side. And we only fetch master, so the code didn't work properly for pmd/7.0.x.
The workaround for PRs that are failing with this message is: merge in the base branch.

[ci] Fetch more commits for danger and regression tester

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ReturnEmptyCollectionRatherThanNullTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReturnEmptyCollectionRatherThanNull.xml

Create a new `ReturnEmptyCollectionRatherThanNull` to supersede the old `ReturnEmptyArrayRatherThanNull`.
The same principle applies not only to arrays, but to all collections (`java.util.Collections` even providing easy no-alloc methods to return empty maps, lists and sets).
I doubted if this should more generally look at any `java.lang.Iterable`, but I felt that was stretching it too much (and it would not on it's own consider maps).

[java] New rule ReturnEmptyCollectionRatherThanNull

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/TokenEntry.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/Tokens.java

Follow up on https://github.com/pmd/pmd/pull/3385/files#r665984073
@jsotuyod I needed to undo a bit your changes as otherwise we would expose "State" in our API in Tokens.
Instead of adding the old methods  back as deprecated I simply internalized the inner class as suggested by @oowekyala .
- Refs #3385

[core] Internalize cpd.TokenEntry.State

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersion.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/BigIntegerInstantiationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UnnecessaryWrapperObjectCreationRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/JavaLanguageModuleTest.java

This didn't work with java 9 compared to java 10,
as the full name was compared ("Java 9" vs. "Java 10")
as a string rather than using version numbers.
Now the logic is much simpler: The versions defined
for a language are ordered, new versions are always added
at the end.
Also backports the useful method "compareToVersion" from pmd 7
and use this in the rules BigIntegerInstatiation and
UnnecessaryWrapperObjectCreation.
- I found this problem while fixing #3393 . So after this is merged, that can be simplified.
- Fixes #1603

[core] Fix LanguageVersion compareTo

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodNamingConventionsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/MethodNamingConventions.xml

- Consider parameterized JUnit5 tests for methodNaming Conventions ;
- Already fixed for PMD 7.0.0 but with no release date, I hope that this can be useful for PMD 6.x.x ;)
- Fixes #3403

[java] Fix #3403 about MethodNamingConventions and JUnit5 parameterized tests

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidAccessibilityAlterationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidAccessibilityAlteration.xml

This adds tests for the rule - they were completely missing.
It also changes the rule to be less surprising (at least for me).
**Main changes:**
* only calls to `setAccessible(true)` are now detected.
* a call to `setAccessible(false)` is now explicitly allowed (this would restore the Java language access controls, so that private member can't be accessed anymore from outside)
* previously calls to `getDeclaredContructors()` (etc..) were detected, but just getting these reflected objects doesn't do any harm yet. So, these calls are not reported anymore. This results in maybe different line numbers.
* When the call to `setAccessible(true)` is within a `PrivilegedAction`, then it is considered deliberate and ignored.
- See also #3010

[java] AvoidAccessibilityAlteration: add tests and fix rule

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java

For now, we don't try to optimize the expression for
rulechain. Although it would be theoretically possible:
the manual optimization looks like variant3 in the
unit test.
The expression
```
//(NodeA | NodeB | NodeC)//NodeD[pmd:customFunction('foo')]
```
was not optimized correctly - the first part with the combined node test was ignored, so that all NodeD nodes have been found.
The equivalent expression
```
(//NodeA | //NodeB | //NodeC)//NodeD[pmd:customFunction('foo')]
```
suffered from the same problem.
The workaround is to expand the expression manually:
```
//NodeA//NodeD[pmd:customFunction('foo')]
|
//NodeB//NodeD[pmd:customFunction('foo')]
|
//NodeC//NodeD[pmd:customFunction('foo')]
```
- See https://stackoverflow.com/questions/69012708/how-do-i-create-a-custom-pmd-rule-to-check-if-a …

[core] Fix XPath rulechain with combined node tests

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InsufficientStringBufferDeclaration.xml

... when StringBuilder is used in lambda and if without else
Found this in one of the regression reports, e.g. https://chunk.io/pmd/6ba1372f8806483e8fe17a4901bc6823/diff2/openjdk-11/index.html#section-errors
In Patterns.java and IllegalAccessLogger.java

[java] InsufficientStringBufferDeclaration: Fix NPE

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ParametricRuleViolation.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/rule/EcmascriptRuleViolationFactory.java
pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/EcmasccriptLanguageModuleTest.java

AbstractEcmascriptRule has a function that takes begin and end lines as parameters. However when using, it produces a null pointer exception. This solution adds the call to the constructor for ParametricRuleViolation in which it was added support for those two line parameters. The new constructor calls the default constructor and then sets the line parameters. 
- Fixes #

[javascript] NPE while creating rule violation when specifying explicit line numbers

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UselessStringValueOfRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UselessStringValueOf.xml

[java] Created fix for UselessStringValueOf false positive

---

.ci/files/project-list.xml
.ci/inc/regression-tester.inc
.github/workflows/build.yml
.github/workflows/troubleshooting.yml
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java

[ci] Upgrade regression tester projects

---

.ci/files/project-list.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/SupertypeCheckCache.java

After upgrading the regression tester projects (#3640), we fail now with `java.lang.OutOfMemoryError: Java heap space`.
I've analyzed the problem and found out, that we keep adding objects into [SupertypeCheckCache](https://github.com/pmd/pmd/blob/pmd/7.0.x/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/SupertypeCheckCache.java). Interestingly, the cache doesn't grow beyond 50 elements, but we have one key ("java.lang.String") with an enormous amount of subtypes...
It turns out, that these subtypes are `InferenceVar`s - I think, we can skip these.
However, now I don't get an OOM anymore, but PMD freezes on a specific file. So, the OOM was just one symptom. The problematic file is [InputJavaParserNoFreezeOnDeeplyNestedLambdas](https://github.com/checkstyle/checkst …

[java] SupertypeCheckCache - exclude also subtypes from caching

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SwitchDensityRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidMultipleUnaryOperatorsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidUsingOctalValuesRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CheckSkipResultRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SwitchDensity.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CheckSkipResult.xml

* Continuation of #2687 
* Contains fixes and tests for
* SingularField
* SwitchDensity
* AvoidMultipleUnaryOperators
* AvoidUsingOctalValues
* CheckSkipResult
- Fixes #3620

[java] Rule improvements part 3

---

docs/pages/pmd/userdocs/tools/tools.md

[Code Inspector](https://www.code-inspector.com) is rebranding as [Codiga](https://www.codiga.io). Therefore, we are changing our references in the PMD documentation and making sure references are up to date.

[doc] Rename Code Inspector to Codiga

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordDeclaration.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

This fixes a ClassCastException in CloseResource
This was found when updating the regression tester projects (#3640).
<details>
<summary>original stack trace</summary>
<pre>
java.lang.ClassCastException: class net.sourceforge.pmd.lang.java.ast.ASTFieldDeclaration cannot be cast to class net.sourceforge.pmd.lang.java.ast.ASTLocalVariableDeclaration (net.sourceforge.pmd.lang.
java.ast.ASTFieldDeclaration and net.sourceforge.pmd.lang.java.ast.ASTLocalVariableDeclaration are in unnamed module of loader 'app')
at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.getDeclaredTypeOfVariable(CloseResourceRule.java:209)
at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.getTypeOfVariable(CloseResourceRule.java:205)
at …

[java] Local records are a find boundary

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedLocalVariable.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml

This affects at least UnusedLocalVariable and UnusedPrivateField.
I found this while trying to run PMD 7 on PMD 7 sources (dogfood).
Sample false positives:
*   `[INFO] PMD Failure: net.sourceforge.pmd.internal.GraphUtils:45 Rule:UnusedLocalVariable Priority:1 Avoid unused local variables such as 'i'..`
https://github.com/pmd/pmd/blob/f36b99fbd755fbe2f6f4f8b35a4299a936305e26/pmd-core/src/main/java/net/sourceforge/pmd/internal/GraphUtils.java#L45
i++ or ++i is not considered a usage...
or String id = "n" + i++; is not considered a usage
*   `[INFO] PMD Failure: net.sourceforge.pmd.internal.util.IteratorUtil$11:369 Rule:UnusedPrivateField Priority:1 Avoid unused private fields such as 'yielded'..`
https://github.com/pmd/pmd/blob/f36b99fbd755fbe2f6f4f8b35a4299a936305e26/pmd-core/src/main/java …

[java] Fix unused variable/field detection with unary expressions

---

pmd-java/pom.xml

Update log4 to 2.16.0 to harden defaults.
Based on CVE-2021-45046 the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations.
for more details CVE-2021-45046 (https://nvd.nist.gov/vuln/detail/CVE-2021-45046)

[java] Bump log4j to 2.16.0

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/documentation/ApexDocRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/documentation/xml/ApexDoc.xml

Adds a new 'reportProperty' property to the Apex Documentation rule which is enabled by default. When disabled, properties are not evaluated for ApexDoc comments regardless of access level.
This solves a request I had personally. While I appreciate ApexDoc comments for classes and methods, they become unwieldy for properties since they require 3 lines of comment for each property. Adding this new property allows you to enforce ApexDoc comments for classes and methods without requiring them for properties.

[apex] ApexDoc: Add reportProperty property

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/missingoverride/AbstractBuilderMixedTypeVarOverride.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MissingOverride.xml

I found this while trying to run PMD 7 on PMD 7 sources (dogfood).
It addresses the following false positive:
*   `[INFO] PMD Failure: net.sourceforge.pmd.properties.PropertyBuilder$GenericCollectionPropertyBuilder:402 Rule:MissingOverride Priority:1 The method 'defaultValue(Collection<? extends V>)' is missing an @Override annotation..`
https://github.com/pmd/pmd/blob/f36b99fbd755fbe2f6f4f8b35a4299a936305e26/pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyBuilder.java#L402
The java compiler doesn't allow here an `@Override`. We would need to use `C val` instead of `Collection<? extends V> val`.
While this erased type for both is `Collection`, the java compiler doesn't see it that way...

[java] MissingOverride - fix false positive with mixing type vars

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LooseCouplingRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LooseCoupling.xml

I found this while trying to run PMD 7 on PMD 7 sources (dogfood).
It addresses the following false positive:
*   `[INFO] PMD Failure: net.sourceforge.pmd.properties.GenericMultiValuePropertyDescriptor:26 Rule:LooseCoupling Priority:1 Avoid using implementation types like 'C'; use the interface instead.`
with generics...
https://github.com/pmd/pmd/blob/f36b99fbd755fbe2f6f4f8b35a4299a936305e26/pmd-core/src/main/java/net/sourceforge/pmd/properties/GenericMultiValuePropertyDescriptor.java#L26

[java] LooseCoupling - fix false positive with generics

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReturnEmptyCollectionRatherThanNull.xml

Fixed XPath for the [ReturnEmptyCollectionRatherThanNull](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#returnemptycollectionratherthannull) rule.
- Fixes #3686

[java] Fix for #3686 - Fix ReturnEmptyCollectionRatherThanNull

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml

Fixed [MissingStaticMethodInNonInstantiatableClass](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#missingstaticmethodinnoninstantiatableclass) for method local classes:
```java
public class Foo {
void method() {
class InnerClass {
private InnerClass() {
}
}
InnerClass innerClass = new InnerClass();
}
}
```
- Fixes #3701

[java] Fix #3701 - fix MissingStaticMethodInNonInstantiatableClass for method local classes

---

pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java

Varargs support was added to `NoWhitespaceAfterCheck`, wercker was failing on PMD.
CS PR: https://github.com/checkstyle/checkstyle/pull/11198
```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle-check) @ pmd-core ---
[INFO] There is 1 error reported by Checkstyle 9.3-SNAPSHOT with
/net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java:[240,88] 
(whitespace) WhitespaceAfter: '...' is not followed by whitespace.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for PMD 6.42.0-SNAPSHOT:
```

[core] Updated SaxonXPathRuleQueryTest.java

---

pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/FinalFieldCouldBeStatic.xml

Improved previous fix for the [FinalFieldCouldBeStatic](https://pmd.github.io/latest/pmd_rules_java_design.html#finalfieldcouldbestatic) rule - #3724.
- Fixes #3679

[java] #3724 - fix FinalFieldCouldBeStatic: triggers only if the referenced name is static

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InsufficientStringBufferDeclaration.xml

Fix bug #3712 where StringBuilder.setLength(int) is incorrectly flagged when the initial constructor capacity cannot be determined.
- Fixes #3712

[java] Fix #3712: InsufficientStringBufferDeclaration setLength false positive

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/DataType.java

Varargs support was added to `NoWhitespaceAfterCheck`, wercker was failing on PMD.
CS PR: https://github.com/checkstyle/checkstyle/pull/11198
```
INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle-check) @ pmd-visualforce ---
[INFO] There is 1 error reported by Checkstyle 9.3-SNAPSHOT with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
[ERROR] src/main/java/net/sourceforge/pmd/lang/vf/DataType.java:[124,49] (whitespace) WhitespaceAfter: '...' is not followed by whitespace.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for PMD 6.42.0-SNAPSHOT:
[INFO] 
[INFO] PMD ................................................ SUCCESS [  2.490 s]
[INFO] PMD
```

[visualforce] Updated DataType.java

---

pmd-core/src/main/java/net/sourceforge/pmd/internal/util/IteratorUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InternalApiBridge.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/OverrideResolutionPass.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaAstProcessor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloneMethodMustImplementCloneableRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ProperCloneImplementationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SuperTypesEnumerator.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/OverrideResolutionTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/SuperTypesEnumeratorTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UselessOverridingMethod.xml

Move the logic that's currently in MissingOverrideRule into a separate attribution pass, so that every rule can benefit from it.
- Fixes #3749

[java] Improve ASTMethodDeclaration::isOverridden

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/documentation/ApexDocRule.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/SuppressWarningsTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRuleTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsNestedClassTest.java
pmd-core/src/main/java/net/sourceforge/pmd/Report.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java
pmd-core/src/main/java/net/sourceforge/pmd/ThreadSafeReportListener.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleViolationFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
pmd-core/src/test/java/net/sourceforge/pmd/stat/MockStatisticalRule.java
pmd-core/src/test/java/net/sourceforge/pmd/stat/StatisticalRuleTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/SuppressWarningsTest.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/AvoidTabCharacterRule.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/LineLengthRule.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/PLSQLXPathRuleTest.java
pmd-scala-modules/pmd-scala-common/src/test/java/net/sourceforge/pmd/lang/scala/rule/ScalaRuleTest.java

Deprecations for #3692 
Unresolved points:
I looked into the designer sources and don't think the designer needs an update.
-  #3692

[core] Deprecations for analysis listeners

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ConfusingTernaryRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ConfusingTernary.xml

[java] Fix #278 - ConfusingTernary should treat `!= null` as positive condition

---

docs/pages/release_notes.md
pmd-java/etc/grammar/Java.jjt
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/jdk9_try_with_resources.java

The LOOKAHEAD(2) was not enough as `f.in` may begin a qualified type of a local var-ish resource, or a concise resource.
- Fixes #3697

[java] Fix #3697 - lookahead error in concise resource spec

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/internal/CliMessages.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/CpdExecutor.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/ExecutionResult.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java
pmd-dist/src/test/resources/sample-source/unparsable/cannot_be_parsed.java

[core] Fix #3427 - Stop printing usage text on error

---

.ci/build.sh

This unifies the build configuration. The dogfood build is now run also for PRs.
In future, we should probably split up the build into multiple jobs that can run in parallel (e.g. regression tester in parallel to dogfood). Then the build log would be better consumable.
This requires however to share files between the jobs to avoid rebuilding PMD over and over again (e.g. dogfood reuses the just now built PMD from the local maven repo and regression tester reuses the existing pmd-dist/target/pmd-bin-*.zip file).

[ci] Run dogfood for PRs and PMD7

---

docs/_layouts/default.html
docs/_layouts/page.html
docs/css/customstyles.css
docs/js/customscripts.js

Moves the existing table of contents to a floating 'sticky' table of contents in the free space of the upper right side of the documentation pages. On small screens the table of contents is not affected.
- Fixes #2502

[doc] Add floating table of contents (issue #2502)

---

docs/pages/pmd/userdocs/tools/ant.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/ant/PMDTask.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java

Also change the default to "1" to be consistent with
CLI `--threads` parameter.
See also #3806

[doc] Document Ant Task parameter `threads`

---

docs/css/customstyles.css

Makes documentation website table of contents scrollable on pages with many subheadings. Leaves pages with small number of subheadings and the small screen view unchanged.
- Fixes #3812

[doc] Make TOC scrollable when too many subheadings

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexHandler.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/internal/ApexDesignerBindings.java

Small enhancement for Apex + Designer - now the name of the called method is displayed:
- none

[apex] Add designer bindings to display main attributes

---

docs/pages/release_notes.md
pmd-modelica/pom.xml
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/AmbiguousResolutionRule.java
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/ConnectUsingNonConnector.java
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/bestpractices/AmbiguousResolutionRule.java
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/bestpractices/ConnectUsingNonConnectorRule.java
pmd-modelica/src/main/resources/category/modelica/bestpractices.xml
pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java

Found this, while working on the Kotlin branch. We stopped checking for our rulesets since we moved from rulesets to categories.

[core] Fix abstract ruleset factory test

---

.ci/files/project-list.xml

We modify (among other files) AutowiredAnnotationBeanPostProcessor.java
but only, when we intend to build the project. This leads to
the situation, that the baseline was created against the
modified file, but PRs use the unmodified file. This is because
the regression-tester does a "git reset --hard" before running
PMD.
Now we patch spring always and only skip the gradle calls.
This should fix Regression Reports like this one (from #3807):

[ci] Fix project-list for spring

---

docs/_data/sidebars/pmd_sidebar.yml
docs/_data/xpath_funs.yml
docs/_includes/custom/xpath_fun_doc.html
docs/pages/pmd/languages/xml.md
docs/pages/release_notes.md
pmd-core/pom.xml
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/xpath/PMDFunctions.java
pmd-core/src/main/java/net/sourceforge/pmd/util/DataMap.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNode.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/DocumentNavigatorTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
pmd-xml/pom.xml
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/AbstractDomNodeProxy.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlNodeWrapper.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/DomXPathRule.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/SaxonDomXPathQuery.java
pmd-xml/src/test/java/net/sourceforge/pmd/lang/xml/rule/XmlXPathRuleTest.java

Not necessarily for PMD 6.44
- Fixes #3863 
- Closes #915 as won't fix, as the issue is Jaxen-specific. This PR adds a solution which only supports XPath 2.
- Fixes #2766

[xml] Add new XPath rule for xml

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java

Might occur when the auxclasspath is incomplete.
I've found this while trying to upgrade pmd-eclipse-plugin to use tycho 2.7.0. There's something wrong with the eclipse/osgi classpath... so lot's of warnings for missing classes/incomplete auxclasspath, but also the following stacktrace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Composite
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethod(Class.java:2128)
at net.sourceforge.pmd.lang.java.rule.design.UselessOverridingMethodRule.modifiersChanged(UselessOverridingMethodRule.java:267)
at net.sourceforge.pmd.lang.java.rule.design.UselessOverridingMethodRule.visit(UselessOverridingMethodRule.java:221) …
```

[java] Catch LinkageError in UselessOverridingMethodRule

---

docs/_includes/sidebar.html
docs/css/pmd-customstyles.css
docs/css/theme-blue.css
docs/css/theme-green.css

- Added the release date under the stable version number on the left sidebar
- Slightly modified the CSS style and made the release date look natural
- The local rendering result is shown in the image below
- Fixes issue #2505

[doc] Improve side bar by Adding Release Date

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/ant/Formatter.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/ant/xml/expected-pmd-ant-xml.xml
pmd-core/src/test/resources/net/sourceforge/pmd/ant/xml/pmdtasktest.xml

PMDTask doesn't need to start it itself.
- Fixes #3884

[core] Renderers are started now by PmdAnalyzer

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ParenthesisGroupTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ParenthesisGroup0.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ParenthesisGroup1.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ParenthesisGroup2.pls

This PR fixes the plsql parser exception encountered in issue 3706. By changing the grammar in .jjt file, this parse error has been fixed and passed all added unit tests.
- Fixes https://github.com/pmd/pmd/issues/3706

[plsql] Fix plsql parsing error in parenthesis groups

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractParser.java
pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/Io.java
pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeExportCli.java
pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRenderers.java
pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/XmlTreeRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNode.java
pmd-core/src/test/java/net/sourceforge/pmd/util/designer/DesignerTest.java
pmd-core/src/test/java/net/sourceforge/pmd/util/treeexport/TreeExportCliTest.java
pmd-core/src/test/java/net/sourceforge/pmd/util/treeexport/TreeRenderersTest.java
pmd-core/src/test/java/net/sourceforge/pmd/util/treeexport/XmlTreeRendererTest.java

Bug was introduced in e64d485384
This is the stacktrace
```
$ pmdrun ast-dump -i -f xml -l java    
-------------------------------------------------------------------------------
This command line utility is experimental. It might change at any time without
prior notice.
-------------------------------------------------------------------------------
Reading from stdin...
class X {}
Exception in thread "main" java.lang.NullPointerException
at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
at java.base/java.nio.file.Path.of(Path.java:147)
at java.base/java.nio.file.Paths.get(Paths.java:69)
at …
```

[core] Fix ast-dump CLI when reading from stdin

---

pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifiedTernary.xml

This PR fixes the SimplifiedTernary rule for 'condition ? true : false' case encountered in issue 3603, 2585. This parse error has been fixed by changing the grammar in design.xml file.
- Fixes https://github.com/pmd/pmd/issues/3603
- Refs https://github.com/pmd/pmd/issues/2585

[java] Modify SimplifiedTernary to meet the missing case #3603

---

.github/workflows/troubleshooting.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

pom.xml

Fixes https://nvd.nist.gov/vuln/detail/CVE-2020-29582
See https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-1b7e275cc8607e-1651305084-d9e3a9499436490b8797b8a1babecb91 for the report from last release.
Also updates kotest to 4.4.3, which is the last compatible version (kotest 4.5.0 introduces breaking changes).

Bump kotlin from 1.4.10 to 1.4.32

---

docs/pages/release_notes.md
pmd-html/src/main/java/net/sourceforge/pmd/lang/html/HtmlLanguageModule.java

xhtml and xht is application/xhtml+xml
shtml is text/html with server side includes
See https://github.com/pmd/pmd/issues/3952#issuecomment-1118376471

[html] Add additional file extensions htm, xhtml, xht, shtml

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pmd-javascript/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pmd-test/src/main/java/net/sourceforge/pmd/cli/BaseCPDCLITest.java

- Internalized the compelte CPDCommandLineInterface
- Especially the system props `NO_EXIT_AFTER_RUN` and `STATUS_CODE_PROPERTY` are deprecated
- Refactor the unit tests a bit to not depend on these system props anymore.
- Introduced enum `CPD.StatusCode` similar to `PMD.StatusCode`.
- Fixes #3835

[core] Internalize CPDCommandLineInterface

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/ant/Formatter.java

Internalizes the methods that should only called by us internally.
Note: `end(Report)` is not called anymore at all. It was used before the refactoring to PmdAnalysis, when the ant task dealt on its own with processing errors by catching exceptions...
- Fixes #3787

[core] Internalize some methods in Ant Formatter

---

.ci/build.sh
pom.xml

With the last m-pmd-p release, it is not anymore forward compatible with PMD7.
The following errors occurs on our dogfood run:
https://github.com/pmd/pmd/runs/6813394883?check_suite_focus=true#step:7:11734
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.17.0:pmd (pmd) on project pmd-core:
Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.17.0:pmd failed:
An API incompatibility was encountered while executing org.apache.maven.plugins:maven-pmd-plugin:3.17.0:pmd:
java.lang.NoSuchMethodError: 'net.sourceforge.pmd.Report net.sourceforge.pmd.Report.filterViolations(net.sourceforge.pmd.util.Predicate)'
```
I've created a new branch for the plugin at https://github.com/apache/maven-pmd-plugin/tree/pmd7 . See …

Use maven-pmd-plugin 3.18.0-pmd7-SNAPSHOT for pmd7

---

pom.xml

This bumps the version of kotlin and dokka so that PMD can be built with JDK 17.
- Fixes #4009

[core] Bump kotlin to version 1.7.0

---

pmd-apex/src/test/java/net/sourceforge/pmd/cpd/ApexCpdTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java
pmd-java/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java
pom.xml

There are still some issues from the last release: https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-1b7e275cc8607e-1653729393-f78e070c82454f4dba74cfafc8d9c0ac
* This PR removes the last reference to commons-io, which was still used as a transitive test dependency
* Upgrade classgraph (used by kotest)
* Upgrade protobuf-java (used by scala)
- Followup on #3968 and #3942

[core] Fix current sonatype lift issues

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/PlainTextLanguage.java
pmd-test/src/main/java/net/sourceforge/pmd/test/lang/DummyLanguageModule.java

Add a "plain text" language in pmd core. This in inacessible from the CLI and other things. It's experimental.
- One step of #2435, the rest has to be done in pmd 7 and is blocked on #3918
- Unblocks #3976

[core] Add plain text language

---

pmd-scala-modules/pmd-scala-common/pom.xml
pmd-scala-modules/pmd-scala_2.12/pom.xml
pmd-scala-modules/pmd-scala_2.13/pom.xml

This module doesn't compile as it is missing dependencies that are provided in its children modules (version-specific scala modules). For instance: https://github.com/pmd/pmd/runs/5800411266?check_suite_focus=true#step:7:7667
This disables the java compilation phase in the common module. It is still enabled in the child modules of course.
I'm not sure why this didn't show up in CI until recently. I've been seeing this locally since #2547
I'm also not sure this should only target pmd 7. Hence the draft status.
- #2547

[scala] Fix build of pmd-scala-common

---

pom.xml

- Tests would fail due to the internal usage of SecurityManager without this flag

[core] Allow building PMD under Java 18+

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml

**Rule:** [ApexSOQLInjection](https://pmd.github.io/latest/pmd_rules_apex_security.html#apexsoqlinjection)
PMD currently has a check for calls to [`Database.query`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database.htm#apex_System_Database_query) to check that it correctly protects against soql injection. However, the very similar method [`Database.countQuery`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database.htm#apex_System_Database_countQuery) doesn't have these checks.
This PR adds support for detecting soql injections in the `countQuery` method in the same way we support the `query` method.
This PR fixes a potential false-negative.
I didn't open an issue for this because fixing it was …

[apex] ApexSOQLInjection: Add support count query

---

pmd-lua/src/main/antlr4/net/sourceforge/pmd/lang/lua/antlr4/Lua.g4
pmd-lua/src/test/resources/net/sourceforge/pmd/lang/lua/cpd/testdata/factorial.lua
pmd-lua/src/test/resources/net/sourceforge/pmd/lang/lua/cpd/testdata/helloworld.lua
pmd-lua/src/test/resources/net/sourceforge/pmd/lang/lua/cpd/testdata/tabWidth.lua

The Lua ANTLR grammar had parsing issues with escaped characters in comments, multiline comments with line breaks, and a few other bits and pieces. Informed by looking at the C# and Go grammars.
I enhanced the existing sample Lua files to reproduce the issues in a way that didn't require modifying their CPD snapshots.
I then tested against some of the largest corpus' of Lua code availble in open source, including test suites from multiple other parsers.
If this looks good here, I'll upstream to antlr4's repo.

[lua] Fix several related Lua parsing issues found when using CPD

---

docs/pages/7_0_0_release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/impl/DefaultRuleViolationFactory.java

I've decided not to use AtomicReference as suggested but instead use a simpler approach with `volatile`. Both solution wouldn't avoid creating the HashSet more than once (for that we would need to synchronize completely), but that shouldn't hurt, since the result should always be the same (always the same suppressors in the Set).
- Fixes #4035

[core] Fix lazy init for allSuppressors in DefaultRuleViolationFactory

---

docs/pages/pmd/userdocs/cpd/cpd.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java

- Also adds the alternative `--verbose`, but doesn't add the single character options.
- Adds a couple of debug log statements to CPD - currently we do not seem to use logging very often here - usually a System.err print is used. But that's something for later to improve.
- Fixes #3796

[core] Add "--debug" flag for CPD

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryimport/package2/C.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

On-demand imports for nested classes (non-static or static) are reported as false positives for `UnnecessaryImport` rule.
When nested classes imported on-demand their full class name is `ParentClass$NestedClass`, so imported nested class must be searched in classpath using that full name.
- Fixes #4082

[java] UnnecessaryImport false positive for on-demand imports of nested classes (fix for #4082)

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTAssignmentExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTBinaryExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTBooleanExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTPostfixExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTPrefixExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexRootNode.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AssignmentOperator.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/BinaryOperator.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/BooleanOperator.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/PostfixOperator.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/PrefixOperator.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/CycloMetric.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/visitors/CognitiveComplexityVisitor.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTFieldTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTMethodTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTNewKeyValueObjectExpressionTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTSoqlExpressionTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTSwitchStatementTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTTryCatchFinallyBlockStatementTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTUserClassTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTUserEnumTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTUserInterfaceTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTestBase.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedNameTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/metrics/ApexProjectMirrorTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileVisitorTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRuleTest.java

Remove some of the references to the internal Jorje parser outside the `ast` package.
Operators
- Create `ApexOperator` class to wrap internal operator classes.
- Refactor operator expression nodes to use `ApexOperator`.
- Refactor metrics classes to use `ApexOperator`.
Tests
- Remove references to internal Jorje nodes.

[apex] Remove Jorje leaks outside `ast` package

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserEnum.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedName.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedNameTest.java

Include enum in qualified name. Properly handle case where enum is root node.
Fixes null deref in ApexQualifiedName.toString() for built-in ASTMethods in enum types.
Reference: https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_enum.htm
Add tests of qualified and unqualified enums. (The former reproduced the null deref.)

[apex] Implement ApexQualifiableNode for ASTUserEnum

---

docs/pages/pmd/userdocs/cpd/cpd_report_formats.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/Mark.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java

Extends the XML output of CPD by adding the indices of the starting and ending tokens in each code duplication entry, like this:
```
<file column="29" endcolumn="75" endline="64" line="32" begintoken="2356" endtoken="2594"
path="/home/pmd/source/pmd-core/src/test/java/net/sourceforge/pmd/RuleReferenceTest.java"/>
```
This is to further help the use case as described in https://github.com/pmd/pmd/pull/4021#issuecomment-1165635048
Continuation of the work done in [#4021](https://github.com/pmd/pmd/pull/4021).

[core] CPD: Added begin and end token to XML reports

---

pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeExportCli.java

missing --file arg in TreeExport -  "Example: ast-dump --format xml --language java --file MyFile.java" added
The official doc is correct: https://pmd.github.io/latest/pmd_devdocs_experimental_ast_dump.html
- Fixes "[core] Missing --file arg in TreeExport CLI example"

[core] Fix missing --file arg in TreeExport CLI example

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/designer.bat
pmd-dist/src/main/resources/scripts/run.sh
pmd-dist/src/test/resources/scripts/designertest.bat
pmd-dist/src/test/resources/scripts/runtest.sh

Fixes run.sh. It spits out a warning when the version looks like "11.0.6.1". Also, we produced version "180" for java 1.8, but expected it later in the script to be "80". This is also fixed.
~Draft because I'm currently checking designer.bat under Windows...~
- Fixes #4118

[cli] Fix java version in run.sh script

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

…ed classes with the same name and in the same package are used together https://github.com/pmd/pmd/issues/4085
Additional search and exclusion of inner classes/interfaces with the same simple name as fully qualified class usage is added.
- Fixes #4085

[java] Fix False-positive UnnecessaryFullyQualifiedName when nested and non-nest… #4103

---

.github/workflows/build.yml
.github/workflows/git-repo-sync.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

[ci] GitHub Workflows security hardening

---

.ci/files/project-list.xml
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java

The new repo with the sample code is https://github.com/pmd/java-regression-tests
It builds with java19 - the produced jar file is committed, so that we don't need to build it again when running regression tests (we would need to install also java 19 in addition to the already installed java7+8+11)
- Fixes #3431

[java] Add java-regression-tests for regression testing

---

pmd-scala-modules/pmd-scala-common/pom.xml
pmd-scala-modules/pmd-scala-common/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/package.txt
pmd-scala-modules/pmd-scala_2.12/pom.xml
pmd-scala-modules/pmd-scala_2.13/pom.xml

* Bump scala-library from 2.13.3 to 2.13.9
* Bump scala-library from 2.12.10 to 2.12.17
* Bump scalameta from 4.2.0 to 4.6.0
* Fixes https://github.com/pmd/pmd/security/dependabot/28
* Fixes https://github.com/advisories/GHSA-8qv5-68g4-248j
* Fixes CVE-2022-36944

[scala] Upgrade scala-library to 2.12.7 / 2.13.9 and scalameta to 4.6.0

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/projectdocs/decisions.md
docs/pages/pmd/projectdocs/decisions/adr-1.md
docs/pages/pmd/projectdocs/decisions/adr-2.md
docs/pages/pmd/projectdocs/decisions/adr-NNN.md

This is a first draft on adding explicit decision records to our project.
It came up as a question in #3766 about Kotlin usage.
I'm not sure in what details we would need to describe the decisions or which decisions at all. I guess, we need to learn this over time.
Feel free to give feedback or ask questions - the goal is to have the decision records as an agreement and understandable by everybody.
I've integrated these into the doc site, they appear under "Project documentation":
But since these documents are simple markdown files, they can also be seen directly on github.

[doc] Add architecture decision records

---

pmd-java/src/main/resources/category/java/documentation.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/UncommentedEmptyConstructor.xml

I reivise the rule  UncommentedEmptyConstructor and make the annotation @Autowired can be detected
- Fixes #4141

[java] fix #4141 Update UncommentedEmptyConstructor - ignore @Autowired annotations

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseArrayListInsteadOfVector.xml

Just uses type resolution to detect `java.util.Vector`
- Fixes #4148

[java] Use type resolution for UseArrayListInsteadOfVector

---

docs/pages/release_notes.md
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTNumberLiteral.java
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/rule/errorprone/xml/InnaccurateNumericLiteral.xml

[javascript] InaccurateNumericLiteral - consider underscores

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/TestClassWithoutTestCasesRule.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/TestClassWithoutTestCases.xml

- Added new property "testClassPatterns" to property detect empty test classes. The default value are the same patterns as [maven-surefire-plugin](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes) uses.
- Added support for different JUnit5 annotations (like ParameterizedTest)
- Added support for TestNG
- Fixes #929
- Fixes #2636

[java] Improve TestClassWithoutTestCases

---

docs/pages/pmd/userdocs/cpd/cpd.md

Languages were missing in the documentation
When running the command line with the help flags (`run.sh cpd --help`), Html and Gherkin show up as supported languages, but they are missing in the documentation.
Since Gherkin is almost a synonym of Cucumber (just like ecmascript and javascript) I added it between braces since most people will be looking for cucumber.
- Fixes #
I checked with Gherkin and this works like a charm

[doc] Add supported CPD languages

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTMapEntryNode.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewKeyValueObjectExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewListInitExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewListLiteralExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewMapInitExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewMapLiteralExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewObjectExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewSetInitExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTNewSetLiteralExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.kt

Build and translate nodes related to variable declaration initializers.
Ref #3766

[apex] Summit-AST Apex module - Part 3 - initializers

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ClassWithOnlyPrivateConstructorsShouldBeFinal.xml

Excludes constructor related lombok annotations (NoArgsConstructor, AllArgsConstructor, RequiredArgsConstructor)
- Fixes #4188

[java] ClassWithOnlyPrivateConstructorsShouldBeFinal: Exclude lombok annotations

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

[java] InvalidLogMessageFormat - check for formatted calls

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ApexClassPropertyTypes.java
pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ApexClassPropertyTypesVisitor.java
pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/DataType.java
pmd-visualforce/src/test/java/net/sourceforge/pmd/lang/vf/ApexClassPropertyTypesVisitorTest.java
pmd-visualforce/src/test/java/net/sourceforge/pmd/lang/vf/DataTypeTest.java

Store and compare primitive type names as Strings instead of using Jorje BasicType enum.
Rewrote some logic using PMD AST instead of raw Jorje nodes.
There ought to be no change in behavior.
Update unit tests and add a few more cases.
In furtherance of: https://github.com/pmd/pmd/issues/3766

[visualforce] Replace uses of Jorje types in pmd-visualforce

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml

This PR excludes lombok's @NoArgsConstructor annotation which generates a public constructor but PMD treats it as a false positive.
- Fixes #4225

[java] Fix #4225 MissingStaticMethodInNonInstantiatableClass: Exclude lombok's @NoArgsConstructor annotation

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml

This PR excludes lombok's UtilityClass  which create a private method which throw a exception but PMD treats it as a false negative.
- Fixes #4224

[java] Fix #4224 MissingStaticMethodInNonInstantiatableClass: Exclude lombok's UtilityClass 

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractIgnoredAnnotationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml

- Fixes #4175
Note: The only use case for this annotations was #1056. But I think, such special cases should be dealt with suppressing the cases.

[java] ImmutableField - deprecate property ignoredAnnotations

---

pmd-java/pom.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/AbstractSymbolTest.java

* Ignore synthetic methods and fields in tests:
When running PMD build for sonar and coveralls, the jacoco agent will insert a synthetic 
method "$jacocoInit()" and synthetic field "$jacocoData".
Both are not present in the class files on disk, which
are used for the asm-based symbol analyzer.
See question "My code uses reflection. Why does it fail when I execute it with JaCoCo?" on https://www.jacoco.org/jacoco/trunk/doc/faq.html
For now, all synthetic methods and fields are ignored
and not just the two jacoco specific ones.
* Compile test sources only once
In the parent pom, the "default-testCompile" execution
is disabled in favor of "java-test-compile". Just
override the configuration for "java-test-compile"
instead of re-adding the default execution.
This should fix the build on …

[java] Fix sonar build (pmd7)

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/main/resources/category/apex/security.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Extending the Rules to handle the ApexCrudViolation using User Mode and System Mode
- #4146
- Add User Mode and System Mode
- Check for Accessible and creatable
- Enforce the rules

[apex] ApexCRUDViolation: user mode and system mode with test cases added

---

pmd-core/src/main/java/net/sourceforge/pmd/internal/Slf4jSimpleConfiguration.java
pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java

Reset log level of already created loggers via reflection. This increases our coupling to slf4j-simple internals, but it really only changes anything in VMs that run multiple instances of PMD one after the other (presumably, mostly our tests).
- Fix #4234
- Unblocks #4060 and #4235

[test] Properly reset log level in slf4j-simple

---

docs/pages/next_major_development.md
docs/pages/release_notes.md
pmd-apex/src/main/resources/category/apex/codestyle.xml
pmd-apex/src/main/resources/category/apex/performance.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveClassLengthRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveLengthRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveMethodLengthRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/main/resources/category/java/multithreading.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml

- Fixes #2127 
- Makes the documentation about deprecated rules consistent
- in next_major_development.md
- in the actual rule documentation
- Marks EmptyStatementNotInLoop as deprecated (seems to have been forgotten in PMD 6.46.0).

[java] Deprecate rules ExcessiveClassLength and ExcessiveMethodLength

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/WhileLoopWithLiteralBoolean.xml

[java] WhileLoopWithLiteralBoolean - don't limit to two bool literals

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTCompactConstructorDeclarationTest.java

Fixes finding lambda scope in record compact constructor
- Fixes #4266

[java] Fix finding lambda scope in record compact constructor

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml

The rule CommentDefaultAccessModifier ignores @VisibleForTesting as stated by the documentation:
_This rule ignores by default all cases that have a @VisibleForTesting annotation or any JUnit5 annotation_
https://pmd.github.io/pmd/pmd_rules_java_codestyle.html#commentdefaultaccessmodifier
This should also apply to the annotation [co.elastic.clients.util.VisibleForTesting](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/util/VisibleForTesting.java)  from the elastic provided java client, [elasticsearch-java](https://github.com/elastic/elasticsearch-java),.

[java] CommentDefaultAccessModifier - add co.elastic.clients.util.VisibleForTesting as default suppressed annotation

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexRootNode.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexUnitTestRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/ApexUnitTestShouldNotUseSeeAllDataTrueRule.java

Update the rules that utilize it. Assume Apex version is >= V176.
This was discussed in https://github.com/pmd/pmd/pull/4251 in the context of replacing the Apex AST. This functionality is [feasible but] not planned for the new AST. It's also not fully certain how it behaves in the existing AST.
The two uses of `ApexRootNode.getApexVersion` are in AbstractApexUnitTestRule.java and ApexUnitTestShouldNotUseSeeAllDataTrueRule.java. It determines whether to also visit test methods without `@IsTest` if they predate the `@isTest` introduction API version 24. Assuming that `getApexVersion` actually parses the metadata API, this could lead to false negatives in rules that would otherwise fire on test-only code.

[apex] Deprecate ApexRootNode.getApexVersion

---

pmd-cli/pom.xml
pmd-cli/src/main/java/me/tongfei/progressbar/PmdProgressBarFriend.java
pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/PmdCommand.java
pmd-cli/src/main/java/net/sourceforge/pmd/cli/internal/ProgressBarListener.java
pmd-core/pom.xml
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/PmdAnalysis.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
pmd-core/src/main/java/net/sourceforge/pmd/reporting/FileAnalysisListener.java
pmd-core/src/main/java/net/sourceforge/pmd/reporting/GlobalAnalysisListener.java
pmd-core/src/main/java/net/sourceforge/pmd/reporting/ListenerInitializer.java
pmd-core/src/main/java/net/sourceforge/pmd/reporting/NoopListenerInitializer.java
pmd-core/src/main/java/net/sourceforge/pmd/util/IOUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/processor/MultiThreadProcessorTest.java
pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java
pmd-javascript/src/test/java/net/sourceforge/pmd/cli/CLITest.java
pmd-xml/src/test/java/net/sourceforge/pmd/lang/xml/XmlCliTest.java
pom.xml

- Took the chance to improve how we render it
- Added support for interactive terminals
- Improved the overall performance / thread-safety of report rendering to STDOUT
- Fixes #3828

[cli] Move CLI progressbar rendering to pmd-cli

---

.ci/files/project-list.xml

Currently regression tester is failing, because the dependency com.ibm.websphere/uow/6.0.2.17 is missing:
```
Execution failed for task ':spring-tx:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':spring-tx:compileKotlin'
> Could not resolve all files for configuration ':spring-tx:compileClasspath'.
> Could not resolve com.ibm.websphere:uow:6.0.2.17.
Required by:
project :spring-tx
> Could not resolve com.ibm.websphere:uow:6.0.2.17.
> Could not get resource 'https://repo.spring.io/libs-spring-framework-build/com/ibm/websphere/uow/6.0.2.17/uow-6.0.2.17.pom'.
> Could not GET 'https://repo.spring.io/libs-spring-framework-build/com/ibm/websphere/uow/6.0.2.17/uow-6.0.2.17.pom'. Received status code 401 from server: Unauthorized
```
The repo "repo.spring.io" …

[ci] Add additional repository for spring-framework-build

---

pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTPatternTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/Java11Test.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ParserTestSpec.kt
pom.xml

Enables the custom surefire console reporter (pmd/build-tools#27) so that we don't see strange output anymore with 0 tests executed.
This also refactors ParserTestSpec slightly, so that we don't depend anymore on kotests internal API to register a test case. We now have our own test scopes, where we can register test cases.
- Fixes #4236

[testing] Use custom surefire console reporter

---

pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java

This is a simple change, that allows users to set the value of a property to an empty string. Previously empty strings and no value have been considered to be the same.
Since there are no other failing tests, I guess this is just an edge case that didn't come up yet.
Note that when defining a property, a default value still needs to be provided - it is still not possible to define a property with an empty default value.
- Fixes #4279

[core] Allow empty values for rule properties

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CSVRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/SimpleRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/VSRenderer.java

This PR makes all old CPD renderers implement the new interface CPDReportRenderer.
This opens up a forward compatible migration path for e.g. maven-pmd-plugin when migrating to PMD 7.
- relates #4340 
- relates #4341 
- needed for #4235 
- after this (#4343) and #4341 are merged into master and master is merged into pmd/7.0.x, it should be possible to create a maven-pmd-plugin version that is compatible with pmd7 without using workaround (see https://github.com/apache/maven-pmd-plugin/tree/pmd7 )

[core] CPD - implement CPDReportRenderer for all renderers

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UseDiamondOperatorRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ast/BaseInvocMirror.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseDiamondOperator.xml

- An IllegalStateException is produced when the inference context corresponds to an invocation of an unresolved method.
- The rule effectively can't determine if the diamond operator can be used, but the current message of "overload resolution is not complete" is noisy, not actionable to the user (the issue is a missing class in the auxclasspath, not the overload resolution itself), and prevents the rule from continuing to analyze the current file.
- The current fix is not elegant, and probably subpar (maybe the Infer logic could remove the check and deal with this seemlessly?) but I fear that code is too complex for me to make that call / change at this time. @oowekyala I'd love your help here.

[java] Fix IllegalStateException in UseDiamongOperator rule

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/UnusedLocalVariable.xml

This PR fix the false positive issue on UnusedLocalVariable rule, when variable is used as bind variable in string soql query.
- Fixes #2669
- Refs #3489

[apex] Feature/unused variable bind false positive with dynamic SOQL

---

docs/pages/release_notes.md
pmd-apex-jorje/pom.xml
pmd-doc/src/main/java/net/sourceforge/pmd/docs/SidebarGenerator.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java

It was a dependency via apex-jorje, but there snakeyaml is actually not needed.
During generating doc, we use snakeyaml to load the sidebar and modify it. The code has been adjusted to use SafeConstructor to mitigate the risk.
- Fixes https://github.com/pmd/pmd/security/dependabot/33
- Fixes CVE-2022-1471
- Fixes https://github.com/advisories/GHSA-mjmj-j48q-9wg2

[core] Refactor usage of snakeyaml

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaComment.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentSizeRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml

CommentSize didn't report long lines on the right lines but always on the first line of the comment.
- Fixes #

[java] Improve CommentSize

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/RuleApplicator.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AstDisambiguationPass.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaAstProcessor.java

- Recover the old behavior, where the number of rule applications is split from the number of tree transversals.
- This means that rules that are applied, but didn't match any node where previously unlisted, but know show they were applied to all files, and evaluated 0 nodes.
- This also allows to more neatly understand which rules are making use of the rulechain and which don't.
- Remove numbers from Java LPS names
- Only Java used them, so it was inconsistent
- The numbers relate to the order they are executed, but don't necessarily imply a required order (ie: `Comment Assignment` could be done at any point in reality)
- Since the benchmark report sorts by time spent on each one, the numbered labels are simply confusing
- AST Disambiguation is only tracked in the dedicated phase started …

[core] Improve benchmarking

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclarator.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/ast/LazyTypeResolver.java

- Fixes #4317 - in the case of ASTCompilationUnit that was already done.

[java] Make ASTVariableDeclarator not be a TypeNode

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

When using type inference and initializing through a method call rather than a direct constructor call, the rule would detect the var as being a `Closeable`, yet fail to retrieve the proper type to check if it was whitelisted / which error message to produce.
We now look at wether there is type inference in play when deciding wether computing the runtime type is required.

[java] Fix NPE in CloseResourceRule

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TypeResTestRule.java
pmd-java/src/main/resources/category/java/security.xml
pmd-java/src/main/resources/rulesets/java/internal/diagnostics.xml

Create a diagnostics.xml internal ruleset for TypeResTestRule
- Fix #4367

[java] Move TypeResTest rule out of security.xml

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JPrimitiveType.java

- Since annotated primitives are now stand-alone instances, ensure they share the supertypes for the unannotated version, otherwise, NPEs occur during inference.
This was introduced during #4245

[java] Avoid NPEs during type inference

---

docs/pages/pmd/userdocs/cli_reference.md
docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/pmd.bat

Fixes the problem found in https://github.com/pmd/pmd/discussions/4391
The environment `CLASSPATH` is supported in `run.sh` for a long time, but this was obviously never added to pmd.bat.
Note: This needs to be ported to PMD 7 as well - there we seem to support `CLASSPATH` only in the bash script, but not in `pmd.bat`.

[core] Support environment variable CLASSPATH with pmd.bat under Windows

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonExprTransformations.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQuery.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SplitUnions.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQueryTest.java

- When a rule uses a property Saxon produces a top-level LetExpression
- Since LetExpressions can also be used to "cache" expensive operations during rule evaluation we generally ignored them, but we don't anymore.
- If a LetExpression was for an expensive operation, we still refrain from using the rulechain so it's only evaluated once
With this changeset, rules such as `AvoidLiteralsInIfCondition` and `ControlStatementBraces` can make use of the rulechain in PMD 7 as they used to in PMD 6, and run significantly faster.

[core] Allow more XPath rules to use the rulechain

---

pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleViolation.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/document/NioTextFile.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/internal/ZipFileFingerprinterTest.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/AnalysisCacheIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/ExecutionResult.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java

Fix the population of the analysis cache, otherwise it is always stored as empty.
When the cache was migrated to a `FileAnalysisListener` the implementation was broken, and it kept working on a local var that was never accessible when persisting the cache. This updated implementation is simpler, avoids explicit (and useless) synchronization, and actually get the cache working once again.
Also, with the introduction of `pathIds` for text documents, the cached reports would output file names as urls, being different to the uncached ones. We revamp the logic to not only fix that, but also allow us to honor relativized roots at each execution, regardless of the cache's state.

[core] Fix cache population

---

pmd-java/src/main/resources/category/java/bestpractices.xml

Updated the error message to contain a bit more relevant information that should be useful to the programmer. Furthermore it now contains proper references to Effective Java.
- Fixes #1205

[doc] Added new error msg to ConstantsInInterface

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/SemanticErrorReporter.java
pmd-core/src/test/java/net/sourceforge/pmd/processor/PmdRunnableTest.java

Removes the "!debug only!" in the log warnings.
E.g. previously:
```
[main] WARN net.sourceforge.pmd.cli.commands.internal.PmdCommand - at !debug only! jdk-master/src/java.base/share/classes/jdk/internal/io/JdkConsoleImpl.java:48:46: Cannot resolve symbol JdkConsole
```
And now:
```
[main] WARN net.sourceforge.pmd.cli.commands.internal.PmdCommand - at jdk-master/src/java.base/share/classes/jdk/internal/io/JdkConsoleImpl.java:48:46: Cannot resolve symbol JdkConsole
```

[core] Log semantic error warnings without debug note

---

pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/PmdCommand.java
pmd-cli/src/test/java/net/sourceforge/pmd/cli/PmdCliTest.java

This fixes the following NPE:
```
java.lang.NullPointerException
at net.sourceforge.pmd.util.AssertionUtil.requireContainsNoNullValue(AssertionUtil.java:30)
at net.sourceforge.pmd.PMDConfiguration.setInputPathList(PMDConfiguration.java:515)
at net.sourceforge.pmd.cli.commands.internal.PmdCommand.toConfiguration(PmdCommand.java:278)
at net.sourceforge.pmd.cli.commands.internal.PmdCommand.execute(PmdCommand.java:328)
at net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand.call(AbstractPmdSubcommand.java:35)
at net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand.call(AbstractPmdSubcommand.java:20)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at …
```

[cli] Fix NPE when only `--file-list` is specified

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexBadCryptoRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexBadCrypto.xml

This PR is targeted at fixing an issue with the ApexBadCrypto test.  The test was not catching situations where the hard coded values were inline with the method call.  Modified the detection code and added two additional unit tests to catch that scenario.  
- Fixes #4427

[apex] ApexBadCrypto bug fix for #4427 - inline detection of hard coded values

---

pmd-apex/pom.xml

The new version of summit-ast is based on apex-parser 2.17 and incorporates the new syntax in the AST.

Bump summit-ast to new release 2.1.0 (and remove workaround).

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml

Default value of "ignoredAnnotations" now include "org.junit.jupiter.api.extension.RegisterExtension" .
- Fixes #4273

[java] CommentDefaultAccessModifier - ignore org.junit.jupiter.api.extension.RegisterExtension by default

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidAccessibilityAlteration.xml

This PR addresses a false positive in the AvoidAccessibilityAlteration rule when using Lambda expressions with PMD 7.0. The update includes changes to the XPath rule to handle Lambda expressions correctly and avoid false positives.
- Fixes  #4449

[java] Fix #4449 AvoidAccessibilityAlteration: Correctly handle Lambda expressions in PrivilegedAction scenarios

---

pom.xml

We don't have the jxr plugin and also don't create reports. Disabling this option avoids the many warnings like `[WARNING] Unable to locate Source XRef to link to - DISABLED`.

Disable maven-pmd-plugin option linkXRef

---

.ci/build.sh
docs/pages/release_notes.md
pmd-dist/src/main/resources/assemblies/pmd-bin.xml
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pom.xml

- Add cyclonedx plugin to generate SBOM (Software Bill of Materials)
- The SBOM is attached and deployed into maven central
- The SBOM is also included in the binary distribution of PMD
See https://github.com/CycloneDX/cyclonedx-maven-plugin

Provide Software Bill of Materials (SBOM)

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml

This fixes a potential false negative when @Getter is used. See discussion on #4474:
> I think that a field (or class) being annotated with the `@Getter` annotation should not be a > reason to exempt from the ImmutableField rule. After all, it only generates a getter, meaning > the field can still be marked final.
>
> _Originally posted by @PimvanderLoos in https://github.com/pmd/pmd/issues/4474#issuecomment-1511014310_

[java] ImmutableField - remove @Getter

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/pmd
pmd-dist/src/main/resources/scripts/pmd.bat
pmd-dist/src/test/resources/scripts/pmdtest.bat

- having quotes or spaces in path names separated by ";" (such as CLASSPATH) is tricky. Checking whether there is a value if `if [%CLASSPATH%]` requires quotes, e.g. `if ["%CLASSPATH%"]...`, as otherwise the ";" is executed, which is a delimiter and end the if statement in the middle. But having surrounding quotes now creates a problem, if the CLASSPATH itself starts with a quote... because double quotes (`""`) escapes the quote and then you have one quote character less and a syntax error...
- but it's easier to just check for the existence of the variable with `if defined CLASSPATH`
- added `setlocal` to avoid creating any environment variables
- using `rem` for comments now everywhere. The double colon theoretically only works at the very start of the line and not in the middle (after …

[dist] Fix pmd.bat script

---

docs/pages/release_notes.md
docs/pages/release_notes_pmd7.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml

As figured out in #4474, the property `ignoredAnnotations` is unfortunately not deprecated anymore in 7.0.0-rc1. So that we don't forget to remove this property - because it is indeed deprecated since 6.52.0 - let's just remove it immediately.

[java] ImmutableField: Remove deprecated property "ignoredAnnotations"

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml

This PR excludes `com.google.inject.Inject` which cause FP.
- Fixes #4493

[java] Fix #4493: false-positive about MissingStaticMethodInNonInstantiatableClass and @Inject

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryConstructorRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryConstructor.xml

This PR excludes `com.google.inject.Inject` and `org.springframework.beans.factory.annotation.Autowired`  which cause FP.
- Fixes #4487

[java] Fix #4487: A false-positive about UnnecessaryConstructor and @Inject and @Autowired

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SignatureDeclareThrowsException.xml

This PR excludes `org.testng.annotations.AfterClass` and `org.testng.annotations.BeforeClass` which cause FP when using in a unit test method and throwing an exception is allowed.
- Fixes #4477

[java] Fix #4477: A false-positive about SignatureDeclareThrowsException

---

docs/pages/pmd/userdocs/cpd/cpd.md

Fixes a small typo: there was a missing quotation mark after `CPD-END` in the provided example.

[doc] Fix typo: missing closing quotation mark after CPD-END

---

.ci/build.sh
do-release.sh

This contains a fix and small improvement:
- The release of 7.0.0-rc1 failed on github actions (https://github.com/pmd/pmd/actions/runs/4519047623), as we have a snapshot dependency to pmd-designer:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.2.1:enforce (enforce-no-snapshots) on project pmd-cli: 
Error:  Rule 0: org.apache.maven.enforcer.rules.dependency.RequireReleaseDeps failed with message:
Error:  No Snapshots Allowed!
Error:  net.sourceforge.pmd:pmd-cli:jar:7.0.0-rc1
Error:     net.sourceforge.pmd:pmd-ui:jar:7.0.0-SNAPSHOT <--- is not a release dependency
Error:  -> [Help 1]
```
The enforcer plugin will verify, that we don't reference snapshot dependencies for release versions. This change will disable the enforcer plugin for release …

[ci] Improve release scripts

---

docs/pages/release_notes.md
docs/pages/release_notes_pmd7.md
pom.xml

- Updates pmd-designer to the stable version. See https://github.com/pmd/pmd-designer/releases/tag/7.0.0-rc1
- Fixes the issue, that PMD 7.0.0-rc1 is not reproducible according to procedure used here https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/net/sourceforge/pmd/README.md
The following error occurs when trying to rebuild 7.0.0-rc1:
```
[ERROR] Failed to execute goal on project pmd-cli: Could not resolve dependencies for project net.sourceforge.pmd:pmd-cli:jar:7.0.0-rc1: Could not find artifact net.sourceforge.pmd:pmd-ui:jar:7.0.0-SNAPSHOT in default (https://repo.maven.apache.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project pmd-cli: Could not resolve dependencies for project …
```

Bump pmd-designer from 7.0.0-SNAPSHOT to 7.0.0-rc1

---

docs/pages/pmd/userdocs/suppressing_warnings.md
docs/pages/release_notes.md
docs/pages/release_notes_pmd7.md
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/ExcessivePublicCount.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SwitchDensityRule.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningLoopVariables.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedLocalVariable.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/MethodArgumentCouldBeFinal.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentRequired.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidLiteralsInIfCondition.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ImplicitSwitchFallThrough.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UselessOperationOnImmutable.xml

- Fixes #3123 
- Closes #4509 
- Closes #4511
- Closes #4512
- Closes #4513 
- Closes #4514
- Closes #4516
- Closes #4517
- Closes #4518

[doc] Document rule changes for PMD 7

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/OverrideBothEqualsAndHashcode.xml

This PR consider the `AnonymousClass`.
- Fixes #4457
- Fixes #4546

[java] Fix #4457: false negative about OverrideBothEqualsAndHashcode

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml

This PR excludes `org.testng.annotations.Test`.
- Fixes #4268

[java] Fix #4268: CommentDefaultAccessModifier - false positive with TestNG's @Test annotation 

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCatchParameter.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTUnionType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExceptionAsFlowControlRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ExceptionAsFlowControl.xml

Rewrite ExceptionAsFlowControl to a more efficient form. Change message to be more informative.
Rewrite description of the rule.
- Fixes #4434

[java] Fix #4434 - FP with ExceptionAsFlowControl

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/AbstractPropertySource.java
pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java

Found this while upgrading PMD Eclipse Plugin to 7.0.0. In the plugin, we often verify that we have the same ruleset active by executing `RuleSet#equals()`. This doesn't work as soon as a rule uses `java.util.regex.Pattern` based properties. The reason is, that `Pattern` doesn't override `equals` - see also https://stackoverflow.com/questions/52103427/why-these-two-java-util-pattern-are-not-equal

[core] Rules with the same regex properties should be equal

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/LawOfDemeter.xml

I believe, this should fix the spurious differing results in the regression tester. At least, I could reproduce on first try the problem when reversing the order of the reaching assignments.
That should then make the test-case-3 of https://github.com/pmd/pmd-regression-tester/pull/119 happy.

[java] Make LawOfDemeter results deterministic

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FieldNamingConventions.xml

This PR adds an annotation whitelist to exclude `UtilityClass`.
- Fixes #4455

[java] Fix #4455: A false positive about FieldNamingConventions and UtilityClass

---

pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/FinalFieldCouldBeStatic.xml

This PR excludes annotation `UtilityClass`
- Fixes #4456

[java] Fix #4456: A false positive about FinalFieldCouldBeStatic and UtilityClass

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/RedundantFieldInitializerRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/RedundantFieldInitializer.xml

This PR add an annotation whitelist to exclude `@Value`
- Fixes #4458

[java] Fix #4458: A false positive about RedundantFieldInitializer and @Value

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ConstructorCallsOverridableMethod.xml

This PR add an whitelist to excludes `@Value`
- Fixes #4510

[java] Fix #4510: A false positive about ConstructorCallsOverridableMethod and @Value

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml

GuardLogStatement gives false positive when a Java method reference is used, although method references are equivalent to lambdas.
- Fixes #4492

[java] Fix #4492: GuardLogStatement gives false positive when argument is a Java method reference

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseTestAnnotation.xml

Changes:
- fixed the JUnit4TestShouldUseTestAnnotation rule for TestNG,
- added test
- updated changelog
* Fixes #4634

 [java] fix #4634 - JUnit4TestShouldUseTestAnnotation false positive with TestNG

---

docs/_config.yml
docs/_layouts/page.html
docs/css/customstyles.css
docs/js/customscripts.js
docs/pages/release_notes.md

Also wrap the inline-toc in an accordion to save some space.
Remove some of the unneeded javascript.
The page appears now:
- Fixes #4521

[doc] Make side fixed only for big screens

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseTryWithResources.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

I believe "closable" and "closeable" could be used interchangeably - however, the proper spelling for the Java interface is `AutoCloseable`.
This PR fixes docs and code snippets that refer/allude to the AutoCloseable interface.

[java] Doc: Fix references AutoClosable -> AutoCloseable

---

pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/CpdCommand.java

Fixes similar issue to #4423, but then for CPD.
#4423
- Fixes #

[cli] CPD: Fix NPE when only `--file-list` is specified

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml

…types
Recognise variables declared as SObjectField and SObjecType as safe for insertion into SOQL statements. These are Table and Field tokens and resolve to the safe name for their respective artefacts when inserted into a string.
- Fixes #4646

[apex] Add SObjectType and SObjectField to list of injectable SOQL variable types

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/UnusedMethodRule.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/design/UnusedMethodTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/UnusedMethod/project1/sfdx-project.json
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/UnusedMethod/project1/src/Foo.cls

* This adds a unit test to verify the rule [UnusedMethod](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#unusedmethod) actually works.
* This is important, as that actually tests the integration with apexlink
I could now confirm, that #4453 is indeed fixed by the update of apexlink (#4528) - since apexlink now hardcoded uses always UTF-8 - for both itself and when creating a antlr char stream (see https://github.com/nawforce/apex-link/blob/7688adcb7a2d7f8aa28d0618ffb2a3aa81151858/pkgforce/jvm/src/main/scala/com/nawforce/runtime/parsers/SourceData.scala#L55-L59 )
I couldn't create a unit test to reproduce #4453, since that would have involved changed the default charset in java in a running vm which is not possible.
But I manually verified, that #4453 is now fixed.
- Fixes …

[apex] Add rule test for UnusedMethod

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageProcessorRegistry.java
pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/LanguageProcessorRegistryTest.java
pmd-core/src/test/java/net/sourceforge/pmd/util/StringUtilTest.java

The environment variables should be uppercase as documented.
Found this while reproducing #4453 when trying to set "PMD_APEX_ROOT_DIRECTORY" which didn't have any effect. I needed to use "PMD_APEX_root_directory" to make it working.
- Refs #2518

[core] Fix loading language properties from env vars

---

pom.xml

* Fixes https://github.com/pmd/pmd/security/dependabot/48
* Fixes CVE-2023-41329
* Fixes https://github.com/advisories/GHSA-pmxq-pj47-j8j4

Bump wiremock from 2.33.2 to 2.35.1

---

pmd-dist/pom.xml
pom.xml

Also remove jcommander, this is not needed anymore.
This partly resolves #4691, as the new pmd-designer doesn't contain commons-io anymore (see pmd/pmd-designer#74).
This also makes the designer workable again in the current SNAPSHOT of PMD.

Bump pmd-designer from 7.0.0-rc1 to 7.0.0-SNAPSHOT

---

.ci/build.sh
do-release.sh
docs/pages/pmd/projectdocs/committers/releasing.md
pmd-doc/pom.xml
pom.xml

1. Release all modules except pmd-cli and pmd-dist
2. Release pmd-cli and pmd-dist
This allows to release pmd-designer in between.
This addresses #4446 in a hackish way, which might even work :crossed_fingers: 
I think, we should keep #4446 open because doing a release in two steps would be really simpler, if we move pmd-cli and pmd-dist somewhere else.
Anyway, I'll try out this solution tomorrow for the 7.0.0-rc4 release.

[ci] Introduce a two-step release process

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaComment.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml

[java] Fix #4578 - CommentDefaultAccessModifier comment needs to be before annotation if present

---

pmd-core/src/test/java/net/sourceforge/pmd/PmdAnalysisTest.java
pom.xml

This is the only change needed, so that PMD builds with java21. This seems to be a bug in mockito (see https://github.com/mockito/mockito/issues/3121) but we seem to use this edge case only here. So I opted to go the simple way...
(mockito fails to call the default method `newListener()` on interface `Renderer`).

Make PMD buildable with java 21

---

pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/internal/XmlParserImpl.java
pmd-xml/src/main/resources/category/xml/bestpractices.xml
pmd-xml/src/test/java/net/sourceforge/pmd/lang/xml/rule/bestpractices/MissingEncodingTest.java
pmd-xml/src/test/resources/net/sourceforge/pmd/lang/xml/ast/testdata/bug1518.txt
pmd-xml/src/test/resources/net/sourceforge/pmd/lang/xml/ast/testdata/sampleNs.txt
pmd-xml/src/test/resources/net/sourceforge/pmd/lang/xml/ast/testdata/sampleXml.txt
pmd-xml/src/test/resources/net/sourceforge/pmd/lang/xml/rule/bestpractices/xml/MissingEncoding.xml

- Expose XML declaration attributes to the DOM
- Implement a rule enforcing the XML declaration includes an encoding
This implementation has a few constraints:
- Since the parser doesn't really expose the declaration, it's not possible to know if the declaration is present or not. The XML version will be declared as "1.0" in such scenarios, and "standalone" be reported as false (the default according to the XML standard)
This would allow us to remove the test from #4586 and instead add this rule to the dogfooding ruleset.

[xml] Add MissingEncoding rule

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/impl/MultiThreadProcessor.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/impl/AbstractPMDProcessorTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/impl/MonoThreadProcessorTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/impl/MultiThreadProcessorTest.java

If an error occurs in multithreading mode, PMD now rethrows this. Such errors indicate a serious problem like incomplete runtime classpath of PMD or other
VM error (out of memory) that shouldn't be swallowed.
When working on #4605 I once had an incomplete runtime classpath (I think guava was missing which jorje needs). The result was, that I didn't see any errors at all, even not with `--debug`. PMD ran fine, but Apex just didn't find anything yet. The fact, that no Apex violations were found was caught by the integration test. But it's not good, if an error is not printed at least to the console.
The solution in this PR is the most basic and could be improved it any thinkable way - but this change at least should be enough to see some errors.
Note: This is not about runtime exceptions or …

[core] Deal with errors from threads in multithreading mode

---

pmd-dist/src/main/resources/scripts/pmd

If run.sh is launched via 'bin/bash run.sh', when run.sh is not in the local directory (i.e., accessed via path env var), it thinks it runs in the local directory.
This change makes sure that all cases are covered.
Tested on local Ubuntu 22.04 and similar Docker container running on Jenkins.
- Fixes #4723

[cli] Launch script fails if run via "bash pmd"

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/userdocs/tools/bld.md

[doc] Add bld PMD Extension to Tools / Integrations

---

pmd-java/src/main/resources/category/java/errorprone.xml

This is the last regex property not using `PropertyDescriptor<Pattern>` underneath.
Fixes #1027

[java] Make allowExceptionNameRegex a Regex

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/SummaryHTMLRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java

The test `SummaryHTMLRendererTest.testRendererMultiple` assumes a particular order for the keys stored in `summary` map. 
The following lines of code in `renderSummary` function may return any random field ordering. This might cause inconsistent output rendering and results in the unit test being flaky.
https://github.com/pmd/pmd/blob/bdc08e44fd92380d59cdc50cf9d8dd36e537c369/pmd-core/src/main/java/net/sourceforge/pmd/renderers/SummaryHTMLRenderer.java#L64-L72
Changing the HashMap to LinkedHashMap, makes the output consistent and fixes the flaky test. There might be other possible fixes like, changing the test code such that, the tests expects and passes for both the orderings.
Setup the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool in your repo and run
```
mvn -pl …
```

[core] Fix flaky SummaryHTMLRenderer

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/EmptyControlStatementRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/EmptyControlStatement.xml

**Rule**: [EmptyControlStatement](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#emptycontrolstatement)
Adds a property to EmptyControlStatementRule to allow empty block containing comments.  It may be good to be able to explain why a condition does not require logic.

[java] EmptyControlStatementRule: Add allowCommentedBlocks property

---

pmd-java/src/main/resources/category/java/errorprone.xml

When using `category/java/errorprone.xml` ruleset with PMD 7.0.0-rc4 I'm getting these warnings:
```
Warning at category/java/errorprone.xml:1039:78
1037|         <properties>
1038|             <property name="version" value="2.0"/>
1039|             <property name="typesThatCompareByReference" type="List[String]" delimiter="," description="List of canonical type names for which reference comparison is allowed.">
^^^^^^^^^ Delimiter attribute is not supported anymore, values are always comma-separated.
1040|                 <value>java.lang.Enum,java.lang.Class</value>
1041|             </property>
Warning at category/java/errorprone.xml:2353:62
2351|         <priority>3</priority>
2352|         <properties>
2353|             <property name="annotations" type="List[String]" delimiter="," …
```

[java] fix: remove delimiter attribute from ruleset category/java/errorprone.xml

---

pmd-compat6/src/it/pmd-for-java/exception_ruleset.xml
pmd-compat6/src/it/pmd-for-java/pom.xml
pmd-compat6/src/it/pmd-for-java/verify.bsh
pmd-compat6/src/main/java/net/sourceforge/pmd/Report.java

When a processing error occurs while using pmd-compat6 (rc4) then a NoSuchMethodError is thrown:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.21.2:pmd (default-cli) on project flexpay-reflectdb: Execution default-cli of goal org.apache.maven.plugins:maven-pmd-plugin:3.21.2:pmd failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-pmd-plugin:3.21.2:pmd: java.lang.NoSuchMethodError: 'java.lang.String net.sourceforge.pmd.Report$ProcessingError.getFile()'`
This PR implements the missing getFile() method.

Fixes NoSuchMethodError on processing errors in pmd-compat6

---

docs/pages/pmd/devdocs/major_contributions/adding_a_new_javacc_based_language.md
docs/pages/release_notes.md

* Added a new section in https://docs.pmd-code.org/latest/pmd_devdocs_major_adding_new_language_javacc.html that describes a bit the XPath integration
* Note: These annotations are probably not available for ANTLR integrations, since we don't have individual AST node classes there...
- Fixes #4308

[doc] Document XPath integration (#4308)

---

pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertySource.java

An alternative implementation is not ready for PMD 7, so I'm undoing this deprecation.
In PMD 6.55.0, this is not deprecated.
It is used in `net.sourceforge.pmd.PmdAnalysis#removeBrokenRules`
The related issues are:
* #3868
* #3901

[core] Undeprecate PropertySource::dysfunctionReason in PMD 7

---

pmd-plsql/etc/grammar/PLSQL.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WithClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WithClause.pls

- WITH clauses were ignored because of missing lookahead. 
- Also added WITH clause support for SELECT INTO statements which actually works although not being documented.
- none that I know
- Fixes #4820

[plsql] Fix ignored WITH clause for SELECT INTO statements

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

[java] UnusedAssignment false positive in record compact constructor

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryimport/item/Item.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryimport/item/ItemProducer.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

[java] UnnecessaryImport - keep analyzing with failed overload selection

---

pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/internal/NodeStreamBlanketTest.java

in order to avoid many ignored unit tests.
E.g. before this change, we had:
Tests passed: 5,417, ignored: 2,539 of 7,956 tests
-> about 30% of the tests were ignored...

[core] NodeStreamBlanketTest - prefilter the test data

---

pmd-core/src/main/java/net/sourceforge/pmd/util/GraphUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/internal/LatticeRelationTest.java

**Problem**
The `LatticeRelationTest.testToString` is detected as flaky. The following lines of code iterate over `vertices` which is of Type Set.
https://github.com/pmd/pmd/blob/f030d7f8d77cf3f943e4ef2a6fe3d7d01ee26c66/pmd-core/src/main/java/net/sourceforge/pmd/util/GraphUtil.java#L46
https://github.com/pmd/pmd/blob/f030d7f8d77cf3f943e4ef2a6fe3d7d01ee26c66/pmd-core/src/main/java/net/sourceforge/pmd/util/GraphUtil.java#L59
Java does not iterate over elements of a set in a particular order. This causes the output `toString` function to be non-deterministic and results in the `LatticeRelationTest.testToString` to be flaky. 
**Solution**
I have modified the code such that we iterate over a sorted list of `Vertex` objects. This results in the `toString` output being deterministic. I had to …

[core] Fix flaky LatticeRelationTest

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InsufficientStringBufferDeclaration.xml

Handle other operation types when computing initial buffer size.
- Fixes #3845

[java] Compute literal expressions for InsufficientStringBufferDeclaration

---

pmd-dist/src/main/resources/scripts/pmd.bat

Hi, thanks for your reply! I tried and found that it's because that `%pmd_classpath%` is without quotation marks. 
- Fixes #4791

Fix #4791 Error caused by space in JDK path

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ForLoopCanBeForeachRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ForLoopCanBeForeach.xml

Seems like the loop stride was never checked. I'm not sure why PMD 6 did not show this bug.
- Fixes #4569

[java] Fix #4569 issue with ForLoopCanBeForeach when stride is not 1

---

docs/pages/release_notes.md
pmd-xml/src/main/resources/category/pom/errorprone.xml
pmd-xml/src/test/resources/net/sourceforge/pmd/lang/xml/pom/rule/errorprone/xml/InvalidDependencyTypes.xml

The XPath (and even tests! 😱) would assume that `<dependency>` was a direct child of `<dependencyManagement>`, but in truth, there is a `<dependencies>` intermediate node.
- Fixes #4388

[pom] Properly navigate dependencyManagement node

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtilTest.java

The pretty printer is not implemented for all expression types and the behavior on these types is just to return the empty string. This makes some messages of eg LawOfDemeter confusing. This adds more implementations...
- changes extracted from #4918

[java] Fix pretty printing for some exprs

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexCommentBuilder.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/EmptyCatchBlock.xml

I don't remember why they were special cased, but it seems that removing the exception does not break anything and it is more regular than before.
- Fixes #3953

[apex] EmptyCatchBlock: Fix FP with doc comments

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

The rule allows for resources being passed as parameters to not be closed, even when copied to another variable or wrapped in another instance. However, those checks fail when it's a simple cast being used.
- Fixes #2056

[java] CloseResource should treat parameters as external even if casted when assigned to a local variable

---

docs/pages/release_notes.md
pmd-ant/pom.xml
pmd-apex/pom.xml
pmd-cli/pom.xml
pmd-core/pom.xml
pmd-doc/pom.xml
pmd-java/pom.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-kotlin/pom.xml
pmd-modelica/pom.xml
pmd-plsql/pom.xml
pmd-scala-modules/pmd-scala-common/pom.xml
pmd-visualforce/pom.xml
pmd-xml/pom.xml
pom.xml

This add [japicmp](https://siom79.github.io/japicmp/MavenPlugin.html) to the build and breaks the build, if we accidentally change a class/interface in an incompatible way.
I've excluded the internal packages by listing them explicitly in the excludes. If we add new packages, we need to update this. Theoretically, we could also add a wildcard (https://github.com/siom79/japicmp/blob/59467d292560d4583884ea42c691bf90992594d1/japicmp/src/main/java/japicmp/filter/JavadocLikePackageFilter.java#L11-L17), but I like for now, that we list the packages explicitly.
For now, I only listed the internal packages. Changes in impl packages would be picked up by the plugin. In case we change something there, we need to decide then: Change it or not. Currently, we don't provide guarantees for impl packages …

[core] Add japicmp

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/EmptyCatchBlock.xml

[java] Fix EmptyCatchBlock with allowCommentedBlock

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

UnnecessaryImport was written with compilable code in mind. In invalid code, or code we do not know is valid because of missing aux classpath, it currently tends to FP which is not user-friendly. This implements a better strategy for when we can't resolve some names.
- Fixes #4602
- fix #4785

[java] Fix #4602 - unnecessaryimport FPs

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTAnnotation.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTAnnotationTest.java

This adds a new getter `getRawName()` for annotations, which returns the original annotation name, that is not normalized.
For Java rules, the same is basically available via `annotationNode.getTextDocument().sliceOriginalText(annotationNode.getTextRegion())`, but for XPath rules this might be useful as an attribute `@RawName`.
- Fixes #4418

[apex] Add ASTAnnotation#getRawName

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/Lub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeSystem.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/testdata/LubTestData.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/GlbTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/LubTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/TypeInferenceTest.kt

[java] Fix problem with type inference with enums sharing a common interface

---

docs/pages/pmd/userdocs/suppressing_warnings.md

The problem was the use of the `@Image` attribute. I added some more details.
- Fix #4901

[doc] Fix xpath expressions in documentation of `violationSuppressXPath`

---

pmd-compat6/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-compat6/src/main/java/net/sourceforge/pmd/Report.java
pmd-compat6/src/main/java/net/sourceforge/pmd/reporting/Report.java

This adds two missing methods, that will be needed if one uses the combination of PMD 7 + maven-pmd-plugin 3.22.0 + pmd-compat6.
Technically, pmd-compat6 won't be needed anymore with m-pmd-p 3.22.0. But if someone already uses m-pmd-p 3.21.2 + pmd 7.0.0 + pmd-compat6 7.0.0, then this probably will happen:
* dependabot suggests to upgrade m-pmd-p from 3.21.2 to 3.22.0
* the build is failing, as m-pmd-p 3.22.0 is now incompatible with pmd-compat6 7.0.0
* later dependabot suggests to upgrade pmd from 7.0.0 to 7.1.0
* this build will work (still with m-pmd-p 3.21.2)
* if projects now rebase/retry upgrade to m-pmd-p 3.22.0, this should work
So, one possible upgrade path would be:
1. pmd 7.0.0 + pmd-compat6 7.0.0 -> 7.1.0
2. m-pmd-p 3.21.2 -> 3.22.0
3. remove pmd-compat6
The correct fix for the …

[compat6] Make compat6 forward compatible with maven-pmd-plugin 3.22.0

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/AstAttributeNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/AstDocumentNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/AstElementNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/BaseNodeInfo.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/DomainConversion.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonExtensionFunctionDefinitionAdapter.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQuery.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQueryTest.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/SaxonDomXPathQuery.java
pom.xml

Saxon currently supports versions 10, 11 and 12. How long version 10 will remain to be supported is not clear, making the upgrade now gives us some future-proofing, while allowing us to benefit from further improvements in Saxon.
All changes are to internal classes, so this is backwards compatible.
Saxon 11+ and 12.1+ support Java 8+, so since PMD 7.0.0 there is no incompatibility on this front either.

[core] Upgrade saxon to 12.4

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java

Upon an incomplete auxclasspath, the symbol may be null. We need to handle that properly.
- Fixes #4751

[java] Avoid NPE in CloseResourceRule

---

docs/pages/release_notes.md
pom.xml

For the latest release 7.0.0, not all artifacts are reproducible:
* https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/net/sourceforge/pmd/README.md
* https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/net/sourceforge/pmd/pmd-7.0.0.buildcompare
15 files are not reproducible. This PR fixes these.
1. The BOM for the parent POM created by cyclonedx contains all modules. However, due to the cyclic dependency between pmd and pmd-designer (see #4446) we do the release in two phases: first without pmd-cli/pmd-dist and in the 2nd phase only pmd-cli/pmd-dist. In the first phase, the parent POM is published and the BOM doesn't contain pmd-cli/pmd-dist. This PR now always excludes these two modules from the BOM, so that the whole project can be …

Fix reproducible build issues with 7.0.0

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

Fix a couple scenarios where we were not properly handling the `@MethodSource` annotation for rule `UnusedPrivateMethod`
- Fixes #4278 
- Fixes #4975

[java] Properly handle @MethodSource in UnusedPrivateMethod

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/BaseNodeInfo.java

This avoids the unchecked cast, but not sure, whether it's better readable at all.
The other point: Now I'm not extends saxon's [ListIterator](https://saxonica.plan.io/projects/saxonmirrorhe/repository/he/revisions/saxon12/entry/src/main/java/net/sf/saxon/tree/iter/ListIterator.java) anymore, which seems to have a lot of optimizations (LastPositionFinder, Lookahead, ...). Maybe that has some performance impact?
So, overall, I'm not sure, whether this change is worth it...
Let's see, whether at least all our XPath rules still work :)
- Relates to #4959

[core] Typesafe saxon node iterators

---

.github/workflows/build.yml
do-release.sh
docs/pages/pmd/projectdocs/committers/releasing.md
pmd-java/src/main/resources/rulesets/java/quickstart.xml

Fixes the following issues noticed during the release:
* release_notes_pmd7.md was gone after the release. I've restored it with 6a1c7de03c92d9c98bdc10102068bb04a307e4a0 already, but this change fixes the root cause in do-release.sh. It was just a left-over.
* make it clear in do-release.sh, what to wait for: the github actions job being successful is enough
* also post the new release message to https://matrix.to/#/#pmd_pmd:gitter.im (manual task)
* Fix the problem for the 2nd stage release: the macos and windows builds failed because they claimed pmd-core-7.1.0.jar was not available. Problem is, that in the first stage, the cyclonedx (I guess, this plugin is the culprit) tries to download these, but of course at that time these artefacts are not in central. And this is recorded in the …

Fix release scripts

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeTestUtil.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/TypeTestUtilTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceVectorWithList.xml

[java]  Fix #4852 - TypeTestUtil.isA considers intersection type subtype of everything

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

- Fix #4985, this will not occur anymore even with incomplete auxclasspath

[java] Improve a bit the recovery behavior for unknown types

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleSetFactory.java

> Create a new {@link RuleSetLoader} with the same config as this factory.
In spite of the javadoc claiming the opposite, we didn't really copy over the current config to a the new `RuleSetLoader` when processing references. This caused the lack of appropriate error messages seen in #4978 
This PR fixes this, ensuring everything gets copied over.
- Fixes #4978

[core] Actually duplicate the whole current config for RuleSetLoader

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CpdAnalysis.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/FileAnalysisException.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/document/BaseMappedDocument.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CpdAnalysisTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/document/FragmentedTextDocumentTest.java

CPD used to crash if an invalid unicode escape was in a file. This was not treated as a (skippable) lexical error even if it should.
Another crash occurred if there was a lexical error and the current position of the token manager is a unicode escape. Then the routine to get the current line/column failed.
- Fixes #

[cpd] Fix CPD crashes about unicode escapes 

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/UnsynchronizedStaticFormatter.xml

[java]  Fix #2368 - UnsynchronizedStaticFormatter FP in static initializer

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseUnderscoresInNumericLiterals.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidUsingOctalValues.xml

ASTNumericLiteral did not correctly determine the base when a number ended with a non-number (L, F, D, .) This PR checks if the number ends with one of those characters, and correctly returns a base of 10.
- Fixes #5007

[java] Fix AvoidUsingOctalValues false-positive

---

pmd-core/src/main/java/net/sourceforge/pmd/util/DataMap.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAssignableExpr.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableCouldBeFinalRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodArgumentCouldBeFinalRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPassTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml

[java] Improve LocalVariableCouldBeFinal 

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/cpd/ApexCpdLexer.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/cpd/ApexCpdLexerTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/cpd/testdata/StringLiterals5053.cls
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/cpd/testdata/StringLiterals5053.txt

This makes it consistent with how the ApexParser
reads the files. And the case-sensitive ANTLR
rules (e.g. for string literals) work that
way.
Also, by using the AntlrTokenManager, we now fail with a LexException if we can't parse (and don't silently ignore such problems).
- Fixes #5053

[apex] Use case-insensitive lexer for CPD

---

pom.xml

- Bumps kotest from 5.5.5 to 5.9.1
- Bumps kotlin from 1.7.20 to 1.9.24
- Bumps dokka from 1.7.20 to 1.9.20
This is for 7.3.0. I did the update trying to debug kotest.
- Related #5009

Update kotest and kotlin

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/impl/AttributeAxisIterator.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/impl/dummyast/AbstractNode.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/impl/dummyast/ConcreteNode.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTBooleanLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCharLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNullLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTStringLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractLiteral.java

Let's give up and ~just~ only allow public methods in AttributeAxisIterator. It seems that the method handle lookup for public interface method implemented by package private methods doesn't work reliably.
So I went to the opposite way of #5021 - explicitly declaring/overriding the method in each subclass and thus elevating the access restrictions.
- Fixes #4885 (hopefully)

[java] Make impl of ASTLiteral#getLiteralText() public

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/MatchCollector.java

- inadvertently I was using the constructor that received an int as initial capacity, which instantiated massive collections leading to an increase in memory usage.
- Fixes #5066

[core] Fix memory usage regression in CPD

---

docs/pages/pmd/userdocs/tools/maven.md

Fixed small typo. It should be "mvn compile" not "mvn complile".

[doc] Update maven.md - Typo fixed for maven target

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/pmd.bat

The fix is to just remove the trailing backslash...
I did some more testing, and for me it looks good:
Test Matrix:
|Test|Result 🟢 🔴|
|----|------|
|cmd| |
|JAVA_HOME without spaces, JAVAFX_HOME without spaces, PMD_HOME without spaces| |
|`pmd check --help`|🟢|
|`pmd designer`|🟢|
|JAVA_HOME with spaces, JAVAFX_HOME without spaces, PMD_HOME without spaces| |
|`pmd check --help`|🟢|
|`pmd designer`|🟢|
|JAVA_HOME without spaces, JAVAFX_HOME with spaces, PMD_HOME without spaces| |
|`pmd check --help`|🟢|
|`pmd designer`|🟢|
|JAVA_HOME without spaces, JAVAFX_HOME without spaces, PMD_HOME with spaces| |
|`pmd check --help`|🟢|
|`pmd designer`|🟢|
|powershell| |
|JAVA_HOME without spaces, JAVAFX_HOME without spaces, PMD_HOME without spaces| |
|`.\pmd check --help`|🟢|
|`.\pmd designer`|🟢|
|JAVA_HOME …

[cli] Fix pmd.bat for Windows when starting designer with JAVAFX_HOME

---

pmd-javascript/pom.xml
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/jquery-selector.txt

Just a small update to [Rhino 1.7.15](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_15_Release).
I don't think, it is necessary to mention this in the release notes.
- None

[javascript] Bump rhino from 1.7.14 to 1.7.15

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

[java] FP for UnusedPrivateMethod with Jakarta @PostConstruct/PreDestroy annotations

---

docs/pages/release_notes.md
pmd-ant/src/main/java/net/sourceforge/pmd/ant/CPDTask.java
pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/CpdCommand.java
pmd-cli/src/test/java/net/sourceforge/pmd/cli/BaseCliTest.java
pmd-cli/src/test/java/net/sourceforge/pmd/cli/CpdCliTest.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CpdAnalysis.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CpdAnalysisTest.java

[core] Don't log warning about skipLexicalErrors twice

---

.github/dependabot.yml
do-release.sh
docs/pages/pmd/projectdocs/committers/releasing.md

- dependabot runs weekly
- github-action and bundler are creating a single PR for updating
- also integrate automatic release notes generation
More info:
- https://github.blog/2024-05-02-dependabot-on-github-actions-and-self-hosted-runners-is-now-generally-available/
I've enabled this option for us, so we should see the dependabot runs under https://github.com/pmd/pmd/actions
- reference doc: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
- for pmd-github-action, we already use it: https://github.com/pmd/pmd-github-actions/blob/main/.github/dependabot.yml
- by default, the created PRs are labeled with "dependencies". When merging them, we must assign them to the correct milestone, to keep track, what is in a …

Enable Dependabot

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ConstantFolder.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientStringBuffering.xml

- Fixes #3602 
- Fixes #4731
- Fixes #5151
- Fixes #5152
- Fixes #5153

[java] Revamp GuardLogStatementRule to allow var, field and array accesses

---

pmd-java/src/main/resources/category/java/multithreading.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/multithreading/AvoidSynchronizedStatementTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/AvoidSynchronizedStatement.xml

see https://openjdk.org/jeps/8337395
Modify advice for AvoidSynchronizedAtMethodLevel and add AvoidSynchronizedStatement.
See https://openjdk.org/jeps/8337395 for detailed information about virtual thread pinning concerns.
- Fixes #

[java] Update AvoidSynchronizedAtMethodLevel message to mention ReentrantLock, new rule AvoidSynchronizedStatement

---

pom.xml

Also bump maven-checkstyle-plugin from 3.4.0 to 3.5.0
After that, we can update build-tools (see pmd/build-tools#33)
- Fixes #

Bump checkstyle from 10.14.0 to 10.18.1

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java

Processing errors might contain inside their details message a CDATA section. This is output itself as
a CDATA section, but XMLStreamWriter#writeCData doesn't escape it automatically - it just outputs the string as is. This results in invalid XML.
- Fixes #5059

[core] Fix PMD's XMLRenderer to escape CDATA

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CheckSkipResultRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CheckSkipResult.xml

[java] Adjust signature matching in CheckSkipResultRule

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleReference.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleSetWriter.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/RuleReferenceTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/RuleSetWriterTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/lang/rule/rulesetwriter-test.xml

RuleReference#getOverriddenPropertyDescriptors should behave consistent to #getOverriddenPropertiesByPropertyDescriptor. RuleSetWriter needs to make sure to
export only the values for properties of rule references.
- Fixes #5222

[core] Fix RuleReference / RuleSetWriter handling of properties

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml

[java] Fix #5068: Class incorrectly identified as non-instantiatable

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/AllDataflowRuleTests.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableCouldBeFinalTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNullPointerExceptionTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ImplicitSwitchFallThroughTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml

(This adds FNs to UnusedAssignment)
- Fixes #5046

[java] Fix #5046 - FPs in LocalVariableCouldBeFinal

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

[java] Fix #5067: CloseResource: False positive for FileSystems.getDefault()

---

javacc-wrapper.xml
pmd-cpp/pom.xml
pmd-java/pom.xml
pmd-javascript/pom.xml
pmd-jsp/pom.xml
pmd-matlab/pom.xml
pmd-modelica/pom.xml
pmd-objectivec/pom.xml
pmd-plsql/pom.xml
pmd-python/pom.xml
pmd-velocity/pom.xml
pmd-visualforce/pom.xml
pom.xml

javacc is on the antrun plugin's classpath. The javacc jar file doesn't need to be copied
explicitly, it can simply be used.
It uses the plugin classpath available from maven - see https://maven.apache.org/plugins/maven-antrun-plugin/examples/classpaths.html
Note: we need to use the java-task with "fork=true" to run javacc, as javacc stops the VM with System.exit(...) at the end - which would end ant/maven as well...
- none

Use plugin-classpath to simplify javacc-wrapper.xml

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CouplingBetweenObjectsRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/CouplingBetweenObjects.xml

That's a small bugfix - the rule [CouplingBetweenObject](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#couplingbetweenobjects) intended to report the actual count to the message, but used the wrong addViolation method call always using the default message.
This refactors now that we use parameters in the message and adds additionally the threshold value to the message.
When we add the actual count to the message, we can more easily verify that the rule works
as expected.
Note: This should now result by the regression tester, that all messages have been changed. Otherwise there should be no other changes (number violations should stay the same).
- none

[java] CouplingBetweenObjects: improve violation message

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/UselessOperationOnImmutableRule.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UselessOperationOnImmutable.xml

Fix #5244: [java] UselessOperationOnImmutable: consider java.time.* types

---

pmd-ant/src/main/java/net/sourceforge/pmd/ant/Formatter.java
pmd-dist/src/test/java/net/sourceforge/pmd/dist/AntIT.java

- for java 17+, there is public API to get the console encoding -> no problem
- for older java versions, try to use system property sun.jnu.encoding if it exists
- only then use the fall-backs with illegal reflective access to private fields/methods on java.io.Console
- Also avoid using reflection utils from apache commons, instead use reflection directly. The illegal access warnings are then properly reported against our class net.sourceforge.pmd.ant.Formatter.
- Fixes #1860

[ant] Formatter: avoid reflective access to determine console encoding

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericTypeParameterCounter.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ModuleStub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/DeadlockTest.java
pmd-java/src/test/resources/simplelogger.properties

When creating a LazyClassSignature or LazyMethodType, make sure
to parse the number of type parameters eagerly, so that AstDisambiguationPass
can get this number without triggering additional parsing.
- Fixes #5293

[java] Fix #5293: Parse number of type parameters eagerly

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexCommentBuilder.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexLexerTest.java

The Apex lexer fails to correctly parse Unicode escape sequences when it does not operate on a `CaseInsensitiveInputStream`.
For example:
~~~java
ApexLexer lexer = new ApexLexer(CharStreams.fromString("'Fran\\u00E7ois'"));
CommonTokenStream tokens  = new CommonTokenStream(lexer);
tokens.fill();
~~~
This causes a runtime error during `tokens.fill()`:
~~~
line 1:0 token recognition error at: ''Fran\u00E'
line 1:14 token recognition error at: '''
~~~
The character stream must be wrapped in a `CaseInsensitiveInputStream`:
~~~java
ApexLexer lexer = new ApexLexer(new CaseInsensitiveInputStream(CharStreams.fromString("'Fran\\u00E7ois'")));
...
~~~
Performing a `pmd check` on Apex classes eventually leads to `ApexCommentBuilder.extractInformationFromComments()`, which does not include the wrapped …

[apex] Use case-insensitive input stream to avoid choking on Unicode escape sequences

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/MethodRefInferenceTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

has compile time decl
- Fixes #5083

[java] Fix #5083 - UnusedPrivateMethod false positive with mref without target type but with exact method

---

pmd-julia/pom.xml
pmd-julia/src/main/java/net/sourceforge/pmd/lang/julia/ast/JuliaBaseListener.java
pmd-julia/src/main/java/net/sourceforge/pmd/lang/julia/ast/JuliaBaseVisitor.java
pmd-julia/src/main/java/net/sourceforge/pmd/lang/julia/ast/JuliaListener.java
pmd-julia/src/main/java/net/sourceforge/pmd/lang/julia/ast/JuliaParser.java
pmd-julia/src/main/java/net/sourceforge/pmd/lang/julia/ast/JuliaVisitor.java

- Flag generated code from the grammar as such, to avoid it impacting coverage.
- Take the chance to remove / deprecate autogenerated classes that are not needed and were not used.
- Follows up on #5258 for Julia

[julia] Ignore generated code in Julia module

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] Fix #5263 - UnnecessaryFullyQualifiedName FP with forward references

---

antlr4-wrapper.xml
javacc-wrapper.xml
pmd-javascript/pom.xml

Ensures the lexer is annotated as generated code
- Follow up on #5258

[typescript] Add cleanup after generating ts lexer

---

pmd-apex/src/main/resources/category/apex/design.xml

Updated the documentation for the Apex > Design > UnusedMethod rule in conjunction with [this](https://github.com/pmd/pmd/discussions/5200#discussioncomment-11037719) discussion around a nuance with apex-link and not finding methods in 'empty' classes unless there's a variable declaration or other method present/called.
As above, relates to findings from discussion #5200 which was causing some unknown behaviour with the rule not firing as expected. Doesn't _fix_ #5200 but makes it clearer in the documentation.

[apex] Updated the docs for UnusedMethod as per discussion #5200

---

.github/workflows/build.yml
.github/workflows/git-repo-sync.yml
.github/workflows/troubleshooting.yml
pom.xml

This contains the PMD Release Signing Key,
that is valid for another year.

Bump build-tools to 28

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LambdaCanBeMethodReferenceRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LambdaCanBeMethodReference.xml

[java] Fix #5214 - LambdaCanBeMethodReference issue with method of enclosing class

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [PMD Guru](https://gurubase.io/g/pmd) to Gurubase. PMD Guru uses the data from this repo and data from the [docs](https://docs.pmd-code.org/latest/) to answer questions by leveraging the LLM.
In this PR, I showcased the "PMD Guru", which highlights that PMD now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable …

[doc] Introducing PMD Guru on Gurubase.io

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SimplifyBooleanReturnsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifyBooleanReturns.xml

Curiously existing tests had correct comments but wrong test assertions...
- Fixes #4763

[java] Fix #4763 - wrong message for SimplifyBooleanReturns

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UseDiamondOperatorRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConfusingArgumentToVarargsMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/PhaseOverloadSet.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeGenerationUtil.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeOpsTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ConfusingArgumentToVarargsMethod.xml

[java] Fix #5070 - confusing argument to varargs method FP when types are unknown

---

pom.xml

- dogfooding
- asm dependency override is not needed anymore, as pmd 7.8.0 uses asm 9.7.1 already

Bump pmd from 7.7.0 to 7.8.0

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/pmd.bat

Fix #5401: [cli] pmd.bat: set codepage to 65001 (UTF-8)

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/pmd.bat

If no quotes are used, then redirection characters such as `&` are interpreted and the resulting variables might contain only part of the desired values.
Performed manual testing. Test cases 6, 8, 9 were failing before and are fixed with this PR.
1) Happy case
```
SET "JAVA_HOME=C:\Users\adangel\openjdk\jdk-21.0.5+11"
SET "PMD_HOME=C:\Users\adangel\binaries\pmd-bin-7.8.0"
SET "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS ;.WSF;.WSH;.MSC"
SET "PATH=%PMD_HOME%\bin;%JAVA_HOME%\bin;C:\Windows\system32;C:\Windows"
SET "JAVAFX_HOME=C:\Users\adangel\openjdk\javafx-sdk-21.0.5"
SET "CLASSPATH="
pmd --version
```
2) JAVAFX_HOME with space
```
SET "JAVAFX_HOME=C:\Users\adangel\openjdk\javafx sdk 21.0.5"
```
3) JAVA_HOME with space
```
SET "JAVA_HOME=C:\Users\adangel\openjdk\jdk 21.0.5+11"
SET …
```

Fix #5399: [cli] pmd.bat: Quote all variables when using SET

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

[java] Fix #4861 - UnusedPrivateMethod FP in JDK classes

---

.github/workflows/build.yml
.github/workflows/git-repo-sync.yml
.github/workflows/troubleshooting.yml
docs/pages/release_notes.md
pom.xml

After merging this PR, the new GPG key will be used for the SNAPSHOT deployments to Maven Central.
Before we release 7.10.0, we of course need to release build-tools 29-SNAPSHOT before.
Note: The new secrets (PMD_CI_GPG_PRIVATE_KEY and PMD_CI_GPG_PASSPHRASE) are setup already.
- See also https://github.com/pmd/pmd-designer/pull/98
- See also https://github.com/pmd/pmd-eclipse-plugin/pull/237

Use new gpg key (A0B5CA1A4E086838)

---

pmd-java/src/main/resources/category/java/multithreading.xml

In https://docs.pmd-code.org/latest/pmd_rules_java_multithreading.html#avoidsynchronizedatmethodlevel the preferred example uses variable `CLS_LOCK` instead of `CLASS_LOCK`.
Renamed variable inside the example code for better consistency.
N/A

[java] AvoidSynchronizedAtMethodLevel: Fixed error in code example

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/SubtypingTest.kt

~I unfortunately wasn't able to create source that triggers the bug. I identified the infinite loop from the stack trace, and had to add a new entry point to the convertibility visitor to fall into it.~ #5505 provided a test case.
- Fix #5442
- Fix #5505

Fix #5442: [java] Fix stackoverflow with recursive generic types

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

 Fix #5504: [java] UnusedAssignment FP with continue in foreach loop

---

.ci/build.sh
docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/userdocs/signed_releases.md
docs/pages/release_notes.md

This creates and upload a detached signature for our release files.
It uses the same gpg key as we use for maven-gpg-plugin.
- none

[ci] Add signed releases

---

.github/workflows/build.yml
.github/workflows/pull-requests.yml
docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/devdocs/github_actions_workflows.md
docs/pages/pmd/projectdocs/committers/infrastructure.md
pom.xml

The goal is
- to have faster feedback for PRs
- better visibility which part of the workflow failed
- have build artifacts available to verify/test locally
The jobs are:
- "compile": First a fast compile job. The result of this job are three artifacts:
- the compilation results (everything in the target/ directories) is available in "compile-artifact"
- a "staging-repository" with the currently built pmd artifacts. This is used by the dogfood job later.
- a "dist-artifact" which contains the binary distribution files, ready to be downloaded from the workflow page, so that one can try out the built PMD from the PR branch without the need to built itself.
- additional, the local maven repo is cached for the other jobs.
- Then in parallel a bunch of other jobs:
- "verify": runs a complete …

[ci] New optimized workflow for pull requests

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/IdenticalCatchBranches.xml

**Rule:** [IdenticalCatchBranches](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#identicalcatchbranches)
While executing PMD locally on our sources I found that IdenticalCatchBranches reports this place:
https://github.com/pmd/pmd/blob/6ac7fc8a9979f1e42b73a2f661e8561939c91d51/pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/internal/RuleApplicator.java#L80-L83
While they look identical, the `AssertionUtils.contexted` is overloaded and each branch calls a different overload. So this is a false positive. I fix it here by comparing that the structure of the subtrees is identical, including the methods that they call.
- The build of #5529 may be failing because of this? The maven log doesn't say, but that's what I found locally.

[java] Fix IdenticalCatchBranch reporting branches that call different overloads

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java

This fixes a small race condition I noticed when fixing the integration test for regression tester (https://github.com/pmd/pmd-regression-tester/actions/workflows/manual-integration-tests.yml):
Sometimes (not reliably reproducible) there appears a false negative for ExhaustiveSwitchHasDefault: The following exhaustive switch is sometimes detected, sometimes not: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java#L62
It is definitely exhaustive, as the enum is declared here with only 3 constants: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java#L42
It turned out, this appears only, when the enum is declared as a inner class. Then we sometimes …

[java] Fix race condition in ClassStub for inner classes

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubBuilder.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/EnumConstantWithBody.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/LocalClasses.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/SigParserTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeCreationDsl.kt

Parsing the class file of an anonymous class was not populating the simple name, causing an NPE. I'm not sure why an anonymous class was parsed at all, but this crash occurred when analysing JDK sources.

[java] Fix crash when parsing class for anonymous class

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/util/AssertionUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/TParamStub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/TypeAnnotationHelper.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeMirror.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/DeadlockTest.java

ClassStubs now cannot request parsing of another ClassStub while they are themselves being parsed. This is enforced when assertions are enabled. ClassStubs can still be loaded in parallel but they never have to wait for another thread anymore which might be good for performance.
Maybe we should remove the logging statements in ParseLock, the ones about threads locking and such. There shouldn't be any threading problem happening
- Fix #5587
- Related to #5293

Fix #5587: [java] Fix deadlock while loading ClassStub

---

.ci/files/Gemfile.lock
docs/Gemfile.lock

Fixes https://github.com/pmd/pmd/security/dependabot/79
Also update bundler and various other gems.

Bump nokogiri from 1.18.3 to 1.18.5

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTBooleanLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCharLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTExpression.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNullLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTStringLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaExpr.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractLiteral.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ConstantFolder.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientStringBufferingRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ConstValuesKotlinTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/FinalFieldCouldBeStatic.xml

To fix this i had to refactor a bit the constant folding logic. It wasn't actually implementing the definition of the JLS for a "compile-time constant". The logic now makes `ASTExpression#isCompileTimeConstant()` and `#getConstValue()` respect the JLS definition, that is, the only variables referenced must be compile-time constant fields (ie static final with CT constant initializer, and cannot have blank initializer). However this is very restrictive, while some rules want to know if the value is known at compile time, even if it uses non-static final fields, or final local variables for instance. I extended the logic of the constant folder to track whether the resolved constant value is a CT constant according to the strict definition or to the loose definition.
- Fix #5590

Fix #5590: [java] LiteralsFirstInComparisons with constant field

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLocalVariableDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableId.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableCouldBeFinalRule.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/LombokTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml

Fix #5079: [java] LocalVariableCouldBeFinal false-positive with lombok.val

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclaration.java
pmd-java/src/main/javacc/Java.jjt
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclarationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/PackageCase.xml

Fix #5452: [java] PackageCase reported on wrong line

---

docs/Gemfile.lock
docs/pages/pmd/userdocs/extending/testing.md
docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/ExcessiveParameterListRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/internal/AbstractCounterCheckRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/ExcessiveParameterList.xml
pmd-test-schema/src/main/java/net/sourceforge/pmd/test/schema/BaseTestParserImpl.java
pmd-test-schema/src/main/java/net/sourceforge/pmd/test/schema/RuleTestDescriptor.java
pmd-test/src/main/java/net/sourceforge/pmd/test/RuleTst.java
pmd-test/src/test/java/net/sourceforge/pmd/test/RuleTstTest.java

* This improves the test framework, so that we can assert line number ranges (begin line - end line)
- Fix #5616

Fix #5616: [apex] ExcessiveParameterList: Report only method signature

---

docs/_plugins/custom_filters.rb
docs/search.json

Affected PMD Version: 7.11.0 (was working with 7.10.0)
Due to missing json escaping, the search.json file couldn't be loaded and no search was possible.
- Fix #

[doc] Fix search index

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AccessorMethodGenerationRule.java

The current implementation performs 90% of the same logic, except for data transformation or type casting. However, instead of using a centralized approach, it follows a duplicated approach, which breaks the design by violating:
- **Feature Envy**  
- **Single Responsibility Principle (SRP)**  
- **Separation of Concerns (SoC)**  
- Refactor redundant `if` statements into a centralized method.  
- Apply the **Don't Repeat Yourself (DRY)** principle.  
- Ensure clear separation of concerns to enhance maintainability.  
`Since this is core business logic, it's important and should be centralized. Having the same logic in two places is one too many in this case, in my opinion.`
[](https://github.com/pmd/pmd/pull/5620)

[java] Cleanup `AccessorClassGenerationRule` implementation

---

pmd-dist/src/main/resources/scripts/pmd

Followup on https://github.com/pmd/pmd/pull/5594#issuecomment-2743410777. This makes the pmd launch script compatible with `/bin/sh` by removing bash-specific features. I did this with copilot and shellcheck.
I'm not sure about one change which is `${BASH_SOURCE[0]:-${(%):-%x}}` to `$0`. Shellcheck cannot even parse the expression on the left so I'm not sure what's going on here. And bash also errors with `bad substitution`.
- Fix #

[dist] Make pmd launch script compatible with /bin/sh

---

.github/workflows/build.yml
.github/workflows/git-repo-sync.yml
.github/workflows/troubleshooting.yml
pom.xml

- https://checkstyle.sourceforge.io/releasenotes.html#Release_10.23.0
- https://checkstyle.sourceforge.io/releasenotes.html#Release_10.22.0
This also updates build-tools to include pmd/build-tools#55

Bump checkstyle from 10.21.4 to 10.23.0

---

pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/AvoidGlobalModifier.xml
pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimeTracker.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/RawFileFingerprinter.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersionDiscoverer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleSetFactory.java
pmd-doc/src/test/resources/expected/java.md
pmd-doc/src/test/resources/expected/sample.md
pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml
pmd-doc/src/test/resources/rulesets/ruledoctest/sample2.xml
pmd-java/src/main/resources/category/java/multithreading.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ant/classpathtest/ruleset.xml
pmd-velocity/src/main/javacc/Vtl.jjt
pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/visualforce/DataType.java

I noticed a mistaken "its" when it should be "it's" in a rule description, and also "doable" when it was supposed to be double.  Decided to poke around more broadly and fix all instances I could find
N/A

[doc] Fix its/it's and doable/double typos

---

pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java14/YieldStatements.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java14/YieldStatements.txt

Seems the value `0x4P60` also hits the bug, that was fixed in Java 19.
See #4401, https://bugs.openjdk.org/browse/JDK-4511638, https://bugs.openjdk.org/browse/JDK-8291475 and https://inside.java/2022/09/23/quality-heads-up/
We now use "0x4P61", which doesn't hit this bug...
- Refs #4401

[java] Fix Double Literal for Java19+ compatibility

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/ApexUnitTestShouldNotUseSeeAllDataTrueRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/ApexUnitTestShouldNotUseSeeAllDataTrue.xml

- Updated ApexUnitTestShouldNotUseSeeAllDataTrueRule.java to check for SEE_ALL_DATA parameter value being true.
- Added a new test case in `ApexUnitTestShouldNotUseSeeAllDataTrue.xml` to validate the updated rule.
- Fix #5667

Fix #5667: [apex] ApexUnitTestShouldNotUseSeeAllDataTrue false negative when seeAllDate parameter is a string

---

.ci/build.sh
.github/workflows/build.yml
README.md
do-release.sh
docs/pages/pmd/projectdocs/committers/releasing.md
docs/pages/release_notes.md

- This enhances the current release workflow to also trigger the workflow in https://github.com/pmd/docker to create a new image
- This is a workflow in a different repository, so GitHub Actions permissions are bit different. In order to make this (hopefully) work, I created a new custom GitHub App in our organization (https://github.com/pmd) and installed it. This GitHub App is named "PMD Actions Helper" and for now has the only permission to trigger workflows in any of our repositories (permission: actions=write).
- This app installation is used to request a new installation access token when the release workflow is run and this token is used to execute workflow dispatch API call (https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event ) …

Fix #5448: [ci] Maintain public Docker image

---

.github/workflows/publish-pull-requests.yml
docs/pages/pmd/devdocs/github_actions_workflows.md

This PR contains small improvements for the "Publish Pull Requests" workflow. These are cherry-picked from #5584:
* Add a timestamp to the PR comment, so that is is better visible, when it was last updated.
* Document robots.txt and follow links impact with search engines. The regression tester reports and the temporary documentation sites should not be indexed by search engines.
* Add a job summary where we can see, which pull request and which workflow run this new run of "Publish Pull Requests" has been triggered
* Use SHA1 for the sticky-pull-request-comment instead of `@v2`
- Refs #5584 
- Refs #4328

[ci] Improvements for "Publish Pull Requests"

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CpdAnalysis.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/SourceManager.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CpdAnalysisTest.java

In keeping with AutoCloseable Javadocs, Effective Java, and https://pmd.github.io/pmd/pmd_rules_java_design.html#avoidthrowingrawexceptiontypes
#5698

[core] Don't accidentally catch unexpected runtime exceptions in CpdAnalysis

---

.github/workflows/build-pr.yml
.github/workflows/build-snapshot.yml
.github/workflows/build.yml
.github/workflows/publish-pull-requests.yml
.github/workflows/publish-snapshot.yml
docs/pages/pmd/devdocs/github_actions_workflows.md

This should avoid triggering unnecessary publish-* workflows, as we can now filter on the events beforehand.
The additional filter is still kept for additional safety.
Refs pmd/pmd#4328

[ci] Make build a reuseable workflow

---

.ci/build.sh
.github/workflows/build.yml
.github/workflows/publish-snapshot.yml
docs/pages/pmd/devdocs/building/building_general.md
docs/pages/pmd/devdocs/github_actions_workflows.md
pom.xml

OSSRH is being shut down, we now need to use central portal for publish artifacts to maven central.
See https://central.sonatype.org/publish/publish-portal-guide/  
See https://central.sonatype.org/news/20250326_ossrh_sunset/
Note: The whole namespace `net.sourceforge.pmd:*` will need to be migrated at once, so we need to migrate pmd-designer and pmd at the same time.
- pmd/build-tools#69
- pmd/pmd-designer#169

[ci] publish-snapshot/old build: migrate to central portal

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedLocalVariable.xml

Fix #5061: [java] UnusedLocalVariable FP when using compound assignment

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JConstructorSymbol.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JExecutableSymbol.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JMethodSymbol.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ImplicitMemberSymbols.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ExecutableStub.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AbstractAstAnnotableSym.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AbstractAstExecSymbol.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstCtorSym.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstMethodSym.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/ClassMethodSigImpl.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/internal/TypeAnnotReflectionOnMethodsTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/internal/TypeAnnotTestUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/ClassWithTypeAnnotationsOnMethods.java

Just an incremental improvement.
- Ref #4334

[java] Support annotated constructor return type in symbol API

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LinguisticNamingRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LinguisticNaming.xml

Fix #2462: [java] LinguisticNaming should ignore setters for Builders 

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseArraysAsList.xml

Collection.add was too broad and included Set.add as well. But this rule should only report, if values are added to a List.
- Fix #5711

Fix #5711: [java] UseArrayAsList - only consider List.add

---

docs/pages/release_notes.md
pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/visualforce/ast/ObjectFieldTypes.java
pmd-visualforce/src/test/java/net/sourceforge/pmd/lang/visualforce/ast/VfExpressionTypeVisitorTest.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/visualforce/ast/VfExpressionTypeVisitor/metadata/sfdx/objects/Case/fields/Description.field-meta.xml
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/visualforce/ast/VfExpressionTypeVisitor/metadata/sfdx/pages/CasePrintPage.page
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/visualforce/ast/VfExpressionTypeVisitor/metadata/sfdx/pages/CasePrintPage.page-meta.xml

- Add a test case with e.g. a apex page that references Case.Description
- Use apex-dev-tools:sobject-types dependency to lookup standard objects/fields
- Fix #5476

Fix #5476: [visualforce] Resolve data types of standard object fields

---

pmd-dist/src/main/resources/scripts/pmd

Now we always determine PMD_HOME based on the script location. If PMD_HOME is already defined, it is ignored.
- Fix #5705

Fix #5705: [cli] Always determine PMD_HOME based on script location

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

Filtered comment text has the prefixes "/**" and "*" removed, so that only the plain javadoc text is used. This allows for correct multiline detection of references in javadoc.
- Fix #1639 
- Fix #5832

Fix #1639 #5832: Use filtered comment text for UnnecessaryImport

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ReplaceJavaUtilCalendarTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ReplaceJavaUtilDateTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReplaceJavaUtilCalendar.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReplaceJavaUtilDate.xml

Add rules discouraging the use of java.util.Calendar and java.util.Date. Instead, one should use the classes in java.time.
- Fix #2862

Fix #2862: [java] Add rules discouraging the use of java.util.Calendar and java.util.Date

---

docs/pages/release_notes.md
pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/test/ast/IntelliMarker.kt

This fixes the following warnings during build (they appeared at some point after a junit upgrade):
```
2025-07-08T17:55:43.6126480Z Jul 08, 2025 5:55:43 PM org.junit.platform.launcher.core.DiscoveryIssueNotifier logIssues
2025-07-08T17:55:43.6127957Z WARNING: TestEngine with ID 'junit-jupiter' encountered 2 non-critical issues during test discovery:
2025-07-08T17:55:43.6129584Z 
2025-07-08T17:55:43.6131442Z (1) [WARNING] @TestFactory method 'public void net.sourceforge.pmd.lang.java.types.SubtypingTest.primer()' must return a single org.junit.jupiter.api.DynamicNode or a Stream, Collection, Iterable, Iterator, Iterator provider, or array of org.junit.jupiter.api.DynamicNode. It will not be executed.
2025-07-08T17:55:43.6133978Z     Source: MethodSource [className = …
```

chore: Fix JUnit warning about invalid test factory

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/TypeParameterNamingConventionsRule.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/TypeParameterNamingConventionsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/TypeParameterNamingConventions.xml

Add a new rule TypeParameterNamingConventions, Deprecate GenericsNaming
The old rule wasn't configurable, the new one is.
The name of the new rule is in line with the existing rules ClassNamingConventions, FormalParameterNamingConventions, LocalVariableNamingConventions, and MethodNamingConventions.
- Fix #972

Fix #972: [java] Add a new rule TypeParameterNamingConventions

---

pmd-java/src/main/resources/category/java/errorprone.xml

Improve message/description/examples for AvoidUsingOctalValues
- Fix #3401 
- [n/a] Added unit tests for fixed bug/feature
- [n/a] Added (in-code) documentation (if needed)

Fix #3401: [java] Improve message/description/examples for AvoidUsingOctalValues

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AddEmptyStringRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AddEmptyString.xml

Expressions that add strings together may span multiple lines, the violation should be reported at the line where the violating string is located.
- Fix #5960

Fix #5960: [java] AddEmptyString: Improve report location

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/FinalFieldCouldBeStaticRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentInOperandRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AvoidThrowingRawExceptionTypes.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AvoidUncheckedExceptionsInSignatures.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/FinalFieldCouldBeStatic.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AssignmentInOperand.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidLiteralsInIfCondition.xml

Add a reference to the error message for 5 rules that may realistically report multiple violations for the same line of code:
* AssignmentInOperand
* AvoidLiteralsInIfCondition
* AvoidThrowingRawExceptionTypes
* AvoidUncheckedExceptionsInSignatures
* FinalFieldCouldBeStatic
- Fix #5960

Fix #5960: [java] Add details to the error message for some rules

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java
pmd-core/src/main/java/net/sourceforge/pmd/util/AssertionUtil.java
pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentInOperandRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AssignmentInOperand.xml

I took @oowekyala's code from #5014, made it apply to the current version of the rule, and fixed all the dogfood issues.
While at it, I fixed some XML issues in AssignmentInOperand.xml
- Fix #3434 
- Closes #5014

Fix #3434: [java] False negatives in AssignmentInOperand rule

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

Fix NPE that occurs when reporting a violation for a `var` variable within a for-each loop.
- Fix #5974

Fix #5974: [java] NPE in CloseResourceRule

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/JavaAstUtils.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java

check if there are enough characters in the Chars object before accessing them.
- Fix #6014

[java] Fix #6014: Crash when encountering a java comment at the end of a file

---

pmd-apex/src/main/resources/category/apex/bestpractices.xml
pmd-apex/src/main/resources/category/apex/codestyle.xml
pmd-apex/src/main/resources/category/apex/design.xml
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-modelica/src/main/resources/category/modelica/bestpractices.xml
pmd-plsql/src/main/resources/category/plsql/codestyle.xml
pmd-scala-modules/pmd-scala-common/src/test/java/net/sourceforge/pmd/lang/scala/RulesetFactoryTest.java
pmd-test/src/main/java/net/sourceforge/pmd/test/lang/rule/AbstractRuleSetFactoryTest.java

Instead of implementing a XML rule as suggested in the issue I just added the check to the factory test.
For easier debugging the test is now parametrized. Since parametrization over empty list is not possible, the Scala test needed to be updated.
- Fixes #6012

[test] Fix #6012: Alphabetically sort all default rules

---

.ci/files/Gemfile.lock

https://github.com/pmd/pmd-regression-tester/releases/tag/v1.6.1
- Should fix the report of #6021

Bump pmdtester from 1.6.0 to 1.6.1
