pmd/pmd

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitAssertionsShouldIncludeMessageRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitAssertionsShouldIncludeMessage.xml
Missing assertions were assertArrayEquals, assertNotSame, assertThat and
fail.
=> Add missing assertions in JUnitAssertionsShouldIncludeMessage test

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitAssertionsShouldIncludeMessageRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitAssertionsShouldIncludeMessage.xml
A missing assertion message for assertEquals(double, double, double)
is detected in most cases now. If the assertEquals method has two
arguments, an assertion message is missing, if the assertEquals method
has three arguments, the first one has to be a string.
Pmd will only print an error if the first argument type has been
determined (getType() != null) and isn't a String. Therefore
assertEquals(getInt(), getInt(), getInt()) won't be detected as an
error. However, double d = 1.0; assertEquals(d, 1.0, 1.0); will be
detected.
The JUnitAssertionsShouldIncludeMessageRule.check method has been moved
to the inner class AssertionCall and has been expanded by an
isException hook. The assertEquals with three arguments check overrides
the isException method, returns true if the first argument …
=> [JUnit] Check assertion message present in assertEquals with delta

pmd-core/src/main/java/net/sourceforge/pmd/dcd/asm/TypeSignatureVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/dcd/graph/UsageGraphBuilder.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/visitors/PMDASMVisitor.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java8/pom.xml, pmd-java8/src/test/java/net/sourceforge/pmd/lang/java/bugs/InterfaceMethodTest.java, pmd-java8/src/test/java/net/sourceforge/pmd/lang/java/bugs/Java8MultipleLambdasTest.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverJava8Test.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/testdata/UsesJavaStreams.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/testdata/UsesRepeatableAnnotations.java, pom.xml
Current version of PMD fails on classes with default methods or static methods. JDK8 has updated semantics for `invokespecial` / `invokestatic` opcodes, upgrading to ASM 5 is not enough to support Java 8 opcodes like in commit 9b91690. In order to support these new semantics it is necessary to indicate to ASM to use the updated `ASM5` op code dictionary. Also this PR replaces the deprecated `visitMethodInsn` with the new version that takes an additional `boolean`
This PR also brings another maven module to allow to test PMD with JDK8 code, however for that one must run maven with the JDK 8.
Here's the stacktrace of the current failure
```
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) …
```
=> Improves JDK8 support for default methods and static methods in interfaces

pmd-xml/src/main/resources/rulesets/pom/basic.xml, pmd-xml/src/main/resources/rulesets/pom/rulesets.properties
Hi,
Given the capacities of XML ruling, I thought it might be interesting to have a ruleset regarding the (in)famous maven's POM file. The proposed ruled is probably controversial more than basic, but it's a start. Hopefully, it will trigger some more idea from the PMD community :)
=> Add a new rulesets for Maven's POM rules

pmd-dist/src/main/scripts/run.sh
When redirecting arguments, "$@" must be used.
=> Fix run.sh for paths with spaces

pmd-xml/src/main/java/net/sourceforge/pmd/lang/wsdl/WsdlLanguageModule.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/wsdl/rule/AbstractWsdlRule.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/AbstractXmlRule.java, pmd-xml/src/main/resources/META-INF/services/net.sourceforge.pmd.lang.Language, pmd-xml/src/test/java/net/sourceforge/pmd/lang/wsdl/rule/AbstractWsdlRuleTest.java
WSDL files are basically XML files but with extension "wsdl". Since PMD looks for the file extension in order to decide which parser to use, WSDL could not be verified without a language module specific for handling this kind of extension.
The changes I've made just create a new WsdlLanguageModule that uses the XML parser but recognizes WSDL files. Also, in order to create WSDL rules, one must extend the AbstractWsdlRule class.
Apart from that, the new module was added to the service file "net.sourceforge.pmd.lang.Language" and a test was created for the new abstract rule.
=> Adding support for WSDL rules

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/comments/CommentDefaultAccessModifierRule.java, pmd-java/src/main/resources/rulesets/java/comments.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/comments/CommentRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/comments/xml/CommentDefaultAccessModifier.xml
I have added a rule to look for methods, fields or nested classes that have a default access modifier. The rule attempts to prevent these from being left as package-private by accident rather than by design by requiring an appropriate comment.
For instance, the rule would expect to find:
```
/* default */ void myMethod() {
```
The regular expression used to match such comments can be configured through a property.
I have added this rule in comment.xml ruleset of the PMD-java code and the test cases have been added to the corresponding folders.
=> Add default access modifier as comment rule

pmd-java/src/main/resources/rulesets/java/basic.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/basic/BasicRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/basic/xml/SimplifiedTernary.xml
I have added a rule to check when a ternary operator has a literal boolean.
For example, if we have
```
condition ? true : otherThingToReturn(); 
```
it can be written as simple as
```
condition || otherThingToReturn() 
```
I have added this rule in basic.xml ruleset of the PMD-java code and the test cases in the corresponding folders.
=> Add rule for unnecessary literal boolean in ternary operators

pmd-java/src/main/resources/rulesets/java/junit.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/UseAssertTrueInsteadOfAssertEquals.xml
I modified the UseAssertTrueInsteadOfAssertEquals rule and tests to look for assertEqual with Boxed booleans as it is being done with the literal booleans.
=> Add check to Boxed booleans in UseAssertTrueInsteadOfAssertEquals rule

pmd-java/src/main/resources/rulesets/java/unnecessary.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/unnecessary/UnnecessaryRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unnecessary/xml/UselessQualifiedThis.xml
I have added this rule to look for qualified this usages in the same class.
for example
```java
public class Foo {
public void doSomething() {
final Foo anotherFoo = Foo.this;  // use "this" directly
}
}
```
The rule has been added in the useless.xml file and the test in their corresponding folder.
=> Add UselessQualifiedThisRule

pmd-java/src/main/resources/rulesets/java/clone.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/clone/CloneRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/clone/xml/CloneMethodReturnTypeMustMatchClassName.xml
If we have a class that implements cloneable the return type of our clone method should match with the class name instead of returning Object.
This makes sense since clone is expected to return an exact copy of the object; and since the return type is not part of the signature, it's still a valid override.
```java
public class Foo implements Cloneable {
@Override
public Object clone() { // Should be Foo
}
}
```
This is not required by the contract of Object.clone (even the [Javadoc says so] (http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#clone)), but is a sane default; and exceptions may suppress this rule were needed.
=> Add CloneMethodReturnTypeMustMatchClassName rule

pmd-java/src/main/resources/rulesets/java/clone.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/clone/CloneRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/clone/xml/CloneMethodMustBePublic.xml
As says in the [java docs](http://docs.oracle.com/javase/7/docs/api/java/lang/Cloneable.html) "By convention, classes that implement this interface should override Object.clone (which is protected) with a public method".
=> Add CloneMethodMustBePublic rule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/basic/CheckResultSetRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/basic/xml/CheckResultSet.xml
I would like to change the CheckResultSet rule to allow for returning the result of one of the navigation methods (next, first, last, previous). This is for the case when you are attempting to see if the query returned data, but you don't need to work with the data, such as checking the existence of a database column.
You can work around this currently with:
```java
if (resultSet.next()) {
return true;
}
return false;
```
But it would be much nicer to just do:
```java
return resultSet.next();
```
=> Change CheckResultSet to allow for the result of the navigation methods to be returned

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/unnecessary/UselessOverridingMethodRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unnecessary/xml/UselessOverridingMethod.xml
Removed unnecessary cast  on the statement var since it isn't always a ASTStatement.
Since the only method called is jjtGetChild() the Node interface is more than enough to work with.
Added a new test where the statement is a LocalVariableDeclaration
=> Fix ClassCastException in UselessOverridingMethodRule.

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/strings/ConsecutiveAppendsShouldReuseRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/strings/xml/ConsecutiveAppendsShouldReuse.xml
Added new append validation.
Check for an append even when the block first child is a LocalVariableDeclaration.
Added a new test to check the validation.
Issue: http://sourceforge.net/p/pmd/bugs/1370/
=> #1370 ConsecutiveAppendsShouldReuse not detected properly on StringBuffer

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/strings/InsufficientStringBufferDeclarationRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/strings/xml/InsufficientStringBufferDeclaration.xml
Added a new method to obtaint the lenght of strings added in appends after a contructor call.
Removed an else statement from the method getConstructorLength since we can have more than one literal in the block (with appends after the constructor call)
New test added for this change.
Fix: http://sourceforge.net/p/pmd/bugs/1371/
=> #1371 InsufficientStringBufferDeclaration not detected properly on StringBuffer

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/GenericToken.java, pmd-java/etc/grammar/Java.jjt, pmd-java/src/main/ant/alljavacc.xml, pmd-jsp/etc/grammar/JspParser.jjt, pmd-jsp/src/main/ant/alljavacc.xml
Added capability in Java and JSP parser for tracking tokens. It is often useful to keep track of each node's first and last token so that input can be easily reproduced again. Ref - https://javacc.java.net/doc/JJTree.html
=> Added capability in Java and JSP parser for tracking tokens.

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/logging/InvalidSlf4jMessageFormatRule.java, pmd-java/src/main/resources/rulesets/java/logging-java.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/loggingjava/LoggingJavaRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/loggingjava/xml/InvalidSlf4jMessageFormat.xml
I have added a rule to check the messages in slf4j loggers that have missing or extra parameters, ignoring the exception as parameter if exists because it is shown separately.
The rule was added in the logging-java file and the test cases have been added to the corresponding folders.
=> Add rule to look for invalid message format in slf4j loggers

pmd-java/src/main/resources/rulesets/java/controversial.xml
otherwise example will not compile even.
=> fix formatting typos in an example of the DoNotCallGarbageCollectionExplicitly rule

pmd-java/src/main/resources/rulesets/java/design.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/MissingStaticMethodInNonInstantiatableClass.xml
This will prevent flagging the class if it has the Builder Pattern and the constructor is private.
=> Add Builder pattern check to the MissingStaticMethodInNonInstantiatableClass rule

pmd-java/src/main/resources/rulesets/java/design.xml
Now mention that auto-generated methods should trigger this rule.
=> Change EmptyMethodInAbstractClassShouldBeAbstract rule's description.

pmd-core/src/test/java/net/sourceforge/pmd/ant/CPDTaskTest.java, pmd-core/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
Seems BuildFileTest was deprecated in ant 1.9.4
https://svn.apache.org/repos/asf/ant/core/trunk/src/tests/junit/org/apache/tools/ant/BuildFileTest.java
Following this ant tutorial
https://ant.apache.org/manual/tutorial-writing-tasks.html
I refactored two tests to avoid the deprecation
=> Refactored two test to stop using the deprecated ant class BuildFileTest

pmd-java/src/main/resources/rulesets/java/design.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/DesignRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ConstantsInInterface.xml
Implemented a new rule to enforce Effective Java, item 19. Constants in interface.
It can be absoutely strict, not allowing fields on interfaces, or relaxed (default), to just not alllow interfaces consisting solely of constants; which better matches the Effective Java definition.
=> Add ConstantsInInterface rule. Effective Java, 19

pmd-java/src/main/resources/rulesets/java/naming.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/naming/xml/BooleanGetMethodName.xml
If a method is annotated as an `@Override` `BooleanGetMethodName` should not be reported on it. If it's our own code, a single report on the interface / class actually defining it is enough, if it's in a library, there is nothing we can do about it.
Weirdly, this was already addressed for `MethodNamingConventions` in issue #1343
=> BooleanGetMethodName: Don't report bad method names on @Override

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CSVRenderer.java
Incorrect CSV was being generated when filepaths had commas.
=> [core] CSVRenderer: escape filenames with commas in csvrenderer

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codesize/StdCyclomaticComplexityRule.java
This fixes 1501: oom when the cyclomatic complexity rule is used without class file reporting.
=> [java] [apex] Fix for 1501: CyclomaticComplexity rule causes OOM when class reporting is disabled

pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java
When loading resources via `Classloader.getResourceAsStream` then these `InputStreams` need to be closed. If not, then on Windows the loaded files cannot be edited or deleted.
It would also be good to close all created `URLClassLoader`s after e.g. finishing the execution of the Ant task - this would also free the file handles allocated through these. I can open another PR for doing that.
We are enabling the Gradle daemon by default for Gradle 3.0. Issues like these will make the use of PMD for Windows developers much more inconvenient, since they have to kill the Gradle daemon in order to continue working each time the pmd Gradle task is invoked.
=> [core] [java] Close opened file handles

pmd-java/etc/grammar/Java.jjt, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/Bug1530.java
- Added a test case to show the regression
- Changed the grammar to handle it properly
I don't fully understand why JavaCC fails to properly use the syntactic lookahead, but it's fully working. All tests green.
=> [java] Fix parser error (issue 1530)

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/basic/BooleanInstantiationRule.java
- In Java 8 annotations may appear in several new places. For instance `Object o = new @Interned MyObject();` would have this rule fail with a `ClassCastException`
- The current code deals with it gracefully
=> [java] Fix BooleanInstantiationRule for Java 8

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/rules/CloneMethodMustImplementCloneable.java
- Java 8 code allows for things such as
`class UnmodifiableList<T> implements @Readonly List<@Readonly T> {}`
where not all token in the ASTImplementsList are ASTClassOrInterfaceType
I took the chance to fix indentation of this file since it was messy. Important changes are lines 37-43 (diff ignoring whitespace)
=> [java] Fix ClassCastException on CloneMethodMustImplementCloneable

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/rules/SignatureDeclareThrowsException.java
- Java 8 code allows for things such as
`class UnmodifiableList<T> implements @Readonly List<@Readonly T> {}`
where not all token in the ASTImplementsList are ASTClassOrInterfaceType
=> [java] Fix ClassCastException on SignatureDeclareThrowsException

pmd-java/etc/grammar/Java.jjt
- Handle less scenarios
- Have scenarios be defined more broadly (ie: allow more than 3 params)
- This improves parsing performance by roughly ~10%
=> [java] Simplify lambda parsing

pmd-java/etc/grammar/Java.jjt
- Don't look for arrays where there can be none
=> [java] Simplify VariableDeclaratorId parsing

pmd-plsql/etc/grammar/PldocAST.jjt
This should fix the issue. The root cause was a loop that would not terminate on error or EOF condition while scanning for an end delimiter.
=> [plsql] Fix PMD issue 1531- endless loop followed by OOM while parsing (PL)SQL

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/apexunit/ApexUnitTestClassShouldHaveAsserts.java
Apex is case-insensitive so removing casing from the check for asserts. If casing is required, should be moved to Style.
=> Changing method names to lowercase so casing doesn't matter

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java, src/site/markdown/overview/changelog.md
- This is now slightly faster, which for a method that gets called
over 1 million times on large projects is significant.
- We should still look for ways to reduce the number of calls to this
method.
This alone was enough to shave ~15% from analysis time when running the exact same test as used in #117
The baseline for PMD 5.5.2 was:
```
--------------------------------<<< Summary >>>--------------------------------
Segment                                         Time (secs)
Collect files:                                        0.241
Load rules:                                           0.053
Parser:                                               6.216
Symbol table:                                        16.711
RuleChain visit:                                      0.290
Reporting: …
```
=> [java] Avoid creating a new String to qualify types

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/PLSQLParserTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/IsNull.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/MultiLineSelect.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SingleLineSelect.pls
fixed crash of parsing following code (from unittest):
IF V_BUF IS NULL THEN
null;
end if;
=> [plsql] Added correct parse of IS [NOT] NULL and multiline DML

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSets.java, pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/PMDTask.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/NoopAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/MonoThreadProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/MultiThreadProcessor.java, pmd-core/src/test/java/net/sourceforge/pmd/ConfigurationTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java, src/site/markdown/overview/changelog.md
- Implement stage 1 of incremental analysis as per https://sourceforge.net/p/pmd/bugs/1538/
This turned out to be much simpler to implement than expected, however, I'd love to have some in-depth peer review. There are actually a couple points on which I'm not completely sure and would love some feedback.
The results are really promising (always analyzing the complete PMD source code):
`-d ./ -b -f text -r no-cache.report -R java-braces -threads 0`
```
-----------------------------<<< Final Summary >>>-----------------------------
Total                                           Time (secs)
Measured total:                                      25.381
Non-measured total:                                   0.729
Total PMD:                                           26.111
```
`-d ./ -b -f text …
=> [core] Incremental analysis

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java, pmd-apex/src/main/resources/rulesets/apex/ruleset.xml, pmd-apex/src/main/resources/rulesets/apex/security.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/SecurityRulesTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
Hi @jsotuyod,
This is an improved version of the rule I recently submitted.
It detects:
- missing Create,Update,Delete checks in DML operations
- missing Read checks before SOQL 
The checks can be added via ESAPI or using native API and this rule properly detects checks.
Some checks are blanket ones: when you do Field level check you get CRUD for free, when you perform any CUD check before accessing SOQL you get Read check for free. This rule accounts for that.
Almost everyone does CRUD checks incorrectly, I've spent a lot of time consulting internally to get this one right.
=> [apex] Detection of missing Apex CRUD checks for SOQL/DML operations

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/SecurityRulesTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexXSSFromURLParam.xml
Hi @jsotuyod,
This is to reduce FPs when URL param variable passed to String.isEmpty.
Cheers,
Sergey
=> [apex] Whitelisting String.isEmpty and casting  

pmd-core/src/main/java/net/sourceforge/pmd/util/ClasspathClassLoader.java
- It's just a bunch of static methods with no state on a URLClassLoader
This is just the finishing touch on #101, it was missing back then, posibly because he wasn't running with the `-auxclasspath` argument.
I also changed new lines to unix-style, check with `?w=1` to see the trivial change.
=> [java] Make ClasspathClassLoader parallel capable

pmd-java/src/main/resources/rulesets/java/design.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/MissingBreakInSwitch.xml
Similar to RETURN after a CONTINUE statement break is not required in a
case section
=> [java] fixes #1552 continue does not require break

pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java
If the cache location points to a file within a non-existing directory
make sure to create it for storage to succeed.
=> [core] Create missing intermediate directories for cache

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexOpenRedirect.xml
Hi @jsotuyod,
This is a bug fix, previously it would only detect Apex fields but ignore Apex class members.
With this fix both are checked. 
Regards,
Sergey
=> [apex] Bug fix, detects both Apex fields and class members

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSuggestUsingNamedCredRule.java, pmd-apex/src/main/resources/rulesets/apex/ruleset.xml, pmd-apex/src/main/resources/rulesets/apex/security.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/SecurityRulesTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSuggestUsingNamedCred.xml
Hi @jsotuyod ,
This is a new rule. We see a lot of developers using HTTP request callouts with Authorization header. This approach requires to store credentials in an object to pass to the callout. 
With named credential the admin can set the credentials, the Apex code can use them without accessing them directly and the logs are scrubbed and will have these sensitive fields masked. 
Cheers,
Sergey
=> [apex] New rule suggests using named credentials

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexOpenRedirect.xml
Hi!
I've fixed a bug where if you have a string prefixed with a literal it would not be considered safe.
Now it's all good.
Regards,
Sergey
=> [apex] Bug fix for FP: open redirect for strings prefixed with / is safe

pmd-core/src/main/java/net/sourceforge/pmd/ant/Formatter.java
Hi,
The writers in the Ant task's formatter use the default platform's encoding (for instance cp1252 on Western Windows) and the XMLRenderer sets the default XML encoding to UTF-8. This may lead to incorrect XML encoding, detected for instance when the XML file is sent to a XSLT task.
This goes undetected as long as the characters in the XML file are in the ASCII subset, which is frequently the case with code, usually in plain Latin language. In my case, the issue was raised because of the localized formatting of some line numbers greater than 999, due to the localized thousand separator 0xA0, which is out of the ASCII subset.
I modified the Formatter class to always use a charset for writers. When no encoding is specified, UTF-8 is used instead of the default platform's encoding.
I …
=> [core] Ant Task Formatter encoding issue with XMLRenderer

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexOpenRedirect.xml
Hi,
This change improves two things.
A. It appears that Apex compiler does not report static fields the same way as non-static. Fixed.
B. Assignment operations were ignored and caused FPs. Fixed.
Thanks!
Sergey
=> [Apex] Improving open redirect detection for static fields & assignment operations

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
In Apex getters callable from VFEL do not have any parameters. 
This fix reduces the false negatives.
=> [apex] Improving detection of getters

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
[select count() FROM ...] should not count as CRUD/FLS violation since the actual data is not being returned.
=> [apex] Excluding count from CRUD/FLS checks

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml
Should not report Integer, Double, Boolean when merged into a dynamic SOQL query.
=> [apex] Dynamic SOQL is safe against Integer, Boolean, Double

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
FieldDeclaration by far has the worst API in Apex Jorje binary.
I cannot get any basic information out of it without resorting to Reflection. 
Here I needed two pieces of information: field type and name. I had to use reflection to get both.
ASTFieldDeclaration.getNode().getFieldInfo() is returning null.
=> [apex] CRUD/FLS rule - add support for fields

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UnnecessaryLocalBeforeReturnRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UnnecessaryLocalBeforeReturn.xml
=> [java] Fix ClassCastException in UnnecessaryLocalBeforeReturn

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/Report.java, pmd-core/src/main/java/net/sourceforge/pmd/ReportListener.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java, pmd-core/src/main/java/net/sourceforge/pmd/SynchronizedReportListener.java, pmd-core/src/main/java/net/sourceforge/pmd/ThreadSafeReportListener.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisCache.java, pmd-core/src/test/java/net/sourceforge/pmd/processor/MultiThreadProcessorTest.java
- This follows discussion on https://github.com/pmd/pmd/pull/125#discussion_r87666694
- We add a marker interface for thread-safe listeners, and implement it were appropriate.
- Breaking change: `getSynchronizedListeners` and `addSynchronizedListeners` now handle
`List<ThreadSafeReportListener>`.
- We may mark the non-thread-safe methods and interfaces as deprecated and force everyone
to handle synchronization on their own for future releases.
=> [core] Allow for thread-safe report listeners

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/TypeSet.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ClassScopeTest.java
- Given an import on `a.Foo`, references to `Foo.Inner` should be qualified
as `a.Foo.Inner`.
- This fixes a couple of wrong missing classes.
- The test also brought to light another issue with resolvers that would fail
to resolve even a qualified inner class if not explicitly imported under
certain circumstances.
=> [java] Qualify references to inner classes of imports

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/TypeSet.java
- If the package was passed as an empty string rather than a `null`, we
would attempt to load classes such as `.Foo` rather than `Foo`.
=> [java] Fix same package import from default package

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/util/ResourceLoader.java
- Fixes #234
- When a single JVM runs multiple PMD instances under different threads,
connections to PMD jars (and streams opened to read standard rulesets)
are shared, causing race conditions where one thread may cause the other
to close it's streams. This in tun produces IOExceptions.
- This happens in Gradle when enabling parallel builds. I believe it can happen
under Maven with -T1C too, but has not been able to reproduce it.
- I take the chance to clean up classloader closing code.
This bug was introduced in PMD 5.5.1 and 5.4.2, when we fixed the leaked file handlers.
=> [core] Fix IOException loading rulesets under concurrency

pmd-java/src/main/resources/rulesets/java/logging-java.xml
The docs were not clear enough as to what constituted an invalid message.
=> [doc] Improve docs on InvalidSlf4jMessageFormatRule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassNameDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ClassScopeTest.java
- A bunch of closely related issues fixed:
- References to `this`, `super` and `Classname` were very badly resolved
(pointed to variables, methods, or nothing at all on empty classes)
- Annotations would not be registered by their parent scopes.
I mark it for version 5.5.4, since I don't think this will merge nicely into branch 4.x (at least, most of the symboltable changes when we improved the performance weren't merged to that branch)
This changeset is fundamental to my work on [#1496](https://sourceforge.net/p/pmd/bugs/1496/), since the bad resolution of `this`, `super` and `Classname` are introducing false positives on my test code.
=> [java] Fix classscope references

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UnnecessaryLocalBeforeReturnRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UnnecessaryLocalBeforeReturn.xml
- We now check symbol table usages to detect violations.
- We drop the consecutive lines requirement.
- Resolves #240
Given our plans for #241, this could probably be only merged to 5.5.x and not bother with master.
=> [java] UnnecessaryLocalBeforeReturn checks usages

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationTypeDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/unusedcode/UnusedModifierRule.java, pmd-java/src/main/resources/rulesets/java/unusedcode.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unusedcode/xml/UnusedModifier.xml
- This covers a ton of missing cases
- Fixes #246
- Fixes #247
- Fixes #248
- Notice `isNested` has been improved on `ASTClassOrInterfaceDeclaration`
to cover being nested in an annotation definition
=> [java] Revamp UnusedModifier

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UnnecessaryLocalBeforeReturnRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UnnecessaryLocalBeforeReturn.xml, src/site/markdown/overview/changelog.md
Just stumbled across an old bug report: https://sourceforge.net/p/pmd/bugs/933/
=> [java] Allow annotations for UnnecessaryLocalBeforeReturnRule

pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java, pmd-java/src/test/java/net/sourceforge/pmd/cpd/JavaTokensTokenizerTest.java, src/site/markdown/usage/cpd-usage.md
This one has been a big missing feature for quite some time. Even old comments on the code (now deleted) wondered on being able to do this.
I didn't reuse the `CPD-START` / `CPD-STOP` literals since I found them unintuitive. START is to tell CPD to stop looking, STOP is to resume analysis. This even contradicted the preexisting `// NOPMD` comments. Again, a negative to suppress.
The start / stop may work given it's within a `@SuppressWarnings` (so we get a "suppress warnings cpd start"), but certainly wouldn't be the same for stand alone comments. To avoid issues, I simply created new literals.
I also updated the docs and moved the annotation based approach to legacy due to lack of flexibility.
Porting this approach to other JavaCC based languages is still pending. I can't find a way to …
=> [java] Allow CPD suppression through comments

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/complexity/NcssTypeCountRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/complexity/xml/NcssTypeCount.xml
- Fixes #251
- The abstract parent class was already handling it properly, no need
to override to visit to a method call.
=> [apex] Fix chained method line count for types

pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleMapper.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleViolation.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/NoopAnalysisCache.java, pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java
- This is phase 2 of the implementation plan for [#1538](https://sourceforge.net/p/pmd/bugs/1538/)
- This allows to completely ignore unmodified files, even if they had violations
```
./pmd-dist/target/pmd-bin-5.6.0-SNAPSHOT/bin/run.sh pmd -d ./ -b -f text -R java-basic -r report-new-no-cache.text -t 0 -auxclasspath file:///home/jmsotuyo/pmd/auxclasspath
```
```
-----------------------------<<< Final Summary >>>-----------------------------
Total                                           Time (secs)
Measured total:                                      33.205
Non-measured total:                                   0.884
Total PMD:                                           34.089
```
```
./pmd-dist/target/pmd-bin-5.6.0-SNAPSHOT/bin/run.sh pmd -d ./ -b -f text -R java-basic -r report-new.text …
```
=> [core] Cache rule violations

pmd-java/etc/grammar/Java.jjt, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/strings/InsufficientStringBufferDeclarationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/unusedcode/UnusedLocalVariableRule.java, pmd-java/src/main/resources/rulesets/java/controversial.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unusedcode/xml/UnusedLocalVariable.xml
- Provide a definite fix for casts. This allowed to remove a bunch of hacks.
- I had to change the grammar a bit... `(int)` is now a cast with a
PrimitiveType as child, not a Type with a nested PrimitiveType. This is due
to JavaCC completely ignoring whatever you place in the LOOKAHEAD in favor
of just looking the follow-up expression completely.
- Removing the hacks raised an issue with expression orders, caused also by JavaCC's
disregard to LOOKAHEAD contents
- Fixes #257
=> [java] Improve grammar for CastExpression

pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/FileDataSource.java
- Fixes #256
- When using relative paths, both the file's path and the inputFileName
are relative, so we can safely compare them directly.
=> [core] Fix shortname computation for reltive paths

pmd-dist/pom.xml, pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistTest.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutionResult.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/SourceDistributionIT.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/ZipFileExtractor.java, pmd-dist/src/test/resources/sample-source/JumbledIncrementer.java, pom.xml
When we do automatic releases from travis by pushing a tag, we need to automate the "last resort" check: Extract the generated zip file, execute PMD against a well known source, check, that there are violations. This should prevent us from accidentally releasing broken binaries.
I've verified that the build still works under Windows.
I'll be working on the deploy script for travis next (see also https://github.com/pmd/pmd/compare/master...Monits:deploy-from-travis).
We should merge this PR for 5.4.5, 5.5.4 and master.
=> [core] Integration test for the binary distribution file

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/coupling/LawOfDemeterRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/coupling/xml/LawOfDemeter.xml
Corrected issue where LawOfDemeter exceptions were being reported erroneously if additional (unrelated) assignments occurred later in the same block (method). (See new test for an example of a condition that causes erroneous error reporting.)
Fixes #270
=> [java] corrected invalid reporting of LoD violation

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
SOQL supports generic way of referring to a query results, e.g.
```List<AggregateResult> res = [SELECT Id From Account];```
This caused CRUD to flag this line as a finding even if correct CRUD check was performed.
This improvement addresses the problem.
=> [apex] Support for Aggregate Result in CRUD rules

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceBody.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AccessorMethodGenerationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinderTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AccessorMethodGeneration.xml
- A new ClassScope was being created for each annon inner class method / field,
which is incorrect.
- I reworked the AccessorMethodGeneration to compare scopes directly, since
I was missing anonymous classes completely.
- Fixes #274
=> [java] Fix class scopes for anon inner classes

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfParser.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfSimpleCharStream.java, pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml
JavaCC by default uses 8 as tab size but most editors use 4. 
That means all column numbers are off by 4, hence the fix.
=> [vf] Setting the tab size to 4 for VF

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexXSSFromURLParam.xml
Adding another esoteric API to prevent false positives for this XSS from URL param rule.
=> [apex] Adding String.IsNotBlank to the whitelist to prevent False positives

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AccessorClassGenerationRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AccessorClassGeneration.xml
- Fixes #291
- Complete rewrite. Simpler and faster, using the RuleChain and SymbolTable.
This fix uses the recent fixes and improvements to symbol table that are only present on the 5.5.x branch and master. Therefore, it can't be merged back to 5.4.x.
=> [java] Revamp AccessorClassGeneration

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UnnecessaryLocalBeforeReturnRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UnnecessaryLocalBeforeReturn.xml
- If the local is initialized using another variable that is later
used, don't consider it a violation. Assume the later use is destructive
and the order is important.
- Fixes #282
=> [java] Fix FP on UnnecessaryLocalBeforeReturn

pmd-dist/src/main/scripts/run.sh
*   fixes #305
*   consider also "MINGW*" as cygwin
*   do not convert empty paths to avoid warnings
=> [core] Fix PMD run script for git bash

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/optimizations/UseStringBufferForStringAppendsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/optimizations/xml/UseStringBufferForStringAppends.xml
Fixes #222 
**PR Description:** This fixes a bug which caused a false positive from UseStringBufferForStringAppendsRule on a snippet such as
```java
String country = request.getParameter("country");
country = (country != null) ? country : "USA";
```
The reason the rule trigerred a false positive in that case and not when inverting the ternary's parameters (`(country != null) ? "USA" : country;`) is that both parameters are not symmetrical (see [java spec](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.25) here). The first is an `Expression` while the other is a `PrimaryExpression`. The first being an `Expression` actually adds one parent to the name occurence. For instance for the following statement:
```java
country = (country != null) ? country : country;
```
the …
=> [java] Fix false positive with UseStringBufferForStringAppendsRule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitTestsShouldIncludeAssert.xml
**Fixes:** #285 
**PR Description:** JUnitTestsShouldIncludeAssertRule no longer reports methods which are not annotated with `@Test(expected=<exceptionclass>)` nor contain assert statements, provided the test class has a field of type `ExpectedException` annotated with `@Rule`, and the Test calls at least one method starting by `expect` on that field.
See #285 for more details.
=> [java] JUnitTestsShouldIncludeAssertRule supports @Rule annotated ExpectedExceptions

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCSRFRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromEscapeFalseRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCSRF.xml, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexOpenRedirect.xml, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSharingViolations.xml
Certain classes run in system mode by design (async jobs, scheduled and install scripts). 
This CL makes sure we don't create false positives for those cases.
=> [apex] Ignoring certain rules in Batch classes, Queueable, and install scripts

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexXSSFromURLParam.xml
Casting to a String to ID would perform proper checks in Apex and result in safe, XSS-free, variable.
This code makes sure PMD never flags it.
=> [apex] Add support for safe ID assignment from URL param 

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitTestsShouldIncludeAssert.xml
**Fixes issue:** #330 
**PR Description:** The exception reported in the issue was caused by some statements in the Test methods, statements of the form `new JFXPanel();` (with no left hand side). The java compiler parses that as a `StatementExpression/PrimaryExpression` (visited by the rule), but instead of having a `PrimaryPrefix/Name` as children, this prim expression had a `PrimaryPrefix/AllocationExpression` as a child. That messed up the check for methods that start with "expect", as it relied on checking the Name descendant of the StatementExpression (an AllocationExpression has no Name and its image is null apparently).
**Solution:** Check whether the PrimaryPrefix contains a Name
=> [java] JunitTestsShouldIncludeAssertRule now handles AllocationExpression correctly

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml
Fixed a bug when you have an escaped variable not being detected.
=> [apex] Fixed SOQL injection detection for escaped vars 

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/imports/DontImportJavaLangRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/imports/xml/DontImportJavaLang.xml
In Java 7+ there was a new class added under the java.lang package. Specifically  java.lang.invoke.MethodHandles.
MethodHandles provides a handy utility in which to obtain the current class name amongst other things. A technique that is gaining in popularity is to use MethodHandles to obtain the class name when getting a logger, for example
`private final Logger log = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());`
However, using this triggers a PMD violation
```
<?xml version="1.0" encoding="UTF-8"?>
<pmd version="5.5.1" …
```
=> [java] Future-proof DontImportJavaLangRule

pmd-visualforce/etc/grammar/VfParser.jjt, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/VfParserVisitorAdapter.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java, pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml
{! NOT(booleanParam) } is a non-XSS vector since the resulting type is a boolean.
JSON.parse('{!someJSON}') is also safe from XSS as well as JSON.parse({!JSENCODE(someJSON)}).
=> [vf] JSON.parse(..) and NOT(..) are safely evaluated

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/SourceFileScope.java, src/site/markdown/overview/changelog.md
`getQualifiedTypeNames` gets called millions of times, since it's extensibly used to determine argument types, variable types, and match methods. Even if it's a relatively small and simple method, the sheer number of calls make it a big bottleneck, and the continuous creation of strings and maps puts pressure on the GC.
Even if the code could be later improved to not rely so heavily on this method call, the memoization of the result is low-hanging fruit from which we can benefit right away, which produces a huge impact (3X improvement from master)
=> [java] Even faster symboltable

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml
- Ids, integers and booleans passed to SOQL are not considered an injection.
- Ternary operator's condition variables are not contributing to SOQL and are considered safe too
=> [apex] int,id,boolean,ternary operator condition are not injection in Soql

pmd-visualforce/etc/grammar/VfParser.jjt, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTNegationExpression.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/VfParserVisitorAdapter.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/AbstractVfRule.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java, pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml
```!(expression)``` or ```NOT(expression)``` resolve to booleans; however, in VisualForce also the following works ```!expression``` and ```NOT expression```. Therefore, I added a new AST node to detect false positive cases and also handle both.
=> [vf] Adding proper AST support for negation expressions

pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java
XSS in the HTML renderer when file name contains markup.
E.g. ```<td width="*%">/tmp/pmd3186397825114149840/src/classes<script>alert(1)</script>AccountMergingController.cls</td>```
=> [core] Fix XSS in HTML renderer

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/FieldDeclarationsShouldBeAtStartOfClassRule.java
fixes #345
@jsotuyod My code looks like this right now which is 😢:
```java
public interface StartCaptureListener {
void onStartCapture(boolean shouldUploadMediaToTba);
}
private static final int TAKE_PHOTO_RC = 334; // NOPMD https://github.com/pmd/pmd/issues/345
private static final List<String> PERMS; // NOPMD https://github.com/pmd/pmd/issues/345
private static final String MEDIA_CREATOR_KEY = "media_creator"; // NOPMD https://github.com/pmd/pmd/issues/345
private WeakReference<Fragment> mFragment; // NOPMD https://github.com/pmd/pmd/issues/345
private TeamHelper mTeamHelper; // NOPMD https://github.com/pmd/pmd/issues/345
private PermissionRequestHandler mPermHandler; // NOPMD https://github.com/pmd/pmd/issues/345
private WeakReference<OnSuccessListener<TeamHelper>> mListener; // NOPMD …
```
=> [java] Add property to ignore interfaces in FieldDeclarationsShouldBeAtStartOfClassRule

src/site/markdown/overview/products.md
The link surprisingly pointed to an Italian blog about sex ^^
=> [core] Fix broken link in the site's doc

pmd-jsp/src/main/resources/rulesets/jsp/basic.xml, pmd-jsp/src/test/resources/net/sourceforge/pmd/lang/jsp/rule/basic/xml/JspEncoding.xml
Fix #369 
There were several nested content nodes in the code sample, which triggered the rule as the deep ones did not contain encoding specification.
=> [jsp] Fixed JspEncoding false positive

pmd-java/src/main/resources/rulesets/java/design.xml
Removes the trailing whitespace in the design.xml file. Dunno if this is something you guys want or not. I just noticed it when submitting #386. In case you don't feel free to close this issue.
PS: This is best reviewed with appending `?w=1` to the URL to avoid white space changes showing up in the diff.
=> [java] Remove trailing whitespaces in design.xml

pmd-apex/src/main/resources/rulesets/apex/style.xml
Fix typo in apex ruleset documentation.
=> [apex] Fix documentation typo

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitTestsShouldIncludeAssert.xml
Fixes #358 by treating Mockito's verify as assert statement
=> [java] Mockito verify method is not taken into account in JUnitTestsShouldIncludeAssert rule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPrimarySuffix.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/SuperClass.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/SuperExpression.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/ThisExpression.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverJava8Test.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/testdata/SuperClass.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/testdata/SuperExpression.java, pmd-java8/src/test/java/net/sourceforge/pmd/typeresolution/testdata/ThisExpression.java
Add support for resolving the types of 'this' and 'super' keywords in Java. PrimaryPrefix and PrimarySuffix nodes containing 'this' or 'super' and PrimaryExpressions containing only qualified or unqualified 'this' now have their types assigned.
=> [java] Type resolution: super and this keywords

pmd-dist/src/main/scripts/bgastviewer.bat, pmd-dist/src/main/scripts/cpd.bat, pmd-dist/src/main/scripts/cpdgui.bat, pmd-dist/src/main/scripts/designer.bat, pmd-dist/src/main/scripts/pmd.bat, pmd-dist/src/main/scripts/run.sh, src/site/markdown/overview/changelog.md
Fixes the start scripts of PMD where at various places quotes were missing to correctly handle path names with spaces.
Fixes #429
=> Fixes #429 [core] Error when running PMD from folder with space

pmd-core/src/main/resources/ruleset_3_0_0.dtd, pmd-core/src/main/resources/ruleset_3_0_0.xsd
This version of the XML schema for rulesets adds a "metrics" attribute to resolve dependency of a rule to the metrics framework. Until this is uploaded to the sourceforge site no rule can be refactored to use metrics (rulesets fail schema validation tests upon building PMD).
@adangel I have no idea how to upload those to the sourceforge site in order to use them though... x)
=> [core] Created ruleset schema 3.0.0 (to use metrics)

pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetWriterTest.java, pmd-core/src/test/java/net/sourceforge/pmd/junit/JavaUtilLoggingRule.java, pmd-test/src/test/java/net/sourceforge/pmd/testframework/RuleTstTest.java, src/site/markdown/overview/changelog.md
This makes sure, we get early errors, if the ruleset being built is not valid - see #380 
I'm unsure about validation when actually building the ruleset (c3888ac). We obviously don't validate the XML against the schema at the moment and this change would make the name and description of a ruleset really required. So, there might be some ruleset.xml files, that worked before and would now fail to load.
=> [core] RuleSetBuilder validation for name and description

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/imports/UnusedImportsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/typeresolution/xml/UnusedImports.xml, src/site/markdown/overview/changelog.md
- When referencing static inner members of imports, false positives
would be reported.
- Fixes #348
=> [java] Fix false positive in UnusedImport

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/strictexception/SignatureDeclareThrowsExceptionRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/rules/SignatureDeclareThrowsException.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/strictexception/xml/SignatureDeclareThrowsException.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/typeresolution/xml/SignatureDeclareThrowsException.xml, src/site/markdown/overview/changelog.md
- Avoid reporting on @Overrides, since we have no control of the
interface.
- The original definition is still reported if it's part of our
application's code.
- Fixes #350
=> [java] SignatureDeclareThrowsException ignores @Override

pmd-java/src/main/resources/rulesets/java/empty.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/empty/xml/EmptyCatchBlock.xml, src/site/markdown/overview/changelog.md
- Allow the developer to setup a regular expression for exception names
to be ignored by the rule.
- Fixes #413
=> [java] EmptyCatchBlock may ignore blocks based on exception name

src/site/markdown/usage/cpd-usage.md
This is just a small documentation update. The usage for cpd for linux used a windows path, I've changed it to a unix path.
=> [core] Changed linux usage to a more unix like path

pmd-apex/src/main/java/net/sourceforge/pmd/cpd/ApexLanguage.java, pmd-apex/src/main/java/net/sourceforge/pmd/cpd/ApexTokenizer.java, pmd-apex/src/test/java/net/sourceforge/pmd/cpd/ApexCpdTest.java, pmd-apex/src/test/java/net/sourceforge/pmd/cpd/ApexTokenizerTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/cpd/issue427/SFDCEncoder.cls, pmd-apex/src/test/resources/net/sourceforge/pmd/cpd/issue427/SFDCEncoderConstants.cls, src/site/markdown/overview/changelog.md
I noticed, that the Apex Jorje parser/compiler is actually based on ANTLR and provides a lexer. Before this change, the Apex CPD used the simple AbstractTokenizer. I expect, that with using the ApexLexer directly to tokenize the source code, the CPD matches should be more accurate, although I don't have a concrete example. It uses a similar integration of the ANTLR based lexer as we use for Swift.
To stay backwards compatible, the tokens are all lowercased. I prepared a property for the ApexTokenizer, to switch this behavior, but the option is not passed through via CPDConfiguration from commandline or CPD GUI (or any other integration).
=> [apex] Use Apex lexer for CPD

pmd-java/src/main/resources/rulesets/java/unnecessary.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unnecessary/xml/UnnecessaryFinalModifier.xml, src/site/markdown/overview/changelog.md
- Mark unnecessary finals in anonymous class methods.
- Mark unnecessary finals in enum instance methods.
- Fixes #412
=> [java] Detect more unnecessary finals

pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
**PR Description:** `test-code` elements can specify the `reinitializeRule` attribute in the xml. The only effect of this was until now to recreate the rule instance from its xml ruleset. This change allows a ruleset test (extending `RuleTst`) to override this behaviour in order to execute arbitrary rule reinitialisation code before a test.
This will enable us to fix one problem mentioned in the comments of #482, which is that the metrics framework must be reset between each test.
**Note:** By default rules are reinitialised even though they don't specify the attribute in the xml (see line 316 of `RuleTst`, as changed by this PR). Is that desirable behaviour?
=> [core] Custom rule reinitialization code

.travis.yml, .travis/build-doc.sh
Note: This PR depends on #507 
It uses a docker image for jekyll to build the site.
Once merged, it will rsync the documentation to http://pmd.sourceforge.net/snapshot/ - overriding the old one.
=> [doc] Add build script for PMD documentation, disable old site build

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/Report.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractIncrementingRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextColorRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/VBHTMLRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTst.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/CSVRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/EmptyRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/HTMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/PapariTextRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/VBHTMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java, src/site/markdown/overview/changelog.md
- All renderers previously including processing errors now also include configuration errors.
- I take the chance to fix a couple of issues with `VBHTMLRenderer`, that was rendering processing errors using `toString()` (which has a default implementation)
- Notice that renderers that didn't previously include processing errors are unmodified
- This resolves part 1 of #194
=> [core] Render config errors

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTType.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unusedcode/xml/UnusedPrivateMethod.xml
Fixes #521
The problem was caused by the method `ASTType.getTypeImage`, which looked greedily for a primitive type before looking for a reference type. That made `addToMap`'s formal parameter (of type `Map<String, double[]>`), which is parameterized with a primitive type, have a type image of `"double"`, which made the comparison fail when [comparing](https://github.com/pmd/pmd/blob/585a555ba5ccafc1c152f89e3d362f2a8a779b57/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java#L244-L249) the name occurence with the name declaration.
=> [java] Fix 521: UnusedPrivateMethod returns false positives with primitive data type in map argument

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/comments/CommentDefaultAccessModifierRule.java, pmd-java/src/main/resources/rulesets/java/comments.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/comments/xml/CommentDefaultAccessModifier.xml, src/site/markdown/overview/changelog.md
=> [java] CommentDefaultAccessModifierRule should consider constructors too

pmd-java/src/main/resources/rulesets/java/design.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UncommentedEmptyConstructor.xml
This whitelists annotations called `Inject`, but not specifically `javax.inject.Inject`
=> [java] Fix #357: UncommentedEmptyConstructor consider annotations on Constructor

pmd-core/src/main/java/net/sourceforge/pmd/Rule.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReference.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSets.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleReference.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java, pmd-core/src/test/java/net/sourceforge/pmd/FooRule.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleReferenceTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java
- Copy constructor for RuleSets
- Copy constructor for RuleSet
- Copy method for Rules
- I'm still sharing a few objects that are not strictly immutables, but
treated as them
This would allow to start resolving the issue commented on https://github.com/pmd/pmd/issues/194#issuecomment-310428462
This change adds new methods, but doesn't modify existing APIs, so it would be safe for 5.8.0.
However, I'd still want a second opinion as to wether the classes that I allow to share are really to be treated / converted to immutables, or I should extend deep copying to them.
=> [core] Allow deep copying of RuleSets

pmd-dist/pom.xml, pom.xml
Just some small updates, so that PMD can be built with a java9 environment.
* Updates the javadoc maven plugin, so that PMD can be built
with a java9+mvn3.5.0 environment
* Makes sure, that the java8 modules are also enabled for java9
and later
=> [core] java9 build updates

pmd-core/src/main/java/net/sourceforge/pmd/Report.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTst.java
Report.ProcessingError should contain more details about the root cause of the issue. This fixes e.g. that maven-pmd-plugin currently only shows "Error while parsing" in case of errors.
=> [core] improve error message

pmd-java/src/main/resources/rulesets/java/controversial.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/controversial/xml/AvoidLiteralsInIfCondition.xml
This has been pending for a while. The solution proposed by @adangel did the trick
Fixes #388
=> [java] Fix #388:  controversial.AvoidLiteralsInIfCondition 0.0 false positive

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java, pmd-core/src/main/resources/pmd-nicerhtml.xsl, pmd-core/src/main/resources/report_2_0_0.xsd, pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java
- Fixes #538
- The schema is named as version 2.0.0, since technically, this is the second iteration of the XML report given the recent changes (the first one never having a formal schema)
- Once this is merged, the file should be published on the site
=> [core] Provide an XML Schema for XML reports

docs/pages/release_notes.md, pmd-java/src/main/resources/rulesets/java/basic.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/basic/BasicRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/basic/xml/DontCallThreadRun.xml
- Use type resolution to determine when we are using a `Thread`
- Fixes #565
=> [java] java-basic/DontCallThreadRun false negative

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java, pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java
- We now look inside the jars of the classpath in search for any
changes. If we find any, we invalidate the cache.
- Resolves #604
=> [core] Incremental Analysis can detect changes to jars

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java, pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java, pmd-core/src/test/java/net/sourceforge/pmd/processor/MultiThreadProcessorTest.java, pmd-core/src/test/resources/rulesets/MultiThreadProcessorTest/dysfunctional.xml
Under multi-thread runs, each thread parsed it's own copy of the ruleset, and removed dysfunctional rules. This meant 1 `ConfigError` per thread was being generated.
Since #519, we now log `ConfigErrors`, meaning multiple identical logs in reports and noise for the user.
Therefore, we change our approach. RuleSets are parsed only once. Dysfunctional rules are filtered and reported early on, before dispathing actual file analysis. Each analysis thread can then produce
their own copy of the ruleset by taking advantage of the `deepCopy` support for rules, ruleset and rulesets introduced in #464.
The result is not only more concise reports, but the analysis thread actually perform less work. Rulesets XMLs are parsed exactly once, instead of 1 + 1 per thread as before, and rule configuration …
=> [core] Dysfunctional rules are logged only once

pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java, pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmarker.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java, pmd-core/src/test/java/net/sourceforge/pmd/ConfigurationTest.java
- File encoding is converted to Charset only once. Errors in it's setup
will fail the run immediately instead of producing one error per file.
- We make sure to close the source stream from the same place we create
it, by using try-with-resources
- When wrapping the stream to a reader, we use try-with-resources
again, just in case
- The bechmark code now takes into account charset setup, and more
closely resembles the normal execution path
- This fixes #618
=> [core] Revamp charset / stream management

pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
- Avoid creating a NoopAnalysisCache by default to prevent a phony
warning about not using the cache being printed.
- This way, we only produce a new instance lazily if not configured,
preserving the same behaviour bu without the warning.
=> [core] Avoid a phony warning about not using cache

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/TypeSet.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
- Resolves #328
- Take the chance to simplify some error handling (`NoClassDefFoundError` extends `LinkageError`)
=> [java] Avoid errors upon resolving invalid classes

docs/pages/release_notes.md, pmd-apex/pom.xml, pmd-dist/pom.xml, pmd-dist/src/main/assembly/bin.xml
[apex] Remove shading for the apex modules - not needed anymore
Fixes #605. The apex modules do not contain any non-apex code anymore
(not an uber-jar anymore).
Explicitely defining asm as runtime dependency.
=> [apex] Remove shading for the apex modules - not needed anymore

pmd-java/etc/grammar/Java.jjt
When running the designer with the following code: https://pastebin.com/xGrHQ3QN I noticed that the **Resource** node contained in the **Resources** node has its _isFinal_ boolean value set to false. After checking the grammar, I noticed the issue here: https://github.com/pmd/pmd/blob/53210842c884bb91b58d2669a10e51d6d9611e53/pmd-java/etc/grammar/Java.jjt#L2256
When a **final** token is found, the _isFinal_ value is currently not set to true. The solution is to invoke `{jjtThis.setFinal(true);}` to the right of `"final"`
=> [java] Fix in Java grammar: Try with final resource node error

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReferenceId.java, pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/util/ClasspathClassLoader.java, pmd-core/src/main/java/net/sourceforge/pmd/util/ResourceLoader.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryCompatibilityTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetReferenceIdTest.java, pmd-test/src/main/java/net/sourceforge/pmd/AbstractLanguageVersionTest.java, pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java
- We will now always load classes from auxclasspath during
typeresolution, even if we have a class with the same name in PMD's
classpath
- This prevents conflicts when using different versions of the same
dependencies
=> [core] Isolate classloaders for runtime and auxclasspath

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/InferenceRuleType.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/TypeInferenceResolver.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/TypeInferenceTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MethodFirstPhase.java
- When a reduce operation return null (it's incompatible), we should
handle it properly instead of producing a NPE.
- This is not extensive, there are other scenarios still failing, but I'm addressing them separately
=> [java] Handle properly reduction incompatibilities

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/MethodTypeResolutionTest.java
- Boolean types were not considered since we were using the
subtypability set which deals exclusively with numeric types
- Fixes #650
=> [java] Fix boxing rules

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/VarargsAsFixedArity.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/VarargsZeroArity.java
- We no longer take all methods as applicable for a 0-arg method call
during type resolution.
This resolves the issue
```
Caused by: java.lang.IllegalStateException: These methods can only be vararg at the same time:
MethodType [method=public org.apache.solr.common.params.ModifiableSolrParams org.apache.solr.common.params.ModifiableSolrParams.set(java.lang.String,int), returnType=JavaTypeDefinition [clazz=class org.apache.solr.common.params.ModifiableSolrParams, definitionType=EXACT, genericArgs=[], isGeneric=false]
, argTypes=[JavaTypeDefinition [clazz=class java.lang.String, definitionType=EXACT, genericArgs=[], isGeneric=false]
, JavaTypeDefinition [clazz=int, definitionType=EXACT, genericArgs=[], isGeneric=false]
]]
MethodType [method=public …
```
=> [java] Properly handle 0-arg calls

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
When loading methods from a lib, which has a transitive dependency we don't have in the classpath, a `NoClassDefFoundError` arises. Similarly, a `LinkageError` can rise under circumstances similar to those of #328 
We therefore handle the `LinkageError` (`NoClassDefFoundError` is a subclass), and ignore it.
=> [java] Avoid runtime errors on incomplete classpath

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/GenericsArrays.java
- The resolution of `GenericArrayType` was broken, so we caused NPEs.
- Those types are now properly resolved, but the test case is still
incomplete due to missing pieces in type inference
=> [java] Fix NPE in type resolution

pmd-java/src/main/resources/rulesets/java/basic.xml
- Remove checks that will always be true (a node can't be a Type and
a Statement and an Expression at the same time)
- Simplify count(*) > 1 checks (expensive) for an Expression check (the one
node we actually care about)
=> [java] Simplify ForLoopShouldBeWhileLoop

pmd-apex/src/main/resources/category/apex/categories.properties, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-java/src/main/resources/category/java/categories.properties, pmd-javascript/src/main/resources/category/ecmascript/categories.properties, pmd-jsp/src/main/resources/category/jsp/categories.properties, pmd-plsql/src/main/resources/category/plsql/categories.properties, pmd-visualforce/src/main/resources/category/vf/categories.properties, pmd-vm/src/main/resources/category/vm/categories.properties, pmd-xml/src/main/resources/category/pom/categories.properties, pmd-xml/src/main/resources/category/wsdl/categories.properties, pmd-xml/src/main/resources/category/xml/categories.properties, pmd-xml/src/main/resources/category/xsl/categories.properties
Add the `category/<language>/categories.properties` files for each language.
The rulesets.properties files are kept for backwards compatibility, if some tool used these properties files directly rather than the `RuleSetFactory.getRegisteredRuleSets()` method.
=> Add categories.properties files

pmd-java/src/main/resources/category/java/design.xml
The second paragraph rendered as a fenced block of code.
=> [doc] Fix NPathComplexity documentation bad rendering

docs/_data/sidebars/pmd_sidebar.yml, docs/_includes/sidebar.html, pmd-core/src/main/resources/rulesets/releases/510.xml, pmd-core/src/main/resources/rulesets/releases/550.xml, pmd-core/src/main/resources/rulesets/releases/600.xml, pmd-doc/pom.xml, pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleSetUtils.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/SidebarGenerator.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleDocGeneratorTest.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleSetResolverTest.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java, pmd-doc/src/test/resources/expected/java.md, pmd-doc/src/test/resources/expected/pmd_sidebar.yml, pmd-doc/src/test/resources/expected/sample.md, pmd-doc/src/test/resources/net/sourceforge/pmd/docs/sidebar.yml, pmd-doc/src/test/resources/rulesets/ruledoctest/other-ruleset.xml, pmd-doc/src/test/resources/rulesets/ruledoctest/sample-deprecated.xml, pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml, pmd-java/src/main/resources/rulesets/java/naming.xml, pmd-visualforce/src/main/resources/rulesets/vf/security.xml
This is about "Documentation: Should we also generate pages about the "old" rulesets" from #709 
Preview available at: http://adangel.github.io/pmd/index.html
Changes:
*   Ruleset Properties are marked as deprecated, e.g. http://adangel.github.io/pmd/pmd_rules_java_design.html#npathcomplexity
Technically, I just check whether the description starts with "Deprecated!".
*   The sidebar part for the rule references is now generated, too, and contains subentries for the new categories/rulesets: http://adangel.github.io/pmd/pmd_rules_java.html
*   On the ruleset index page (per language), I added the other rulesets, that are existing in our source code: http://adangel.github.io/pmd/pmd_rules_java.html#additional-rulesets
If the ruleset only contains rule references and all rule references are …
=> [doc] Render old/deprecated rulesets

pmd-core/src/main/java/net/sourceforge/pmd/properties/AbstractMultiNumericProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/AbstractNumericProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/LongMultiProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/modules/NumericPropertyModule.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/AbstractNumericPropertyDescriptorTester.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/DoublePropertyTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/FloatPropertyTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/IntegerPropertyTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/LongPropertyTest.java
This straightforward fix also shows that builders could help mocking properties for tests. Though I wonder if it's worth refactoring the entire properties testing framework. It's unlikely to change often, and already yields good coverage for most properties. Builders are not tested though.
Resolves #725
=> [core] Fix #725: numeric property descriptors now check their default value

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentRequired.xml
The rule now has comment requirements specific to getter and setters, and to methods that are annotated with override -> #396
The rule also prints prettier messages and uses the new property builders. 
Cheers!
=> [java] Some improvements to CommentRequired

docs/pages/release_notes.md, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/EmptyCatchBlock.xml
- We change the default to ignore exceptions named `ignore` or
`expected`, users can still override this behavior.
- Part of #709
=> [java] EmptyCatchBlock ignore expected by default

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java
- We can't assume the classes needed for analysis will be available
in the execution classpath, we need to make sure to load them from the
same classloader / auxclaspath used during analysis.
- Resolves #732
=> [java] Don't expect to load classes from execution classpath

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/AttributeNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyDescriptorUtil.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/AbstractPropertyDescriptorTester.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java, pmd-xml/src/main/resources/category/pom/errorprone.xml
As exposed in #735, XPath rules couldn't declare multi valued properties due to a trivial error. That is now corrected.
Additionally, XPath rules couldn't actually use such properties, nor did they support all properties they could (see  [the code which translates PMD properties to XPath variables](https://github.com/pmd/pmd/blob/227a0046c5069b9c9e98d4269bcd7eb415339f76/pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java#L93) for Saxon). I corrected that for Saxon, making use of the sequence datatype provided by XPath 2.0. Jaxen treats any value [as a string](https://github.com/pmd/pmd/blob/227a0046c5069b9c9e98d4269bcd7eb415339f76/pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQuery.java#L237) anyway
Hopefully this can make XPath …
=> [core] Make Saxon support multi valued XPath properties

pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyDescriptorUtil.java
While working on the designer, it occurred to me that we need a way to list the different (type id -> property extractor) mappings, if we want to make a GUI to define properties.
=> [core] Expose the full mapping from property type id to property extractor  

pmd-apex/src/main/resources/category/apex/errorprone.xml, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/EmptyStatementBlock.xml
- IfElseStatement always has 2 BlockStatements, for the if and the
else, even if not present on the code. When that happens, the phantom
block is given the same location the parent has.
- Fixes #760
=> [apex] Avoid FPs on non-existing else block

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedName.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/CyclomaticComplexityRule.java, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedNameTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/CyclomaticComplexity.xml
The Apex metrics framework was previously oblivious to triggers... Our parser parses them as an ASTUserTrigger with an ASTMethod node inside, which contains the actual code. So there wasn't much to change, except assign a special qualified name to the method. I'm no Apex developer though, and I couldn't find a detailed syntax spec for Apex, so I made a few assumptions:
* A trigger is never contained in a class
* There are never two triggers with the same name in a project (except maybe if they're applied to different objects)
* A trigger cannot contain another trigger
Could an experienced Apex developer confirm these hold for the projects PMD analyses? @up2go-rsoesemann maybe?
Based on these, the qualified name of an apex trigger (well the method of the trigger) is of the form …
=> [apex] Fix Apex metrics framework failing on triggers, refs #768

pmd-apex/src/main/resources/category/apex/errorprone.xml, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/AvoidDirectAccessTriggerMap.xml
=> [apex] AvoidDirectAccessTriggerMap incorrectly detects array access in classes

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml
- uses now a Java only implementation for the rule
- Fixes #783
=> [java] Rewrite GuardLogStatementRule without XPath

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
- Handle equally incomplete classpath, having a classpath which
requires a different JRE version than the one used to run PMD and
others.
- Fixes #814
=> [java] Avoid crashes during type resolution when used JRE is older than dependencies' version

.travis/build-deploy.sh, docs/pages/release_notes.md, pmd-apex-jorje/pom.xml, pmd-apex/pom.xml, pmd-java8/pom.xml, pom.xml
This fixes #842 locally for me...
I hope, on travis there is still java7 available, but we would see this already in this PR build.
Note: I added a new property - if the new property (java7.home) is not set, the build will behave like before and won't fail, if non-java7 code is used.
When building locally, you'll need to execute for now:
`./mvnw clean install -Dpmd.skip=true -Djava7.home=/path/to/java7`
I've found out, it might be possible now, to combine scala and java9: https://groups.google.com/forum/#!topic/maven-and-scala/EDEmr6KIvcI - but this involves upgrading scala. I'd do this for 6.1.0 then.
=> [core] Use bootclasspath when building for java7

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLiteral.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/RedundantFieldInitializerRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTLiteralTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InsufficientStringBufferDeclaration.xml
- InsufficientStringBufferDeclaration now supports all numbr formats (even octal and binary)
- We move the logic of understanding the literal value to the literal node
- We unify all logic to get the literal value to the literal node
- Resolves #841
=> [java] Resolve NumberFormatException

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/TccMetric.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/TccAttributeAccessCollector.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclarationTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/QualifiedNameTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractMetricTestRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AllMetricsTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/DesignRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/TccTest.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/GodClass.xml, pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
Fixes #827. This change needed  a bit of work around JavaQualifiedName to handle local classes in a sensible manner. In this implementation, the qualified name of a local class is determined in the following way:
* The qualified name is identical to the qualified name of the innermost enclosing class (not the method), up until the local classe's own name
* The local classe's name is written after a dollar symbol, like for nested classes, but we add an integer index to differentiate between local classes with an identical name.
eg with: 
```java
package pack;
class Outer {
void foo() {
class Inner {}
}
void bar() {
class Inner {}
}
}
``` 
the two local classes will have different qualified names, respectively `pack.Outer$1Inner` and `pack.Outer$2Inner`. The text representation of the …
=> [java] Fix TCC metric crashing on local class

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/PMDVersion.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
- All rules will log where they where moved to, even if the ruleset is referenced as a whole
- All deprecation warnings now let's users know on which version support will be removed.
This may be a little noisier, but may help reduce anxiety caused in users, by letting them know when things will break; and how to reference each loaded rule under the new category system.
=> [core] Log all rules' movements to categories

docs/pages/release_notes.md, pmd-doc/pom.xml, pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleSetUtils.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/SidebarGenerator.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleDocGeneratorTest.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleSetResolverTest.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java
This fixes #848 
There were several issues:
* line endings
* path names (filtering the names for the rulesets, generating the editme-links, etc.)
* a file handle leak
I've verified the build now under Windows. Currently, the generated documentation (under `docs/...`) is exactly the same as it is being generated under Linux.
This PR is not strictly required for 6.0.1, since it fixes the build under Windows and doesn't change anything else. But I think, it also wouldn't do any harm.
For now, I've selected milestone 6.1.0.
=> [doc] Fix build under Windows

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PreserveStackTraceRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/PreserveStackTrace.xml
PMD should fire PreserveStackTrace in the following code
public void foo(String a) throws Exception {
try {
int i = Integer.parseInt(a);
} catch(Exception e){
throw new Exception("something bad:" + e);
// Stack trace is lost, but no violation was reported!
}
}
Closes pmd/pmd#543
=> [java] Fix false negative PreserveStackTrace on string concatenation

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveClassLengthRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveMethodLengthRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ExcessiveClassLength.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ExcessiveMethodLength.xml
Resolves #825. 
I'll do another PR for the new rule replacing ExcessiveClassLength and ExcessiveMethodLength
=> [java] Make Excessive*Length consider all type declarations and constructors

pmd-core/pom.xml, pmd-core/src/main/java/net/sourceforge/pmd/util/document/DeleteDocumentOperation.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/Document.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/DocumentFile.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/DocumentOperation.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/DocumentOperationsApplierForNonOverlappingRegions.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/InsertDocumentOperation.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/RegionByLine.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/RegionByLineImp.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/RegionByOffset.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/RegionByOffsetImp.java, pmd-core/src/main/java/net/sourceforge/pmd/util/document/ReplaceDocumentOperation.java, pmd-core/src/test/java/net/sourceforge/pmd/util/document/DocumentFileTest.java, pmd-core/src/test/java/net/sourceforge/pmd/util/document/DocumentOperationsApplierForNonOverlappingRegionsWithDocumentFileTest.java
To be able to make the fixes persist on the file on which the AST was created on, a new handler is needed that is able to manage all the operations (insert, delete and replace) and apply them in order to the original file.
- **Document** interface to represent a file in which fixes can be applied.
- **DocumentOperation** represents one operation (insert, delete or replace) that will be managed by the **DocumentOperationsApplier** as to when or in what order to apply all of them.
- **RegionByLine** and **RegionByOffset** are both representations of regions in a document. The difference between them are, when one is used over the other. The RegionByLine is first used when an operation is created because the regions of the tokens are represented in this manner and there is no way to map it …
=> [core] Add operations to manipulate a document

pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/FileDataSource.java
This pull request attempts a fix to issue #872.
The `inputFileName` ('master' file) parameter may be null,
in which case the `getNiceFileName` function should return just the file name if short name is required.
=> [core] Support shortnames when using filelist

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CompareObjectsWithEqualsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CompareObjectsWithEquals.xml
Fix #885: `CompareObjectsWithEqualsRule` Java rule should not be triggered by enums.
Enum class exlicit usage was not being considered an Enum type in the rule.
=> [java] Fix #885

docs/pages/release_notes.md, pmd-java/etc/grammar/Java.jjt, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
- Fixes #888
- Allow the contents of an anonymous class to use diamong notation, but the anonymous class itself can't use it
=> [java] Fix grammar for <> in Java 1.8

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml
The first commit fixes #855. The others are cleanups.
I ran a formatter on the test cases, hence the big diff. It could be nice to do that on all rule test files, to uniformize a bit
=> [java]  Fix ImmutableField false positive when lambda is in constructor 

.travis/build-coveralls.sh
I *think*, this fixes the following issue: Whenever we release a new PMD version, the coveralls step is failing on travis: e.g. the [6.0.1 release build](https://travis-ci.org/pmd/pmd/builds/331484137).
The error message is this:
`[ERROR] Failed to execute goal on project pmd-apex: Could not resolve dependencies for project net.sourceforge.pmd:pmd-apex:jar:6.0.1: Could not find artifact net.sourceforge.pmd:pmd-apex-jorje:jar:lib:6.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`
This fix now runs first a `mvn install` to install all modules into the local repository and then execute the tests with coveralls in a second step.
=> [ci] Fix coveralls integration: run a install first

docs/pages/pmd/userdocs/suppressing_warnings.md
Fixes #891 apex uses Single Quotes ' ' instead of Double " "
Updated the document to represent the same to the user.
=> [doc] Apex @SuppressWarnings documentation updated

pmd-java/etc/grammar/Java.jjt
Type annotations can be nearly everywhere since Java 8, which makes the grammar really hard to read when the check for correct jdk version is repeated all over the place.
=> [java] Add ghost production for type annotations to cleanup the grammar

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDTask.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/CSVRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/FileReporter.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/Renderer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/SimpleRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/VSRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/renderer/CPDRenderer.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDConfigurationTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/CSVRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java
- Refactor CPD renderers to write directly to `java.io.Writer` instead of building the whole report into a single `String`. This is done by introducing a new interface to avoid a breaking API change. The old interface and related objects / methods are deprecated, to be removed on 7.0.0
- Fixes #795 
- Supersedes #815 
This changeset allows to fully process large codebases with lots of duplicates such as Lucene using `--ignore-identifiers --ignore-literals --minimum-tokens 75` with the default heap / stack; which previously required ~7-8GB as per https://github.com/pmd/pmd/issues/185#issuecomment-273597773
=> [cpd] Render to Writers instead of Strings

docs/pages/release_notes.md, pmd-dist/pom.xml, pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/CpdExecutor.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/SourceDistributionIT.java, pmd-scala/pom.xml, pmd-scala/src/main/scala/org/sonar/plugins/scala/compiler/Lexer.scala, pom.xml
This fixes #853 
I did a small integration test locally and CPD for Scala was still working when running on java9.
Building with java9 works as well.
=> [scala] Upgrade scala version to support Java 9

.travis.yml, .travis/build-coveralls.sh, .travis/build-deploy.sh, .travis/build-sonar.sh, docs/pages/release_notes.md, pmd-apex-jorje/pom.xml, pmd-apex/pom.xml, pmd-doc/pom.xml, pmd-java8/pom.xml, pom.xml
Fixes #854
**Note:** This will enforce to use java9 for building... We had this described already in the docs (BUILDING.md, and pmd_devdocs_building), but this might be suprising now...
=> [ci] Use Java9 for building PMD

docs/pages/pmd/userdocs/tools/tools.md
Added a qa-Eclipse plugin to the table.
In reference to the issues #909 added the plugin to the list of tools available.
=> [doc] Add qa-eclipse as new tool

pmd-core/src/main/java/net/sourceforge/pmd/document/DocumentFile.java
This prevents problems when building PMD under Windows
Seems like the code works fine under Linux, but fails under Windows. The target file (filePath) exists and temporaryPath can't be renamed. Furthermore, temporaryPath - if renamed successfully - should not exist anymore and doesn't need to be deleted?
I've changed the code to use Files.move(...) with REPLACE_EXISTING option - at least it builds again under Windows.
=> Use Files.move instead of File.renameTo

docs/pages/release_notes.md, pom.xml
Refs #699
Note: this only updates to 1.7.7.2.
Rhino 1.7.8 is also available, but requires Java8 as runtime (currently only java7 is required).
I'd keep #699 open and would schedule the update to rhino 1.7.8 (or later) for PMD 7.0.0.
=> [ecmascript] Update rhino to 1.7.7.2

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/GridBagHelper.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/XSLTRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/util/designer/CreateXMLRulePanel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/designer/DFAPanel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/ASTPanel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/EvaluationResultsPanel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/MainFrame.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/ParseExceptionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/SourceCodePanel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/XPathPanel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/AttributesSubMenu.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/SimpleNodeSubMenu.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/XPathFragmentAddingItem.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/ASTModel.java, pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/SimpleNodeTreeNodeAdapter.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetSchemaTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/SimpleTypedNameDeclarationTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/TypeInferenceTest.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/symboltable/NameFinder.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/AbstractPLSQLParserTst.java, pom.xml
This upgrades checkstyle, activates the fix from https://github.com/pmd/build-tools/pull/3
The new checkstyle version (and its configuration) should now also be compatible with the latest IDE plugins again.
Note: We use now the snapshot version of pmd's build-tools. It should just work (because the oss-snapshot repo is activated), but we'll need to release this dependency before we can release PMD.
This fixes also the last problem described in #928:
Now, PMD can be build under Windows, regardless of how the source code has been obtained (via git clone or via zip download).
=> Upgrade checkstyle, make build work under Windows

pmd-java/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java, pmd-java/src/test/resources/net/sourceforge/pmd/ant/xml/pmdtasktest.xml
Avoiding deprecation warnings
References #946 
I've removed the dogfood ruleset check from RuleSetFactoryTest - we'll remove the (old) dogfood ruleset anyway.
=> [java] Migrate internal rulesets used in unit tests

pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReferenceId.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java, pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/SimpleRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/dcd/graph/MemberNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/BaseLanguageModule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/VariableAccess.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ImportWrapper.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/AbstractProperty.java
=> [java] Use char notation to represent a character to improve performance

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java
- If a class extends a class that references / extends a missing class,
it's possible for the `NoClassDefFoundError` to only rise once we call
`isAnonymousClass()` on the `Class`.
- For consistency with missing classes, we set the type to null.
- Logging such missing classes is still pending #194
=> [java] Avoid a NPE in Type Resolution

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ArrayIsStoredDirectlyRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ArrayIsStoredDirectly.xml
=> [java] Make Varargs trigger ArrayIsStoredDirectly

docs/pages/pmd/rules/java/bestpractices.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
=> [java] Add ignoredAnnotations property to unusedPrivateMethod rule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SignatureDeclareThrowsExceptionRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SignatureDeclareThrowsException.xml
…roperty not honored for constructors
Fixed issue #839
=> [java] SignatureDeclareThrowsException's IgnoreJUnitCompletely property not honored for constructors

docs/pages/pmd/userdocs/getting_started.md, docs/pages/pmd/userdocs/tools/ant.md, docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/PMDTask.java, pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/NoopAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java, pmd-core/src/test/java/net/sourceforge/pmd/ConfigurationTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cli/PMDCommandLineInterfaceTest.java, pmd-java/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/ant/xml/pmdtasktest.xml, pmd-test/src/main/java/net/sourceforge/pmd/ant/AbstractAntTestHelper.java, pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
- The switch discards the argument provided to '-cache' if any
- Using the switch disables the suggestion to use incremental analysis
- Rule tests use that option to avoid the warning, which cluttered build logs. I measured the log to be about 4 times smaller (in bytes) than before.
- Refs #946
I couldn't find how to add the switch to maven or ant, only CLI
=> [core] Allow to explicitly disable incremental analysis

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFormalParameters.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclarator.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedFormalParameterRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedFormalParameter.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
- UnusedFormalParameter ignores them explicitly
- The symbol table is updated to ignore it when matching calls. The AST to ignore it from `getParameterCount()` calls
- Resolves #719
=> [java] Better handle explicit receiver parameters

pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtil.java, pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/generate-xpath-from-stack-trace.fxml
Adds a small dialog that's accessible by right click on the xpath editor, that allows to generate an XPath query from the stack trace of a visitor. The generated query will match nodes which may have caused the failure (nodes with exactly the same ancestor hierarchy as the node in which the exception was thrown).  This can be useful to pin down a bug, I was fed up with doing it by hand ^^
=> [ui] Add Generate XPath from stack trace context menu

pmd-core/pom.xml, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/AbstractNodeTest.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNodeWithDeprecatedAttribute.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIteratorTest.java, pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java, pom.xml
Deprecated attributes were previously removed from the attribute iterator entirely, thus producing breaking API changes. This changeset keeps them, but logs their usage as a warning. 
Closes #917
=> [core] Detect deprecated XPath attribute usage

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaTypeQualifiedName.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameFactory.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
I tried to update PMD dogfood, to enable the MissingOverride rule. But I ran into the following issue:
When resolving the QualifiedNames, we run into LinkageErrors, telling the "org.apache.tools.ant.BuildException" has not been found. This is in ant.jar and this dependency has scope provided (so it is on the compile classpath but not on the runtime classpath...).
It turned out, that we were using not our auxclasspath, but the runtime classpath (that one, that is used by the maven plugin).
This is fixed by the first commit.
Then I tried, to refactor, how make the auxclasspath available to the qualified names. I'm not sure, whether this is really an improvement or not. While I like the idea, that the visitor (QualifiedNameResolver) knows about the classloader, I don't see an easy solution …
=> [java] NoClassDefFoundError when analyzing PMD with PMD

pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/BasicProjectMemoizer.java
Make BasicProjectMemoizer thread safe by adding synchronization to creation of map entries. Fixes issue #1020.
=> [java] Make BasicProjectMemoizer thread safe.

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingleMethodSingletonRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/SingleMethodSingleton.xml
Fixed the issue with traversing the tree and checking out if the getInstance method is used twice under the same class.
Fixes #816 
It checks the AST in from top to bottom getting to check the names of methods and making sure that only one method with the same name is present there. In this regard "getInstance()"
=> [java] Fix for issue #816

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/util/log/ConsoleLogHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/util/log/ScopedLogHandlersManager.java
- CLI runs log only to stderr, never to stdout
- Both Ant and CLI runs log only once, the root logger never gets a
hold of the logs, completely isolating PMD
- Fixes #1036
=> [core] Log only once all messages

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/AvoidHardcodingIdRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/AvoidHardcodingId.xml
- IDs are only 15, or 18 digits long
- 18 digits long IDs are actually 15 digit IDs + checksum, which is now
validated
- Resolves #776
=> [apex] Stricter hardcoded ID detection

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/NullAssignmentRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/NullAssignment.xml
Fixes #629
Note: This is a partial fix only.
This FP is not detected:
```java
String key;
if (a) {
key = "a";
} else if (b) {
key = "b";
} else {
key = null;
}
```
=> [java] NullAssignment false positive

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ClassNamingConventions.xml
=> [java] Allow numbers in class names by default

pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java, pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java
While working on java10 support, I stumbled across these problems:
* PMDCoverageTest didn't break when rules where failing
* There was no processing error reported in the report, even though, rules were failing
* PMDCoverageTest was running single threaded
=> [core] Report rule exceptions

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/PrematureDeclarationRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/PrematureDeclaration.xml
- The code failed to detect closures once we enforced find boundaries,
so we now explicitly ask to cross them
- Fixes #1067
=> [java] Fix false-positives on PrematureDeclaration

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ClassNamingConventions.xml
Fixes #1064
Classes with a superclass or which implement an interface are not flagged as utility classes anymore.
=> [java] Make ClassNamingConventions' utility class definition more precise

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java, pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmark.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/BenchmarkReport.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/BenchmarkResult.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmarker.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/RuleDuration.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/StringBuilderCR.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TextReport.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TextTimingReportRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimeTracker.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimedOperation.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimedOperationCategory.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimingReport.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimingReportRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java
The old implementation had many limitations:
- Relayed ALL measuring logic to the client
- Used `synchronized` methods
- Was unable to measure nested operations without mixing values
- Mixed wall-clock and CPU time, which caused trouble when running
multithreaded analysis (negative values for non-meassured time)
- A separate `main` existed which was undocumented and unsupported.
So I reworked it and added some goodies along the way:
- When not running in benchmark mode, all operations are NOOPs
- Nested operations are the default. Total and self time are
differentiated. This allows and encourages to better track overhead (ie:
time spent in a loop over another timed operation)
- We can meassure call count along with custom counters, which add
meaning to metrics
- Wall clock time for total …
=> [core] Rework benchmarking code

docs/pages/release_notes.md, pmd-java/etc/grammar/Java.jjt, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidReassigningParametersRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedFormalParameterRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/ConsecutiveAppendsShouldReuseRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/LocalScope.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/MethodScope.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/VariableNameDeclaration.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/AcceptanceTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ClassScopeTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/LocalScopeTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ScopeCreationVisitorTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidAssertAsIdentifier.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidEnumAsIdentifier.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveAppendsShouldReuse.xml
- Reduce LocalScope creations. Method parameters and method locals have
the same visibility / reachability, so they should be in the same scope.
- Fix the grammar `assert` lookahead. There is no need to use `(`
- Fix illegal test code (shadowing of parameters is illegal)
- Update Scope tests to deal with changes
- Fixes #1051
=> [java] Fix scoping inconsistencies

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/xpath/TypeOfFunction.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseTestAnnotation.xml, pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java
Fixes #572
I gave it a try:
* The rule now assumes, that classes, that are supposed to be JUnit4 Tests, end with "Test". Otherwise it is difficult to know, whether the class should be a test or not - Junit4 tests classes are not special in any way.
* Typeresolution is used to determine TestCase (Junit3)
It will flag the class again, if you name your predicate "FooTest"... We could alternatively check, whether the method has an `@Override` annotation or whether the class specifically implements `java.util.function.Predicate`.
=> [java] False Alarm of JUnit4TestShouldUseTestAnnotation on Predicates

pmd-dist/src/main/scripts/designer.bat, pmd-dist/src/main/scripts/run.sh, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/MainDesignerController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/NodeInfoPanelController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/SourceEditorController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ASTTreeCell.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ScopeHierarchyTreeCell.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ScopeHierarchyTreeItem.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/TreeViewWrapper.java, pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/editor.fxml
This syncs the primary selected node between the AST treeview and the scopes tab. Selecting a node in the scopes tab now selects the correct node in the AST and scrolls to it if necessary. Clicking again on an already selected node makes the editor scroll to the node correctly. (These were listed in #714)
Selecting a node in the scopes tab or in the XPath result view now makes the Treeview scroll *only if the node is not already visible*, in which case it doesn't scroll and it's just highlighted. This makes the treeview much less confusing when selecting XPath results which are very close (in terms of AST), avoiding jumping every time. That was the reason why scrolling to the selected node was disabled in the treeview until now:
https://github.com/pmd/pmd/blob/master/pmd-ui/src/main/java/n …
=> [ui] Fix designer treeview scroll

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientEmptyStringCheckRule.java, pmd-java/src/main/resources/category/java/performance.xml
InefficientEmptyStringCheckRule.java and the corresponding section
both contain information which the other doesn't. The class Javadoc and
the description section in performance.xml has thus been adjusted.
Successor of #1126.
Resolves #1125
=> [java] Adjust InefficientEmptyStringCheck documentation

.github/ISSUE_TEMPLATE.md
We often ask for JDK info or OS info when issues seem to be caused by linkage errors for example, or missing JRE libraries. Putting that in the issue template helps us investigate more quickly if we don't have to ask
=> [core] Update issue template

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java
- Resolves #1131 
- The codebase needs some rework. We have lots of code dealing with the classloader, so we may as well refactor it away (to the classloader itself?). The classloader however hides several `NoClassDefFoundError` as `ClassNotFoundException`, which is wrong and may lead us to believe a class doesn't exist when it's simply missing some pieces. I think this refactor is too large to make it into 6.4.0, but the quick fix here provided should be ok and get value to our users ASAP.
=> [java] Improve how we deal with broken classes

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java, pmd-java/src/main/resources/category/java/codestyle.xml
- We now create docs from the properties registered on the class, so
the default was undocumented. Therefore, I moved the default from XML to
code
- I take the chance to convert the property to a RegexProperty as it's
most apropriate
- I take the chance to allow `/* package */` as valid too by default
=> [java] Fix doc for CommentDefaultAccessModifierRule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLabel.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchStatement.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/switchstmtsshouldhavedefault/SimpleEnum.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/SwitchStmtsShouldHaveDefault.xml
The rule now whitelists enum switches that test for all enum constants
Fix #651
=> [java] Make SwitchStmtsShouldHaveDefault aware of enum switches

pmd-core/etc/xslt/corley-pmd-report.xslt, pmd-core/etc/xslt/cpdhtml.xslt, pmd-core/etc/xslt/junit-txt-output.xsl, pmd-core/etc/xslt/only-prio1.xslt, pmd-core/etc/xslt/only-prio2.xslt, pmd-core/etc/xslt/only-prio3.xslt, pmd-core/etc/xslt/only-prio4.xslt, pmd-core/etc/xslt/only-prio5.xslt, pmd-core/etc/xslt/pmd-report-per-class.xslt, pmd-core/etc/xslt/pmd-report.xslt, pmd-core/etc/xslt/pmd-xmlfilter-prio1.xsl, pmd-core/etc/xslt/pmd-xmlfilter-prio2.xsl, pmd-core/etc/xslt/pmd-xmlfilter-prio3.xsl, pmd-core/etc/xslt/pmd-xmlfilter-prio4.xsl, pmd-core/etc/xslt/pmd-xmlfilter-prio5.xsl, pmd-core/etc/xslt/pmd-xmlfilter-upto-prio2.xsl, pmd-core/etc/xslt/pmd-xmlfilter-upto-prio3.xsl, pmd-core/etc/xslt/pmd-xmlfilter-upto-prio4.xsl, pmd-core/etc/xslt/wz-pmd-report.xslt
Add xpath namespace to fix stylesheets for current xml report output
Fixes #1168
=> [core] Update stylesheets with a default namespace

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml
Fixes #869 
The rule is still very prone to false-positives, since we use string matching...
=> [java] GuardLogStatement false positive on return statements and Math.log

pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/DOMLineNumbers.java, pmd-xml/src/test/java/net/sourceforge/pmd/lang/xml/XmlParserTest.java
The length of autoclosing elements (like `<foo name="foo" />`) was not being determined properly.
=> [xml] Fix XML node length with autoclosing element

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationMethodDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractAnyTypeDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryModifierRule.java, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryModifier.xml
- Enum constructors are inherently private, no need to add that
modifier
=> [java] Fix FN in UnnecessaryModifierRule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/AtLeastOneConstructorRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryConstructorRule.java, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/AtLeastOneConstructor.xml
- Lombok annotations that create a constructor whitelist the class
- Take the chance to cover a bunch of other FNs
- Improve documentation on the rule
- Some other minor improvements
- Fixes #667
=> [java] AtLeastOneConstructor supports Lombok

docs/_plugins/xpath_lexer.rb, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java, pmd-doc/src/test/resources/expected/sample.md
This is only used when building the site, like the Liquid extensions. The changeset doesn't strictly depend on #1138, unless there are some updates to do to the release / site building scripts
Preview:
Edit: I corrected a bug, the highlighting is now richer:
=> [doc] Add Rouge XPath syntax highlighter 

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/Comment.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/CommentUtil.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/FormalComment.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/javadoc/JavadocTag.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/AbstractCommentRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/CommentTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/CommentUtilTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/FormalCommentTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/documentation/AbstractCommentRuleTest.java
Fixes #1174
Work in progress - this is missing:
=> [java] Deprecated CommentUtil, move implementation to AST Comment

pmd-java/src/main/resources/category/java/performance.xml
There seems to be some confusion about the use of `./mvnw test` which fails with OpenJDK 8 because 9 is enforced and causes test failures even on `master` with 9.
StringBuilder is a faster non-synchronized alternative to StringBuffer
which should be used where synchronization is not needed. Since "use
StringBuilder or StringBuffer" would immediately lead to the question
which one to use the hints "non-synchronized" and "synchronized" are
added.
=> [java] Recommend StringBuilder next to StringBuffer

.gitignore, docs/pages/release_notes.md, pmd-core/pom.xml, pmd-java/pom.xml, pmd-java8/pom.xml, pmd-plsql/pom.xml, pmd-xml/pom.xml
Fixes #1074
Jaxen is now shaded into pmd-core, without org.w3c.dom.**
I gave it a try, but it doesn't seem to be working: If I remove the m-pmd-p configuration in pmd-xml and use the fixed snapshot version of PMD (with the shaded jaxen dep), m-pmd-p execution still fails when analyzing pmd-xml.
In the binary distribution, I don't see org.w3c.dom.UserDataHandler anymore in the libraries... so this is gone...
=> [java] MissingOverrideRule exception when analyzing PMD under Java 9

docs/pages/release_notes.md, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ContextMenuWithNoArrows.java, pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/designer.less
In the end I found a way to do that with css. Fix #1233
=> [ui] Hide context menu arrows on XPath autocomplete popup

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
Some tests previously didn't test anything since `node.findDescendantsOfType(TypeNode.class)` returned an empty list. The correct way to resolve is to allow findDescendantsOfType to match subtypes.
The tests were still broken though, since the nodes had some subexpressions that were also tested (by mistake). E.g.
```java
int[][] a = new int[1][];
```
tested both the expressions `new int[1][]` and `1` for the type `int[][]`, and also the PrimitiveType node `int`. I thus replaced the whole subtree comparison by a simple assertEquals.
=> [java] Fix tests of ClassTypeResolver

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLocalVariableDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/AbstractNamingConventionRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FormalParameterNamingConventionsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableNamingConventionsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodNamingConventionsRule.java, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/CodeStyleRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FormalParameterNamingConventions.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableNamingConventions.xml
These replace VariableNamingConventions in part. Still FieldNamingConventions to go. I'll add the release note and deprecate old rules when that last rule is added.
Refs #972
=> [java] Add FormalParameterNamingConventions and LocalVariableNamingConventions

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/AbstractNamingConventionRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ClassNamingConventions.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FormalParameterNamingConventions.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableNamingConventions.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/MethodNamingConventions.xml
Without them, the rules flag loop index variables and other stuff, eg short method parameters. This is not completely wrong, but I think makes the adoption cost greater by adding some noise to the initial report. Besides, for now, we have other rules about name length.
=> [java] Allow length 1 identifiers in naming convention rules

.travis.yml, .travis/all-java.xml, .travis/build-deploy.sh, .travis/project-list.xml
This is one of the tasks of the third phase of the [pmdtester project](https://github.com/pmd/pmd/wiki/%5BGSoC-2018%5D-Automated-regression-tests-against-real-world-projects#third-coding-period-july-14-2018---august-14-2018). The PR is WIP.
=> [ci] [GSoC] Upload baseline of pmdtester automatically

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/NpathBaseVisitor.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NPathComplexityRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/NPathTest.xml
Fixes #1226
I actually stayed with Integer - if the complexity is bigger than Integer.MAX_VALUE, then PMD won't be the problem...
I added a simple check for overflow, when we multiply/sum the child's complexities. The overflow happened btw. already with PMD 5.3.8 - we just ended up with a big positive number instead of a negative number. The difference is, how we handle since 6.0.0 `ASTConditionalExpression` nodes: We additionally take the boolean expression into account, which the old implementation didn't. But that should not be a problem.
=> [java] NPath complexity false negative due to overflow

pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/MissingSerialVersionUIDBase.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingSerialVersionUID.xml
I'm not 100% sure about the following, however #1078 is open since May and @jsotuyod suggested the solution which I hope I understood correctly.
The construct
```
count(ImplementsList
[ClassOrInterfaceType/@Image='Serializable'
or ClassOrInterfaceType/@Image='java.io.Serializable']) =1
```
doesn't cover subclasses of a class or interface implementing or
extending Serializable whereas the `typeof` operator does.
close #1078
=> [java] Use typeof in MissingSerialVersionUID

pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPLanguage.java
Due to `skipBlocks = true` and `skipBlocksStart` being uninitialised in `CPPTokenizer`, `maybeSkipBlocks` would always throw a NullPointerException as it is assuming that `setProperties` is always called after the constructor.
Changed `CPPLanguage` to always invoke `setProperties`, similarly to `CsLanguage`.
This only happens in programmatic invocations.
=> [cpp] Fix NullPointerException in CPPTokenizer:99

.travis.yml, .travis/build-deploy.sh, Dangerfile, Gemfile
* We only perform the regression testing when `mvn verify` runs successfully and the PR is mergeable.
* When contributor have submitted the new commits, old and new regression diff reports are both available.
=> [ci] [GSoC] Integrating the danger and pmdtester to travis CI

pmd-test/src/main/java/net/sourceforge/pmd/testframework/PMDTestRunner.java
This is a small improvements on how the JUnit Tests are reported in Eclipse:
Before:
After:
So, if there are no unit tests on a test class (just rule tests), then there is no empty node "Unit Tests" anymore, and the class is completely green.
=> Test Framework: Only show "Unit Tests" node, if there are unit tests

docs/pages/release_notes.md, pmd-core/src/test/java/net/sourceforge/pmd/ReportTest.java, pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java, pmd-test/src/test/java/net/sourceforge/pmd/testframework/RuleTstTest.java
Fixes #1191
It turned out, we were already sorting (Report.violations is a sorted list), but not using it for assertLinenumbers...
I've seen, that ReportTree is not used anymore by us... Should we mark this as deprecated and remove it with PMD 7?
=> [core] Test Framework: Sort violations by line/column

pmd-jsp/src/main/java/net/sourceforge/pmd/cpd/JSPLanguage.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/JspLanguageModule.java, pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/JspParserTest.java
Pmd-Jsp only support .jsp files but .jspf (jsp fragment) and also .tag extensions are valid
Both extensions are mentioned in sections E.16.48 and JSP.1.1.8 of the JSP spec http://download.oracle.com/otn-pub/jcp/jsp-2_3-mrel2-eval-spec/JSP2.3MR.pdf
Resolves #1276
=> [jsp] #1276 add support for jspf and tag extensions

pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UselessParentheses.xml
…arentheses in condition statement.
This PR passes the checks mentioned.
NOTE: I have not performed a full build of root module, as this requires JavaFX. (I am currently running OpenJDK without having a full JavaFX distribution available.) I have built, tested, pmd-checked, checkstyle-checked the 'pmd-java' module.
The fix consists only of XPath rule changes and subsequent test passes all other testcases, so I assume this is okay.
This fixes issue #1285, which I have also reported previously. I have added an XPath condition and a test-case to prove it works for a short piece of code which triggers the issue.
=> [java] UselessParentheses: Fix false positive with assignments

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/util/log/AntLogHandler.java
I've changed the default fallback loglevel to WARN, so that an unsupported build listener won't have a performance impact in the future.
Fixes #1288
=> [core] Add support for Gradle's AntLoggingAdapter

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/AbstractReportNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ClassNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/PackageNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportHTMLPrintVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportTree.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ViolationNode.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/YAHTMLRenderer.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTst.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java, pmd-core/src/test/resources/net/sourceforge/pmd/renderers/yahtml/YAHTMLSampleClass1.html, pmd-core/src/test/resources/net/sourceforge/pmd/renderers/yahtml/YAHTMLSampleClass2.html, pmd-core/src/test/resources/net/sourceforge/pmd/renderers/yahtml/index.html
* This change deprecates ReportTree and all related classes
in net.sourceforge.pmd.lang.dfa.report
* Reworked YAHTMLRender to work without ReportTree
* Adds a unit test for YAHTMLRenderer
Fixes #1283
=> [core] Deprecate ReportTree

pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/main/resources/category/java/design.xml, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseAfterAnnotation.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseBeforeAnnotation.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseTestAnnotation.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseAssertEqualsInsteadOfAssertTrue.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseAssertNullInsteadOfAssertTrue.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseAssertSameInsteadOfAssertTrue.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifyBooleanAssertion.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UnnecessaryBooleanAssertion.xml
Added JUnit5 annotations to XPath which identify JUnit methods (tests, setup, teardown), so that PMD doesn't report false positives for JUnit5 tests. 
Fixes #940. 
A minimal example of a false positive is the following JUnit5 test: 
import org.junit.jupiter.api.Test;
public class MyTest {
@Test
public void testSomething() {
}
}
PMD 6.5 reports: "JUnit 4 tests that execute tests should use the @Test annotation".
=> [java] #940 Avoid JUnit 4 false positives for JUnit 5 tests

.travis/build-deploy.sh, do-release.sh, docs/pages/pmd/projectdocs/committers/releasing.md, docs/pages/release_notes.md
The release notes were not rendered before being pushed to sourceforge: https://sourceforge.net/projects/pmd/files/pmd/6.7.0-SNAPSHOT/
I'm not sure we can keep the `--without=release_notes_preprocessing` now, since this is in build-deploy.
=> [doc] Render release notes for sourceforge 

pmd-apex/src/main/resources/category/apex/codestyle.xml, pmd-apex/src/main/resources/rulesets/apex/ruleset.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/codestyle/CodeStyleRulesTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/codestyle/xml/OneDeclarationPerStatement.xml
This PR adds the OneDeclarationPerStatement rule to apex. It applies to field declarations (inside classes) and variable declarations (inside methods).
```
Integer a, b;   // not recommended
Integer a;      // preferred approach
Integer b;
```
=> [apex] Add OneDeclarationPerStatement rule

.travis.yml, .travis/build-deploy.sh, .travis/common-functions.sh, BUILDING.md, docs/pages/pmd/devdocs/building.md, docs/pages/pmd/userdocs/installation.md, pmd-dist/src/main/scripts/designer.bat, pmd-dist/src/main/scripts/run.sh, pmd-ui/pom.xml, pom.xml
This uses the available openjfx dependencies instead of relying that jfx is available. With that change, PMD builds under Linux with plain OpenJDK 11.
Since the openjfx jars are included as dependencies, we don't use the module system of java9 anymore when running the Designer, so we don't need the extra vm flags. The openjfx jars are just available on the classpath.
The resulting pmd-bin-...zip is also bigger, since the openjfx jars are included now.
However, the resulting pmd-bin-....zip would only be runnable right now on Linux, since the dependencies automatically include the platform dependent part.
This happens in the parent pom of openjfx: https://search.maven.org/#artifactdetails%7Corg.openjfx%7Cjavafx%7C11-ea%2B19%7Cpom
```
<profile>
<id>linux</id>
<activation>
<os> …
```
=> Java 11 and OpenJFX

docs/pages/release_notes.md, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/OneDeclarationPerLine.xml
The `OneDeclarationPerLine` check was only checking local variables. In order to match it's behavior with the Apex equivalent (#1315), I added checks for fields too.
One interesting thing 'though. The Apex rule is under the `codestyle` category, but the Java one is under `bestpractices`... I'm not sure why we decided to place it here, and I'm tending to think this was a mistake... Having it as `codestyle`, as Apex do seems more accurate.
=> [java] OneDeclarationPerLine should check fields too

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/CodeStyleRulesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FieldNamingConventions.xml
Exclude serialVersionUID by default. Fix #1329 
I think it would be better to have a more powerful scheme to match excluded fields than just comparing the name. But property versatility is stuck for now, because values are expected to be a single string.
=> [java] Add exclude property to FieldNamingConventions

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolationTest.java
To build the class name JavaRuleViolation#setClassNameFrom(JavaNode) either iterates all ClassOrInterfaceDeclaration's or finds the first public class/enum declaration.
This fails if the file only contains a non-public non-class, e.g. a package-private enum.
This PR makes it iterate all java types (class/interface, enum and annotations).
=> [java] Derive correct classname for non-public non-classes

pmd-core/src/main/java/net/sourceforge/pmd/Rule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractDelegateRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleReference.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/AbstractPropertySource.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertySource.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/RegexProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/Renderer.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/EcmascriptParserOptions.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/XmlParserOptions.java
I was working on making required properties a thing for #973 (the last comments), and it occurred to me that for that to work, PropertySources should provide kind of the same functionality as RuleReferences: track the overridden properties. This was already kind of the case, except it wasn't documented. 
This PR brushes up on PropertySource, fixing some inconsistencies, deprecating unneeded API, and making it consistent with RuleReference. The goal for 7.0.0 would be to have RuleReference extend AbstractPropertySource to share the implementation. This can't be done right now as making AbstractDelegateRule extend AbstractPropertySource would break the contract of AbstractDelegateRule by baking in some property overriding facilities. Since AbstractDelegateRule is only used by RuleReference …
=> [core] Improvements and planned updates around PropertySource

Dangerfile, Gemfile
Fixes issue https://github.com/pmd/pmd-regression-tester/issues/38
=> [ci] Improve danger message

BUILDING.md
The documentation was recently updated to specify the requirement of Java 10 for building PMD, but one location still referred to Java 9 by mistake.
=> [doc] Updated outdated note in the building documentation.

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml
Resolves #1365
`mvnw test` failed for me on master so I wasn't able to run it.
=> [java] Simplify check for 'Test' annotation in JUnitTestsShouldIncludeAssertRule.

pom.xml
**PR Description:** This updates the version of Apache Commons IO from 2.4 (released June 2012) to 2.6 (released October 2017).
Ran `mvnw.cmd clean verify` on my local machine and got a successful build.
=> [core] Upgrading Apache Commons IO from 2.4 to 2.6

pom.xml
This updates the version of Apache Commons Lang 3 from 3.7 (released November 2017) to 3.8.1 (released September 2018).
Ran `mvnw.cmd clean verify` on my local machine and got a successful build.
=> [core] Upgrading Apache Commons Lang 3 from 3.7 to 3.8.1

pmd-java/src/main/resources/category/java/bestpractices.xml
Resolves #1202 complaining about the message of the GuardLogStatement rule.
=> [java] Improved message for GuardLogStatement rule

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageRegistry.java
=> [core] Use current classloader instead of context classloader for LanguageRegistry

pom.xml
Upgrading SLF4J from 1.7.12 (released March 2015) to 1.7.25 (released March 2017).
Ran `mvnw.cmd clean verify` and it built successfully.
=> [all] Upgrading SLF4J from 1.7.12 to 1.7.25

docs/pages/pmd/userdocs/cli_reference.md, pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java, pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
Fixes #1394 
When the cache file 
* Is a valid file name and doesn't exist, a single log "Analysis cache created" is output
* Is a valid file name and exists, previous checks and logs about the rulesets and classpath are run. If the rulesets have changed, the classpath isn't checked anymore
* Is a directory name, then two special logs are output when trying to load and persist the cache
* Everything else is the same
This adds an abstract method to AbstractFileAnalysisCache though I don't think it's API breaking since AbstractFileAnalysisCache should be internal, right?
=> [core] Fix logs when creating cache file

pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmarker.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/AnyTokenizer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/FileReporter.java, pmd-core/src/main/java/net/sourceforge/pmd/dcd/graph/UsageGraphBuilder.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportHTMLPrintVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextColorRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/util/database/DBType.java, pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java, pmd-core/src/test/java/net/sourceforge/pmd/util/database/DBTypeTest.java, pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPTokenizer.java, pmd-cs/src/main/java/net/sourceforge/pmd/cpd/CsTokenizer.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidDuplicateLiteralsRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java, pmd-javascript/src/main/java/net/sourceforge/pmd/cpd/EcmascriptTokenizer.java, pmd-jsp/src/main/java/net/sourceforge/pmd/cpd/JSPTokenizer.java, pmd-matlab/src/main/java/net/sourceforge/pmd/cpd/MatlabTokenizer.java, pmd-objectivec/src/main/java/net/sourceforge/pmd/cpd/ObjectiveCTokenizer.java, pmd-python/src/main/java/net/sourceforge/pmd/cpd/PythonTokenizer.java, pmd-scala/src/main/java/org/sonar/plugins/scala/util/StringUtils.java, pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/SettingsPersistenceUtil.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/cpd/VfTokenizer.java
Replaces most `IOUtils.closeQuietly(foo)` calls with try-with-resources statements for better memory handling. I have run `./mvnw clean verify` and it passes. 
There were two remaining issues that I was unsure of how to address:
- In some cases, `IOUtils.closeQuietly(foo)` was suppressing an `IOException`, and since that's a checked exception, I had to catch it if it wasn't being closed already. The most common way of handling this I saw in existing code was to just print the stack trace, so that's what I did. If I should handle it differently, let me know.
- There were several instances in PMD Core where I couldn't get rid of `IOUtils.closeQuietly()`, and I would appreciate suggestions on how to handle them:
- [RuleSetWriter L65](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/ja …
=> [all] Replacing IOUtils.closeQuietly(foo) with try-with-resources statements

docs/pages/pmd/userdocs/extending/writing_pmd_rules.md, docs/pages/pmd/userdocs/extending/writing_xpath_rules.md, docs/pages/pmd/userdocs/making_rulesets.md
Refs #1249
Fixes the wrong URL in the documentation and uses the https variant (note: hostname is now pmd.sourceforge.**io**) on the other places as well.
=> [doc] Use https://pmd.sourceforge.io/ruleset_2_0_0.xsd as schema location

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
Fixes #1343, the class CommentDefaultAccessModifierRule now extends AbstractIgnoredAnnotationRule. Also added a small comment about the ignored nodes in CommentDefaultAccessModifierRule.
=> [java] Fix Issue 1343: Update CommentDefaultAccessModifierRule

docs/pages/pmd/userdocs/cpd.md
The current CPD documentation covers very well how to use it, but there was no information here that describes why someone would care about how much duplicate code they have.  The developers I work with want to "cheat" on their SonarQube quality gates by excluding some code from CPD checks, because they don't really understand what the problem is. Ironically, the main risk from duplicate code is when that code unintentionally becomes not duplicate anymore, creating a hidden problem that may or may not erupt on you.
The text I've added here is excerpted from a short tech note I wrote to my team on the subject.
Fixes #1349 
- [ ] `./mvnw pmd:check` passes.
=> [doc] Update cpd.md with information about risks

pom.xml
Upgrading JCommander 1.48 (released April 2015) to 1.72 (released June 2017).
`mvnw clean verify` passes.
=> [core] Upgrading JCommander from 1.48 to 1.72

pmd-ui/pom.xml
* This makes it easier to create a customized and tailored
PMD distribution.
* Also sort the languages alphabetically
*Example usage:*
The [sample project for plsql](https://github.com/pmd/pmd-examples/tree/plsql) creates a tailored pmd distribution, which only contains plsql support. All other languages are irrelevant.
Currently, these other languages need to be excluded:
https://github.com/pmd/pmd-examples/blob/c8a1e5bf5d39440482e5ee0ab8571393ca4c6dec/pom.xml#L36-L65
With this change, you would create your own PMD distribution by packaging your language (pmd-plsql) and the ui tools (pmd-ui) together.
Note: we currently declare all modules explicitly in our main distribution file - https://github.com/pmd/pmd/blob/master/pmd-dist/pom.xml#L75 - so, this change should not affect the main …
=> [ui] make the language dependencies optional

docs/_data/sidebars/pmd_sidebar.yml, docs/pages/next_major_development.md, docs/pages/release_notes.md, docs/pages/release_notes_old.md
This implements something like #1284. It's a bit like [this wiki page](https://github.com/pmd/pmd/wiki/PMD-7.0.0) but for things we want to announce officially. Could become part of the release notes for 7.0.0.
Closes #1284
=> [doc] Add pmd 7.0.0 dev page to docs

docs/pages/pmd/rules/jsp/security.md
Ironically, the corresponding documentation page (https://pmd.github.io/latest/pmd_rules_jsp_security.html#nounsanitizedjspexpression) is subject to XSS!
=> [doc] Fix XSS on documentation web page

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArrayDimsAndInits.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFormalParameter.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLocalVariableDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPrimitiveType.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTReferenceType.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTResource.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTType.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/Dimensionable.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/PrematureDeclarationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingletonClassReturningNewInstanceRule.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/main/resources/category/java/performance.xml
Deprecates Dimensionable so that we can remove it with 7.0.0. Adding a node for the dimensions to tackle #997 will replace its functionality
=> [java] Deprecate Dimensionable

pmd-fortran/src/main/java/net/sourceforge/pmd/cpd/FortranTokenizer.java
This edit replaces type parameters to invoke the constructor of a generic class with an empty set (<>), diamond operator and allow inference of type parameters by the context. This edit ensures the use of generic instead of the deprecated raw types.
=> [fortran] Use diamond operator in impl

pmd-java/etc/grammar/Java.jjt, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml
Fixes #1440. Changed the grammar to set the image for the node, thereby resulting in the name of the constructor to be appearing in the error message.
=> [java]  Adding the fix for #1440. Showing correct message for CommentDefaultAccessmodifier.

.travis/render_release_notes.rb, docs/_config.yml, docs/_plugins/all_extensions.rb, docs/_plugins/javadoc_tag.rb, docs/_plugins/jdoc_namespace_tag.rb, docs/pages/pmd/userdocs/extending/defining_properties.md, docs/pages/pmd/userdocs/extending/metrics_howto.md, docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/properties/LongMultiProperty.java
Adds Liquid tags to link to a javadoc page.
* Links point to javadoc.io
* There's a provision to refer to a member that was removed in a previous API version (jdoc_old tag)
* There's a nice way to keep doc references short ("namespaces")
* It's well documented and tested for all documented inputs
* It plays well with the release notes preprocessor, and it'll probably be most useful in the release notes
Test it with `.travis/render_release_notes.rb docs/pages/release_notes.md` or on a local instance of the site.
Note that on a local site or snapshot site the links are 404 because they point to an unreleased version of the API (6.10.0), which makes sense because it's the site for 6.10.0. The links in the examples below are generated for 6.9.0 for them to work. You can edit _config.yml and …
=> [doc] Adds Liquid tags to link to javadoc

pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/DAAPathFinder.java
Make maxLoops configurable in DAAPathFinder.
With the fixed value of 100, we're limited to work on code blocks of about 100 lines.
Making it configurable allows the caller to decide to work with more lines (decide the balance between more lines or faster processing)
=> [core] Configurable max loops in DAAPathFinder

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/Rule.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSets.java, pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractCpdLanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractPmdLanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/XPathHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AstAnalysisConfiguration.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AstProcessingStage.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java, pmd-cpp/src/main/java/net/sourceforge/pmd/lang/cpp/CppHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/AbstractJavaHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaProcessingStage.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/Ecmascript3Handler.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/JspHandler.java, pmd-matlab/src/main/java/net/sourceforge/pmd/lang/matlab/MatlabHandler.java, pmd-objectivec/src/main/java/net/sourceforge/pmd/lang/objectivec/ObjectiveCHandler.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLHandler.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PlsqlProcessingStage.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java, pmd-python/src/main/java/net/sourceforge/pmd/lang/python/PythonHandler.java, pmd-test/src/main/java/net/sourceforge/pmd/test/lang/DummyLanguageModule.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfHandler.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmHandler.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/XmlHandler.java
First PR for 7.0.0! :smile: :metal: 
Basically this is a first step to simplify the way we handle optional AST traversals like typeresolution or symbol table. It's necessary to detect XPath dependencies automatically, and globally will make our life easier.
Type resolution, DFA, etc. all use a visitor that runs on the AST, wrapped in not-so-useful "façades" and provided by a LanguageVersionHandler. At the moment:
* Every language must have all of them, even if it's just a dummy. This is bad because these stages are ultimately language-specific ---e.g. not all languages will implement their type res with a preliminary qname resolution like Java  
* Each language should be able to define themselves the visits they want to schedule independently of how other languages do it
* They are all …
=> [core] Abstract away optional AST traversals (first step)

docs/_plugins/javadoc_tag.rb, docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/AvoidDeeplyNestedIfStmtsRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/StdCyclomaticComplexityRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/TooManyFieldsRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/MockRule.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/GenericPropertyDescriptor.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/IntegerProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyBuilder.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyFactory.java, pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/IntegerPropertyTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/NonRuleWithAllPropertyTypes.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/PropertyDescriptorTest.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AvoidDeeplyNestedIfStmtsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CouplingBetweenObjectsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NPathComplexityRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NcssCountRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/StdCyclomaticComplexityRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/TooManyFieldsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentSizeRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidDuplicateLiteralsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/DataflowAnomalyAnalysisRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/ConsecutiveLiteralAppendsRule.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/CodeFormatRule.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/design/CyclomaticComplexityRule.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/design/TooManyFieldsRule.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/rule/design/AvoidDeeplyNestedIfStmtsRule.java
* I removed most internal usages, except where it was public (if it's public and in a concrete rule class I refactored it anyway).
* I intend to do one such PR for each property type (depending on number of usages) so it will take some time. But after this one they'll mostly be independent so I can maybe open the PRs in parallel
* I did the big documentation effort in this PR, next prs for other property types won't be as big
Refs #1432
=> [core] Deprecate IntegerProperty

docs/pages/release_notes.md, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/metrics/impl/AbstractApexMetricTestRule.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/DoubleMultiProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/DoubleProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/FloatMultiProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/FloatProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/IntegerMultiProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyBuilder.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyFactory.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/DoublePropertyTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/NonRuleWithAllPropertyTypes.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NPathComplexityRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractMetricTestRule.java
Takes care of
* IntegerMultiProperty
* DoubleProperty
* DoubleMultiProperty
They barely had any usages so I though doing them together was ok.
I also updated the deprecated notices on Float[Multi]Property. 
Refs #1432
=> [core] Deprecate some more property types

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/Rule.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSets.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/DataFlowHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/VisitorStarter.java
This PR ports deprecations from #1426 to master.
I added a few `@InternalApi` annotations on the data-flow related methods of LanguageVersionHandler. Perhaps all data-flow related methods and classes should be downgraded to `@Experimental` API and not relied upon outside of PMD, until someday we improve them enough to be stable API again. Wdyt?
Also, maybe the jdoc tag should display by default the arguments of a method. The most common case is that `!a!` is specified
=> [core] Port deprecations from the AST processing stages PR

pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml
- [ X ] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
- [ X ] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)
Adding test for Issue #647 JUnitTestsShouldIncludeAssertRule should support `this.exception` as well as just `exception`
=> [java] Adding test for Issue #647

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml
This fixes #647 .
It uses the test from PR #1457.
=> [java] JUnitTestsShouldIncludeAssertRule should support `this.exception` as well as just `exception`

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/properties/CharacterMultiProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/CharacterProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/LongMultiProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/LongProperty.java, pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyFactory.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/CharacterPropertyTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/LongPropertyTest.java
Last item on the checklist #1432 for 6.10.0 :smile: 
Those properties were not used at all... but supporting them is practically free as we can use the standard library to parse them
=> [core] Deprecate char and long properties

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/visitors/PMDASMVisitor.java, pom.xml
Remove ASM7_EXPERIMENTAL flag since ASM7 has been released.
PMD 6.10.0 passes the `ASM7_EXPERIMENTAL` flag to asm, which fails on asm 6.2.1 - `ClassVisitor` enforces only stable ASM per https://gitlab.ow2.org/asm/asm/blob/master/asm/src/main/java/org/objectweb/asm/ClassVisitor.java#L69
Upgrading PMD to use the recently released ASM 7.0 library and replacing `ASM7_EXPERIMENTAL` with `ASM7` works.
=> [java] Upgrade to ASM7 for JDK 11 support

docs/pages/pmd/rules/java/errorprone.md, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReturnFromFinallyBlock.xml
ReturnFromFinallyBlock was giving wrong results for Lambdas or Class return statements.
Added new Tests also.
Fixes #1035
=> [java] Fix for ReturnFromFinallyBlock false-positives

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableCouldBeFinalRule.java, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml
This PR fixes #1513 
- a new property to exclude the for-each variable (it is "false" by default, so existing rule definitions don't change)
- a test case to check the new property
=> [java] LocalVariableCouldBeFinal: allow excluding the variable in a for-each loop

pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/ForLoopVariableCountTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ForLoopVariableCount.xml
This PR fixes #1519
- new XPath rule "ForLoopVariableCount"
- test cases for the default configuration (one variable max) and a few custom configurations
=> [java] New rule: ForLoopVariableCount: check the number of control variables in a for loop

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidReassigningLoopVariablesRule.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidReassigningLoopVariablesTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningLoopVariables.xml
This implements the new AvoidReassigningLoopVariables rule proposed in #1518
- the rule checks for and foreach loops
- "for" loops: configuration to completely allow/deny changing the variable in the loop body or allow only incrementing/decrementing the variable
- "foreach" loops: configuration to completely allow/deny changing the variable in the loop body or allow changing it in the first statement
- test-cases to verify the allow, deny, and intermediate configuration options
**Rationale for the intermediate configuration options:**
Incrementing or decrementing a "for" loop variable is fairly common, e.g. when skipping/re-reading elements. Setting the variable directly is either a bug or an indicator that the loop is overly complicated. This ensures that the loop variable in general …
=> [java] New rule: AvoidReassigningLoopVariables

pmd-apex/src/main/resources/category/apex/categories.properties
We are currently not generating documentation for the `ApexDoc` rule, included in the documentation category.
=> [apex] Include the documentation category

docs/pages/next_major_development.md, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/main/resources/category/java/design.xml
Just enhances the documentation a bit and directly points to the rule, that should be used instead.
=> [doc] Add note which rules replace the deprecated rule.

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidSlf4jMessageFormatRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidSlf4jMessageFormat.xml
InvalidSlf4jMessageFormatRule should support enums
Fixes #1549
=> [java] InvalidSlf4jMessageFormatRule should not throw NPE for enums

pom.xml
This fixes the build of #1576 because pmd/build-tools#12 is now included
=> [core] Update build-tools to 1.4.0

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractStatisticalApexRule.java, pmd-core/src/main/java/net/sourceforge/pmd/Report.java, pmd-core/src/main/java/net/sourceforge/pmd/ThreadSafeReportListener.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/stat/StatisticalRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/stat/StatisticalRuleHelper.java, pmd-core/src/main/java/net/sourceforge/pmd/stat/DataPoint.java, pmd-core/src/main/java/net/sourceforge/pmd/stat/Metric.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractStatisticalJavaRule.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractStatisticalPLSQLRule.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/rule/AbstractStatisticalVmRule.java
This relates to #483. The concrete rule classes can't be refactored for now without breaking the API, because of the properties declared by StatisticalRule. Statistical rules also need to be removed before #1432 can proceed on the 7.0.x branch
=> [core] Deprecate StatisticalRule

pmd-core/pom.xml
Upgrading Google Gson from 2.5 (released November 2015) to 2.8.5 (released May 2018).
`mvnw clean verify` passes.
=> [core] Upgrading Google Gson from 2.5 to 2.8.5

pom.xml
Upgrading System Rules dependency from 1.8.0 (released January 2015) to 1.19.0 (released November 2018).
`mvnw clean verify` passes.
=> [core] Upgrading System Rules dependency from 1.8.0 to 1.19.0

pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/AstPackageExplorer.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/XPathAutocompleteProvider.java
The refactoring of AstPackageExplorer done in #1577 didn't work properly --Files.walkFileTree doesn't work inside of a jar file. I tried to revert the change but for some reason I found that that didn't work anymore. I took ideas from [this SO post](https://stackoverflow.com/a/28057735/6245827) and made something that should work both when the libraries are inside a jar and when they're unpacked (so that it works when running inside an IDE). Without that the autocompletion doesn't find any suggestions.
Please test it works on your systems by bundling a zip distribution and checking that the autocomplete works without exception, eg with `mvn install -pl pmd-ui,pmd-dist`
=> [ui] Fix package exploration in jars

pmd-core/src/main/java/net/sourceforge/pmd/util/FileFinder.java
Sorts the listed files by path in order to avoid inconsistencies since the listing on directories provided by the java api does not guarantee always the same order. Therefore, sorting the files by path (ignoring the case), we can guarantee that the files will be iterated always by the same order, avoiding returning different clones for the same files in different CPD executions.
=> [core] Fixes 1196: inconsistencies of clones returned by different CPD executions for the same files 

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/UpdateStatementExample.pls
=> [plsql] updates should allow for multiple statements

docs/pages/release_notes.md, pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/main/ant/alljavacc.xml, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTCompoundCondition.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ASTCompoundConditionTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseLike.pls
=> [plsql] Parse Exception when functions are used with LIKE

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/AtLeastOneConstructorRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/AtLeastOneConstructor.xml
This didn't pass, but it failed in a module I didn't touch (core). `./mvnw clean verify -pl pmd-java` passes.
Fixes a copy/paste error that caused lombok.AllArgsConstructor to not count as a constructor. Fixes #1547.
=> [java] Fix lombok.AllArgsConstructor support

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LinguisticNamingRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LinguisticNaming.xml
Overriden methods are ignored from LinguisticNamingRule.
fixes #1543
=> [java] LinguisticNaming should ignore overriden methods

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/UnsynchronizedStaticFormatter.xml
Thread safe formatter org.apache.commons.lang3.time.FastDateFormat can now avoid UnsynchronizedStaticFormatterRule.
Fixes #1633
=> [java] UnsynchronizedStaticFormatter reports commons lang FastDateFormat

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AccessorMethodGenerationRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AccessorMethodGeneration.xml
Compile time constants with literals only expression avoiding AccessorMethodGenerationRule.
Fixes #808
=> [java] Compile time constants initialized by literals avoided by AccessorMethodGenerationRule

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/ConsecutiveLiteralAppendsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml
ASTTryStatement added to BLOCK_PARENTS.
fixes #1632
=> [java] ConsecutiveLiteralAppends false positive 

docs/pages/pmd/rules/apex/codestyle.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/codestyle/MethodNamingConventionsRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/codestyle/xml/MethodNamingConventions.xml
Add a 'skipTestMethodUnderscore' boolean property that allows an
annotated Apex test method (@isTest or testMethod) to contain underscores
Fixes #1573
=> [apex] Add property to allow apex test methods to contain underscores

docs/pages/release_notes.md, pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/CodeFormatRule.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/SelectExpressionsTest.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/SelectHierarchicalTest.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectExpressions.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectHierarchical.pls
Fixes #1590 
This slightly changes the parse tree: In order to properly support function calls in select statements, I needed to move them down to PrimaryPrefix.
I also figured out, that we are hitting a limit here with the tokens: I first started out to define each built-in function name as a token and use these tokens to determine the function name, but it turns out, that the generated parser can't be compiled anymore (the compiler throws a stack overflow exception...) probably due to the big switch-case statements. So I tried to define not too many new tokens...
=> [plsql] Support hierarchical query clause

pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/Designer.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/MainDesignerController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/NodeInfoPanelController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/SourceEditorController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/app/MessageChannel.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/app/NodeSelectionSource.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ObservableXPathRuleBuilder.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/PropertyDescriptorSpec.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtil.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/AstTreeView.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/NodeEditionCodeArea.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/PropertyTableView.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ToolbarTitledPane.java, pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/TreeViewWrapper.java
Inspired by the discussion on #1672 
User-facing:
* If the VM parameters have been forgotten on JRE 9+, a warning is output on `System.out` and it doesn't cause the app to crash (the treeview just can't estimate visibility of items nicely). I'll try to find a way to displays those errors in-app instead of using System.out.
* System.err is not closed until after the end of the initialisation sequence, so as not to hide fatal errors
* XPath syntax errors and other reasons why XPath can't be evaluated are now displayed very prominently in the XPath results area
Internal:
* NodeSelectionSource has been simplified to a more basic form. In particular the selection events are only used by the initialisation method, so they were converted from an interface method to a method parameter. Same can …
=> [ui] Improved error reporting for the designer

pom.xml
There's a bug with the `useIncrementalCompilation` flag of the maven compiler plugin: https://issues.apache.org/jira/browse/MCOMPILER-209
Basically the flag must be explicitly set to false to get incremental compilation, otherwise maven always picks up changes and recompiles everything.
=> [core] Fix bug with maven incremental compilation

docs/pages/pmd/rules/java/bestpractices.md, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseTryWithResources.xml
=> [java] Fix false positive in useTryWithResources when using a custom close method with multiple arguments

docs/pages/pmd/userdocs/configuring_rules.md
The example for how to set a custom value to a property of a rule is incorrect. This PR corrects the example.
Fixes #1721.
=> [doc] Correct property override example

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/stat/StatisticalRule.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java, pmd-doc/src/test/resources/expected/sample.md
Refs #1712
In case a rule has properties, we now generate additionally a section "Use this rule and customize it".
Example:
=> [doc] Generate property override examples in rule doc

docs/pages/pmd/rules/java/codestyle.md, pmd-java/src/main/resources/category/java/codestyle.xml
This fixes #1674.
Documentation of CommentDefaultAccessModifier used `/` which renders as italic font, and disappears.
Instead, using ` to mark these symbols as code, as it should be.
=> [java] fix escaping of CommentDefaultAccessModifier documentation

docs/pages/release_notes.md, pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/XMLElementTest.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/XMLTableTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/XMLElement.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/XMLTable.pls
It fixes #1510, but only supports the minimal set of functions to be able to parse the example code from https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/XMLTABLE.html and https://docs.oracle.com/en/database/oracle/oracle-database/18/adxdb/xquery-and-XML-DB.html
=> [plsql] Support XMLTABLE functions

pmd-apex/pom.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/DefaultRulesetTest.java, pmd-java/src/main/resources/rulesets/java/quickstart.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/QuickstartRulesetTest.java
I noticed, that we get a deprecation warning about UnsynchronizedStaticDateFormatter …
So, I updated it, added a unit test, that we detect such cases earlier and took the chance to add the templates for any new rule, we added since we initially created the quickstart ruleset.
No new rules are activated, I only reordered them.
=> [java] Update quickstart ruleset 

docs/pages/release_notes.md, pmd-core/src/main/resources/rulesets/releases/6130.xml, pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLParser.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTInput.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/AvoidTabCharacterRule.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/LineLengthRule.java, pmd-plsql/src/main/resources/category/plsql/codestyle.xml, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/AvoidTabCharacterTest.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/LineLengthTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/rule/codestyle/xml/AvoidTabCharacter.xml, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/rule/codestyle/xml/LineLength.xml
This adds 2 new sample rules for PLSQL, which make use of the plsql source directly.
I think, that's an interesting idea that we should consider in PMD 7 for "official" support in all languages (this PR only adds it for PLSQL).
This PR fixes #1716
=> [plsql] New rules which use the plsql source directly

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java, pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidDuplicateLiteralsTest.java
=> [java] AvoidDuplicateLiterals warning about deprecated separator property when not used

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml
This fixes #1720.
Allowing `[]` at the variable names of JavaDoc functions, when checking for unused imports.
=> [java] Update rule to prevent UnusedImport when using JavaDoc with array type

docs/pages/pmd/rules/java/design.md, pmd-java/src/main/resources/category/java/design.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UseObjectForClearerAPI.xml
The description and implementation of the rule suggest that is should only apply
to public methods, but it is effective against all methods as for the existence
of the `@Public` attribute is tested instead of the value, so the condition is
always true.
With this fix, only public methods are considered like intended.
Fixes #1760
=> [java] UseObjectForClearerAPI Only For Public

pmd-java/src/main/resources/category/java/bestpractices.xml
- We are already using `pmd-java:typeIs`, so it's the correct thing to do.
- Plus, this way it's 6X faster
=> [java] JUnitTestContainsTooManyAsserts uses XPath 2

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java
This removes one incompatibility between Jaxen- and Saxon-flavoured XPath queries. In Jaxen you need the `fn:` prefix for standard function calls, now in Saxon it's allowed, but not necessary, instead of causing failure.
Refs #1687, #1770
=> [core] Declare fn namespace on Saxon 

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentToNonFinalStaticRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AssignmentToNonFinalStatic.xml
The rule AssignmentToNonFinalStatic reports violations when a static field is initialized in the constructor. Sometimes, people get confused about this, because they can't find the part when the variable is initialized.
I've adjusted the implementation to report the violations at the location of the initialization. In addition to this, violations are now reported for each initialization rather than once at the declaration.
=> [java] Location change in AssignmentToNonFinalStatic

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
- The data is now a fixed-size array instead of a fixed-size arraylist, this removes the need to manually add null elements all over.
- This in turn avoids the resizing / runtime exceptions under multithreaded accesses.
- Take the change to fix the way `isGeneric` is resolved to beconsistent over time and correct.
- Fixes #1691
=> [java] Fixes to JavaTypeDefinitionSimple

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/cpd/LanguageFactory.java
This fixes #1788 by using the current's classloader instead of the current Thread's ones. This is required if executing CPD in a separate worker.
Also adjusts the release notes.
As discussed in #1788, here is the desired PR. Orientates on #1387.
=> [cpd] [core] Use current classloader instead of Thread's classloader

pmd-dart/src/main/antlr4/net/sourceforge/pmd/lang/dart/antlr4/Dart2.g4, pmd-dart/src/test/java/net/sourceforge/pmd/cpd/DartTokenizerTest.java, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/escaped_string.dart
This is a fix for strings containing escaped quotes in Dart. Without this fix, this results in a lexical error.
Example:
`"$a(b: $b, c: \"$c\")"`
=> [dart] [cpd] Dart escaped string

pmd-dart/src/main/antlr4/net/sourceforge/pmd/lang/dart/antlr4/Dart2.g4, pmd-dart/src/test/java/net/sourceforge/pmd/cpd/DartTokenizerTest.java, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/escape_sequences.dart, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/escaped_backslash.dart
This is a fix for escape sequences in Dart. As a result of #1791, certain escape sequences resulted in parse errors. These have now been made explicit.
=> [dart] [cpd] Dart escape sequences

pmd-python/etc/grammar/python.jj, pmd-python/src/test/java/net/sourceforge/pmd/cpd/PythonTokenizerTest.java
This pull request adds backticks (\`) to the Python grammar. Backticks are an alternative for the `repr` function in Python 2.
=> [python] [cpd] Add support for Python 2 backticks

pmd-matlab/etc/grammar/matlab.jj, pmd-matlab/src/test/java/net/sourceforge/pmd/cpd/MatlabTokenizerTest.java
We encountered the follow construct in a Matlab file, which CPD fails to parse:
`function [obj, c,t, s ] = Classification( obj,m,t, cm )%#codegen`
This did work in early versions of PMD (5.3 specifically). I believe it's a regression that was introduced by commit cf9b768b90e11e022b2cbd4baad6419702abf532.
=> [matlab] [cpd] Matlab comments

pmd-matlab/etc/grammar/matlab.jj, pmd-matlab/src/test/java/net/sourceforge/pmd/cpd/MatlabTokenizerTest.java
This adds supports for double-quoted string to the Matlab tokenizer.
Traditionally, Matlab strings have looked as follows:
```c = 'Hello World'```
Starting from version R2017a, double quotes can be used as well:
```str = "Greetings friend"```
Refer to https://nl.mathworks.com/help/matlab/characters-and-strings.html for details.
=> [matlab] [cpd] Double quoted string

pmd-cpp/etc/grammar/cpp.jj, pmd-cpp/src/test/java/net/sourceforge/pmd/cpd/CPPTokenizerTest.java
This adds support for digit separators in C++. This is a C++14 feature.
Example: `auto integer_literal = 1'000'000;`
The single quotes can be used to add some structure to large numbers.
=> [cpp] [cpd] Add support for digit separators

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/CommentTest.java
* This PR is for PMD 7
Changes:
* Ensures that a node has it's parent, when it is added as a child.
* Makes `getXPathNodeName()` abstract by removing the default implementation.
Todo:
* The default implementation of this method issued a warning. We have it mentioned in `next_major_development.md`, the we will remove it (under 6.1.0). Should we add it again (under 7.0.0?) that it has been removed?
=> [core] Remove default implementation of getXPathNodeName

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLabeledBlock.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLabeledExpression.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLabeledThrowStatement.java, pmd-lang-test/pom.xml, pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/AstMatcherDslAdapter.kt, pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/NodeExtensions.kt, pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/TestUtils.kt
* This PR is for PMD 7
Changes:
* adds the new `assertTextRangeIsOk`, that is executed on every node in the kotlin-based tests
* this ensures, that the position of the nodes in the AST is the same as they appear in the source code
* For the new switch labeled rules, we have the following grammar
```
void SwitchStatement():
{}
{
"switch" "(" Expression() ")" SwitchBlock()
}
void SwitchBlock() #void :
{}
{
"{"
(
SwitchLabel()
(
"->" SwitchLabeledRulePart() (SwitchLabeledRule())*
|
":" (LOOKAHEAD(2) SwitchLabel() ":")* (BlockStatement())* (SwitchLabeledStatementGroup())*
)
)?
"}"
}
void SwitchLabeledRulePart() #void:
{checkForSwitchRules();}
{
(
( Expression() ";" ) #SwitchLabeledExpression(2)
|
( Block() ) #SwitchLabeledBlock(2)
|
( ThrowStatement() ) …
```
=> pmd-lang-test: Improvement to check node position

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNodeBase.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaNode.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/AbstractEcmascriptNode.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/AbstractJspNode.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/AbstractPLSQLNode.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/AbstractVFNode.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/AbstractVmNode.java
* This PR is for PMD 7.
Changes:
* The children array in AbstractNode is now initialized with an empty array.
* This means, it is now never null, thus the null checks can be removed.
* The only change to the children array is, when adding a new child (`jjtAddChild`), or removing a child (`removeChildAtIndex`).
Future:
* the children array is protected. This means, sub classes could assign null to it... do we really need field available in subclasses? I'd assume, the already available methods are enough. -> this is something for defining a general AST API (which methods should be package private only, as they are only used by the parser, which methods define the API, when do we implement iterator, etc..)
=> refactor: Make the children array never null

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexHandler.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/DumpFacade.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractLanguageVersionHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/AbstractJavaHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/DumpFacade.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/Ecmascript3Handler.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/DumpFacade.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/JspHandler.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/DumpFacade.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLHandler.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/DumpFacade.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfHandler.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/DumpFacade.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmHandler.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/AbstractVmNode.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/XmlHandler.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/DumpFacade.java
Refs #1801
The method `LanguageVersionHandler#getDumpFacade(Writer, String, boolean)` was already deprecated. Looking at the implementations of this (we remove them in PMD 7), I don't see a direct warning in eclipse IDE... I see, the VisitorStarter is deprecated, but I don't see the method `getDumpFacade` is deprecated.
Should we add deprecations also in `AbstractLanguageVersionHandler` and every implementation?
=> deprecate: DumpFacade will be removed in PMD 7

pmd-core/pom.xml
* This PR is for PMD 7
This only adds the dependency (compile time), and does not make use of it yet.
I've added a section in the wiki: https://github.com/pmd/pmd/wiki/PMD-7.0.0-API
We'll need to flesh out the details over time and verify our APIs, that we have properly annotated them (if we all agree, that we use `@Nullable`).
=> [core] Add checker-qual dependency

pmd-java/etc/grammar/Java.jjt, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/JDKVersionTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/jdk9_module_info_with_annot.java
Fixes #1842 
There's also this weird thing at the end of the CompilationUnit production:
```
( < "~[]" > )?
```
I think this is meant to allow any additionnal trailing characters, but in that case it should be written `( < ~[] > )*` (no quotes, a star). With the current grammar, an empty file with just the contents `~[]` is a valid compilation unit.
=> [java] Fix annotated module declaration

pmd-dart/src/main/antlr4/net/sourceforge/pmd/lang/dart/antlr4/Dart2.g4, pmd-dart/src/test/java/net/sourceforge/pmd/cpd/DartTokenizerTest.java, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/regex.dart, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/regex2.dart, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/regex3.dart, pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/string_with_backslashes.dart
This is yet another improvement on the Dart grammar for CPD. I found some other cases that weren't tokenized correctly. This time, the grammar is much more closely aligned to the official specification (see https://github.com/chalin/dart-spec-and-grammar/blob/master/doc/grammar-AUTOGENERATED-DO-NOT-EDIT.txt).
One aspect that is not taken into account are interpolated strings. These are strings with a $ character followed by a character in them. These could, in principle, be tokenized differently (with identifiers being separate tokens). However, this is more difficult, and it won't help too much for duplicated code analysis, since an interpolated string including all interpolated variables will typically result in the same …
=> [dart] [cpd] Improved string tokenization

docs/pages/pmd/userdocs/suppressing_warnings.md
There are two recent questions on stackoverflow regarding violationSuppressXPath suppressing too many violations:
* https://stackoverflow.com/questions/56002416/pmd-custom-junit-method-naming-rule-not-working
* https://stackoverflow.com/questions/56492868/suppress-pmd-violation-in-certain-classes 
The former also was raised here as #1811
I think we should strongly emphasize in the docs, that the violationSuppressXPath is supposed to be evaluated with the context node (though it's already stated), and so not use `//`, as in those two issues.
=> [docs] Clarify violationSuppressXPath docs

pmd-core/src/main/java/net/sourceforge/pmd/lang/antlr/AntlrBaseParser.java, pmd-swift/pom.xml, pmd-swift/src/main/ant/antlr4.xml, pmd-swift/src/main/java/net/sourceforge/pmd/lang/swift/SwiftParserAdapter.java
This pull request depends on #1658.
We added an ant-file to make all Antlr4 autogenerated nodes extend `AntlrBaseNode` for swift, a base parser adapter for all Antlr4 autogenerated parsers and it's implementation for swift. 
Team Raptor.
=> [core] [swift] Antlr Base Parser adapter and Swift Implementation

docs/pages/release_notes.md, pmd-java/src/main/resources/category/java/codestyle.xml
Rather than being a generally useful rule, `AvoidFinalLocalVariable` contradicts a good code style in most cases and only serves to avoid a special case (local literals) which it doesn't distinguish.
=> [java] Explain the existence of AvoidFinalLocalVariable in it's description

docs/pages/pmd/userdocs/installation.md
Frontpage (https://pmd.github.io/) uses ruleset quickstart.xml but https://pmd.github.io/pmd-6.16.0/pmd_userdocs_installation.html#sample-usage uses deprecated ruleset basic.xml 
(page https://pmd.github.io/pmd-6.16.0/pmd_rules_java.html shows status of both rulesets)
Fixes #1909
=> [doc] Update ruleset filename from deprecated basic.xml to quickstart.xml

pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDCommandLineInterface.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
…command is invoked.
This fixes, in theory, the issue #1913 by creating a new status code in the PMDCommandLineInterface class with the value of zero, and makes the CLI return it when the help command is used.
Fixes #1913
=> [core] Add 'no error' return option, and assign it to the cli when the help command is invoked

docs/pages/pmd/rules/java/errorprone.md, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml
I added exclusion from MissingStaticMethodInNonInstantiatableClass rule for private annotated constructors handled by DI framework. I also considered to add suggested @ApplicationScoped, @Dependent, @RequestScopedm but them to specific from my perspective.
And thank you for great project!
Fixes #1832
=> [java] Exclude Autowired and Inject for MissingStaticMethodInNonInstantiatableClass

pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java, pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java
As I was working on #1923 I came across this bug due to how ant is setup on my machine.
This issue is not included in the original #1923 report, so it seems to be unrelated to those problems.
=> [core] Avoid crashes with analysis cache when classpath references non-existing directories

pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisResult.java
If the checksum couldn't be determined, then we use now
System.currentTimeMillis. This should result in a different
checksum everytime the same file is analyzed, so that it
appears dirty. In that case, the cached results won't be used.
=> [core] analysis cache: Use always different checksum

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/NoAttribute.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/NoAttributeTest.java
* This PR is for PMD 7.
Changes:
* Adds the `@net.sourceforge.pmd.lang.ast.xpath.NoAttribute` annotation
* With that, you can annotate getters in AST nodes, that should not be exposed as XPath attributes and thus cannot be used for xpath expressions/queries.
* The annotation can also be applied to the whole AST class - then all methods are not exposed.
Todo:
* This feature needs to be documented somewhere... it seems to be part of the AST API -> https://github.com/pmd/pmd/wiki/PMD-7.0.0-API
* We need to add a unit test
=> [core] Support NoAttribute for XPath

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/RecordTypeTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/RecordType.pls
Used Name() instead of ID() and modified VariableName() so package.record_variable.field can be parsed correctly.
Fixes #1950
Fixes #1948
Fixes #1935
=> [plsql] Fixes for referencing record type variables

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ViewTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/QueryWithoutSemicolon.sql
Scripts shown below is bad coding exmaple (it should end with semicolon), but it is accepted by sqlplus so it should also be parsed.
It results in ParseException because / is consumed in MultiplicativeExpression.
```
create or replace view beneficiary as
select os.obj_seq_no,
nvl(os.n01, 0) procentage
from   object_slave os
where  obj_slave_type_id = 'BENEFICIARY'
/
```
=> [plsql] Fix for mistaking / for MultiplicativeExpression

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/CursorWithWithTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/CursorWithWith.pls
=> [plsql] fix for skipping sql starting with WITH

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/AnonymousBlockTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/AnonymousBlock1.sql, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/AnonymousBlock2.sql
**PR Description:** Functions for skipping tokens (like Skip2NextTokenOccurrence or Read2NextOccurrence) do not work when used in LOOKAHEAD. It often causes parsing exceptions,
I simplified LOOKAHEAD expressions in Global function.
Fixes #1936
Fixes #1933
=> [plsql] Fix for cursors in anonymous blocks

pmd-java/src/main/resources/category/java/bestpractices.xml
Added justification as to why we are not checking unused parameters for public methods.
Fixes #1227
=> [java] Update doc for unused formal parameter

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/CanSuppressWarnings.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexRuleViolation.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/CanSuppressWarnings.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java
This follows up on #1927 to implement the required deprecations. I chose to keep the release notes just a simple listing, because they already link to javadoc
=> [java,apex] Deprecate CanSuppressWarnings

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
Retrieving the enclosing class might result in a LinkageError or
ClassFormatError.
For now this error is just logged as a warning and ignored.
fixes #2042
=> [java] PMD crashes with ClassFormatError: Absent Code attribute

Gemfile, Gemfile.lock
faraday 0.16.2 has been released today, so this PR
* reverts the temporary workaround
* add Gemfile.lock to pin down the current versions
This means, that we'll need to run "bundle update" manually from time to time. But we shouldn't be surprised by any updated dependency in the future.
Fixes #2040
=> fix:[ci] Danger is failing builds

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractJavaClassMetric.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/NoamTest.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/NopaTest.xml
Fixes #1912 by using all children of a body declaration instead of just the first child to find a specific type of node.
=> [java] Fix computation of metrics with annotations

docs/pages/pmd/rules/java.md, docs/pages/pmd/rules/java/errorprone.md, pmd-java/pom.xml, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidSlf4jMessageFormatRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/MoreThanOneLoggerRule.java, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidSlf4jMessageFormat.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MoreThanOneLogger.xml
Fixes #336.
The InvalidSlf4jMessageFormat rule can apply to log4j2 as well. The scope of the changes is limited to adding log4j2 support to the rule.
Changing the name of the rule should be considered at some point but this would also require a documentation change.
Modified rules:
* [InvalidSlf4jMessageFormat](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#invalidslf4jmessageformat)
* [MoreThanOneLogger](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#morethanonelogger)
=> [java] Fixes 336, slf4j log4j2 support

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/LawOfDemeter.xml
Adds another conditional to the [LawOfDemeter](https://pmd.github.io/latest/pmd_rules_java_design.html#lawofdemeter) rule to allow for the use of the Inner Builder pattern, like so:
```java
public class Test {
public void bar() {
// Inner Builder pattern chained
final Bar bar = Bar.newBuilder()
.withFoo("foo")
.build();
}
}
```
**Care**: Does not use the _PREFIX_EXCLUSION_PATTERN_ as this would only check against the _baseName_ when it had to check for the _methodName_ in this case.
=> [java] LawOfDemeter to support inner builder pattern

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/DataflowAnomalyAnalysisRule.java, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DataflowAnomalyAnalysis.xml
This PR stops checking for UR anomalies in the DataflowAnomalyAnalysis rule in Java. Note, I retained the UR anomaly test, but changed the expected number of errors to zero. I also updated the documentation to remove the reference to UR anomalies.
Fixes: #1636
=> [java] Stop checking UR anomalies

pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTst.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/CSVRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/CodeClimateRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/EmacsRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/EmptyRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/HTMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/IDEAJRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/PapariTextRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/RenderersTests.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextPadRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/VBHTMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java, pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java
Remove the platform-specific file separators from the test cases and does some cleaning work.
Before, there were many instances of the `sourcecodeFilename` being hard-coded into the dest data. This PR also cleans up the tests so that they will always rely on the values returned by a utility method (most commonly `AbstractRendererTest#getSourceCodeFilename`.
Fixes #2067
=> [core] Fix renderer tests for windows builds

pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
The PR puts expected and actual line numbers and fixes the misprint
fixes #2072
=> [test][core] Add expected and actual line of numbers to message wording

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
Fixes #1531
In case we determined, that the method argument is a method call,
then we skip now completly trying to determine the correct argument
type. It was half-way fixed before for the first if condition, but
we still evaluated e.g. the allocation expression in
print(new Integer(1).toString());
and wrongly assumed, the argument type would be an integer,
without taking into account the `toString()` method call.
The same happened with
privateBooleanMethod(s, "true".equals(s));
where we took the 2nd argument as a literal and assumed
it is a "String", while the method call result actually
is a boolean.
With this change now, the false positive is fixed.
However, since we don't determine the argument type at all, the
method is matched solely on argument count. This will obviously
lead to …
=> [java] UnusedPrivateMethod false-positive with method result

pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleBuilder.java, pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/util/ResourceLoader.java
In PMDTaskImpl
RuleSet is loaded via the resourceLoader, however, Rule is loaded via a default classloader.
If a customized rule jar is supplied via another path, a ClassNotFoundException would be thrown.
=> [core] Rule loader should use the same resources loader for the ruleset

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java
~add replacement JavaNode#getEnclosingType()~
Follow-up on #2034
btw. I've also updated https://github.com/pmd/pmd/wiki/PMD-7.0.0-Java and https://github.com/pmd/pmd/wiki/Java_clean_changes
=> [java] Deprecate AbstractJavaRule#getDeclaringType(Node)

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
Fixes #2048
All XPath rules will have now type resolution enabled by default.
While this change is in core, it actually only affects Java, since
this is the only language which has a type resolution facade
registered in its language handler.
=> [core] Enable type resolution by default for XPath rules

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexJorjeLogging.java, pmd-dist/src/test/java/net/sourceforge/pmd/it/AllRulesIT.java
The fix introduced with #503 (fba00843bb523cbeb06157c4793ffc29bd9a6ee7)
was incomplete and didn't work:
* The logger uses the full class name insteand of simple name
* After we changed the log level of the logger, the logger
could be garbage collected before ApexLexer retrieves it and
thus the configuration could be lost
Fixes #2092 
=> [apex] Really fix ApexLexer logging

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/test/resources/rulesets/dummy/basic.xml, pmd-dist/src/test/java/net/sourceforge/pmd/it/AllRulesIT.java
There are two variants, how a renamed rule can be expressed in the
ruleset via a deprecated rule reference: referencing just the
new rule name or referencing the ruleset+new rule name. The latter
case was not covered yet, it was not detected, that the rule ref
references are rule in the same ruleset.
Fixes #2096
=> [core] RuleSetFactory - recognize rule reference for same ruleset

docs/pages/pmd/userdocs/cli_reference.md, docs/pages/pmd/userdocs/tools/ant.md, docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/BaseLanguageModule.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/LanguageRegistryTest.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java
This fixes #1861 
Newer java compiler (java 9+) support the `--release` option to choose
for which version of the JRE to compile. This parameter only takes
simple values as documented by `javac --help`:
```
--release <release>
Compile for a specific VM version. Supported targets: 6, 7, 8, 9, 10, 11
```
adding these versions to pmd allows the use of the same versions (6, 7
and 8) with PMD as with the compiler, thus removing the need to juggle
between single digit versions for the compiler and 1.<x> for PMD.
=> [java] Add more version shortcuts for older java

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolationTest.java
Fix #2105.
When a Java class has inner classes, their classname is not correctly reported when looking at the class itself. This is not an issue for code inside a class, but the inner class declaration itself.
This is fixed by also looking at the scope of the current node instead of just its parents.
=> [java] Wrong name for inner classes

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LinguisticNamingRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LinguisticNaming.xml
Fixes #1362 
Related to #1362. The rule java/codestyle/LinguisticNaming doesn't treat Predicates as booleans, even though they are boolean-valued functions. This PR changes the behaviour of the respected class so that predicates are treated as booleans for this rule.
=> [java] Predicates treated like booleans

pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractLanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/util/designerbindings/DesignerBindings.java, pmd-core/src/main/java/net/sourceforge/pmd/util/designerbindings/RelatedNodesSelector.java
Add an interface that language implementations may implement to bind to the designer and display node highlight. This is a first step towards removing the designer dependency on the old symbol table that's in pmd-core. Once this is merged we can bump the pmd-core version of the designer and reimplement usage highlight in terms of this interface. It would be defaulted to the current behaviour, of using ScopedNode. 
This will allow the Modelica module to support usage highlight in the designer without relying on the old symbol table interfaces (ref #2041). Same can be said for the java module and its 7.0 symbol table reimplementation.
Eventually other interfaces may be provided by DesignerBindings, each being an extension point of the designer. For example, one of those can replace …
=> [core] Add designer bindings interface

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/Issue2016.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MethodCallExpressionTypes.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml
This fixes #2016, where we already resolved the method invocation to the result type. That's ok for the whole expression, but we loose the information, on which type the method is invoked.
I've put that now back down the AST like that:
```
Code:
Objects.toString(null);
PrimaryExpression  -> Type = java.lang.String
|- PrimaryPrefix  -> Type = java.util.Objects
|- Name "Objects.toString" -> Type = java.util.Objects
|- PrimarySuffix
|- Arguments
|- ArgumentList
```
The solution is not elegant, since we resolve the type of ASTName multiple times, but it works for this case at least and doesn't seem to break other parts - except for the one test case I adjusted.
The reason, why the class "Issue2016" needs to be compiled on the …
=> [java] Preserve possible type of the target reference for method invocations

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/AbstractJavaHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/AbstractJavaParser.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaDataFlowHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageParser.java
The deprecations listed on #2120. 
In the end I think this should be done for all language modules, though this PR only implements it for Java
=> [java] Deprecate abstract java parser, internalize some other APIs

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexRuleViolation.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexRuleViolationFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleViolation.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleViolationFactory.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolationFactory.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/DaaRuleViolation.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/rule/EcmascriptRuleViolationFactory.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/rule/JspRuleViolationFactory.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/PLSQLRuleViolationFactory.java, pmd-scala/src/main/java/net/sourceforge/pmd/lang/scala/rule/ScalaRuleViolationFactory.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/VfRuleViolationFactory.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/rule/VmRuleViolationFactory.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/XmlRuleViolationFactory.java
These deprecations are prerequisite to #2055. Client code should exclusively use the interfaces, and the implementations can be internalized (or factored out, like #2055 does) for 7.0.0.
=> [core] Deprecate implementations of RuleViolation[Factory]

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringInstantiationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java, pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/ArrayAccess.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/StringInstantiation.xml
This fixes #2141 
It also adds missing type resolution for array access expressions.
=> [java] Fix false negative for StringInstantion with array access

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeBodyDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractAnyTypeDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractMethodLikeNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiableNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/MethodLikeNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtil.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaOperationQualifiedName.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaTypeQualifiedName.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameFactory.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryModifierRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/DataClassRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NPathComplexityRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NcssCountRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/main/resources/category/java/performance.xml
Deprecations are explained in javadoc. Removing JavaQualifiedName is possible through simplifying the metrics framework for 7.0. It's also becoming less relevant because of symbols. Deprecations for the metrics framework can come in another PR (maybe we can even work on the new implementation on master).
=> [java] Deprecate JavaQualifiedName and a few other things

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/ElementNode.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNode.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/saxon/ElementNodeTest.java, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidLiteralsInIfCondition.xml
Fixes #2140 
This also contains a fix in the Saxon XPath integration in PMD: When using the union operator, we sometimes threw some nodes of the result away...
=> [java] Fix false negative in AvoidLiteralsInIfCondition

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/AbstractCommentRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java, pmd-java/src/main/resources/category/java/documentation.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentRequired.xml
The PR fixes #1683 by introducing a separate property for class comment and making header property checking only header top-level comments
=> [java] CommentRequired: make property names consistent

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/document/DocumentFile.java, pmd-core/src/test/java/net/sourceforge/pmd/document/DocumentFileTest.java, pmd-core/src/test/resources/net/sourceforge/pmd/document/ShouldPreserveNewlines.java
Fixes #2170 [core] DocumentFile doesn't preserve newlines
=> [core] Preserve newlines in DocumentFile

pmd-test/src/main/java/net/sourceforge/pmd/testframework/PMDTestRunner.java
Condition `noRuleTests && noUnitTests` is always false when reached here. `noUnitTests` should be probably set to `true`, not `false`.
(I found this with the [data-flow analyzer](https://github.com/Egor18/jdataflow) I'm working on.)
=> [core] Fix odd logic in test runner

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java
Condition `('0' <= c) || (c <= '9')` is always true and makes no sense. Looks like `&&` should be used here instead of `||`.
(I found this with the [data-flow analyzer](https://github.com/Egor18/jdataflow) I'm working on.)
=> [java] Fix odd logic in AvoidUsingHardCodedIPRule

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java, pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmarker.java, pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleBuilder.java, pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleFactory.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryCompatibilityTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryDuplicatedRuleLoggingTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java, pmd-core/src/test/java/net/sourceforge/pmd/RuleSetWriterTest.java, pmd-core/src/test/java/net/sourceforge/pmd/processor/MultiThreadProcessorTest.java, pmd-core/src/test/java/net/sourceforge/pmd/properties/PropertyDescriptorTest.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleDocGeneratorTest.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleSetResolverTest.java, pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java, pmd-java/src/test/java/net/sourceforge/pmd/ExcludeLinesTest.java, pmd-java/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/xpath/XPathMetricFunctionTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java, pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/ast/XPathJspRuleTest.java, pmd-scala/src/test/java/net/sourceforge/pmd/lang/scala/rule/ScalaRuleTest.java, pmd-scala/src/test/java/net/sourceforge/pmd/lang/scala/rule/XPathRuleTest.java, pmd-test/src/main/java/net/sourceforge/pmd/AbstractLanguageVersionTest.java, pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java, pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
This fixes #2161 
* Introduces methods  in RulesetFactoryUtils to create a ruleset factory from a PMD configuration with/without ClassLoader, but without ResourceLoader
* Deprecate the factory method that takes a ResourceLoader as parameter in RulesetFactoryUtils.
* Deprecate all RulesetFactory constructors, replace them with factory methods on RulesetFactoryUtils
Rationale for internalizing ResourceLoader is that it's just a helper object for RulesetFactory. Its error handling logic is tightly coupled to RulesetFactory, so it can't reliably be implemented outside of PMD. For clients of PMD it's enough to pass a ClassLoader or use the default. Alternatively we could redesign ResourceLoader to be extension-friendly, but for now it doesn't look worth the effort and added published API.
=> [core] Internalize API that exposes ResourceLoader

docs/pages/release_notes.md, pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/MultipleDDLStatementsTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/DDLCommands.sql
This fixes #2009 
It only adds parsing support for Comments, the other ddl commands are skipped as before.
=> [plsql] Fix DDLCommands parsing

docs/pages/release_notes.md, pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/main/ant/alljavacc.xml, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTStringLiteral.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/StringLiteralsTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/MultilineVarchar.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/StringLiterals.pls
StringLiterals can use a custom quote delimiter that
marks the end of a string literal. This quote delimiter
is only effective together with the quote character.
A single quote character, that is not preceded by the
delimiter, should be allowed.
Additionally, the ASTStringLiteral node gives
now access to the plain string value of the
literal without the quoting.
Fixes #2008
This partly obsoletes PR #1988 
=> [plsql] Fix StringLiteral token

pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ast/AbstractModelicaImportClause.java, pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ast/ModelicaNode.java, pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/resolver/CompositeName.java, pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/resolver/Watchdog.java
* fix one `@return` tag misspelled as `@returns`
* fix several method references initially written without `#` sign prepended
=> [modelica] Fix Javadoc tags

pmd-modelica/pom.xml, pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ast/AbstractModelicaNode.java, pmd-modelica/src/test/kotlin/net/sourceforge/pmd/lang/modelica/ast/ModelicaCoordsTest.kt
Some files were parsed into ASTs with nodes having negative ranges.
For example:
```modelica
package TestPackage
package EmptyPackage
end EmptyPackage;
end TestPackage;
```
has subtree:
```
SimpleLongClassSpecifier "EmptyPackage"
SimpleName "EmptyPackage"
Composition
ElementList <-- start = 3:3, end = 2:22
SimpleName "EmptyPackage"
```
=> [modelica] Normalize invalid node ranges

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolationTest.java
=> [java] JavaRuleViolation reports wrong class name

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml
Fixes #2196
Also refactors the implementation to not use a XPath query anymore.
=> [java] InvalidLogMessageFormat: handle zero placeholders correctly

pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRendererDescriptor.java, pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRendererDescriptorImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRenderers.java, pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/XmlTreeRenderer.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNode.java, pmd-core/src/test/java/net/sourceforge/pmd/util/treeexport/TreeRenderersTest.java, pmd-core/src/test/java/net/sourceforge/pmd/util/treeexport/XmlTreeRendererTest.java
Refs #2215. This renderer matches our Node -> DOM mapping. The output is eg
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<CompilationUnit BeginColumn='1' BeginLine='1' EndColumn='12' EndLine='1' FindBoundary='false' Image='' PackageName='' SingleLine='true' declarationsAreInDefaultPackage='true'>
<TypeDeclaration BeginColumn='1' BeginLine='1' EndColumn='12' EndLine='1' FindBoundary='false' Image='' SingleLine='true'>
<ClassOrInterfaceDeclaration Abstract='false' BeginColumn='1' BeginLine='1' BinaryName='' Default='false' EndColumn='12' EndLine='1' Final='false' FindBoundary='false' Image='Foo' Interface='false' Local='false' Modifiers='0' Native='false' Nested='false' PackagePrivate='true' Private='false' Protected='false' Public='false' SimpleName='Foo' SingleLine='true' Static='false' …
```
=> [core] Add xml tree renderer

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTFormalComment.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNodeBase.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexNode.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParserVisitor.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParserVisitorAdapter.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParserVisitorReducedAdapter.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/AbstractNcssCountRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/ExcessiveLengthRule.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/ExcessiveNodeCountRule.java, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java
Fixes #2208. We can create a dummy Jorje node to avoid returning null.
=> [apex] Make FormalComment extend ApexNode

pmd-core/src/main/java/net/sourceforge/pmd/cpd/AntlrTokenizer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/Mark.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/MatchAlgorithm.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/TokenEntry.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/Tokens.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/MarkTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/TokenEntryTest.java, pmd-core/src/test/java/net/sourceforge/pmd/cpd/XMLRendererTest.java, pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java
Currently, CPD only reports a single line number for the begin of each duplication. In order to pinpoint exactly which tokens are considered duplicate, it can be useful to also include the line where the duplication ends and column positions for the start and end of the duplication.
This PR adjust CPD to optionally include column information for languages for which the tokenizer supports it. If this information is available, it is added to the XML output. If not, these fields are omitted. In addition, the line where the duplication ends is added in all cases.
The languages that provide column information are those that use a JavaCC-based tokenizer (C++, EmcaScript/JavaScript, Java, Matlab, Modelica, Objective-C, PL/SQL and …
=> [core] CPD: report endLine / column informations for found duplications

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/AbstractNodeTransversalTest.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PreserveStackTraceRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
returns a list like all other find-methods
That's a small addition for the Node API, to make all find methods consistent.
https://github.com/pmd/pmd/wiki/PMD-7.0.0-API#description-of-node-api
=> [core] Add Node#findDescendantsOfType with crossFindBoundaries that

pmd-core/src/main/java/net/sourceforge/pmd/lang/BaseLanguageModule.java, pmd-test/src/main/java/net/sourceforge/pmd/AbstractLanguageVersionTest.java
#2088 didn't change the implementation of `Language::getVersions`, causing the returned list to contain duplicates. Spotted in the designer:
=> [core] Fix Language::getVersions duplicating aliased versions

pmd-modelica/pom.xml
Avoid:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.sourceforge.pmd:pmd-modelica:jar:6.22.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: net.sourceforge.pmd:pmd-lang-test:jar -> duplicate declaration of version (?) @ line 92, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.junit.vintage:junit-vintage-engine:jar -> duplicate declaration of version (?) @ line 102, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
=> [modelica] Remove duplicated dependencies

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml
This fixes #2250 .
Ignore the first argument of a logging call if it is a known non-string value.
This still fails if the type of argument is unknown, but at least in our code markers are defined as static final fields (just like the logger) and can be detected easily.
=> [java] FP for InvalidLogMessageFormat when using slf4j-Markers

docs/pages/release_notes_old.md
In the PMD 6.21.0 release notes, the XML properties that are specified are not consistent with the implementation.
Example of the format:
`<?xml version="1.0" encoding="UTF-8"?>
<pmd-cpd>
<duplication lines="8" tokens="68">
<file column="26" endcolumn="9" endline="14" line="7" path="..."/>
...`
=> [doc] Corrected XML attributes in release notes

pmd-java/etc/grammar/Java.jjt, pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java, pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTLiteralTest.kt
* There was a problem with the token specs for decimal literals. They allowed eg `09`, which is supposed to be an invalid octal literal (starts with zero, but a digit is greater than 7), but was lexed as a decimal literal.
* This also cleans up the regexes for other numeric literals. This is a cleaned up version of what the [Javacc parser](https://javacc.github.io/javacc/documentation/bnf.html#reserved-and-literals) currently uses
* This can't be done on master, since adding some token regexes breaks the binary API (token ids are inlined compile-time constants)
=> [java] Fix octal literals

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AppendCharacterWithCharRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AppendCharacterWithChar.xml
make AppendCharacterWithCharRule ignore String literals, which are part of an expression, such as in StringBuffer.append("X".repeat(5));
This fixes #2275
=> [java] AppendCharacterWithCharRule ignore literals in expressions

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParser.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/SuppressWarningsTest.java
Fixes #1087 
Adds support for the `// NOPMD` comment in apex.
=> [apex] Add support for suppressing violations using the // NOPMD comment

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml
UnusedImports rule now matches regular static imports first and on-demand static imports after that
this fixes #2277
=> [java] fix UnusedImports rule for ambiguous static on-demand imports

docs/_data/sidebars/pmd_sidebar.yml, docs/pages/pmd/userdocs/tools/gradle.md, docs/pages/pmd/userdocs/tools/java-api.md, docs/pages/pmd/userdocs/tools/maven.md
This improves the documentation and gives an example on how to call PMD programmatically.
Refs #2274 
Here's the content for easier reviewing:
---
The easiest way to run PMD is to just use a build plugin in your favorite build tool
like [Apache Ant](pmd_userdocs_tools_ant.html), [Apache Maven](pmd_userdocs_tools_maven.html) or
[Gradle](pmd_userdocs_tools_gradle.html).
There are also many integrations for IDEs available, see [Tools](pmd_userdocs_tools.html).
If you have your own build tool or want to integrate PMD in a different way, you can call PMD programmatically,
as described here.
You'll need to add the dependency to the language, you want to analyze. For Java, it will be
`net.sourceforge.pmd:pmd-java`. If you use Maven, you can add a new (compile time) dependency …
=> [doc] Provide documentation for gradle integration and plain java API integration

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml
Fixes #2255 
This doesn't really solve the underlying problem (we don't know the type of the lambda parameter), but merely ignores lambda parameters altogether - basically restoring the behavior before #2196 was fixed.
=> [java] Fix InvalidLogMessageFormat false-positive with lambda arguments

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java, pmd-java/src/main/resources/category/java/security.xml
So I was fiddling with Intellij's profiler, and found out that the constructor of ClassNotFoundException slows down classloading by a huge factor. In all usages that matter, the exception is immediately caught by the caller and ignored.
With this change we return null instead. This speeds up type resolution by a factor of 2.
Here's a comparison on the sources of OpenJDK 12 (around 17700 source files):
* Master:
```java
17700
Resolved: 18006988, unresolved 2591866
Resolved 88.0%
Errors 5
--------------------------------------------<<< Rule >>>--------------------------------------------
Label                                              Time (secs) Self Time (secs)  # Calls     Counter
TypeResTest                                             2,4144           2,4144   17 742
Total Rule …
```
=> [java] Don't use ClassNotFoundException to report unresolved classes

pmd-java/etc/grammar/Java.jjt, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTEnumBody.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaParser.java, pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTEnumConstantTest.kt, pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TestExtensions.kt
This is a minor improvement to EnumBody. In the future we could have a rule to mandate trailing commas or so.
=> [java] Make enum body track trailing comma/semi

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/api/ApexClassMetricKey.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/api/ApexOperationMetricKey.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/ClassCognitiveComplexityMetric.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/CognitiveComplexityMetric.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/visitors/CognitiveComplexityVisitor.java, pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/CognitiveComplexityRule.java, pmd-apex/src/main/resources/category/apex/design.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/metrics/impl/AllMetricsTest.java, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/metrics/impl/CognitiveComplexityTestRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/metrics/impl/xml/CognitiveComplexityTest.xml, pmd-apex/src/test/resources/rulesets/apex/metrics_test.xml
Fixes https://github.com/pmd/pmd/issues/2162
Adds a cognitive complexity metric for apex allowing you to use either cyclomatic complexity or cognitive complexity (or both). This is work in progress. I still need to run it against some real apex code (not just my tests) to ensure that something reasonable happens here.
I've created the PR early to get some early feedback in case people feel like I'm going in the wrong direction.
Still TODO:
Not done:
* Mutual recursion. This is probably quite hard so unless it is really wanted, I won't do this yet.
* Switch statements. It seems like these don't parse in the current version of PMD?
* Boolean expressions. The way I've done it here doesn't 100% line up with the version in the …
=> [apex] Cognitive complexity metrics

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/BaseClass.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/DirectSubclass.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/DirectSubclass2.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/DirectSynchronizingSubclass.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/ExposingSerializer.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/OtherSubclass.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/Serializer.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/TransitiveSubclass.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/other/DirectSubclassInOtherPackage.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/other/OtherClassInOtherPackage.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UselessOverridingMethod.xml
=> [java] Fix UselessOverridingMethod when evelating access modifier

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/visitors/CognitiveComplexityVisitor.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/metrics/impl/xml/CognitiveComplexityTest.xml
- x ] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
Switch statements were not correctly counted in #2297 due to them not being fully implemented by the parser. This was fixed in #2307, so now we can correctly handle switch statements when calculating cognitive complexity for apex.
=> [apex] Support switch statements correctly in Cognitive Complexity

pmd-apex/src/main/resources/category/apex/errorprone.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/TestMethodsMustBeInTestClassesTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/TestMethodsMustBeInTestClasses.xml
The title pretty must says what this is for. It fixes #639.
=> [apex] New Rule - Test Methods Must Be In Test Classes

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/FunctionsTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExtractExpressions.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/XMLFunctions.pls
As in title: added parsing of XML functions and test cases.
Fixes #2328
=> [plsql] Added XML functions to parser: extract(xml), xml_root and fixed xml_forest

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/SlashAsDivisionTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SlashAsDivision.sql
Sometimes slash used as divide operator may be parsed as execute and vice versa.
=> [plsql] fix for parsing / as divide or execute

pmd-cs/src/main/java/net/sourceforge/pmd/cpd/CsTokenizer.java, pmd-cs/src/test/java/net/sourceforge/pmd/cpd/CsTokenizerTest.java
The --ignore-usings option was no longer respected because of a regression introduced by PR #2280. Instead, using directives were filtered regardless of whether the option was used.
=> [cs] CPD: Fixed CPD --ignore-usings option

pmd-core/src/main/java/net/sourceforge/pmd/cpd/token/internal/BaseTokenFilter.java, pmd-cs/src/main/java/net/sourceforge/pmd/cpd/CsTokenizer.java, pmd-cs/src/test/java/net/sourceforge/pmd/cpd/CsTokenizerTest.java
This fixes two issues with the filtering of using directives in C#.
The first was that tokens that appeared after a using directive that weren't supposed to be filtered, were discarded anyway. This was because the state of the tokenizer was not updated whenever tokens that were used in lookahead before were processed.
Fixing this issue revealed a regression: semicolons following using directives were not filtered out anymore. As a result of this, a big list of using directives would result in a long string of semicolons, essentially rendering the filter useless in some cases.
Both of these are regression introduced by PR #2280.
=> [cs] CPD: fixes in filtering of using directives

docs/pages/pmd/userdocs/tools/ant.md
Avoid:
```
Use Rule name category/java/bestpractices.xml/ConstantsInInterface
instead of the deprecated Rule name rulesets/java/design.xml/ConstantsInInterface.
PMD 7.0.0 will remove support for this deprecated Rule name usage.
```
Doc page, that is being updated:
https://pmd.github.io/latest/pmd_userdocs_tools_ant.html
=> [doc] Update ruleset examples for ant

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractLanguageVersionHandler.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/AbstractPLSQLNode.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ASTExtractExpressionTest.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/TriggerTest.java, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/StringLiterals.pls, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/TriggerUnit.pls
This allows languages, that don't need a classloader while creating
symbol table to just override the one method.
In the test, we call always the overloaded method with class loader
which made the symbol table processing not being run for tests
in plsql.
Fixes #2325
=> [core] Call SymbolFacade without classloader by default

pom.xml
I propose to update `RepositoryPolicy.snapshots.enabled` for pluginRepository jcenter (from default **true** to explicit **false**).
Although
- it will save only one trip for `pmd-build-tools-config` (https://travis-ci.org/pmd/pmd/jobs/659474901#L4913), which is handled by original jcenter very well
but
- with jcenter mirrored via nexus - following warning from maven could also be prevented:
```
[WARNING] Could not transfer metadata net.sourceforge.pmd:pmd-build-tools-config:6-SNAPSHOT/maven-metadata.xml from/to nexus-jcenter (...):
Transfer failed for .../net/sourceforge/pmd/pmd-build-tools-config/6-SNAPSHOT/maven-metadata.xml 400
Repository version policy: RELEASE does not allow metadata in path: …
```
=> [ci] Disable checking for snapshots in jcenter

pmd-plsql/etc/grammar/PldocAST.jjt, pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/XMLTable.pls
In reference to [comment](https://github.com/pmd/pmd/pull/2326#discussion_r388178966).
It looks like there is a mistake in Oracle doc, because code compiles and works both with and without AS (on Oracle 12c).
For example
`SELECT XMLELEMENT("Emp", 
XMLFOREST(e.dummy AS foo, e.dummy last_name))
"Emp Element"
FROM dual e;` 
I modified parser and test case.
=> [plsql] xmlforest with optional AS

pmd-core/src/main/java/net/sourceforge/pmd/util/designerbindings/DesignerBindings.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/AbstractJavaHandler.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaDesignerBindings.java
Refs pmd/pmd-designer#33
This will be published in 6.23.0 and used by the designer for its 6.24.0 version (it's not urgent)
* getMainAttribute breaks the dependency on Node::getImage, which gives a clear alternative for when this attribute is deprecated/removed
* getAdditionalInfo breaks the dependency on reflection to display the type of a node, and more things may be displayed this way in the future (eg results of XPath functions) 
* getIcon is something that may improve readability in the treeview, not yet implemented at all in the designer.
=> [core] Add more bindings for the designer

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/DocumentSorter.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/ExpressionPrinter.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SplitUnions.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/Visitor.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQueryTest.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
This uses now a custom visitor for Saxon expressions to analyze and modify the expression tree.
The existing rules still work as before.
Having this done would allow us, to migrate our own XPath 1.0 rules to XPath 2.0, without loosing any performance. Then we could issue a deprecation warning when XPath 1.0 is still used.
Note: I didn't do any performance comparisons... so I don't know, whether rulechain is really necessary here.
Refs #1687 
=> [core] Add support for rule chain execution for XPath 2.0

docs/pages/pmd/userdocs/tools/maven.md
The maven configuration will generate an issue if we don't specify the maven-pmd-plugin's version. Without the version, maven wouldn't be able to find the pmd plugin in central.
=> [doc] maven integration - Add version to plugin

pmd-apex/src/main/resources/category/apex/bestpractices.xml, pmd-apex/src/main/resources/category/apex/design.xml, pmd-apex/src/main/resources/category/apex/errorprone.xml
@rsoesemann spotted in #2358 that some of the examples in the apex rules documentation are wrong. This fixes all the ones I spotted (there are some more that won't compile because they refer to variables that don't exist, but I think they are okay to leave as is).
Closes #2358.
=> [apex] Fix invalid apex in documentation

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/ExpressionPrinter.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonExprVisitor.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SplitUnions.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/Visitor.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
This doesn't optimize rules that use a separate unbounded path expression. It assumes, that Saxon has factored it out already into a own let/lazyexpression. In that case, if any path expression in such a lazy expression is found, rule chain is not used.
This fixes the performance issues found in #2377
=> [core] Saxon rulechain excludes for path expressions

pmd-java/etc/grammar/Java.jjt, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordConstructorDeclaration.java
Type parameters are not allowed on compact record constructors. See the [latest JLS draft](https://cr.openjdk.java.net/~gbierman/jep359/jep359-20200115/specs/records-jls.html#jls-8.10.5)
=> [java] Forbid type params for compact record constructors

pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/main/resources/category/java/design.xml, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/main/resources/category/java/multithreading.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AbstractClassWithoutAnyMethod.xml
If an unbounded path expression like
//PrimaryExpression[//ClassOrInterfaceDeclaration]
is used, then this will search the whole document again.
It will also avoid using rule chain later on, see #2382
I'll try to get some performance numbers from these changes...
=> [java] Performance improve xpath based rules

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/DuplicateImportsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/internal/NullableClassLoader.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelperTest.java
* Makes TypeHelper profit from #2236, by making it reuse the ClassTypeResolver cache. This improves performance when the classpath is *incomplete* (fewer ClassNotFoundExceptions thrown)
* Also add a fast-path for subtyping checks for annotations. An annotation only has Object and j.l.annotation.Annotation as strict supertypes. This applies only when the classpath is reasonably complete, ie when the annotation type is resolved. Note that for a project that doesn't use annotation-heavy frameworks, the `@Override` annotation is overwhelmingly the most used, and it is always resolved since it's in java.base
This should fix #2378 
(meaning, classpath is complete)
* master:
```
* errors:   30
* warnings: 1551
--------------------------------------------<<< Rule …
```
=> [java] Make TypeHelper use the class loading cache of ClassTypeResolver

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
Rule: [ApexCrudViolation](https://pmd.github.io/latest/pmd_rules_apex_security.html#apexcrudviolation)
Modified the regex used when checking if WITH SECURITY_ENFORCED is used to ensure it will account for any extra line break characters due to stylistic choices. Before, newlines would cause a false negative.
This continues to fix https://github.com/pmd/pmd/issues/2210
=> [apex] fixed WITH SECURITY_ENFORCED regex to recognise line break characters

pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseDiamondOperator.xml
Fixes #1723
I found a false negative, that depends on the java version. Java 8's type inference algorithm makes more type arguments redundant than with java 7. See the bottom of the test file for an example. The problem is that we need more insight into the type arguments to find out whether they are really redundant or not (and we need access to the java version used). I think this will be easily solved with PMD 7's improved type resolution, and for that reason I don't think it's worth patching together a solution on master, so I kept the current behaviour but added some tests to be enabled later.
=> [java] Fix UseDiamondOperator false positive inside lambda

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/codestyle/FieldDeclarationsShouldBeAtStartRule.java, pmd-apex/src/main/resources/category/apex/codestyle.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/codestyle/FieldDeclarationsShouldBeAtStartTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/codestyle/xml/FieldDeclarationsShouldBeAtStart.xml
A rule discussed in #2322 was field declarations should be at the start of a class. This adds that rule.
I first tried to implement this using an xpath rule, but unfortunately the apex parser seems to always put all the field definitions first in the AST, so I had to resort to using line number information and writing the rule in java.
=> [apex] New rule: field declarations should be at start

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java, pmd-apex/src/main/resources/category/apex/bestpractices.xml, pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableTest.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/UnusedLocalVariable.xml
Variables that are only ever assigned but never otherwise used.
This was discussed in https://github.com/pmd/pmd/issues/2322
Adds a basic implementation of detecting variables that are assigned but not used. I believe it does not get any false positives, just false negatives in the case of variable shadowing. I'm not sure if that is acceptable so I've left this as a draft for now until I get an opinion on that.
A way to fix shadowing issue would be to make sure the parser's variable resolver runs so we can work out which variables are the same. This information would probably be helpful for other rules, so it may be worth doing as a separate PR prior to this going in?
=> [apex] New Rule: Unused local variables

pmd-java/src/main/resources/category/java/multithreading.xml
[java] Fixes #2313 Documentation for DoNotUseThreads is outdated
The [current rule description for DoNotUseThreads](https://pmd.github.io/pmd/pmd_rules_java_multithreading.html#donotusethreads) shows implementing `Runnable` as a violation but PMD was updated few months back to ignore this.
=> [doc] Update DoNotUseThreads rule documentation

pmd-java/src/main/resources/category/java/bestpractices.xml
The message string used `?` instead of `"`, which resulted in invalid syntax and hence code which would not compile. This PR replaces the `?` character with `"`.
=> [java] Fix UseAssertEqualsInsteadOfAssertTrue Example

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ClassNamingConventions.xml
Code has been fixed as per suggestion https://github.com/pmd/pmd/issues/1164#issuecomment-393776672.
Also updated Unit Tests.
Fixes #1164
=>  [java] ClassNamingConventions suggests to add Util for class containing only static constants, fixes #1164

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/AbstractLanguageVersionHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/XPathHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AbstractASTXPathHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/DefaultASTXPathHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ImmutableLanguage.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/MockRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/AbstractXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/XPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/XPathVersion.java, pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/xpath/XPathMetricFunctionTest.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/Ecmascript3Handler.java, pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/JspHandler.java, pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ModelicaHandler.java, pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLHandler.java, pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/PLSQLXPathRuleTest.java, pmd-scala/src/test/java/net/sourceforge/pmd/lang/scala/rule/XPathRuleTest.java, pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfHandler.java, pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmHandler.java, pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/XmlHandler.java
Part of #1687
* Deprecate XPathRuleQuery as internal API. On the 7.0 branch this will probably be removed as there is no need for several implementations without Jaxen
* Make an enum to represent XPath versions. This will be useful to manage migration for users I think, by issuing deprecation warnings. This replaces the string constants of XPathRuleQuery
* Deprecate the property descriptors for xpath version and xpath expression (note, that the properties are not `deprecated!`, so they don't produce a warning in the XML, it's just their programmatic usage that is deprecated). Implementing these as properties was an easy solution, but they should not be overridden by users, as they're part of the implementation of the rule. Since we'll be giving a special XML syntax to XPath rules in 7.0, …
=> [core] Deprecate Jaxen and XPath internal API 

pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptTreeBuilder.java, pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/DefaultLocale.java, pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/TrailingCommaTest.java
Fixes #384 
Edit: this solution is a bit patchy, because the default locale may have changed between the time the message is reported by the parser, and the time we read it later. Maybe a slightly more robust solution would be to replace the MessageProvider of ScriptRuntime with something that takes a fixed locale (and even then, the message provider can be overwritten by anyone). Since this looks like a very very rare situation, I'm reluctant to go the extra step
=> [javascript] Fix issue with Rhino localization and trailing commas

pmd-core/src/main/java/net/sourceforge/pmd/lang/XPathHandler.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/internal/ContextualizedNavigator.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/internal/DeprecatedAttrLogger.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/internal/DeprecatedAttribute.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/AttributeNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/DocumentNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQuery.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/AbstractNodeTest.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNode.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNodeWithDeprecatedAttribute.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIteratorTest.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAdditiveExpression.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclaration.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclarator.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/main/resources/category/java/performance.xml
Right now, we log only the deprecated attribute usages, but not, in which rule these are used. This is not helpful to find and fix the deprecations.
This PR fixes this by logging additionally the rule name.
- Fixes #2019
=> [core] XPath warnings for deprecated attributes

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/NodeStream.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/AxisStream.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/Filtermap.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/IteratorBasedNStream.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/SingletonNodeStream.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/StreamImpl.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/TreeWalker.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/BoundaryTraversalTest.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiableNode.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/VariableAccessVisitor.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/internal/visitors/AtfdBaseVisitor.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/PrematureDeclarationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentInOperandRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringInstantiationRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
Followup on https://github.com/pmd/pmd/pull/2385#discussion_r403494429
Indeed this change is a contagious, but it maximises the usability of the API. 
I also checked out filterIsAny from the java-grammar branch and used it in one rule to see if it works. This discovered a bug with find boundaries. I changed this API a bit, now it's called asInstanceOf.
Also I think we should deprecate `Node::getFirstParentOfAnyType` on master. This causes an unchecked warning because of the generic varargs creation. In 7.0 you can now just do `node.ancestors().map(asInstanceOf(....))` without a warning
=> [core] Add wildcards to node stream API

docs/pages/release_notes.md, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/EcmascriptParserOptions.java, pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTForInLoop.java, pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/EcmascriptParserOptionsTest.java, pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTForInLoopTest.java, pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTVariableDeclarationTest.java
Fixes #1235
Fixes #2379
Note: this does not update Rhino, just makes use of the Version `ES6` (which we could have done long time ago...). It seems the VERSION_DEFAULT is not ES6 and ES6 needs to be enabled explicitly.
Unfortunately, `import` statements are not supported.
=> [javascript] Add support for ES6 version and use that as default

.travis/build-doc.sh, .travis/pmd-code-api.sh, .travis/setup-secrets.sh, docs/_config.yml, docs/_plugins/javadoc_tag.rb, docs/pages/pmd/projectdocs/committers/releasing.md, pmd-lang-test/pom.xml, pom.xml
This PR obsoletes #1769 . It applies on master and can be merged to pmd/7.0.x as well - it should work on the pmd/7.0.x branch exactly the same - it uses the current version number, so the two branches don't override each other
PMD's own documentation is now additionally deployed to https://docs.pmd-code.org/pmd-doc-VERSION/ . On snapshot builds, a symlink is updated, so that https://docs.pmd-code.org/snapshot/ always points to the latest snapshot. Note: This is only done on branch master, so pmd/7.0.x has no symlink.
On a release, the symlink "latest" is created and the old snaphot doc is deleted.
The javadoc linking between modules is solved manually using a relative url. This means, it should work also on javadoc.io (I'm using the same folder hierarchy). Only the linking to the core …
=> [core] Host own javadoc on docs.pmd-code.org

docs/pages/release_notes.md, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
${title}:
* `getFirstParentOfAnyType` and  `hasDescendantOfAnyType`: as stated on #2405, there is a better way to do this on PMD 7 (node streams) without an unchecked warning, and with a single tree traversal for the descendant method
* `getAsDocument`: I just think this is not very useful, and because of the difficulties outlined in #2215 it's not very reliable anyway. The transformation is not very hard to write for a client, and this doesn't need  to be part of the core Node interface IMO
#2215, #2216, #2405, #2172
=> [core] Deprecate a few more methods in Node, AbstractNode

docs/pages/pmd/userdocs/making_rulesets.md
Noticed that [the documentation](https://pmd.github.io/latest/pmd_userdocs_making_rulesets.html) has indentations a bit off. Removed excessive ones and changed to 4 spaces everywhere.
=> [doc] Fix "Making Rulesets" doc sample code indentation

pmd-apex-jorje/pom.xml, pmd-apex/pom.xml, pmd-doc/pom.xml, pmd-java8/pom.xml, pom.xml
Update maven-compiler-plugin to 3.8.1 and remove workaround for IDEA (those bug is closed in Youtrack)
No issues
=> [core] Update maven-compiler-plugin to 3.8.1

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java, pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/UnusedLocalVariable.xml
In the following example, `used` would be considered unused even though a method is called on it (and the result is returned, but we don't check that at the moment).
```apex
public String foo() {
String used = 'foobar';
return used.substringAfter('b');
}
```
This fixes that issue.
- Fixes #2468 
(don't think it is needed)
=> [apex] fix false positive unused variable if only a method is called

pom.xml
This was outdated, still enforcing Java 10, which would not work anymore.
Our wiki is already updated to require Java 11.
Fixes #2484
=> [core] Require Java 11

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml
Add support for Hamcrest's assertion.
- Fixes #2288
=> [java] False positive with Hamcrest's assertThat

pmd-core/src/main/java/net/sourceforge/pmd/lang/BaseLanguageModule.java, pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleBuilder.java, pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java, pmd-java/src/test/java/net/sourceforge/pmd/LanguageVersionTest.java
Builds on top of #2088 with an improved API 
The old experimental API allowed calls such as `addVersions(langHandler, false)` which were not only invalid, but would throw an `ArrayIndexOutOfBoundsException`, so we split the name
(required) and the aliases (varargs, and therefore optional). We now had:
```java
addVersion("1.4", java4Handler, false);
addVersions(java6Handler, false, "1.6", "6");
```
In doing so, I was bothered by parameter order. The version name is the most significant change when setting 2 versions for a language, so I liked it being first as the old `addVersion` method did, so I moved that ahead. I know had:
```java
addVersion("1.4", java4Handler, false);
addVersions("1.6", java6Handler, false, "6");
```
With that, I now had 2 methods that where equivalent, except one …
=> [core] Revamp the language version alias APIs

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/JUnitSpellingRule.java, pmd-java/src/main/resources/category/java/errorprone.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/JUnitSpelling.xml
Do not trigger if it's a junit5 class (isJUnit5Class from AbstractJUnitRule can be used).
Do not trigger if junit4 doesn't extend TestCase
It'd be probably good to add more explanation to the rule itself.
- Fixes #2477
=> [java] Fix JUnitSpellingRule false positive

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml
Adds a new rule `LiteralsFirstInComparisons` that examines the positioning of literals for all String comparison operations. This rule's logic is identical to `AbstractPositionLiteralsFirstInComparisons` with the exception of the `AbstractNode.image` check.
The following comparisons are supported:
- `.equals`
- `.equalsIgnoreCase`
- `.compareTo`
- `.compareToIgnoreCase`
- `.contentEquals`
This is a generalization of the previously defined rules `PositionLiteralsFirstInComparisons` and `PositionLiteralsFirstInCaseInsensitiveComparisons`. These now redundant rules will be deprecated in a separate PR.
Included all the original test cases for the original rules, as well as test cases for the new comparisons as well.
- Ref #2145 - this rule will replace the two old rules
=> [java] New rule: LiteralsFirstInComparisons

docs/pages/release_notes.md, pmd-apex/src/main/java/net/sourceforge/pmd/cpd/ApexTokenizer.java, pmd-core/src/main/ant/alljavacc.xml, pmd-core/src/main/java/net/sourceforge/pmd/cpd/AntlrTokenizer.java, pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/antlr/AntlrTokenManager.java, pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/TokenMgrError.java, pmd-core/src/main/java/net/sourceforge/pmd/util/StringUtil.java, pmd-groovy/src/main/java/net/sourceforge/pmd/cpd/GroovyTokenizer.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
* JavaCharStream doesn't throw Error anymore on invalid escape, it throws TokenMgrError
* Extract the version of TokenMgrError from the 7.0.x branch, add necessary stuff to make it binary compatible with master and deprecate members that will be removed 
- Fixes #2472
=> [core] Stop JavaCharStream from throwing Error

pmd-cs/src/main/antlr4/net/sourceforge/pmd/lang/cs/antlr4/CSharpLexer.g4, pmd-cs/src/test/java/net/sourceforge/pmd/cpd/CsTokenizerTest.java
See [the C# documentation](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#enhancement-of-interpolated-verbatim-strings) about changes to the syntax for interpolated verbatim strings in C# 8. In the past, these strings could only have the `$@` prefix, but now the `@$` prefix (where the characters are reversed) is also allowed.
=> [c#] Support for interpolated verbatim strings

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractPositionLiteralsFirstInComparisons.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PositionLiteralsFirstInCaseInsensitiveComparisonsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PositionLiteralsFirstInComparisonsRule.java, pmd-java/src/main/resources/category/java/bestpractices.xml, pmd-java/src/main/resources/rulesets/java/quickstart.xml
The `AbstractPositionLiteralsFirstInComparisons`, `PositionLiteralsFirstInComparisons`, and `PositionLiteralsFirstInCaseInsensitiveComparisons` Java rules are replaced with a more general rule (`LiteralsFirstInComparisons`) that checks all forms of String comparisons.
This PR adds deprecated tags to the rules and the rulesets.
Added new replacement rule: #2478 
Original thread: #2145
=> [java] Deprecate redundant String Comparison rules 

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodNamingConventionsRule.java, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelperTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/MethodNamingConventions.xml, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ProperLogger.xml, pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
Rule: MethodNamingConventions
Provide a `junit5TestPattern` property that allows customisation of test method naming in JUnit 5 tests.
The motivation behind this PR was to allow method naming conventions for JUnit5 style tests. These can be annotated using the `org.junit.jupiter.api.Test`. The current implementation is checking for the JUnit 4 annotations (`org.junit.Test`) only.
I discovered this because we are using the Osherove naming pattern for our JUnit 5 tests and therefore need to allow additional characters (namely underscores) in the method names. After setting the JUnit 4 style pattern, I simply noted that these were not applied.
=> [java] MethodNamingConventions - Add support for JUnit 5 method naming

docs/pages/pmd/userdocs/cpd/cpd.md, pmd-core/src/main/java/net/sourceforge/pmd/cpd/token/AntlrToken.java, pmd-cs/src/test/java/net/sourceforge/pmd/cpd/CsTokenizerTest.java
CPD Suppressions for c# fixed
test added
CPD suppression with comments CPD-OFF/CPD-ON doesn't work for c#
[c#] CPD suppression with comments doesn't work #2551
- Fixes #2551
=> [c#] Fix CPD suppression with comments doesn't work #2551

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryCastRule.java, pmd-java/src/main/resources/category/java/codestyle.xml, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryCastTest.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryCast.xml
This PR adds tests for the already existing but not referenced rule "UnnecessaryCast".
I've decided to move this rule into category "codestyle".
While adding tests, I've seen, that iterator was not supported yet, I've added this. Also, there was a problem with accessing fields via "this" (the AST is different in that case).
The rule is still very simplistic, e.g. it doesn't use typeresolution and doesn't check which method is actually called.
- none.
- The rule was first mentiond in https://sourceforge.net/p/pmd/discussion/188192/thread/276fd6f0/
=> [java] Enable rule UnnecessaryCast (codestyle)

docs/pages/release_notes.md, pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java, pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/UselessOverridingMethodHashCode.java, pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UselessOverridingMethod.xml
The following code doesn't trigger the rule [UselessOverridingMethod](https://pmd.github.io/latest/pmd_rules_java_design.html#uselessoverridingmethod):
```java
public class UselessOverridingMethodHashCode {
@Override
public int hashCode() {  // violation expected
return super.hashCode();
}
@Override
public boolean equals(Object obj) { // violation expected
return super.equals(obj);
}
}
```
If the method is already public in the super class, then there is no elevating access ongoing, it's just useless.
- Introduced when fixing #911
=> [java] UselessOverridingMethod false negative with already public methods
