pmd/pmd

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/TypeSet.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ClassScopeTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/TypeSetTest.java

This PR fixes some NPEs we encountered with our production code.
Tests with the stripped down real-world code are included.

Fix some NullPointerExceptions

---

pmd-java/src/main/resources/rulesets/java/design.xml

Please, use proper java code style in your own examples. An if statement without brackets? More cases all over the examples

Fix code example

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java
pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/MonoThreadProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/MultiThreadProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdRunnable.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java

To enhance performance of RuleSetFactory, the RuleSets generated by RuleSetFactory from ruleSetString is set in PMDConfiguration and is checked before generating it again in MonoThreadProcessor, MutliThreadProcessor and PMDRunnable classes.

RuleSetFactory Performance Enhancement

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java

Addresses https://sourceforge.net/p/pmd/bugs/1491/

Clean up Code Climate renderer

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
src/site/markdown/usage/running.md.vm

Input filelist parameter

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserTrigger.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/complexity/StdCyclomaticComplexityRule.java

Fixed Trigger name is reported incorrectly
https://github.com/Up2Go/codeclimate-apexmetrics/issues/23

[apex] Fixed Trigger name is reported incorrectly

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java

While using PMD on a large code base I noticed that performance was bad. On a 12 CPU fast machine it used only 2.5 CPU's max, and it took 6 minutes to evaluate the code. The root cause was huge contention on the classloader used.
I replaced the synchronized blocks with a ConcurrentHashMap and defined the classloader as multithread-capable (which it is, since it just extends the normal classloader).
With this change, the same load now takes 11 CPU's for 50 seconds and the job is done.

[java] Improve multithreading performance: do not lock on classloader

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/style/AvoidLogicInTriggerRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/style/xml/AvoidLogicInTrigger.xml

fixed https://github.com/Up2Go/codeclimate-apexmetrics/issues/24

[apex] Restrict AvoidLogicInTrigger rule to max. 1 violation per file

---

pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/JavaTokensTokenizerTest.java

- Unrelated classes that just happen to have matching constructor types
(maybe sibling classes extending the same base class, and simply
calling super on all constructors) should not be reported as copy-pasted
- If you copied a whole class, CPD should still match it due to other
member methods / fields, only case it would no longer catch is that of
a class exclusively containing constructors, but that should probably be
a PMD rule, and not catched by CPD itself
This fixes [#1517](https://sourceforge.net/p/pmd/bugs/1517/)

[java] CPD: Keep constructor names under ignoreIdentifiers

---

pmd-groovy/pom.xml
pmd-groovy/src/main/java/net/sourceforge/pmd/cpd/GroovyTokenizer.java
pmd-groovy/src/main/java/net/sourceforge/pmd/lang/groovy/GroovyLanguageModule.java
pmd-groovy/src/main/resources/META-INF/services/net.sourceforge.pmd.cpd.Language
pmd-groovy/src/main/resources/META-INF/services/net.sourceforge.pmd.lang.Language
pmd-groovy/src/site/markdown/index.md
pmd-groovy/src/test/java/net/sourceforge/pmd/LanguageVersionTest.java
pmd-groovy/src/test/java/net/sourceforge/pmd/cpd/GroovyLanguage.java
pmd-groovy/src/test/java/net/sourceforge/pmd/cpd/GroovyTokenizerTest.java
pmd-groovy/src/test/resources/net/sourceforge/pmd/cpd/BTree.groovy
pom.xml

Basic support, no additional flags are currently supported.

[groovy] Initial support for CPD Groovy

---

pmd-core/src/main/java/net/sourceforge/pmd/AbstractPropertySource.java
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQuery.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/MultiThreadProcessor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleChainVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codesize/StdCyclomaticComplexityRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/logging/InvalidSlf4jMessageFormatRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/Search.java

Improve collection usage to improve performance and memory footprint.

[core] [java] Improve collection usage

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/MethodNameDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/TypeSet.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java

These changes alone have improved symboltable times reported using `-b` flag when analyzing the whole PMD sourcecode in ~20%.
Changes were confirmed with jvisualvm profiler too.

[java] Improve symboltable performance

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/TokenEntry.java
pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/JavaTokensTokenizerTest.java
src/site/markdown/overview/changelog.md

- Right now it throws an NPE
- Having fixed the NPE, it threw an ArrayIndexOutOfBounds
- Finally, it was just not working as expected

[java] Properly handle enums with ignore identifiers

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java
pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java
pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmarker.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/MultiThreadProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/PmdThreadFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
src/site/markdown/overview/changelog.md

- RuleSetFactory is now immutable. This means we no longer need synchronized methods, which in turn, means threads don't contend with each other.
This change should only be applied to master, no need to include it outside 5.6.0.

[core] Make RuleSetFactory immutable

---

pmd-apex/src/main/resources/rulesets/apex/ruleset.xml

Code Climate remediation points for the nex security rules didn't fit real world repos so they should be adjusted before part of a new PMD release.

[apex] Adjusted remediation points

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexXSSFromURLParam.xml

Hey @jsotuyod!
This PR contains:
- NPE bug fix
- Detection of potential XSS in return statements.
Cheers,
Sergey

[apex] Adding XSS detection to return statements

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml

Hey @jsotuyod!
This enhancement improves detection of SOQL injection in variables passed to Database.query.
Cheers,
Sergey

[apex] Improving detection of SOQL injection

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexBadCryptoRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexInsecureEndpointRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromEscapeFalseRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexXSSFromURLParam.xml

Hey @jsotuyod!
Lots of refactoring + improvements for variable detection. 
Git merge made the diffs looks less useful, sorry about that.
Cheers,
Sergey

[apex] Xss rules improvements

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/symboltable/AbstractScope.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/SourceFileScope.java

The change is small, and the small effect on both memory and performance is neglible to make it worth merging back to 5.5.3. However, 5.6.0 should benefit from it.

[java] Tiny improvements and code tidy up

---

src/site/markdown/usage/ant-task.md
src/site/markdown/usage/running.md.vm

- Now both command line and ant pages have proper documentation on the newly available option

[core] Add documentation on analysis cache usage

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Hey @jsotuyod,
Here's some code to reduce FPs for cases when VF getter method gets info, read checks happen automatically, so now PMD won't flag those.
Cheers,
Sergey

[apex] Reducing FPs in SOQL with VF getter methods

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexDangerousMethodsRule.java
pmd-apex/src/main/resources/rulesets/apex/ruleset.xml
pmd-apex/src/main/resources/rulesets/apex/security.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/SecurityRulesTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexDangerousMethods.xml

This rule flags dangerous FinancialForce method that disables CRUD/FLS security.

[apex] Flagging of dangerous method call

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexDangerousMethodsRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexDangerousMethods.xml

Hey @jsotuyod,
This rule flags when potentially sensitive variables are in System.debug(), which would leak the data to the end user. 
Cheers,
Sergey

[apex] Flagging of System.debug

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexOpenRedirect.xml

Hi @jsotuyod,
This is a bug fix. 
P.S. I've been going through all of my rules, I'll refactor some of them and send you way.
Thanks,
Sergey

[apex] Improving open redirect rule to avoid test classes/methods

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexBadCryptoRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexInsecureEndpointRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java

Hi @jsotuyod,
The old branch had merge issues, so I created a new one.
Cheers,
Sergey

[apex] GC and thread safety changes

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Hi @jsotuyod,
This is to address lack of detection of DML operation with inline object creation.
Regards,
Sergey

[apex] Improving detection for DML with inline new object

---

pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/typeresolution/xml/CloneMethodMustImplementCloneable.xml

- This asserts the issue has actually been fixed and makes sure it won't return
- This makes sure we can close the issue [#681](https://sourceforge.net/p/pmd/bugs/681/)

[java] Uncomment the test scenario for issue 681

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Hi,
Legacy test classes are declared with Test being in the name of the class.
This fix is to address that.
Thanks!
Sergey

[apex] Legacy test class declaration support

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
pmd-core/src/main/java/net/sourceforge/pmd/ant/Formatter.java
src/site/markdown/overview/changelog.md
src/site/markdown/usage/ant-task.md

Hi,
Here's a rather significant improvement for CRUD rules. We've observed that a lot of folks do CRUD checks in other methods within the class or in the method constructor. To help significantly reduce the # of issues reported I've added control flow handling (see tests).
Regards,
Sergey

[Apex] Control flow based CRUD rule checking

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSOQLInjectionRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSOQLInjection.xml

Hi @jsotuyod,
This a bug fix for concatenated vars detection in SOQL injection rule.
Thanks!

[Apex] Bug fix of SOQL concatenated vars detection 

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/Helper.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSharingViolations.xml

HI,
This is an improvement to detect sharing violations when dynamic SOQL Database methods are used.
Regards,
Sergey

[Apex] Detection of sharing violation when Database. methods are used

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexOpenRedirectRule.java

[Apex] Dead code removal

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexSharingViolations.xml

[Apex] Sharing violation SOQL detection bug fix

---

pmd-core/pmd-core-checkstyle-suppressions.xml
pmd-java/pmd-java-checkstyle-suppressions.xml
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/ExtraTopLevelClass.java
pmd-javascript/src/test/java/net/sourceforge/pmd/cpd/EcmascriptTokenizerTest.java
pmd-plsql/pmd-plsql-checkstyle-suppressions.xml
pmd-scala/pmd-scala-checkstyle-suppressions.xml
pmd-vm/pmd-vm-checkstyle-suppressions.xml

Use OS independent path and line separators

[core] Make it build on Windows

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclaration.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclarationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/optimizations/xml/RedundantFieldInitializer.xml

- This fixes #215
- I created a new method so we didn't change public APIs

[java] Treat annotation members as public static final

---

pmd-java/src/main/resources/rulesets/java/design.xml

[doc] [java] Improve docs on NonThreadSafeSingleton

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/TypeSet.java

- There are certain cases where we know exactly what to look for, not needing
to brute force our way to inner classes. For those, use a direct approach.
ie:
```java
import a.b.c.*;
class A {
One.Two x; // if in package a.b.c, MUST be a.b.c.One$Two
}
```
Same logic applies to same-package references, and implicit imports (`java.lang.*`)

[java] Restrict type searches for inner classes

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java

- Sibling node search can be easier
- Remove dead code in generic resolution
- Make sure generics resolution goes up through nested classes

[java] Tidy up ClassScope code

---

pmd-java/src/main/resources/rulesets/java/basic.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/basic/xml/SimplifiedTernary.xml

- Fixes #232
- Also improve the docs formatting, it's getting garbled on the web..

[java] Fix FP in SimplifiedTernary with null value

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassScope.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AccessorMethodGeneration.xml

- This fixes the last known false negative for `AccessorMethodGeneration`
- Fixes false negative outstanding from #244

[java] syboltable resolves inner class methods

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexXSSFromURLParamRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexXSSFromURLParam.xml

Fix for [Issue 264](https://github.com/pmd/pmd/issues/264)

[Apex] Support safe escaping via String method

---

pmd-apex/pom.xml

Shade Jackson on Apex to avoid conflicts.
Needed for https://github.com/codacy/codacy-pmdjava/issues/23

[apex] Shade jackson on apex

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclaration.java
pmd-java/src/main/resources/rulesets/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/FinalFieldCouldBeStatic.xml

[java] fields in annotations are public static

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexXPathRule.java
pmd-apex/src/main/resources/rulesets/apex/braces.xml
pmd-apex/src/main/resources/rulesets/apex/ruleset.xml
pmd-apex/src/main/resources/rulesets/apex/rulesets.properties
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/braces/BracesRulesTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/braces/xml/ForLoopsMustUseBraces.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/braces/xml/IfElseStmtsMustUseBraces.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/braces/xml/IfStmtsMustUseBraces.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/braces/xml/WhileLoopsMustUseBraces.xml

Implements [apex] Add Java Braces rules #272

[apex] Add Braces Rule Set

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

A few bug fixes.
1. Complex nested SOQL needed to have multiple CRUD checks.
2. Type<>DML multimap accumulated duplicated copies of values.
3. List<SomeObjectType> was not being detected well due to some Jorje bugs.

[apex] Complex SOQL Crud check bug fixes

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
src/site/markdown/usage/cpd-usage.md

Now you can provide files through a CSV file instead of putting them in command arguments.
Closes https://github.com/pmd/pmd/issues/295

[core] CPD: Adding the --filelist option from pmd to cpd

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml

Hi!
This is a fix for adding detection of ```<apex:iframe srs='{!xss}' />```

[vf] Apex:iFrame not being detected - bug fix

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml

[vf] Bug fixes for incorrect Id detection and escaping

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml

Bug fixes for VF XSS detection.

[vf] Quote detection improvement and method argument detection

---

pmd-apex/src/main/resources/rulesets/apex/security.xml

- Make the syntax actually valid
- Fixes #315

[apex] Fix syntax of sample code

---

pmd-core/src/main/java/net/sourceforge/pmd/util/ResourceLoader.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java

Addresses issues with open file leaks.

[core] Fix ResourceLoader open file leaks, fixes #337

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml

@jsotuyod This is to fix a small regression introduced by my PR #341  and introducing a comprehensive dictionary of safe methods.

[vf] Fixing regression introduced by #341

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AccessorClassGenerationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AccessorClassGeneration.xml
src/site/markdown/overview/changelog.md

[java] Fix ClassCastException in AccessorClassGeneration

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitTestsShouldIncludeAssertRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitTestsShouldIncludeAssert.xml

[java] Fix NPE in JUnitTestsShouldIncludeAssert

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Bug fix for ClassCastException in CRUD violation rule.

[apex] ApexCRUDViolationRule: Bug fix for ClassCastException

---

pmd-java/src/main/resources/rulesets/java/strings.xml

Fixes #334 
Is there any way to add a hyperlink in the rule description? That would remove the disgracious URL

[java] Added documentation details on InefficientEmptyStringCheck

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/EmptyRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/RendererFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/renderers/EmptyRendererTest.java
src/site/markdown/overview/changelog.md

Add the 'empty' Renderer which writes nothing.

[core] Add the 'empty' Renderer which writes nothing.

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/coupling/LawOfDemeterRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/coupling/xml/LawOfDemeter.xml

Fix for FP: https://sourceforge.net/p/pmd/bugs/1427/

[java] False positive for Law Of Demeter (Builder pattern)

---

pmd-java/etc/grammar/Java.jjt
pmd-java/src/test/resources/net/sourceforge/pmd/ast/ParserCornerCases18.java

- added testcase to reproduce the errors
- fix #414 
- fix #415 
- fix #417

[java] FIXED: Java 8 parsing problem with annotations for wildcards

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml
src/site/markdown/overview/changelog.md

[java] ImmutableField: False positive with lombok (fixes #410)

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/AbstractJUnitRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitTestsShouldIncludeAssert.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/TestClassWithoutTestCases.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/migrating/xml/JUnitUseExpected.xml
src/site/markdown/overview/changelog.md

[java] PMD requires public modifier on JUnit 5 test (fixes #428)

---

pmd-apex/src/test/java/net/sourceforge/pmd/cpd/ApexCpdTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/cpd/ApexTokenizerTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/cpd/Simple.cls
pmd-apex/src/test/resources/net/sourceforge/pmd/cpd/issue427/SFDCEncoder.cls
pmd-apex/src/test/resources/net/sourceforge/pmd/cpd/issue427/SFDCEncoderConstants.cls
pmd-core/src/main/java/net/sourceforge/pmd/cpd/AbstractTokenizer.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/SourceCode.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/TokenEntry.java
src/site/markdown/overview/changelog.md

[core] cpd: fix line number issue, add tests for apex cpd, Fixes #427

---

pmd-jsp/etc/grammar/JspParser.jjt
pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/JspParserTest.java
src/site/markdown/overview/changelog.md

[jsp] Support parsing boolean attributes

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/logging/InvalidSlf4jMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/loggingjava/xml/InvalidSlf4jMessageFormat.xml
src/site/markdown/overview/changelog.md

[java] Simplify handling of SLF4J log arguments

---

pmd-java/src/main/resources/rulesets/java/empty.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/empty/xml/EmptyTryBlock.xml
src/site/markdown/overview/changelog.md

[java] Allow try-with-resources to be empty

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitTestsShouldIncludeAssertRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/junit/xml/JUnitTestsShouldIncludeAssert.xml
src/site/markdown/overview/changelog.md

- Don't assume all anotations are marker annotations
- Fixes #465

[java] Fix NPE in JUnitTestsShouldIncludeAssertRule

---

pmd-apex/src/main/java/net/sourceforge/pmd/cpd/ApexTokenizer.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexJorjeLogging.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParser.java
src/site/markdown/overview/changelog.md

[apex] Disable logging of jorje apex lexer

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/AnoymousExtendingObject.java

- This is really an edge case, with little or no real-world scenarios,
just fix it for completeness

[java] Fix typeresolution for anonymous extending object

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/sunsecure/ArrayIsStoredDirectlyRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/sunsecure/xml/ArrayIsStoredDirectly.xml
src/site/markdown/overview/changelog.md

- This is still not perfect. There are plenty of scenarios where this could fail (ie: multidimensional arrays), but is closer to what we want without a full rewrite.
- On the future we need to review this rule once again.
- Resolves #468

[java] Fix issue 468

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractLombokAwareRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml

[java] Fix issue #527: Lombok getter annotation on enum is not recognized correctly

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/LanguageFactory.java

[core] Fix typo

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParserVisitorAdapter.java

The adapter always returned null

[apex] Fix broken Apex visitor adapter

---

.travis/build-deploy.sh

As discussed in #526, this implements step 2: it pushes any updates to the generated documentation, if there are any changes. The infrastructure for pushing was already setup, since we use it during releasing (pushing to pmd.github.io).
The push will be done only, if we are on the master branch. We won't execute it, while releasing (building the tag).

[ci] Push changes to docs, if there are any

---

pmd-java/src/main/resources/rulesets/java/strings.xml

Fixes #571.
Adds a hint to a Guava alternative to the documentation of InefficientEmptyStringCheck.

[doc][java] Add hint for Guava users in InefficientEmptyStringCheck

---

docs/pages/pmd/languages/java_metrics_index.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedName.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/AbstractJavaMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/api/JavaClassMetricKey.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractJavaClassMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/NoamMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/NopaMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/WocMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/rule/DataClassRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/signature/JavaOperationSignature.java
pmd-java/src/main/resources/rulesets/java/metrics.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractMetricTestRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AllMetricsTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/NoamTestRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/NopaTestRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/WocTestRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/metrics/MetricsRulesTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/NoamTest.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/NopaTest.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/WocTest.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/metrics/xml/DataClass.xml
pmd-java/src/test/resources/rulesets/java/metrics_test.xml

* Added metrics NOPA, NOAM, WOC
* Added detection strategy for Data Class
* AbstractMetricsTestRule is changed to handle double metrics properly
* I added a convenience method to the `Node` interface. I was originally using it then changed my implementation, so it's unused for the moment. This can probably be useful though so I'd be for keeping it

[java] Data class rule

---

pmd-java/src/main/resources/rulesets/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AbstractClassWithoutAnyMethod.xml

Fixes #438 thanks to @oowekyala in #556.

[java] Relax AbstractClassWithoutAnyMethod when class is annotated by @AutoValue

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedMultiProperty.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/EnumeratedProperty.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/modules/EnumeratedPropertyModule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/modules/MethodPropertyModule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/modules/PackagedPropertyModule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/properties/modules/TypePropertyModule.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRule.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/NonRuleWithAllPropertyTypes.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/basic/AvoidUsingHardCodedIPRule.java

[core] Properties refactoring: factorized enumerated property

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/devdocs/metrics_howto.md
docs/pages/pmd/languages/apex_metrics_index.md
docs/pages/pmd/languages/java_metrics_index.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/AbstractMetricsComputer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/AbstractMetricsFacade.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/BasicMetricMemoizer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/BasicProjectMemoizer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/Metric.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricKey.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricKeyUtil.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricMemoizer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricOption.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricOptions.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricsComputer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/ParameterizedMetricKey.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/ProjectMemoizer.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/ResultOption.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/SigMask.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/Signature.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/AtfdMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/NpathMetric.java

Hey,
This is the documentation about writing metrics. Not sure it's the clearest it could be, feel free to give your opinion

[java] Documentation about writing metrics

---

docs/pages/release_notes.md
pmd-java/src/main/resources/rulesets/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/MissingStaticMethodInNonInstantiatableClass.xml

- Remove false positives
- Simplify xpath expression
- Don't use count for checking for `= 0` or `> 0`
- Fixes #590

Improve java-design/MissingStaticMethodInNonInstantiatableClass

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java

[core] Harden XML parsing

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleViolation.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java

[core] Fix NPE on cache

---

pmd-core/src/main/resources/ruleset_2_0_0.xsd
pmd-core/src/main/resources/ruleset_3_0_0.xsd

- Unfortunately DTD doesn't allow to do this... we should probably
cease to support DTD altogether...

[core] Restrict root element of ruleset xml

---

docs/pages/pmd/userdocs/getting_started.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/NoopAnalysisCache.java

- Resolves #608
- Log succesful cache loading / storing
- Log hits / misses on debug, reason for miss too
- Invite users to enable incremental analysis
- Provide a new section on the web for the feature. May be promoted to
a top level page at some point.

[core] Improve incremental analysis logging

---

docs/pages/pmd/userdocs/help.md

[doc] Add the minimal version of "Getting help"

---

pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java

… documentation markdown
Fix #643

[core] Prevent internal dev-properties from being displayed on CodeClimate renderer

---

pmd-core/src/main/resources/rulesets/internal/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/optimizations/RedundantFieldInitializerRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/strings/StringToStringRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/TypeInferenceResolver.java
pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/TypeInferenceTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/AbstractReturnTypeUseCase.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MethodFirstPhase.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MethodGenericParam.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/OverloadedMethodsUsage.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/SubTypeUsage.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/VarArgsMethodUseCase.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/AbstractReturnType.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/GenericSuperType.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/OverloadedMethods.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/ParametrizedSubType.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/SubType.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/SuperType.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/dummytypes/WildcardMethod.java
pmd-java/src/test/resources/net/sourceforge/pmd/coverage/pmd_tests.conf
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codesize/xml/NcssCount.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/optimizations/xml/RedundantFieldInitializer.xml

I was trying to reproduce #650 , no luck yet.
However, I've added the check for parsing/processing errors in PMDCoverageTest, and started to fix some. I'm not finished yet, but wanted to share the current status.
Note: These are all bugs found while analyzing PMD's own code with PMD... 
There are currently 41 processing errors left...

[java] Fix processing errors

---

docs/pages/pmd/rules/apex/performance.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/performance/AvoidSoslInLoopsRule.java
pmd-apex/src/main/resources/rulesets/apex/performance.xml
pmd-apex/src/main/resources/rulesets/apex/ruleset.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/performance/PerformanceRulesTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/AvoidSoslInLoops.xml

[apex] avoid sosl in loops

---

docs/pages/pmd/rules/apex/security.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/AvoidHardcodingIdRule.java
pmd-apex/src/main/resources/rulesets/apex/ruleset.xml
pmd-apex/src/main/resources/rulesets/apex/security.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/SecurityRulesTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/AvoidHardcodingId.xml

[apex] avoid hardcoding id's

---

pmd-java/etc/grammar/Java.jjt
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArrayDimsAndInits.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/VariableNameDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/ArrayTypes.java

- Honor dimensions of arrays
- Resolve types for allocations as well as declarations of arrays

[java] Properly resolve array types

---

pom.xml

- Add `source` & `target` fields to `maven-compiler-plugin`
- Fix deprecated configuration for `antlr4-maven-plugin` and `maven-pmd-plugin`

[core] Add minor fixes to root pom

---

pmd-visualforce/src/main/resources/category/vf/bestpractices.xml
pmd-visualforce/src/main/resources/category/vf/codestyle.xml
pmd-visualforce/src/main/resources/category/vf/design.xml
pmd-visualforce/src/main/resources/category/vf/documentation.xml
pmd-visualforce/src/main/resources/category/vf/errorprone.xml
pmd-visualforce/src/main/resources/category/vf/multithreading.xml
pmd-visualforce/src/main/resources/category/vf/performance.xml
pmd-visualforce/src/main/resources/category/vf/security.xml
pmd-visualforce/src/main/resources/rulesets/vf/rulesets.properties
pmd-visualforce/src/main/resources/rulesets/vf/security.xml
pmd-visualforce/src/test/java/net/sourceforge/pmd/lang/vf/rule/security/SecurityRulesTest.java

[visualforce] Reorganize rules into categories

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/AnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/FileAnalysisCache.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java

[core] Changes to execution classpath invalidate cache

---

pmd-core/pom.xml
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/AbstractNodeTest.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java
pom.xml

Implements: #693: Add remove operation over nodes
**List of changes**
- Add remove & removeChildAtIndex to Node interface
- Implement these methods at AbstractNode.
- Add AbstractNodeTest class with test cases for the implemented methods.
- Add JUnitParams dependency: https://github.com/Pragmatists/JUnitParams
- Implement these test cases using JUnitParams features
- Other changes:
- Fix missing validation on cast for `AbstractJavaRule`

[core] Add remove operation over nodes

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidSlf4jMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidSlf4jMessageFormat.xml

The problem was that the visited expression was in a constructor, not a method
Resolves #721

[java] Fix issue #721 (NPE in InvalidSlf4jMessageFormat)

---

docs/pages/pmd/devdocs/adding_new_language.md
docs/pages/pmd/devdocs/architecture.md
docs/pages/pmd/devdocs/codestyle.md
docs/pages/pmd/devdocs/making_rulesets.md
docs/pages/pmd/devdocs/rule_guidelines.md
docs/pages/pmd/devdocs/testing.md
docs/pages/pmd/devdocs/writing_pmd_rules.md
docs/pages/pmd/userdocs/best_practices.md
docs/pages/pmd/userdocs/understanding_rulesets.md
docs/pages/release_notes.md
pmd-core/src/main/resources/rulesets/internal/all-ecmascript.xml
pmd-core/src/main/resources/rulesets/internal/all-java.xml

[doc] Update documentation to mention categories

---

docs/pages/pmd/userdocs/cpd.md

[doc] Added Apex to supported languages

---

pmd-core/src/main/java/net/sourceforge/pmd/util/ClasspathClassLoader.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java

- Avoid a race condition that could produce multiple threads loading
the same class at the same time.
- Fixed a broken check on PMDASMClassLoader that would always return
false.

[core] Improve classloaders

---

docs/_includes/links.html
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
pmd-doc/src/test/resources/expected/java.md
pmd-doc/src/test/resources/rulesets/ruledoctest/sample-deprecated.xml

[doc] Two fixes for rule index and automated links generation

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/OptimizableToArrayCall.xml

Part of #709 
See https://sourceforge.net/p/pmd/bugs/1454/
and https://shipilev.net/blog/2016/arrays-wisdom-ancients/

[java] Update OptimizableToArrayCall rule for current JVMs

---

docs/pages/pmd/devdocs/adding_metrics_support_to_language.md
docs/pages/pmd/devdocs/metrics_howto.md

Many things were outdated, including broken links. I removed references to the inners of the multifile framework, since it's not helpful and subject to change.

[doc] Update metrics documentation pages

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractJavaClassMetric.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/DataClass.xml

[java] Fix #785: NPE with metrics on empty declarations

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

[apex] Method chaining breaks ApexCRUDViolation

---

docs/pages/pmd/userdocs/getting_started.md
docs/pages/pmd/userdocs/tools/ant.md
docs/pages/pmd/userdocs/tools/maven.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cache/NoopAnalysisCache.java

[doc] Improve incremental analysis docs

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
pmd-core/src/test/resources/rulesets/dummy/empty-ruleset.xml

Remove wrong deprecation warning for empty category

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ForLoopCanBeForeachRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ForLoopCanBeForeach.xml

- Take the chance to make this rule use the rulechain
- This fixes partially #800, but the FN is still unhandled

[java] Avoid NPE in ForLoopCanBeForeachRule

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryModifierRule.java

[java] Fix NPE on UnnecessaryModifierRule

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionUpper.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/PmdStackOverflow.java

[java] Resolve StackOverflow in JavaTypeDefinitionSimple.toString()

---

docs/pages/release_notes.md
pmd-java/src/main/resources/rulesets/java/typeresolution.xml

[java]  typeresolution points directly to categories

---

pmd-java/src/main/resources/category/java/performance.xml

I added a note about UseArraysAsList, which should IMHO be mentioned, as Arrays.asList(..) is not exactly equivalent to the original code. I hope I made my point clear.
Feel free to rephrase it if you like (hopefully I didn't make many typos).

[java] UseArraysAsList: Description added

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/main/resources/category/java/performance.xml

This pull request adds some notes about methods that have been deprecated since JDK 9.
Feel free to change the phrasing in any way you see fit.

[java] Added some comments for JDK 9

---

docs/pages/pmd/userdocs/similarprojects.md

Added SpotBugs as successor of FindBugs.

[doc] Added SpotBugs as successor of FindBugs

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/NcssTypeCountRule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/AtfdBaseVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentInOperandRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringInstantiationRule.java

One method name had a typo, we should remove it in 7.0.0
Replace unchecked casts with dynamic casts

[core] Cleanup AbstractNode

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java

[java] Fix misconfiguration detection

---

.travis/build-deploy.sh
pom.xml

- Reenable pmd dogfoding
- Upgrade to use PMD 6.0.1 on self

[ci] Upgrade m-pmd-p

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/CurrentPath.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricOptions.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidBranchingStatementAsLastInLoopRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/xpath/MetricFunction.java
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/MainDesignerController.java

... to 0  in Collections classes.

[core] Use the isEmpty method instead of comparing the value of size() to 0

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml

*   Updated documentation to include also non-string literals
*   Added additional test cases
*   Fixes #541

[java] ConsecutiveLiteralAppends with types other than string

---

pmd-core/src/main/java/net/sourceforge/pmd/properties/builders/MultiNumericPropertyBuilder.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/AbstractPropertyDescriptorTester.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/BooleanPropertyTest.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/FloatPropertyTest.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/LongPropertyTest.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/SimpleEnumeratedPropertyTest.java

Ensures the build cannot crash like in #918 anymore

[core] Fix non-deterministic property tests

---

pmd-java/src/main/resources/category/java/design.xml

Hi Team,
When I'm testing about PMD's features, found broken example code in the documentation. This pr makes correct it :)

[java][doc] Fix example of AbstractClassWithoutAnyMethod

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ImportWrapper.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/ClassWithConstants.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml

[java] UnusedImports false positive for static import

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml

[java] UnusedPrivateField false-positive with @FXML 

---

docs/pages/pmd/userdocs/suppressing_warnings.md

Issue 959: fixed broken link to XPath Rule Tutorial

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractLombokAwareRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UseUtilityClassRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UseUtilityClass.xml

[java] Issue 968 Add logic to handle lombok private constructors with utility classes

---

docs/pages/pmd/rules/java/design.md
pmd-java/src/main/resources/category/java/design.xml

I Updated Doc on AvoidThrowingNullPointerException to close Issue #832

[java] Updated Doc on AvoidThrowingNullPointerException to close Issue #832

---

CONTRIBUTING.md

An update to Contibute.md to close Issue #978

[core] Update Contribute.md to close Issue #978

---

docs/pages/pmd/devdocs/writing_documentation.md

Update writing_documentation.md to fix Issue #992

[core] Update writing_documentation.md to fix Issue #992

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/MethodLikeNode.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java

[java] Add getPrintableName to MethodLikeKind

---

docs/pages/pmd/userdocs/tools/maven.md

Documentation: fix closing tag for `<pmdVersion>`

[core] DOC: fix closing tag for <pmdVersion>

---

pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/SimpleRegexSyntaxHighlighter.java
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/ApexSyntaxHighlighter.java
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/HighlightClasses.java
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/JavaSyntaxHighlighter.java
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/XPathSyntaxHighlighter.java
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/css/editor-theme.css

In particular, the XPath syntax highlighter was bugged (eg didn't recognise comments, lacked many keywords) and what it did tokenize correctly was not styled very well

[ui] Improvements to designer syntax highlighting

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java

[core] Ignore missing files form auxclasspath

---

docs/pages/pmd/rules/java/codestyle.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryConstructorRule.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryConstructor.xml

Resolves #1003 
Rewriting UneccessaryConstructorRule into java rule

[java] UnnecessaryConstructor triggered on required empty constructor (Dagger @Inject)

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitAssertionsShouldIncludeMessageRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitAssertionsShouldIncludeMessage.xml

[java] JUnitAssertionsShouldIncludeMessage - False positive with assertEquals and JUnit5

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UselessParentheses.xml

[java] False positive for useless parenthesis

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/JavaTypeDefinitionToStringNPE.java

- Resolves #894 
- Resolves #899

java] Prevent NPEs during `JavaTypeDefinitionSimple.toString`

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidUsingShortType.xml

[java] AvoidUsingShortType erroneously triggered on overrides of 3rd party methods

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/InsecureCryptoIvRule.java
pmd-java/src/main/resources/category/java/categories.properties
pmd-java/src/main/resources/category/java/security.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/security/SecurityRulesTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/security/xml/InsecureCryptoIv.xml

Hi folks,
This rule reports hard coded IVs in crypto operations.
I'm hoping to add a few more rules for bad usage of crypto in Java.
Cheers,
Sergey

[java] New security rule: report usage of hard coded IV in crypto operations

---

pom.xml

closes #1061 
This should bring ASM to a version that supports Java 10.

[core] Update ASM to version 6.1.1

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryConstructor.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml

[java] Property ignoredAnnotations does not work for SingularField and ImmutableField

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedNameTest.java

[java] Fix lambda qname in enum constants

---

docs/pages/release_notes.md
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java

[doc] Add header before XPath expression in docs

---

pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/donotextendjavalangerror/Error.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/DoNotExtendJavaLangError.xml

**PR Description**
Fixes #1021

[java] Fixes false positive for `DoNotExtendJavaLangError`

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java

* isFindBoundary didn't return true for local classes (Java)
* hasImageEqualTo didn't consider the case where both comparands are null (core)
* Add some doc on the node interface and fix some javadoc warnings

[core] Minor bug fixes on Node methods and doc

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/InsecureCryptoIvRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/security/xml/InsecureCryptoIv.xml

Found this one while testing with PMD against openjdk sources

 [java] Fix NPE in InsecureCryptoIvRule

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java
pmd-core/src/main/java/net/sourceforge/pmd/util/log/AntLogHandler.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java

- Very ugly, uses reflection and is limited to the few
implementatations that come with Ant itself and testutils
- Intended as a starting point for fixing #1018

[core] Honor Ant's log level

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/LocalGenericClass.java

While testing PMD against openjdk / spring sources, I found this NPE.
Any ideas?
The problem seems to be, to find the correct method for the method call `accept(other.state);`, which is within the same class.
And it is a local scoped class...
Original source: It was somewhere deep in the JDK sources, actually `java.util.stream.ReduceOps` (which is package private class).

[java] Parser Error / Nullpointer when analyzing local generic class

---

pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ShortVariable.xml

[java] ShortVariable should whitelist lambda parameters 

---

pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java

[core] Fix JCommander help for -min option

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] Fix star import overwritten by explicit import not correctly handled

---

do-release.sh

Automate a couple of extra steps and cleanup

[ci] Release improvements

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/IdenticalCatchBranches.xml

[java] Fix IdenticalCatchBranches false positive

---

docs/pages/release_notes.md
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTNumberLiteral.java
pmd-javascript/src/main/resources/category/ecmascript/errorprone.xml
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/rule/errorprone/xml/InnaccurateNumericLiteral.xml

 [ecmascript] InnaccurateNumericLiteral false positive with hex literals

---

docs/pages/pmd/rules/java/performance.md
pmd-java/src/main/resources/category/java/performance.xml

- [ ] `./mvnw pmd:check` passes.
Typo in one of the java rules.

[java] fixed typos in rule remediation

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/DocumentNavigator.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/NodeIterator.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/AttributeAxisIterator.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/AttributeNode.java
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/NodeInfoPanelController.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlNodeWrapper.java

At some point I think it would be best to merge the AttributeNode interface into the Node interface.

[xml] Fix Saxon not reading xml DOM attributes

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java

[core] Fix broken concatenation on CPD GUI

---

pmd-dist/src/main/scripts/designer.bat
pmd-dist/src/main/scripts/run.sh
pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/DesignerStarter.java

Alternative to #1146. It shows a simple message dialog.
It should work for Windows, too, but I didn't test it...

[ui] Designer javafx check

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NcssCountRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/NcssCount.xml

Fix #1200 
I think now, that constraining the values of properties within a bounded range is not cool. I'll open a ticket for that

[java] Prop up Ncss report levels, allow greater configurability

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAssertStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTConditionalExpression.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTForStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/CycloMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/CycloBaseVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/CycloPathAwareDecorator.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/CycloTest.xml

[java] Fix cyclo miscounting ternaries

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

Fix #1216 
I added some comments on ASTImportDeclaration, I think we should consider making it a non-TypeNode

[java] Fix unnecessaryFQCN false positive with import-on-demand

---

docs/pages/pmd/userdocs/installation.md

Additionnally --> Additionally changed only.

[doc] Minor typo fix in installation.md

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ViewTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ViewIssue981.pls

[plsql] plsql.ast.ParseException when parsing VIEW

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediateTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediate1047a.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediate1047b.pls

[plsql] plsql.ast.ParseException when parsing EXECUTE IMMEDIATE

---

pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/UniformStyleCollection.java
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/designer.fxml
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/editor.fxml
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/node-info.fxml
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/constants.less
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/designer.less
pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/editor-theme.less

Less adds a nice structure to the stylesheets, I think they're much easier to grok now. I also pruned some dead rules, although I didn't review everything in depth.

[ui] Convert designer stylesheets to Less

---

docs/pages/release_notes.md
pmd-dist/src/main/scripts/run.sh

while detecting installed version of Java
Fixes #1225

Fixes #1225 [core] Error in sed expression on line 82 of run.sh

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/util/log/AntLogHandler.java

[core] "Unsupported build listener" in gradle build

---

pmd-jsp/etc/grammar/JspParser.jjt
pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/JspParserTest.java

Adding support to EL in tag attributes.
Resolves https://github.com/pmd/pmd/issues/1274

[jsp] Issue #1274 - Support EL in tag attributes

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/devdocs/pmdtester.md

This document briefly introduces pmdtester and how to run it locally.

[docs] [GSoC] Create the documentation about pmdtester

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaTypeQualifiedName.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameFactory.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java

Changelog:
* The classloader is now final in TypeQualifiedNames
* The QualifiedNameResolver now shares qualified name lists across threads

[java] Small improvements to Java qualified names

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLiteral.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/RedundantFieldInitializer.xml

[java] RedundantFieldInitializer - NumberFormatException with Long

---

docs/pages/release_notes.md
pmd-java/etc/grammar/Java.jjt
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRSIGNEDSHIFT.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRUNSIGNEDSHIFT.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTShiftExpression.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaParserDecoratedVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaParserVisitorAdapter.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaParserVisitorDecorator.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java

This is on the checklist for #1019

[java] Deprecate R[UN]SIGNEDSHIFT

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LinguisticNamingRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LinguisticNaming.xml

[java] LinguisticNaming - make tranform method names configurable

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/bestpractices.xml

[java] Remove no longer used property

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LinguisticNamingRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LinguisticNaming.xml

[java] LinguisticNaming should support AtomicBooleans

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/ConsecutiveLiteralAppendsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml

[java] False positive in ConsecutiveLiteralAppends

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingSerialVersionUID.xml

[java] MissingSerialVersionUID false-positive on interfaces

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingSerialVersionUID.xml

[java] MissingSerialVersionUID false-negative with abstract classes

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryModifierRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryModifier.xml

[Java] Static Modifier on Internal Interface pmd #1356

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaAnnotatableNode.java

While making change for #1374 I noticed `TypeHelper.isA` may throw an NPE if `getFirstDescendantOfType` returns null.
`mvnw test` failed on master for me so I wasn't able to run in.

[java] Add missing null check AbstractJavaAnnotatableNode

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaTypeQualifiedName.java

attribute in method that is not native or abstract in class file
javax/xml/ws/Service
Fixes #1330

[java] PMD crashes with java.lang.ClassFormatError: Absent Code

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] fix FN on same package FQCN usage

---

docs/pages/release_notes.md
pmd-dist/src/main/scripts/run.sh

[core] Allow symlinking run.sh

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/HardCodedCryptoKeyRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/InsecureCryptoIvRule.java

- Thanks to https://github.com/pmd/build-tools/pull/10

[java] Fix the rulechain usage

---

pmd-jsp/etc/grammar/JspParser.jjt

[jsp] Fix issue 1402: JspTokenManager has a problem about jsp scriptlet

---

docs/pages/pmd/userdocs/cpd.md

[doc] Fix broken link. Fixes #1412

---

docs/pages/pmd/userdocs/cli_reference.md
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java

This PR adds basic functionality to allow a command line ignore file.
This PR documents the new cli option to ignore a list of files.
This fixes #649

[core] Add ignore file path functionality

---

pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
pmd-doc/src/test/resources/expected/sample.md
pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml

[doc] #1341 Updating Regex Values in default Value Property 

---

docs/pages/pmd/userdocs/suppressing_warnings.md

[doc] Who really knows regex?

---

pmd-java/src/main/resources/category/java/design.xml

[java] Fix broken link in CyclomaticComplexity 

---

pmd-java/src/main/resources/category/java/design.xml

[java] 1151: Rephrase ImmutableField documentation in design.xml

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/PLSQLParserTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/CaseIssue1454.pls

[plsql] ParseException for IF/CASE statement with >=, <=, !=

---

docs/pages/release_notes.md
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/metrics/impl/AbstractApexMetricTestRule.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/EnumeratedMultiProperty.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/EnumeratedProperty.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/GenericMultiValuePropertyDescriptor.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyBuilder.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/properties/ValueParserConstants.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRule.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/PropertyDescriptorTest.java
pmd-core/src/test/java/net/sourceforge/pmd/properties/SimpleEnumeratedPropertyTest.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NcssCountRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidBranchingStatementAsLastInLoopRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractMetricTestRule.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/EcmascriptParserOptions.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/rule/AbstractEcmascriptRule.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/rule/EcmascriptXPathRule.java

[core] Deprecate enumerated properties

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/SelectExpressionsTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectCount.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectExpressions.pls

[plsql] Parse Exception when using SELECT COUNT(*)

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/JoinClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/FullOuterJoin.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/InnerJoinSubquery.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/InnerNaturalJoin.pls

[plsql] Parse Exception with OUTER/INNER Joins

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/IsNull.pls

[plsql] Parse Exception with IS NOT NULL

---

pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/UseDiamondOperator.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseDiamondOperator.xml

[java] This is the change regarding the usediamondoperator #1517

---

pmd-doc/src/main/java/net/sourceforge/pmd/docs/DeadLinksChecker.java

- Do a HEAD request instead of a GET
- Some minor code simplifications

[doc] Improve deadlink detection

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclaration.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclarationTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/testdata/InterfaceWithNestedClass.java

[java] Private field is detected as public inside nested classes in interfaces

---

pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ParserTstUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java

Some piece of work I cherry picked out of #1566

[java] Share utilities defined in ClassTypeResolverTest

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpression.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpressionExamples.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpressionIssue1526.pls

Fixes #1526
Also adding InsertStatement
Once #1554 is merged, I'll rebase this one. They both touch the UpdateStatement.

[plsql] ParseException when using TableCollectionExpression

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/Base.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml

Updated SEE_PATTERN regex pattern.
Fixes #1555

[java] UnusedImports false positive for method parameter type in @see Javadoc

---

pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseDiamondOperator.xml

Also includes Minor Correction in one test case. Do check if the test cases are correct and if any test case is missing.
fixes #1624

[java] UseDiamondOperator doesn't work with var

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/AntlrTokenizer.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/JavaCCTokenizer.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/internal/JavaCCTokenizer.java
pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPTokenizer.java
pmd-cpp/src/test/java/net/sourceforge/pmd/cpd/CPPTokenizerContinuationTest.java
pmd-cpp/src/test/java/net/sourceforge/pmd/cpd/CPPTokenizerTest.java
pmd-cpp/src/test/resources/net/sourceforge/pmd/cpd/cpp/issue-1559.cpp
pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/JavaTokensTokenizerTest.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/MatchAlgorithmTest.java
pmd-javascript/src/main/java/net/sourceforge/pmd/cpd/EcmascriptTokenizer.java
pmd-matlab/src/main/java/net/sourceforge/pmd/cpd/MatlabTokenizer.java
pmd-objectivec/src/main/java/net/sourceforge/pmd/cpd/ObjectiveCTokenizer.java
pmd-plsql/src/main/java/net/sourceforge/pmd/cpd/PLSQLTokenizer.java
pmd-python/src/main/java/net/sourceforge/pmd/cpd/PythonTokenizer.java

[core] CPD: Lexical error in file (no file name provided)

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpressionTest.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseSubqueries.pls

[plsql] ParseException with subqueries in WHERE clause

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/main/ant/alljavacc.xml
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTRegexpLikeCondition.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseExists.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseMultiset.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseRegexpLike.pls

Fixes #1587
Also adds support for multiset conditions and regexp_like condition in where clause.

[plsql] Parse Exception with EXISTS

---

docs/pages/release_notes.md
pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/MockedFileWriter.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleDocGeneratorTest.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java

[core] Failed build on Windows with source zip archive

---

docs/pages/pmd/userdocs/suppressing_warnings.md

This will fix the issue #1671 
Replaced `&gt;` with `>`

[doc] Replaced wrong escaping with ">"

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java

We took the oportunity to add some missing final modifiers into [AbstractNode](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java) while we were trying to understand the usages of Node and Parser.

[core] Add final modifiers into AbstractNode

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/DetachedTestCaseTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DetachedTestCase.xml

Add a rule to detect methods that probably should be annotated with `@Test`. This can happen by mistake while refactoring or while migrating from JUnit3 to JUnit4 or JUnit5.

[java] Add DetachedTestCase rule

---

docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md

As promised, we updated the CPD documentation, to make it easier for future contributors to add new Antlr languages to the project, as we did with Kotlin, Go and Swift.
Team Raptor

[doc] Update CPD documentation

---

pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/codestyle/xml/MethodNamingConventions.xml
pmd-java/pom.xml
pmd-lang-test/pom.xml
pmd-test/pom.xml
pom.xml

* Fix test in pmd-apex (MethodNamingConventionsTest in apex was the only test, that has not been executed...)
* Upgrade surefire and test enginges. This is necessary, so that errors during test initialization are reported as test failure and are not silently ignored...

Upgrade surefire and junit test engine

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/CursorAttributesTest.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/IfStatementTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/CursorAttributes.pls

[plsql] Fix parse problems (elsif, cursor attribute)

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseUnderscoresInNumericLiterals.xml

[java] UseUnderscoresInNumericLiterals false positive on floating point numbers

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolationTest.java

[java] Report class name for package-private only classes

---

docs/pages/pmd/devdocs/pmdtester.md
docs/pages/pmd/projectdocs/credits.md
docs/pages/pmd/userdocs/configuring_rules.md
docs/pages/pmd/userdocs/cpd.md
docs/pages/pmd/userdocs/incremental_analysis.md

I only fixed some small typo errors in the docs.

[doc] Fixed some errors in docs

---

docs/pages/release_notes.md
pmd-go/src/main/antlr4/net/sourceforge/pmd/lang/go/antlr4/Golang.g4
pmd-go/src/test/java/net/sourceforge/pmd/cpd/EdgeCasesTokenizerTest.java
pmd-go/src/test/resources/net/sourceforge/pmd/cpd/issue1751.go

[go] Fix grammar handling of escape sequences

---

pmd-dart/pom.xml
pmd-dart/src/main/antlr4/net/sourceforge/pmd/lang/dart/antlr4/Dart2.g4
pmd-dart/src/main/java/net/sourceforge/pmd/cpd/DartLanguage.java
pmd-dart/src/main/java/net/sourceforge/pmd/cpd/DartTokenizer.java
pmd-dart/src/main/resources/META-INF/services/net.sourceforge.pmd.cpd.Language
pmd-dart/src/test/java/net/sourceforge/pmd/cpd/DartTokenizerTest.java
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/comment.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/imports.dart
pmd-dart/src/test/resources/net/sourceforge/pmd/cpd/increment.dart
pmd-dist/pom.xml
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pom.xml

This is a pull request for the addition of Dart support for CPD. This does not include full PMD support, so it can only be used to check for code duplication.

[dart] [cpd] Added CPD support for Dart

---

pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/NoPackage.xml

- Also make it's search much more precise, making it 10X faster

[java] Fix NoPackage rule for enums

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java

[java] Show more detailed message when can't resolve field type

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java

[java] Fix NPE in type resolution

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryLocalBeforeReturn.xml

[java] Fix FN in UnnecessaryLocalBeforeReturn

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/JavaNameOccurrence.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/OccurrenceFinder.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedLocalVariable.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml

- Concise resources are valid usages.
- Fixes #1190

[java] Have symbol table recognize concise resources

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactoryCompatibility.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryCompatibilityTest.java
pmd-core/src/test/resources/rulesets/dummy/oldbasic.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/PMD5RulesetTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/pmd5ruleset.xml

[core] Ruleset Compatibility fails with excluding rules

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractSunSecureRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml

MethodReturnsInternalArray does not work in inner classes #1738 - Fixed

[java] MethodReturnsInternalArray does not work in inner classes - Fixed #1738

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryLocalBeforeReturn.xml

[java] Fix NPE in UnnecessaryLocalBeforeReturnRule

---

.travis/build-deploy.sh

[ci] Fix missing local branch issues when executing pmd-regression-tester

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java
pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java

Added small minor performance improvements.

[core] Minor performance improvements

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FieldNamingConventions.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentRequired.xml

[java] Whitelist serialPersistentFields

---

pmd-java/etc/grammar/Java.jjt
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclaration.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceDeclarationTest.java

[java] Preserve local class modifiers

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseParens.pls

[plsql] Parentheses stopped working

---

docs/pages/pmd/userdocs/tools/ant.md

* Add installation section
* Update supported sourceLanguages and improve description
when this is needed
* Add full build.xml example with auxclasspath configuration
refs #1861, refs #1870

(doc) Improve documentation for ant task

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UseUtilityClassRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UseUtilityClass.xml

* Make the rule UseUtilityClass LombokAware
* Fixes #1094

 [java] Make UseUtilityClass LombokAware

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/UpdateStatementExample2.pls

[plsql] Add parenthesis equation support for Update

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectExpressions.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseParens.pls

I made a refactor to the tree because IsOfTypeCondition was inside IsNullCondition.

[plsql] Fix #1873 Expression list not working

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/NonStaticInitializer.xml

[java] Fix NonStaticInitializer FP in anonymous classes

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTSelectStatement.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/JoinClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/LeftOuterJoin.pls

[plsql] Fix JoinClause preceded by subquery

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml

[java] CommentDefaultAccessModifier: add new property "checkTopLevelTypes"

---

docs/pages/release_notes.md
pmd-doc/pom.xml
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleTagChecker.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleTagCheckerTest.java
pmd-doc/src/test/resources/ruletagchecker/docs/pages/pmd/rules/java/bestpractices.md
pmd-doc/src/test/resources/ruletagchecker/docs/pages/ruletag-examples.md

Fixes #1896
This adds a RuleTagChecker, that is executing in the pmd-docs module and will fail the build if
* a rule tag is not closed properly
* a rule tag references a rule, that doesn't exist

[doc] Error in changelog 6.16.0 due to not properly closed rule tag

---

pmd-dist/pom.xml
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-lua/pom.xml
pmd-lua/src/main/antlr4/net/sourceforge/pmd/lang/lua/antlr4/Lua.g4
pmd-lua/src/main/java/net/sourceforge/pmd/cpd/LuaLanguage.java
pmd-lua/src/main/java/net/sourceforge/pmd/cpd/LuaTokenizer.java
pmd-lua/src/main/resources/META-INF/services/net.sourceforge.pmd.cpd.Language
pmd-lua/src/test/java/net/sourceforge/pmd/cpd/LuaTokenizerTest.java
pmd-lua/src/test/resources/net/sourceforge/pmd/cpd/factorial.lua
pmd-lua/src/test/resources/net/sourceforge/pmd/cpd/helloworld.lua
pom.xml

This is a pull request for the addition of Lua support for CPD. This does not include full PMD support, so it can only be used to check for code duplication.
The tokenizer uses an ANTLR4 grammar based on the one at https://github.com/antlr/grammars-v4/tree/master/lua.

 [lua] [cpd] Added CPD support for Lua

---

pmd-xml/src/main/resources/category/xml/errorprone.xml
pmd-xml/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java

Fixes #1666 
Fixed description. Example section needs clarifying, though

[xml] fix #1666 wrong cdata rule description and examples

---

docs/pages/release_notes.md
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
pmd-doc/src/test/resources/expected/sample.md
pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml
pmd-java/src/main/resources/category/java/bestpractices.xml

[doc] Escape code examples for liquid with {%raw%}

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/UnsynchronizedStaticFormatter.xml

[java] Fix false positive with UnsynchronizedStaticFormatter when using allowMethodLevelSynchronization

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

[java] Exclude ByteArrayInputStream from CloseResource

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/VariableAccessVisitor.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DataflowAnomalyAnalysis.xml

- [v] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
- [v] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)
Fixes   #1749, I checked this issue and I fixed as follows. Please, review this Pull Request
- Added a logic that could make DataflowAnomlayAnalysis Rule check codes in right order.
- When assignment is occurred between same varaibles, it read left to right without caring of the precedence. In my opinion, it would make a many DD False Positive. Therefore, I added the logic which could check and swap …

[java] DataflowAnomalyAnalysis Rule in right order

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/AtfdBaseVisitor.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/AtfdTest.xml

* Fixes #1910
* Method call chains are now considered

[java] ATFD calculation problem

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/TypeNode.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryfullyqualifiedname/TestClass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryfullyqualifiedname/subpackage/MyClass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] Fix unnecessary FQCN false positive

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/closeresource/Statement.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

* Fixes #1922 
* Fixes #1966 
* Fixes #1967 
These are the FPs found in PR #1955 .

[java] Fix Close resource false positives

---

pmd-java/src/main/resources/category/java/bestpractices.xml

Updated documentation to make the example compile (there is no varargs version of addAll(..))

[java] DoubleBraceInitialization: Fix example

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleMapper.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/CachedRuleViolation.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/FileAnalysisCacheTest.java

[core] Fix handling of cached XPath rule violations

---

pmd-core/etc/xslt/pmd-report.xslt

Fixes #1465 
Adopted the best alternative given by @jsotuyod

[core] Resolve pmd-report failure when java folder in filepath

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/SelectForUpdateTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectForUpdateWait.pls

Fixes #1947
Added FOR UPDATE OF clause

[plsql] ParseError - SELECT with FOR UPDATE OF

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/TrimWithRecordTypeTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/TrimWithRecordType.pls

[plsql] TRIM function with record type variables

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeResolutionFacade.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/TypeDefinition.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/Bound.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/BoundOrConstraint.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/Constraint.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/InferenceRuleType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/TypeInferenceResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/Variable.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/visitors/PMDASMVisitor.java

[java] Mark typeres implementation as internal API

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] Fix FP in UnnecessaryFullyQualifiedName when accessing static methods / inner classes

---

pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java

[core] Log wrong include/exclude patterns

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java

Allows adding SourceCode objects directly into CPD. This is useful for projects that use custom file systems that do not work with the Java File API. Users of these systems can create a StringCodeLoader to create a SourceCode, and pass that SourceCode object into CPD.
Fixes #2014

[core] Allow adding SourceCode directly into CPD

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/benchmark/Benchmarker.java
pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDTask.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/EmacsRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/IDEAJRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextPadRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/VBHTMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/XSLTRenderer.java
pmd-core/src/main/java/net/sourceforge/pmd/util/FileUtil.java
pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/DataSource.java
pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/FileDataSource.java
pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/ReaderDataSource.java
pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/ZipDataSource.java
pmd-core/src/main/java/net/sourceforge/pmd/util/datasource/internal/AbstractDataSource.java
pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java
pmd-core/src/test/java/net/sourceforge/pmd/processor/MultiThreadProcessorTest.java
pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPTokenizer.java
pmd-test/src/main/java/net/sourceforge/pmd/AbstractLanguageVersionTest.java
pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java
pmd-test/src/main/java/net/sourceforge/pmd/cli/BaseCLITest.java
pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/AbstractVmNode.java
pom.xml

There seem to be some false positives for the CloseResource rule...
We'll have to verify these, before merging...

dogfood: Upgrade to PMD 6.18.0 and fix CloseResource issues

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ImportWrapper.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml

[java] Fix false positive in UnusedImports when using FQCN in @see or @link

---

pmd-java/src/main/resources/category/java/multithreading.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/DoNotUseThreads.xml

[java] DoNotUseThreads should not warn on Runnable #1627

---

docs/pages/pmd/languages/java_metrics_index.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/api/JavaClassMetricKey.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/api/JavaOperationMetricKey.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/ClassFanOutMetric.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/internal/CfoVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/internal/ClassFanOutVisitor.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/AllMetricsTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/impl/CfoTestRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/CfoTest.xml
pmd-java/src/test/resources/rulesets/java/metrics_test.xml

I'd like to add a new Java Metric, the ClassFanOutComplexity. It counts the number of other classes a given class or operation relies on.
It is inspired by the same [Checkstyle Metric](https://checkstyle.sourceforge.io/config_metrics.html#ClassFanOutComplexity).

[java] Add Metric ClassFanOutComplexity 

---

docs/pages/pmd/userdocs/making_rulesets.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
pmd-core/src/test/java/net/sourceforge/pmd/junit/JavaUtilLoggingRule.java
pmd-core/src/test/resources/rulesets/dummy/basic.xml

This PR fixes #1978 and fixes #2082 
It does **not** fix the issues / PRs #2006  / #2059 

[core] Improve logging of deprecated/renamed rules and non-existing excluded rules

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/Parser.java

[core] Deprecate Parser#getSuppressMap

---

pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDCommandLineInterface.java
pmd-core/src/main/java/net/sourceforge/pmd/processor/AbstractPMDProcessor.java

- `PMD.java`
- Use now public `PMDCommandLineInterface.NO_ERRORS_STATUS` for status 0
- Add some private methods to improve readability (like obtaining a new file processor) or encouragement to use incremental analysis
- For `getApplicableLanguages` invert if condition inside loop to avoid `continue` keyword
- `SourceCodeProcessor.java`
- Add some private methods to improve readability (e.g. attempt to use cache or process source code)

[core] Minor unrelated improvements to code

---

.travis.yml

Switches directly from trusty to bionic, skipping xenial.
See https://docs.travis-ci.com/user/reference/linux/ for available versions.

[ci] Update to bionic on travis

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/devdocs/rule_deprecation.md
docs/pages/pmd/userdocs/extending/rule_deprecation.md

This tries to pin down the rule deprecation policy we want to have.
This would allow us to tackle cases such as #2064 (moving rule to a different category).
Let me know, what you think!

[doc] Rule deprecation policy

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml

[java] ImmutableField false positive with inner class

---

docs/pages/pmd/projectdocs/trivia/products.md
docs/pages/pmd/userdocs/extending/writing_pmd_rules.md
docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
docs/pages/release_notes.md
docs/pages/release_notes_old.md

[doc] Issue with http://pmdapplied.com/ linking to a gambling Web site

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java
pmd-core/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/ant/src/sample.dummy
pmd-core/src/test/resources/net/sourceforge/pmd/ant/xml/pmdtasktest.xml
pmd-core/src/test/resources/rulesets/dummy/basic.xml

[core] Shortnames parameter does not work with Ant

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryfullyqualifiedname/subpackage/MyAnnotation.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] UnnecessaryFullyQualifiedName: regression / false positive

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTSoqlExpression.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTSoqlExpressionTest.java

[apex] Provide access to underlying query of SoqlExpression

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitAssertionsShouldIncludeMessageRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitAssertionsShouldIncludeMessage.xml

[java] Fix false-positive in JUnitAssertionsShouldIncludeMessage

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryLocalBeforeReturnRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryLocalBeforeReturn.xml

[java] Fix false positive in UnnecessaryLocalBeforeReturn with method references

---

pmd-modelica/pom.xml
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ast/ASTClassDefinition.java
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ast/ASTElementList.java
pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ast/ASTStoredDefinition.java
pmd-modelica/src/main/resources/category/modelica/bestpractices.xml
pmd-modelica/src/test/resources/net/sourceforge/pmd/lang/modelica/rule/bestpractices/xml/AmbiguousResolution.xml

[modelica] Follow-up fixes for Modelica language module

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleReference.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryDuplicatedRuleLoggingTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/rulesets/duplicatedRuleLoggingTest/duplicatedRuleReference.xml
pmd-core/src/test/resources/net/sourceforge/pmd/rulesets/duplicatedRuleLoggingTest/duplicatedRuleReferenceWithOverride.xml
pmd-core/src/test/resources/net/sourceforge/pmd/rulesets/duplicatedRuleLoggingTest/duplicatedRuleReferenceWithOverrideBefore.xml
pmd-core/src/test/resources/net/sourceforge/pmd/rulesets/duplicatedRuleLoggingTest/multipleDuplicates.xml

Fixes #2006
This PR makes #2059 obsolete.

[core] Add warnings for duplicated rule references in rulesets

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAssertStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTConditionalExpression.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTDoStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFinallyStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTForStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTIfStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTryStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTWhileStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTYieldStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/internal/CycloVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java

Deprecations prerequisite to #2164

[java] Deprecations for statements PR 

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/DeprecatedAttribute.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/internal/DeprecatedAttribute.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNodeWithDeprecatedAttribute.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIteratorTest.java

[core] Deprecated Node#isFindBoundary for XPath

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelperTest.java

Fix #2268 
This should normally help https://github.com/pmd/pmd/issues/1668#issuecomment-582546356

[java] Improve fallback strategy of TypeHelper

---

CONTRIBUTING.md
README.md

[doc] Update support channels

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTElseWhenBlock.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTEmptyReferenceExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTIdentifierCase.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTLiteralCase.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTSwitchStatement.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTTypeWhenBlock.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTValueWhenBlock.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParserVisitor.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParserVisitorAdapter.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRule.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTSwitchStatementTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/ast/SwitchStatements.cls

[apex] Add support for SwitchStatement

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MisplacedNullCheck.xml

* Upgrade to XPath 2.0
* Extend test cases
* Report on variable that is being null check and
improve violation message. Due to this change, I expect many new and removed violations from the regression test tool.
Fixes #2242

[java] MisplacedNullCheck - fix false positive

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereCurrentOf.pls

As in title: parsing of WHERE CURRENT OF in UPDATE statement and simple test case

[plsql] Parsing of WHERE CURRENT OF added

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediateTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediateString.pls

Fixed and turned on (I think it was parsed by SqlStatement production before) Execute Immediate statement parsing.

[plsql] Fixed Execute Immediate statement parsing

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/MultipleDDLStatementsTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/DDLCommands.sql

Small fix in Comment statement with test case.
Ending comment without ";", but with "/" is accepted by SQLPlus
Also removed not needed productions (CursorSpecification, ...) and reformat some code.

[plsql] Fix in Comment statement

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeBodyDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractTypeBodyDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractInefficientZeroCheck.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractPoorMethodCall.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringToStringRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/VariableNameDeclaration.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14PreviewTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MissingOverride.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientEmptyStringCheck.xml
pmd-test/src/main/resources/rule-tests_1_0_0.xsd

This fixes some processing errors when executing rules for java 14.

[java] Fix Java14 processing errors

---

pmd-xml/src/main/resources/category/pom/errorprone.xml

This fixes the example on the following doc page:
https://pmd.github.io/latest/pmd_rules_pom_errorprone.html#projectversionasdependencyversion

[xml] Update property used in example

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml
pom.xml

Updating This rule to support the new feature 'WITH SECURITY_ENFORCED'.  To learn more about this feature go to (https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_with_security_enforced.htm).
This fixes #2210.

[apex] Update ApexCRUDViolation Rule

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new_rule.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/rule_violation.md

Refs #2249
Note: this sets "blank_issues_enabled: false", so that one is forced to select a template.

[doc] Add github issue templates

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/Parser.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/TokenManager.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractTokenManager.java

[core] Deprecations for token managers

---

docs/pages/pmd/userdocs/incremental_analysis.md
docs/pages/release_notes.md

Fixes #2355
Preview: https://github.com/adangel/pmd/blob/issue-2355/docs/pages/pmd/userdocs/incremental_analysis.md

[doc] Improve documentation about incremental analysis

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/projectdocs/committers/main_landing_page.md
docs/pages/pmd/projectdocs/committers/releasing.md
docs/pages/release_notes.md

[doc] Add missing doc about pmd.github.io

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
pmd-java/etc/grammar/Java.jjt
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14Test.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java14/YieldStatements.java

[java] Make yield statements more conditional

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

[java] #2402 fix false-positives on Primitive Streams

---

pmd-core/src/main/java/net/sourceforge/pmd/cpd/AbstractTokenizer.java

As per the discussion in https://github.com/checkstyle/checkstyle/pull/8095#issuecomment-613764460

[core] Fix Checkstyle OperatorWrap in AbstractTokenizer

---

CONTRIBUTING.md
README.md
code_of_conduct.md
docs/pages/release_notes.md

Fixes #2357
I've set up the email address "moderators@pmd-code.org". It is forwarding emails to @adangel , @oowekyala , @jsotuyod , @rsoesemann

Add code of conduct

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloneMethodMustImplementCloneableRule.java

As per the discussion in https://github.com/checkstyle/checkstyle/pull/8095#issuecomment-619156375
Sorry  @oowekyala I forgot to update the current file so creating a new PR there was one more file which is already merged you can view it here:
https://github.com/pmd/pmd/pull/2423

[java] Operator Wrap check

---

pmd-swift/src/main/antlr4/net/sourceforge/pmd/lang/swift/antlr4/Swift.g4
pmd-swift/src/test/java/net/sourceforge/pmd/cpd/SwiftTokenizerTest.java
pmd-swift/src/test/resources/net/sourceforge/pmd/cpd/Swift4.2.swift
pmd-swift/src/test/resources/net/sourceforge/pmd/cpd/Swift5.0.swift
pmd-swift/src/test/resources/net/sourceforge/pmd/cpd/Swift5.1.swift
pmd-swift/src/test/resources/net/sourceforge/pmd/cpd/Swift5.2.swift

Add swift 4.2 to 5.2 support
- Fixes #2473
validated on our CI (where the initial job failed)

[swift] Swift 4.2-5.2 support

---

pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidPrintStackTrace.xml

See #2437 for the problem.
- Fixes #2437

[java] AvoidPrintStackTrace - consider method calls

---

do-release.sh
docs/pages/next_major_development.md

This fixes the TODO on the page
- None

[doc] Update next major development page for PMD 7 plans

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java

[java] Optimize UnusedPrivateMethodRule

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NPathComplexityRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/NPathComplexity.xml

Add information about expected NPath complexity to rule violation message
- Fixes #2570

[java] NPathComplexity should mention the expected NPath complexity

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/bestpractices/UnusedLocalVariableRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/UnusedLocalVariable.xml

[apex] Exception applying rule UnusedLocalVariable on trigger

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexUnitTestRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexXPathRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/AbstractNcssCountRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractIgnoredAnnotationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractInefficientZeroCheck.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaMetricsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractLombokAwareRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractPoorMethodCall.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/SymbolTableTestRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractSunSecureRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AbstractNcssCountRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/AbstractCommentRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AbstractOptimizationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/regex/RegexHelper.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/design/AbstractNcssCountRule.java

[apex][plsql][java] Deprecate base rule classes

---

pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java

Revert "[visualforce] add new safe resource for VfUnescapeEl"

---

docs/pages/release_notes.md
pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/rule/security/VfUnescapeElRule.java
pmd-visualforce/src/test/resources/net/sourceforge/pmd/lang/vf/rule/security/xml/VfUnescapeEl.xml

Continuation of #2621 
- Fixes #2620

[visualforce] add new safe resource for VfUnescapeEl

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/performance/AvoidSoqlInLoopsRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/AvoidSoqlInLoops.xml

Handles for-each loop correctly now.
- Fixes #2598

[apex] AvoidSoqlInLoops false positive for SOQL with in For-Loop

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ImportWrapper.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/DuplicateImports.xml

Fix false positive with static import
- Fixes #2546
- Replaces #2559

[java] DuplicateImports - fix false positive with static import

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/DataFlowHandler.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/AbstractDataFlowNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/DataFlowNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/Linker.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/LinkerException.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/NodeType.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/SequenceChecker.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/SequenceException.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/StackObject.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/StartOrEndDataFlowNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/Structure.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/VariableAccess.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/VariableAccessException.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/CurrentPath.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/DAAPathFinder.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/Executable.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/PathElement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/DataFlowFacade.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/JavaDataFlowNode.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/StatementAndBraceFinder.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/VariableAccessVisitor.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/DataflowAnomalyAnalysisRule.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLDataFlowHandler.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/dfa/DataFlowFacade.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/dfa/PLSQLDataFlowNode.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/dfa/StatementAndBraceFinder.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/dfa/VariableAccessVisitor.java

Deprecate DataflowAnomalyAnalysisRule, and all the DFA codebase. This includes what's in the PLSQL module (which I assume is ok, but can be reverted).
- Part of #2647 (the other part is about closing issues as "won't fix")

[core] Deprecate DFA

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

[java] Skip abstract methods in UnusedAssignment

---

pmd-java/src/main/resources/category/java/codestyle.xml

Fixes Java code example for rule "OnlyOneReturn". Method "foo" is type "void" but should be "String".

[java] Fix OnlyOneReturn code example

---

pmd-core/src/test/java/net/sourceforge/pmd/cpd/FileReporterTest.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/ZipFileExtractor.java

Cleanup: use try with resources

---

pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/rule/design/NoInlineJavaScriptRule.java

Cleanup: avoid compiling Patterns repeatedly

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ParametricRuleViolation.java
pmd-core/src/main/java/net/sourceforge/pmd/util/database/SourceObject.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractPoorMethodCall.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/PositionalIteratorRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SignatureDeclareThrowsExceptionRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientEmptyStringCheckRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientStringBufferingRule.java

Cleanup: replace indexOf() < 0 with contains

---

pmd-core/src/main/java/net/sourceforge/pmd/util/database/DBMSMetadata.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/Comment.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/multifile/ClassStats.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SimplifyBooleanReturnsRule.java

Cleanup: javadoc issues

---

pmd-java/src/main/resources/category/java/performance.xml

Updates Java SimplifyStartsWith rule description and example
- Fixes #1868

[java] SimplifyStartsWith: update description and example, fixes #1868

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/ImmutableList.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitUseExpectedRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/testdata/MethodFirstPhase.java
pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/ast/JspDocStyleTest.java

Cleanup: Collection::addAll issues

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

[java] Fix #2759, UnusedAssignment false positive

---

docs/pages/pmd/userdocs/pmd_report_formats.md

Correction of a single word in the documentation.

Small correction in pmd_report_formats.md

---

pom.xml

A security fix is included in this version. See https://github.com/antlr/antlr4/issues/2069.

[core] Bump antlr4 from 4.7 to 4.7.2

---

pmd-java/src/main/resources/category/java/design.xml

Docs of [CouplingBetweenObjects](https://pmd.github.io/latest/pmd_rules_java_design.html#couplingbetweenobjects) has a Programming issue. I also made "something" a method.

[java] (doc) Fix example for CouplingBetweenObjects

---

docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/internal/AstNodeOwner.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/DocumentNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/ElementNode.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java

These are fixed only for Saxon. The merge into 7.0.x will be non-trivial though.
- Fixes #1939
- Adds tests for #1938, to check that Saxon has the correct behavior. But this issue is a wont-fix for Jaxen. 
- Refs #2523

[core] Test some XPath corner cases

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTypeParameter.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LoosePackageCouplingRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclarationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/Records.txt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/expression/Expr.txt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/geometry/Shape.txt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/geometry/Square.txt

- Those are the deprecations for #2887

[java] Deprecations for #2887 (replace some attributes with getName)

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceBody.java

Deprecations described in #905
- Fixes #905

[java] Deprecations for #905

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

Fix #3062  (extracted from #2977)

[java] Fix CloseResource FP with reassigned stream

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml

[java] Fix ignoredAnnotation property in UnusedPrivateField

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml

[java] Fix NPE in SingularFieldRule with concise resource syntax

---

docs/pages/release_notes.md
pmd-xml/src/main/java/net/sourceforge/pmd/lang/wsdl/rule/AbstractWsdlRule.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/AbstractDomXmlRule.java
pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/AbstractXmlRule.java

Deprecations for #2971, see there for rationale

[xml] Deprecate xml base rule classes

---

.ci/files/all-java.xml
pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractClassWithoutAbstractMethodRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/CheckResultSetRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractClassWithoutAbstractMethodTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/CheckResultSetTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/SystemPrintlnTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AbstractClassWithoutAbstractMethod.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/CheckResultSet.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/SystemPrintln.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/WhileLoopWithLiteralBoolean.xml

A small batch of 6 rules, see commit list
- Items of #2701

[java] Update a few more rules in bestpractices

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java

- protected and public members
- refs #3116

[java] Deprecation in AvoidUsingHardCodedIPRule

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/ImportWrapper.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/Hello.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/HelloMore.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml

[java] UnusedImports with static imports on subclasses (fixes #3132)

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

[java] InvalidLogMessageFormat more String.format detection

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ReplaceEnumerationWithIteratorTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ReplaceHashtableWithMapTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ReplaceVectorWithListTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceEnumerationWithIterator.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceHashtableWithMap.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceVectorWithList.xml

Update ReplaceEnumerationWithIterator, ReplaceHashtableWithMap, ReplaceVectorWithList
- Items of #2701

[java] Update replace x with x rules

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/UseIOStreamsWithApacheCommonsFileItemTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseIOStreamsWithApacheCommonsFileItem.xml

[java] Update rule UseIOStreamsWithApacheCommonsFileItem

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/ClassNamingConventionsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryModifierRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NcssCountRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ClassNameDeclaration.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryModifierTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryModifier.xml

[java] Update rule UnnecessaryModifier

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLocalVariableDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/closeresource/FakeContext.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml

[java] Fix #2757: make CloseResource support @lombok.Cleanup

---

.ci/files/all-java.xml
pmd-core/src/main/java/net/sourceforge/pmd/internal/util/IteratorUtil.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/NodeStream.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/AxisStream.java
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/IteratorBasedNStream.java
pmd-core/src/test/java/net/sourceforge/pmd/internal/util/IteratorUtilTest.java
pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/internal/NodeStreamBlanketTest.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/OnlyOneReturnRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/OnlyOneReturnTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/OnlyOneReturn.xml

[java] Update rule OnlyOneReturn

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryImportRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryimport/package1/U.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryimport/package2/C.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

[java] UnnecessaryImport false positive for on-demand imports

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableCouldBeFinalRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml

This fixes a couple of false negatives of [LocalVariableCouldBeFinal](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#localvariablecouldbefinal), which were found in #2687 .
Note: :warning: This rule has been already updated on pmd7 branch.
The original code samples:
*   fixes FN: https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlockBasic.java#L97
*   fixes FN: https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule488numericliterals/InputUpperEll.java#L80
*   fixes FN: https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/require …

[java] LocalVariableCouldBeFinal: false negatives with interfaces, anon classes

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml

[java] Fix #3248 - doc of SingletonClassReturningNewInstance

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/assemblies/pmd-bin.xml
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java

Now the ast dump program is available on windows.
- Fixes #2466 
- This might be made redundant by #2234 in the future anyway

[dist] Include all batch scripts in distribution archive

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/DataClass.xml

[java] Fix #2780 DataClass example from documentation results in false negative

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml

[java] Deprecate rule CloneThrowsCloneNotSupportedException

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml

[java] Deprecate rule DefaultPackage

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/OptimizableToArrayCallTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/OptimizableToArrayCall.xml

[java] Update rule OptimizableToArrayCall

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AvoidRethrowingExceptionTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AvoidRethrowingException.xml

[java] Update rule AvoidRethrowingException

---

pmd-java/src/main/resources/category/java/design.xml

Hi folks.
I was checking released cognitive complexity metric and found the the doc unfortunately is not correct - it was copied from Apex but Apex implementation has incorrect implementation for hybrid increment case.
Rule doc (old version): https://pmd.github.io/latest/pmd_rules_java_design.html#cognitivecomplexity
- Fixes #

[java] Fix incorrect increment for "else if" branch in Cognitive Complexity docs

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AbstractClassWithoutAnyMethodTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AbstractClassWithoutAnyMethod.xml

[java] Update rule AbstractClassWithoutAnyMethod

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveClassLengthRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveImportsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveMethodLengthRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveParameterListRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExcessivePublicCountRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveClassLengthTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveImportsTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveMethodLengthTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ExcessiveParameterListTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ExcessivePublicCountTest.java

Update rules
- ExcessiveClassLengthRule
- ExcessiveImportsRule
- ExcessiveMethodLengthRule
- ExcessiveParameterListRule
- ExcessivePublicCountRule
most of them without changes.
- Items of #2701

[java] Update ExcessiveSomething rules

---

.ci/files/all-java.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/DoNotExtendJavaLangErrorTest.java

[java] Update DoNotExtendJavaLangError

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExceptionAsFlowControlRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/ExceptionAsFlowControlTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ExceptionAsFlowControl.xml

[java] Update rule ExceptionAsFlowControl

---

pmd-apex/src/main/resources/category/apex/performance.xml
pmd-apex/src/main/resources/category/apex/security.xml

Update documentation for features that were added in #3198 and #2312

[apex] Update ApexCRUDViolation and OperationWithLimitsInLoop docs

---

docs/pages/release_notes.md
pmd-core/etc/xslt/cpdhtml.xslt
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CpdXsltTest.java
pmd-core/src/test/resources/net/sourceforge/pmd/cpd/ExpectedCpdHtmlReport.html
pmd-core/src/test/resources/net/sourceforge/pmd/cpd/SampleCpdReport.xml

[core] cpd: Error Loading stylesheet cpdhtml.xslt

---

docs/pages/pmd/languages/apex_metrics_index.md
docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedName.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/impl/visitors/CognitiveComplexityVisitor.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/CognitiveComplexityRule.java
pmd-apex/src/main/resources/category/apex/design.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedNameTest.java
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/design/CognitiveComplexityTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/metrics/impl/xml/CognitiveComplexityTest.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/CognitiveComplexity.xml

Fix Cognitive Complexity metric:
* else if blocks are only hybrid increments (fixes #3332)
* add rule test
* also report current threshold in rule violations
* ignore continue/break statements. These don't support labels
in apex
* add documentation
- Fixes #3332

[apex] Fix Cognitive Complexity metric

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseArraysAsList.xml

Note: This rule has been updated on pmd7 already.
- Fixes #3331

[java] UseArraysAsList false negative with for-each loop

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientStringBufferingRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InsufficientStringBufferDeclaration.xml

Updates the rule for pmd7.
Part of #2701 
This contains the same changes as in #3277

[java] Update rule InsufficientStringBufferDeclaration

---

.ci/files/project-list.xml

Just to see, how it would look. Maybe we can add it to the baseline...

[ci] Add openjdk-11 as pmd-regression-tester project

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/util/IOUtil.java
pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java

[core] NPE when specifying report file in current directory in PMD CLI

---

docs/pages/pmd/userdocs/tools/tools.md

Add [Code Inspector](https://www.code-inspector.com) to the list of tools that uses PMD in their CI/CD pipeline to check Java and Apex code.
Will be added to this page: https://pmd.github.io/latest/pmd_userdocs_tools.html

[doc] Add Code Inspector in the list of tools

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/IdempotentOperationsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/IdempotentOperationsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/IdempotentOperations.xml

[java] Update rule IdempotentOperations

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ComparisonWithNaNTest.java

[java] Update rule ComparisonWithNaN

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/CollapsibleIfStatementsTest.java

[java] Update rule CollapsibleIfStatements

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UseTryWithResourcesRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseTryWithResources.xml

* Reimplement the XPath rule as a Java rule
* Check for Java9+ and report only local vars otherwise
- Fixes #3235

[java] UseTryWithResources - fix for #3235

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientStringBufferingRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientStringBuffering.xml

[java] Fix NPE in `InefficientStringBuffering` with Records

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidCalendarDateCreationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidCalendarDateCreation.xml

[java] Update rule AvoidCalendarDateCreation

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AvoidUncheckedExceptionsInSignaturesTest.java

[java] Update AvoidUncheckedExceptionsInSignatures

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidArrayLoopsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidArrayLoops.xml

[java] Update rule AvoidArrayLoops

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidInstantiatingObjectsInLoopsRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/AvoidInstantiatingObjectsInLoopsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidInstantiatingObjectsInLoops.xml

[java] Update rule AvoidInstantiatingObjectsInLoops

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidUsingOctalValuesRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidUsingOctalValuesTest.java

[java] Update rule AvoidUsingOctalValues

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ReturnFromFinallyBlockTest.java

Update ReturnFromFinallyBlock to pmd 7.

[java] Update ReturnFromFinallyBlock

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/FinalizeDoesNotCallSuperFinalizeTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/FinalizeOnlyCallsSuperFinalizeTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/FinalizeOverloadedTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/FinalizeShouldBeProtectedTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/InstantiationToGetClassTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/MissingSerialVersionUIDTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/NonStaticInitializerTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingSerialVersionUID.xml

Updated:
* NonStaticInitializer
* MissingSerialVersionUID
* InstantiationToGetClass
* FinalizeShouldBeProtected
* FinalizeOverloaded
* FinalizeOnlyCallsSuperFinalize
* FinalizeDoesNotCallSuperFinalize

[java] Update many Java rules

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

ApexCRUDViolationRule will now properly drill into for-each loops, finding violations within, and resets its state across files.
- Fixes [#3462](https://github.com/pmd/pmd/issues/3462)
- Fixes [#3484](https://github.com/pmd/pmd/issues/3484)

[apex] Fix ApexCRUDViolationRule - add super call

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SimplifyConditionalRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/StablePathMatcher.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/DoubleCheckedLockingRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SimplifyConditionalTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifyConditional.xml

[java] Update rule SimplifyConditional

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SimplifiedTernaryTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifiedTernary.xml

[java] Update rule SimplifiedTernary

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnonymousClassDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UseUtilityClassRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/UseUtilityClassTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UseUtilityClass.xml

* note that the property `ignoredAnnotations` has been removed
- Refs #2701

[java] Update rule UseUtilityClass

---

.ci/files/all-java.xml
pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/NodeStream.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SwitchDensityRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SwitchDensityTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SwitchDensity.xml

This also adds support for switch expressions, composed switch labels (eg `case 0, 1, 2:`) and switch arrow branches for free 
- Refs #2701

[java] Update rule SwitchDensity

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryBoxingRule.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryBoxing.xml

This implements the last point of #2973
- See #2973
- See #3364

[java] UnnecessaryBoxing - check for Integer.valueOf(String) calls

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/multithreading/UnsynchronizedStaticFormatterTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/UnsynchronizedStaticFormatter.xml

[java] Update rule UnsynchronizedStaticFormatter

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/multithreading/NonThreadSafeSingletonRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/multithreading/NonThreadSafeSingletonTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/NonThreadSafeSingleton.xml

[java] Update rule NonThreadSafeSingleton

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/UseEqualsToCompareStringsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UseEqualsToCompareStrings.xml

[java] Update rule UseEqualsToCompareStrings

---

.ci/files/all-java.xml
docs/pages/7_0_0_release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/UseProperClassLoaderTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UseProperClassLoader.xml

* Part of #2701 
* Fixes #3173

[java] Update rule UseProperClassLoader

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/UseLocaleWithCaseConversionsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UseLocaleWithCaseConversions.xml

[java] Update rule UseLocaleWithCaseConversions

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/UnusedNullCheckInEqualsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UnusedNullCheckInEquals.xml

[java] Update rule UnusedNullCheckInEquals

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PlsqlTreeDumpTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/OpenForStatement.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/OpenForStatement.txt
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/Using.pls

- Fixes #3487
Note - this removes the token "IN_OUT", since that is wrong. The correct form is using a space instead of an underscore as delimiter: so two tokens "IN" and "OUT"

[plsql] Parsing exception OPEN ref_cursor_name FOR statement

---

docs/pages/release_notes.md
pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PlsqlTreeDumpTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectIntoArray.pls
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectIntoArray.txt

Simplest way. I didn't find a clear documentation, that this is allowed. Oracle only talks about "variable" - which seems to be also a array dereference...
-> https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/RETURNING-INTO-clause.html#GUID-38F735B9-1100-45AF-AE71-18FB74A899BE
- Fixes #3515

[plsql] Parsing exception SELECT...INTO on Associative Arrays Types

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CheckSkipResultRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/CheckSkipResultTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CheckSkipResult.xml

[java] Update CheckSkipResult

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

[java] Update rule InvalidLogMessageFormat

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/MissingStaticMethodInNonInstantiatableClassTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/MissingStaticMethodInNonInstantiatableClass.xml

[java] Update rule MissingStaticMethodInNonInstantiatableClass

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ClassCastExceptionWithToArrayTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ClassCastExceptionWithToArray.xml

[java] Update rule ClassCastExceptionWithToArray

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidInstanceofChecksInCatchClauseTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidInstanceofChecksInCatchClause.xml

[java] Update rule AvoidInstanceofChecksInCatchClause

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidBranchingStatementAsLastInLoopRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidBranchingStatementAsLastInLoopTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidBranchingStatementAsLastInLoop.xml

[java] Update rule AvoidBranchingStatementAsLastInLoop

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentToNonFinalStaticRule.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AssignmentToNonFinalStaticTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AssignmentToNonFinalStatic.xml

[java] Update rule AssignmentToNonFinalStatic

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/BaseClass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/DirectSubclass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/DirectSubclass2.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/GeneratedValue.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/GenerationType.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/Id.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/OtherSubclass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/TransitiveSubclass.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/other/DirectSubclassInOtherPackage.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/uselessoverridingmethod/other/OtherClassInOtherPackage.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UselessOverridingMethod.xml

Part of #2701
I'm sure the implementation can be much improved, but I'm happy that the tests already run...

[java] Update rule UselessOverridingMethod

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/FinalFieldCouldBeStaticTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/FinalFieldCouldBeStatic.xml

[java] Update rule FinalFieldCouldBeStatic

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/SimpleDateFormatNeedsLocaleTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/SimpleDateFormatNeedsLocale.xml

[java] Update rule SimpleDateFormatNeedsLocale

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/ProperLoggerTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ProperLogger.xml

[java] Update rule ProperLogger

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AccessorMethodGenerationRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ArrayIsStoredDirectlyRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitAssertionsShouldIncludeMessageRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitUseExpectedRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LooseCouplingRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/TestClassWithoutTestCasesRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AccessorMethodGeneration.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ArrayIsStoredDirectly.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitAssertionsShouldIncludeMessage.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LooseCoupling.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/TestClassWithoutTestCases.xml

* Continuation of #2687 
* Contains fixes and tests for
* AccessorMethodGeneration
* ArrayIsStoredDirectly
* JUnitTestsShouldIncludeAssert
* LooseCoupling
* TestClassWithoutTestCases
- Fixes #3613 
- Fixes #3614 
- Fixes #3624

[java] Rule improvements part 1

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedFormalParameterRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UseCollectionIsEmptyRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryReturnRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CouplingBetweenObjectsRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ExceptionAsFlowControlRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedFormalParameter.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseCollectionIsEmpty.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryReturn.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/CouplingBetweenObjects.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ExceptionAsFlowControl.xml

* Continuation of #2687 
* Contains fixes and tests for
* MethodReturnsInternalArray
* UnusedFormalParameter
* UseCollectionIsEmpty
* UnnecessaryFullyQualifiedName
* UnnecessaryReturn
* CouplingBetweenObjects
* ExceptionAsFlowControl
- Fixes #3618
- Fixes #3630

[java] Rule improvements part 2

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PrimitiveWrapperInstantiationRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/PrimitiveWrapperInstantiation.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/BooleanInstantiation.xml

* Verify that the cases were before reported by BooleanInstantiation
* Add missing test cases for PrimitiveWrapperInstantiation
- Fixes #3595

[java] Fix PrimitiveWrapperInstantion false negative with new Boolean

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/MoreThanOneLoggerTest.java

[java] Update rule MoreThanOneLogger

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/DoNotThrowExceptionInFinallyTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DoNotThrowExceptionInFinally.xml

[java] Update rule DoNotThrowExceptionInFinally

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/DoNotHardCodeSDCardTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DoNotHardCodeSDCard.xml

[java] Update rule DoNotHardCodeSDCard

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidLiteralsInIfConditionTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidLiteralsInIfCondition.xml

[java] Update rule AvoidLiteralsInIfCondition

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidCatchingNPETest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidCatchingNPE.xml

[java] Update rule AvoidCatchingNPE

---

.ci/files/all-java.xml
docs/pages/7_0_0_release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/NullAssignmentRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/NullAssignmentTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/NullAssignment.xml

Part of #2701 
- Fixes #2320
- Fixes #1669
- Not addressed by this PR is #1050.

[java] Update rule NullAssignment

---

pmd-apex-jorje/pom.xml
pmd-core/pom.xml
pmd-doc/pom.xml
pom.xml

This addresses the concerns raised in #3690 
Note: This moves gson and snakeyaml to dependency management, as those dependencies are used by pmd-core and pmd-doc as well.

[apex] Dependencies updates

---

pmd-java/pom.xml

Upgrades log4j dependency to the version 2.17.1
https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.1
- Fixes #

[java] Upgrade log4j to 2.17.1

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidLosingExceptionInformationTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidLosingExceptionInformation.xml

[java] Update rule AvoidLosingExceptionInformation

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/UseObjectForClearerAPITest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UseObjectForClearerAPI.xml

[java] Update rule UseObjectForClearerAPI

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LoosePackageCouplingRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/LoosePackageCouplingTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/LoosePackageCoupling.xml

Part of #2701
The rule stayed the same, no change was needed.

[java] Update rule LoosePackageCoupling

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingRawExceptionTypesTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AvoidThrowingRawExceptionTypes.xml

[java] Update rule AvoidThrowingRawExceptionTypes

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AvoidThrowingNewInstanceOfSameExceptionTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/AvoidThrowingNewInstanceOfSameException.xml

[java] Update rule AvoidThrowingNewInstanceOfSameException

---

.ci/files/all-java.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/AvoidDeeplyNestedIfStmtsTest.java

Part of #2701 
No change was needed for the rule.

[java] Update rule AvoidDeeplyNestedIfStmts

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/FinalParameterInAbstractMethodTest.java

[java] Update rule FinalParameterInAbstractMethod

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/NameFinder.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinderTest.java

[java] Fix #3698 - Error resolving Symbol Table

---

docs/pages/release_notes.md
pmd-javascript/pom.xml
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTBigIntLiteral.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTErrorNode.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTGeneratorExpression.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTGeneratorExpressionLoop.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTScriptNode.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTTaggedTemplateLiteral.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTTemplateCharacters.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTTemplateLiteral.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTUnaryExpression.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTUpdateExpression.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTXmlElemRef.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTXmlLiteral.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTXmlPropRef.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTYield.java
pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptTreeBuilder.java
pmd-javascript/src/main/resources/category/ecmascript/codestyle.xml
pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/JsTreeDumpTest.java
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/decorators.js
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/decorators.txt
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/jquery-selector.txt
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/templateStrings.js
pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/ast/testdata/templateStrings.txt

* Add ASTXmlPropRef node
* Update Rhino from 1.7.13 to 1.7.14
* Add more missing nodes from new Rhino
* Fix rule AssignmentInOperand as incrementors/decrementors are now parsed as UpdateExpression rather than UnaryExpression
- Fixes #3703

[java] Fix #3703 and update Rhino

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/UseStringBufferLengthRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseStringBufferLength.xml

[java] UseStringBufferLength: false negative with empty string variable

---

docs/pages/release_notes.md
pmd-doc/src/main/java/net/sourceforge/pmd/docs/DeadLinksChecker.java
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReturnEmptyCollectionRatherThanNull.xml

- Fixes #3721
Note: This is a regression only introduced on master. Found while running dogfood. Maybe it would be good to include PMD as well as a project in regression tester....

[java] Fix #3721 ReturnEmptyCollectionRatherThanNull false positive with lambdas

---

.ci/files/all-java.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/DoNotTerminateVMTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DoNotTerminateVM.xml

Part of #2701
**Good News!** This seems to be the last rule that needed to be updated :tada:

[java] Update rule DoNotTerminateVM

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTThrowsList.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SignatureDeclareThrowsExceptionRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SignatureDeclareThrowsExceptionTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SignatureDeclareThrowsException.xml

[java] Update rule SignatureDeclareThrowsException

---

docs/pages/release_notes.md
pmd-dist/src/main/resources/scripts/ast-dump.bat
pmd-dist/src/main/resources/scripts/bgastviewer.bat
pmd-dist/src/main/resources/scripts/cpd.bat
pmd-dist/src/main/resources/scripts/cpdgui.bat
pmd-dist/src/main/resources/scripts/designer.bat
pmd-dist/src/main/resources/scripts/designerold.bat
pmd-dist/src/main/resources/scripts/pmd.bat

[core] Handle quotes correctly in designer.bat and other *.bat files

---

.ci/files/all-java.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CouplingBetweenObjectsRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/CouplingBetweenObjectsTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/CouplingBetweenObjects.xml

[java] Update rule CouplingBetweenObjects

---

pmd-core/src/main/java/net/sourceforge/pmd/util/DataMap.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml

- Fixes #3754
Related to #3657

[java] Fix #3754 singularfield fp

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/coreimpl/NameResolver.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/coreimpl/ShadowChainIteratorImpl.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/coreimpl/ShadowChainNode.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/coreimpl/ShadowChainNodeBase.java
pmd-java/src/test/java/javasymbols/testdata/deep/StaticContainer.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/JavaParsingHelper.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/HeaderScopesTest.kt
pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/BaseParsingHelper.kt

[java] Fix #3763 - ambiguity error

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseStringBufferForStringAppends.xml

[java] Fix #3374 UseStringBufferForStringAppends rule example

---

pmd-plsql/etc/grammar/PldocAST.jjt
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLParser.java
pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserTest.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/RelationalOperators.pls

[plsql] Fix #3746 - Parsing exception with operators containing spaces

---

pom.xml

Upgrade Saxon HE to 10.7
- Fixes #3815

[core] Update saxon to 10.7

---

pmd-core/src/main/java/net/sourceforge/pmd/util/log/MessageReporter.java

[core] Fix AssertionError about exhaustive switch

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ArrayIsStoredDirectlyRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ArrayIsStoredDirectly.xml

A couple of improvements for [ArrayIsStoredDirectly](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#arrayisstoreddirectly)
- Fixes #3879 
- Fixes #1474 
- Fixes #1185 
- Fixes #3929

[java] Improve rule ArrayIsStoredDirectly

---

pmd-test/src/main/java/net/sourceforge/pmd/testframework/PMDTestRunner.java
pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTestRunner.java
pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
pmd-test/src/main/java/net/sourceforge/pmd/testframework/TestDescriptor.java
pmd-test/src/test/java/net/sourceforge/pmd/testframework/TestDescriptorTest.java

This helps to select just this failed test to rerun it within the IDE.
Also replace parenthesis in the test case description. This was a problem in the past (the single test could not be selected to be re-run in Eclipse).
In IntelliJ IDEA you can still not just  select the test case to be run alone. I think, they check, whether the test method for this test case indeed exists - which is not the case, since these rule test cases are defined in the XML files.
But now, we print out the "fake" test method:
```
--------------------------------------------------------------
Test Failure: Clear violation
-> Expected 2 problem(s), 1 problem(s) found.
-> Expected messages: []
-> Expected line numbers: []
Test Method Name: ArrayIsStoredDirectly_1_Clear_violation
n/a:3:	ArrayIsStoredDirectly:	The …
```

[test] Print Test Method Name for failed rule tests

---

docs/pages/release_notes.md
pmd-core/src/main/resources/rulesets/releases/6460.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTInitializer.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTResource.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSynchronizedStatement.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/EmptyControlStatementRule.java
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/EmptyControlStatementTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessarySemicolonTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/EmptyControlStatement.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessarySemicolon.xml

Prepares the merge of #3716 into pmd/7.0.x

[java] Merge rules that check for empty things (pmd7)

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetLoader.java
pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReferenceId.java
pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java

Prepare merge of #3958 into pmd/7.0.x

[core] Deprecate some syntax for ruleset references (pmd7)

---

pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidDuplicateLiterals.xml

Add the method buz definition in test cases.
- Fixes #3937

[java] AvoidDuplicateLiterals - Add the method "buz" definition to test cases

---

docs/pages/release_notes.md
pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleSetResolverTest.java

[doc] Fix missing additional rulesets

---

docs/pages/pmd/userdocs/tools/ci.md

Add MegaLinter in the list of PMD integrations :)

[doc] Add MegaLinter in the list of integrations

---

docs/_data/sidebars/pmd_sidebar.yml
docs/pages/pmd/projectdocs/trivia/news.md
docs/pages/pmd/userdocs/3rdpartyrulesets.md

Adds a new page under "User Documentation" which lists known 3rd party rulesets from the community.

[doc] Add page for 3rd party rulesets

---

pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/main/resources/category/java/design.xml

[doc] Fix typos in Java rule docs

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidArrayLoops.xml

- Fixes #1167 
- Fixes #2692 
- Fixes #3847

[java] AvoidArrayLoops improvements

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringToStringRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/stringtostring/Issue2080.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/stringtostring/StringToStringFP.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/stringtostring/User.java
pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/StringToString.xml

* Add type resolution for StringToString
* Improves type resolution to consider `class` literal
- Fixes #2080
- Fixes #3437 
- Fixes #3681 
- Fixes #3977

[java] StringToString improvements

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/unnecessaryfullyqualifiedname/Deprecated.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml

[java] Fix UnnecessaryFullyQualifiedName for current package java.lang

---

docs/pages/release_notes.md
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
pmd-doc/src/test/resources/expected/sample.md
pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml
pmd-java/src/main/resources/category/java/bestpractices.xml

- Document the maximum language version in general for the rules. We already had this for the minimum version.
- Add the reasoning for AccessorClass/MethodGeneration
- Fixes #4140

[doc] Rule doc: add maximum language version

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/TestClassWithoutTestCasesRule.java

Fix a small typo in `TestClassWithoutTestCases` description.

[java][doc] TestClassWithoutTestCases - fix small typo in description

---

docs/pages/pmd/userdocs/cli_reference.md
docs/pages/pmd/userdocs/cpd/cpd.md
docs/pages/pmd/userdocs/installation.md
docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
pmd-core/src/main/java/net/sourceforge/pmd/cli/PmdParametersParseResult.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
pmd-dist/src/main/resources/scripts/run.sh

- Companion PR for #4059
- Add deprecations and path the way for the upcoming changes to the CLI in PMD7
- Cover the PMD6 side of #3426 
- Fixes #3426

[core] Backport to PMD6 changes to accomodate PicoCli in PMD7

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/InvalidLogMessageFormatRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/InvalidLogMessageFormat.xml

[java] Fix NPE in InvalidLogMessageFormat

---

docs/_data/sidebars/pmd_sidebar.yml
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java
pmd-doc/src/test/resources/expected/pmd_sidebar.yml
pmd-doc/src/test/resources/net/sourceforge/pmd/docs/sidebar.yml

Even languages without rules.
- Relates #4205
- Relates #4105

[doc] List all languages in rule doc

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/performance.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidArrayLoops.xml

[java] Fix #4183 AvoidArrayLoops false positive

---

docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
docs/pages/pmd/projectdocs/committers/releasing.md
docs/pages/pmd/projectdocs/credits.md
docs/pages/pmd/projectdocs/trivia/similarprojects.md
docs/pages/pmd/userdocs/extending/metrics_howto.md
docs/pages/pmd/userdocs/making_rulesets.md
docs/pages/release_notes.md
docs/pages/release_notes_old.md
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/dfa/StatementAndBraceFinder.java
pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/CodeFormatRule.java
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/rule/codestyle/xml/CodeFormat.xml

Tthi PR fixes typos found in the documentation.

[doc] Fixing typos

---

docs/pages/release_notes.md
pmd-core/src/main/resources/rulesets/releases/6520.xml
pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/InvalidJavaBeanRule.java
pmd-java/src/main/resources/category/java/design.xml
pmd-java/src/main/resources/rulesets/java/quickstart.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/InvalidJavaBeanTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/InvalidJavaBean.xml

[java] New Rule InvalidJavaBean (pmd7)

---

pmd-apex/src/main/java/net/sourceforge/pmd/cpd/ApexTokenizer.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTAnnotation.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTAnnotationParameter.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTExpressionStatement.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTField.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTLiteralExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTModifierNode.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTParameter.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTTriggerVariableExpression.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserEnum.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserInterface.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserTrigger.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTVariableDeclarationStatements.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexQualifiedName.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.kt
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/TriggerUsage.java

Translate and implement remaining AST nodes, including: fields, triggers, annotations, and parameters.
Fixups from previous code review:
* Make ctor package private
* ASTExpressionStatement wraps statement instead of expression node
Relates #3766

[apex] Summit-AST Apex module - Part 5 - annotations, triggers, misc.

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java

In pmd 7 LawOfDemeter uses the rulechain, which makes it faster, but since the rule is stateful, its violations are also unstable, because the rulechain does not define a visitation order.
- comment here: https://github.com/pmd/pmd/pull/4049#issuecomment-1242946780

[java] Make LawOfDemeter not use the rulechain

---

docs/pages/pmd/languages/java.md

[doc] Fix doc showing deprecated CLI switches

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/multithreading.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/DoNotUseThreads.xml

[java] DoNotUseThreads: Fix duplicated violations reporting

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml

[java] UnusedPrivateField - add new property "reportForAnnotations"

---

docs/pages/release_notes.md
pmd-java/src/main/resources/category/java/errorprone.xml

[java][doc] AvoidAssertAsIdentifier and AvoidEnumAsIdentifier - clarify use case

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDReport.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDReportTest.java

* Add CPDReport#filterMatches
- Fixes #4340

[core] Add CPDReport#filterMatches

---

docs/pages/release_notes.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
pmd-test/src/main/java/net/sourceforge/pmd/ant/AbstractAntTestHelper.java
pmd-test/src/main/java/net/sourceforge/pmd/cli/BaseCLITest.java
pmd-test/src/main/java/net/sourceforge/pmd/cli/BaseCPDCLITest.java

* Adds the deprecation notes for #4235 
* Also adds some deprecations for #4155

[core] Deprecations in CPDConfiguration, Base(CPD)CLITest, AbstractAntTestHelper

---

docs/pages/pmd/userdocs/cpd/cpd.md
docs/pages/pmd/userdocs/installation.md
pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
pmd-java/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
pmd-javascript/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java

Just use the non-deprecated option, also in CLI help examples.

[doc] CPD - use non deprecated `--dir` cli option

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentContentRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentSizeRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentContent.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentSize.xml

Fix a problem with line number not being incremented. Compare with https://github.com/pmd/pmd/pull/4369
- Fixes #

[java] Fix reported line number in CommentContentRule

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/ExcessivePublicCountRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/NcssMethodCountRule.java
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/internal/AbstractCounterCheckRule.java
pmd-apex/src/main/resources/category/apex/design.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/ExcessivePublicCount.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/NcssMethodCount.xml

and verify inner class behavior.
- found while checking #3123

[apex] Improve ExcessivePublicCount message

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ImplicitSwitchFallThrough.xml

[java] Fix NPE in ImplicitSwitchFallThrough

---

pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/multifile/ApexMultifileAnalysis.java

When running PMD as an Eclipse plugin, ApexLink can't initialize due to the special bundle classloader used for plugins. This change just catches the additional possible errors.
More details can be found in the comment. I'm working around this problem current by duplicating the ApexMultifileAnalysis class in pmd-eclipse-plugin, but I'd like to delete this class again. See https://github.com/pmd/pmd-eclipse-plugin/commit/5e0cd6fd14d71fc494f39fe77caa69cea519650b.
While looking into this problem, I found two more things, that are not addressed:
* we use apex link 1.4.1, but the latest version is 2.3.7 (see https://repo1.maven.org/maven2/com/github/nawforce/apexlink/)
* apex-link seems to be discontinued, the github repo is archived: https://github.com/nawforce/apex-link - do we need to be …

[apex] Handle ApexLink initialization errors

---

pmd-core/src/main/java/net/sourceforge/pmd/lang/Language.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/java/net/sourceforge/pmd/coverage/PMDCoverageTest.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPassTest.java

Enable the coverage test in pmd-java and fix a bug found that way in the data flow code.

[java] Enable coverage test

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/InvalidTypeSignatureException.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/SignatureParser.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/SignatureScanner.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/TypeSigParser.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/SigParserTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TestUtilitiesForTypes.kt

Just a couple of unit tests for the ASM signature parser. I also replaced stacks within the parser with just a one element swap as an optimization.
- Fixes #

[java] More unit tests for sig parser

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/JavaResolvers.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/MemberInheritanceTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

[java] Fix #4432 - FP with UnnecessaryImport

---

pmd-core/etc/xslt/cpdhtml-v2.xslt

Provides New XML to HTML Transformer for PMD CPD
- [Details for this transformer](https://github.com/mohan-chinnappan-n/xml-xslt/blob/main/img/cpd.md)
- Fixes #

[cpd] New XML to HTML XLST report format for PMD CPD

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/PhaseOverloadSet.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/OverloadResolutionTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml

[java] Fix FP of UnnecessaryImport

---

docs/pages/pmd/userdocs/cli_reference.md
docs/pages/pmd/userdocs/configuring_rules.md
docs/pages/pmd/userdocs/extending/rule_guidelines.md
docs/pages/release_notes.md
docs/pages/release_notes_pmd7.md
pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/PmdCommand.java
pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/typesupport/internal/RulePriorityTypeSupport.java
pmd-cli/src/test/java/net/sourceforge/pmd/cli/PmdCliTest.java
pmd-core/src/main/java/net/sourceforge/pmd/RulePriority.java

[doc] Update documentation regarding minimum-priority

---

pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceHashtableWithMap.xml

[java] Fix #4433 - FP with ReplaceHashtableWithMap

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/ExcessivePublicCountRule.java
pmd-apex/src/main/resources/category/apex/design.xml
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/ExcessivePublicCount.xml

[apex] ExcessivePublicCount: consider properties

---

docs/pages/pmd/userdocs/cpd/cpd.md
docs/pages/pmd/userdocs/tools/ant.md
pmd-ant/src/main/java/net/sourceforge/pmd/ant/CPDTask.java
pmd-ant/src/main/java/net/sourceforge/pmd/ant/PMDTask.java

[ant] Improve documentation

---

docs/index.md

Added reference to the [PMD extension for bld](https://github.com/rife2/bld-pmd)
N/A
Yes, only a small change to the docs index

[doc] Added reference to the PMD extension for bld

---

pom.xml

Totally harmless, no API changes affecting us, but hopefully will stop people from wanting to report vulnerabilities on us.
- Fixes #

[core] Bump snakeyaml dependency

---

pmd-java/src/main/resources/category/java/errorprone.xml

[java] UnnecessaryCaseChange: example doc toUpperCase() should compare to a capitalized string

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeConversion.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/CaptureInferenceTest.kt

[java] Fix #4753 - PMD crashes while using generics and wildcards 

---

.ci/build.sh
.github/workflows/build.yml
do-release.sh
docs/pages/pmd/projectdocs/committers/releasing.md
docs/pages/release_notes.md
pom.xml

[ci] Build improvements

---

docs/pages/pmd/userdocs/configuring_rules.md
docs/pages/release_notes.md

[doc] Fix configuring rule docu for multivalues properties

---

pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/AbstractAnalysisCache.java
pmd-core/src/test/java/net/sourceforge/pmd/cache/internal/FileAnalysisCacheTest.java

[core] Fix NPE in AbstractAnalysisCache in case of processing errors

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/SingletonClassReturningNewInstanceRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/SingletonClassReturningNewInstance.xml

[java] SingletonClassReturningNewInstance - fix double assignment case

---

.mvn/wrapper/maven-wrapper.properties
pmd-apex/pom.xml
pmd-core/pom.xml
pmd-dist/pom.xml
pmd-html/pom.xml
pmd-java/pom.xml
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java
pmd-scala-modules/pmd-scala-common/pom.xml
pmd-scala-modules/pmd-scala-common/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/List.txt
pmd-scala-modules/pmd-scala_2.12/pom.xml
pmd-scala-modules/pmd-scala_2.13/pom.xml
pmd-test-schema/pom.xml
pom.xml

- Note: I didn't touch kotlin/junit5/kotest/dokka
- Couldn't update apexlink, needs to be done with #4848

Update various dependencies

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JClassType.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ExprCheckHelper.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/InferenceContext.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/package-info.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/ExplicitTypesTest.kt

I hadn't implemented it as explicitly typed lambdas are rare. But for completeness we should support it, to avoid bugs like https://github.com/pmd/pmd/issues/4785#issuecomment-2036524337

[java] Support explicitly typed lambdas

---

pmd-java/src/main/resources/category/java/codestyle.xml

[java]  #4779 - Improve doc of MethodArgumentCanBeFinal

---

pmd-java/src/main/resources/category/java/errorprone.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/StringBufferInstantiationWithChar.xml

[java] Fix #4042 - FN with StringBufferInstantiationWithChar

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeOpsTest.kt

[java] Fix #5029 - infinite recursion in TypeOps::projectUpwards

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/InferenceVar.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/TypeInferenceTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

[java] Fix #5047 - type inference with enum

---

do-release.sh
docs/_config.yml
docs/_data/sidebars/pmd_sidebar.yml
docs/_includes/sidebar.html
docs/pages/pmd/about/release_policies.md
docs/pages/pmd/about/support_lifecycle.md
docs/pages/pmd/projectdocs/committers/releasing.md
docs/pages/release_notes.md

Adds documentation about
* release schedule
* version policies
* support lifecycle
This should reflect, what we currently do. Please double-check that this is your understanding as well.
Some parts could be written down as a decision (e.g. usage of semver / version policy), but I kept it simple for now.
I got inspiration from
* https://airflow.apache.org/docs/apache-airflow/stable/release-process.html#deprecation-policy
There's an interesting info about semver - https://hynek.me/articles/semver-will-not-save-you/
* https://docs.chocolatey.org/en-us/chocolatey-components-dependencies-and-support-lifecycle/
* https://github.com/FasterXML/jackson/wiki/Jackson-Releases
* https://spring.io/projects/spring-framework#support
- none

[doc] Release schedule, version policies, support lifecycle

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/performance/AvoidNonRestrictiveQueriesRule.java
pmd-apex/src/main/resources/category/apex/performance.xml
pmd-apex/src/main/resources/rulesets/apex/quickstart.xml
pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/performance/AvoidNonRestrictiveQueriesTest.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/AvoidNonRestrictiveQueries.xml

- Adds a new rule AvoidNonRestrictiveQueries as suggested back then in #663 
- Ported the rule to PMD 7
- Added more test cases
- Fixes #635
- Refs old PR #663

[apex] New Rule: AvoidNonRestrictiveQueries

---

docs/pages/release_notes.md
pmd-jsp/etc/grammar/Jsp.jjt
pmd-plsql/etc/grammar/PLSQL.jjt
pmd-velocity/etc/grammar/Vtl.jjt
pmd-visualforce/etc/grammar/Vf.jjt

Deprecate generated parser implementations

---

docs/pages/release_notes.md
pmd-plsql/src/main/resources/category/plsql/bestpractices.xml
pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/rule/bestpractices/xml/TomKytesDespair.xml

[plsql] Fix TomKytesDespair for more complex exception handlers

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeOpsTest.kt

[java] Fix #5167 - issue with type projection

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml

[java] Fix #5162 SingularField FP with synchronized block

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeSystem.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/InferenceVar.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/internal/infer/InferenceCtxUnitTests.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/TypeInferenceTest.kt

[java] Fix #5190 - NPE in type inference caused by null type

---

docs/pages/pmd/userdocs/tools/tools.md

Added Codety into the tool document page(https://docs.pmd-code.org/latest/pmd_userdocs_tools.html) , Codety Scanner uses PMD as Java code analyzer. 
GitHub issue review example: 
* https://github.com/codetyio/codety-scanner/actions/runs/10786005219/job/29912188828 
GitHub Pull Request automation example: 
* https://github.com/codetyio/codety-scanner/pull/15#issuecomment-2320351633
Codety Scanner also added PMD into the credits list https://github.com/codetyio/codety-scanner/blob/main/CREDITS.md

[doc] Added Codety to "Tools / Integrations"

---

javacc-wrapper.xml
pmd-core/src/main/java/net/sourceforge/pmd/annotation/Generated.java
pom.xml

Add a marker annotation for generated code, and ensure it's added to all JavaCC generated classes.

Ignore javacc code in coverage report

---

pom.xml

Also update junit-platform from 1.10.2 to 1.11.2
- Supersedes and closes #5260
- Supersedes and closes #5259

Bump org.junit from 5.8.2 to 5.11.2

---

pom.xml

Since we renamed a couple of rules, we also need to new build-tools which contains our dogfood ruleset.
- Fixes #

Bump pmd from 7.5.0 to 7.7.0

---

pom.xml

This enables support for Java 24
- Refs #5154

Bump asm from 9.7 to 9.7.1

---

pom.xml

https://github.com/apache/maven-pmd-plugin/releases/tag/maven-pmd-plugin-3.26.0
- Fixes #

Bump maven-pmd-plugin from 3.24.0 to 3.26.0

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/SubtypingTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml

[java] Fix #5097 - problem with unchecked conversion

---

pmd-tsql/pom.xml

Ensures the lexer is annotated as generated code
- Follow up on #5258

[tsql] Flag generated lexer as generated

---

docs/pages/release_notes.md
pmd-coco/pom.xml
pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoBaseListener.java
pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoBaseVisitor.java
pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoListener.java
pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoParser.java
pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoVisitor.java

- Remove / deprecate unused generated code
- Flag everything as Generated
- Follow up on #5258

[coco] Remove generated coco files form coverage

---

docs/pages/pmd/devdocs/major_contributions/adding_a_new_antlr_based_language.md
docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md

- Properly name the antlr4 plugin instead of ant.
- Mention the ant cleanup task and targets.

[doc] Improve docs on adding Antlr languages

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeVar.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeConversion.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeVarImpl.java
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/AstTestUtil.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/CaptureTest.kt
pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/GlbTest.kt

[java] Fix #5096 - StackOverflowError with recursively bounded tvar

---

pom.xml

Bump PMD from 7.8.0 to 7.9.0

---

docs/pages/release_notes.md
pom.xml

Bump pmd-designer from 7.2.0 to 7.10.0

---

pom.xml

Bump PMD from 7.9.0 to 7.10.0

---

.ci/files/all-regression-rules.xml
.ci/files/project-list.xml
pmd-core/src/main/java/net/sourceforge/pmd/PMDVersion.java

Adds the plsql files from https://github.com/Qualtagh/OracleDBUtils to our regression testing.
I expect that there are some parse errors, like #5522 . But once that is solved, we should get some feedback from this regression testing project, we we make progress or not.
- Refs #5522

[plsql] Add OracleDBUtils as regression testing project

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryCastRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryCast.xml

[java] Fix #5523: UnnecessaryCast FP with integer division

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryCastRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryCast.xml

Fix #4822: [java] UnnecessaryCast FP with unchecked cast

---

pom.xml

Bump PMD from 7.10.0 to 7.11.0

---

Gemfile.lock
docs/Gemfile.lock

Fixes https://github.com/pmd/pmd/security/dependabot/71
Fixes https://github.com/pmd/pmd/security/dependabot/73

Bump nokogiri from 1.16.7 to 1.18.3

---

Gemfile.lock
docs/Gemfile.lock

Fixes https://github.com/pmd/pmd/security/dependabot/75
Fixes https://github.com/pmd/pmd/security/dependabot/76

Bump uri from 0.13.1 to 1.0.3

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ImplicitFunctionalInterfaceRule.java
pmd-java/src/main/resources/category/java/bestpractices.xml
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/ImplicitFunctionalInterfaceTest.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ImplicitFunctionalInterface.xml

Fix #2849: [java] Add rule ImplicitFunctionalInterface

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/DataflowPass.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml

Fix #5592: [java] Fix UnusedAssignment FP with compact record ctor

---

pom.xml

Bump PMD from 7.11.0 to 7.12.0

---

docs/report-examples/pmd-report.sarif.json
pmd-core/src/main/java/net/sourceforge/pmd/renderers/internal/sarif/SarifLog.java
pmd-core/src/main/java/net/sourceforge/pmd/renderers/internal/sarif/SarifLogBuilder.java
pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-multiple-locations.sarif.json
pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-multiple.sarif.json
pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected.sarif.json

Adding and filling the field for the severeness of a rule in the sarif report according to the defined priorities in the pmd ruleset.
- adding the suggested feature from ticket #5525
- Fixes #5525

Fix #5525: [core] Add Sarif Level Property

---

docs/pages/pmd/userdocs/extending/designer_reference.md

Fix typo in documentation.
None.

[doc] typo fix in PMD Designer reference

---

pom.xml

Bump PMD from 7.13.0 to 7.14.0

---

docs/pages/release_notes.md
pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/ApexCRUDViolationRule.java
pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/security/xml/ApexCRUDViolation.xml

Fix #5788: [apex] ApexCRUDViolation - consider deeper nested Soql

---

pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceHashtableWithMap.xml

This fixes a misnamed test (too much c+p, I suspect)
- [n/a] Added unit tests for fixed bug/feature
- [n/a] Added (in-code) documentation (if needed)

chore: [java] ReplaceHashtableWithMap: Fix name of test

---

docs/pages/release_notes.md
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/UselessOverridingMethod.xml

- Fix #5804 
- Depends on #5806

Fix #5804: [java] UselessOverridingMethod needs to ignore SuppressWarnings

---

pmd-java/src/main/resources/category/java/codestyle.xml
pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ShortVariable.xml

Fix #5892: [java] ShortVariable FP for java 22 Unnamed Variable

---

.mvn/wrapper/maven-wrapper.properties

https://github.com/apache/maven/releases/tag/maven-3.9.11
- Fix #

Bump maven from 3.9.10 to 3.9.11

---

pom.xml

Bump PMD from 7.15.0 to 7.16.0

---

pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/RelianceOnDefaultCharsetRule.java
pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/InvocationMatcher.java
pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/InvocationMatcherTest.java

@jsotuyod had some valid comments in #5934 after it was merged. This addresses these concerns.
- [n/a] Added unit tests for fixed bug/feature
- [n/a] Added (in-code) documentation (if needed)

[java] Improve performance of RelianceOnDefaultCharset

---

package-lock.json

Fixes https://github.com/advisories/GHSA-968p-4wvh-cqc8

chore(deps): Update @babel/runtime from 7.16.7 to 7.28.7

---

pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml

See #3122. Turns out, the code already works. Just need to make sure the variable is used.
- Fix #3122

[java] Reactivate deactivated test in LocalVariableCouldBeFinal
